// GENERATED BY `beak prepare` — DO NOT EDIT.
// Run `beak prepare` after changing a schema class, a resource class, a screen or beak.yaml.
library;

import 'package:beak/panel.dart';
import 'package:beak/ui.dart';
import '../resources/assets/models/asset.dart';
import '../resources/candles/models/price_candle.dart';
import '../resources/faqs/models/faq.dart';
import '../resources/habitats/habitat_resource.dart';
import '../resources/habitats/models/habitat.dart';
import '../resources/invoices/models/invoice.dart';
import '../resources/invoices/models/invoice_item.dart';
import '../resources/keepers/keeper_resource.dart';
import '../resources/keepers/models/keeper.dart';
import '../resources/keepers/models/keeper_profile.dart';
import '../resources/messages/models/message.dart';
import '../resources/plans/models/plan.dart';
import '../resources/plans/models/plan_perk.dart';
import '../resources/sightings/models/sighting.dart';
import '../resources/specimens/models/specimen.dart';
import '../resources/specimens/specimen_resource.dart';
import '../resources/tasks/models/task.dart';
import '../resources/tasks/task_resource.dart';

/// The panel configuration for this project.
///
/// Assembled from `beak.yaml`, every model and resource class under
/// `lib/`, and the screens under `lib/screens/`.
BeakPanelConfig buildBeakPanel() {
  // The resource classes under lib/, keyed by the table of the model
  // each one configures. Each replaces that model's default resource.
  final authored = <String, BeakResource>{
    for (final resource in <BeakResource>[
      HabitatResource(),
      KeeperResource(),
      SpecimenResource(),
      TaskResource(),
    ])
      resource.model.table: resource,
  };
  final config = BeakPanelConfig(
    title: 'The Aviary',
    apiBaseUrl: const String.fromEnvironment(
      'BEAK_API_BASE_URL',
      defaultValue: 'http://localhost:8082',
    ),
    sidebarCollapsible: true,
    sidebarDefaultCollapsed: false,
    resources: [
      for (final resource in <BeakResource>[
        BeakResource(
          model: const AssetModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const PriceCandleModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const FaqModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const HabitatModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const InvoiceModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const InvoiceItemModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const KeeperModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const KeeperProfileModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const MessageModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const PlanModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const PlanPerkModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const SightingModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const SpecimenModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const TaskModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
      ])
        authored.remove(resource.model.table) ?? resource,
      ...authored.values,
    ],
  );
  return config;
}
