// GENERATED BY `beak prepare` — DO NOT EDIT.
// Run `beak prepare` after changing a schema class, a resource class, a screen or beak.yaml.
library;

import 'package:beak/beak.dart';
import '../resources/assets/models/asset.dart';
import '../resources/candles/models/price_candle.dart';
import '../resources/faqs/models/faq.dart';
import '../resources/habitats/models/habitat.dart';
import '../resources/invoices/models/invoice.dart';
import '../resources/invoices/models/invoice_item.dart';
import '../resources/keepers/models/keeper.dart';
import '../resources/keepers/models/keeper_profile.dart';
import '../resources/messages/models/message.dart';
import '../resources/plans/models/plan.dart';
import '../resources/plans/models/plan_perk.dart';
import '../resources/sightings/models/sighting.dart';
import '../resources/specimens/models/specimen.dart';
import '../resources/tasks/models/task.dart';

/// Every model discovered under `lib/`, in path order.
const List<BeakModel> beakModels = <BeakModel>[
  AssetModel(),
  PriceCandleModel(),
  FaqModel(),
  HabitatModel(),
  InvoiceModel(),
  InvoiceItemModel(),
  KeeperModel(),
  KeeperProfileModel(),
  MessageModel(),
  PlanModel(),
  PlanPerkModel(),
  SightingModel(),
  SpecimenModel(),
  TaskModel(),
];

/// A registry populated with every model in [beakModels].
BeakModelRegistry buildBeakRegistry() {
  final registry = BeakModelRegistry();
  for (final model in beakModels) {
    registry.register(model);
  }
  return registry;
}
