import 'dart:io';

import 'package:args/command_runner.dart';

import '../cli_runner.dart';
import '../project/beak_project_config.dart';
import 'prepare_command.dart';

/// Scaffolds a new Beak project.
///
/// The output is deliberately tiny: a pubspec, a `beak.yaml`, one example
/// model, and the files git needs. Everything else — the panel, the router,
/// the API, the entrypoints — is generated by `beak prepare` and stays out of
/// the way.
///
/// ```console
/// $ beak create acme_admin
/// $ cd acme_admin && beak dev
/// ```
final class CreateCommand extends Command<int> {
  /// Creates the command against [environment].
  CreateCommand(this.environment) {
    argParser.addOption(
      'beak-path',
      help:
          'Depend on a local Beak checkout at this path instead of git. '
          'Use it when developing Beak itself.',
      valueHelp: 'path/to/beak',
    );
  }

  /// The injected seams (output sink, target directory).
  final BeakCliEnvironment environment;

  @override
  String get name => 'create';

  @override
  String get description => 'Scaffold a new Beak project.';

  @override
  String get invocation => 'beak create <name>';

  @override
  Future<int> run() async {
    final List<String> rest = argResults?.rest ?? const [];
    if (rest.length != 1) {
      throw UsageException('Expected exactly one project name.', invocation);
    }
    final String name = rest.single;
    if (!RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(name)) {
      throw UsageException(
        '"$name" is not a valid Dart package name — use lower_snake_case.',
        invocation,
      );
    }
    final Object? beakPath = argResults?['beak-path'];

    for (final file in scaffoldFiles(
      name,
      beakPath: beakPath is String ? beakPath : null,
    )) {
      environment.writeFile(file.path, file.contents);
    }

    final String projectPath = '${environment.rootDirectory.path}/$name';

    // `web/` is Flutter's to own — index.html, the manifest, and the icon set
    // change between releases, so scaffolding a copy here would rot. Failure
    // is not fatal: the project still builds for every other platform, and
    // `beak doctor` reports the gap.
    //
    // `--no-pub` matters: only the `web/` assets are wanted here, and letting
    // `flutter create` resolve first makes scaffolding fail whenever the
    // dependencies cannot be fetched yet — offline, or behind a proxy — for a
    // step that never needed the network.
    final int webExit = await environment.runProcess('flutter', [
      'create',
      '--platforms=web',
      '--no-pub',
      '--project-name',
      name,
      '.',
    ], workingDirectory: projectPath);
    if (webExit != 0) {
      environment.out.writeln(
        '  skipped   web/ — `flutter create --platforms=web .` failed '
        '(exit $webExit). Run it in the project to build for the web.',
      );
    }

    // `flutter create` leaves a counter-app widget test referencing a MyApp
    // this project does not have. Replace it with one that exercises the
    // panel through the data-source seam.
    for (final file in postScaffoldFiles(name)) {
      environment.writeFile(file.path, file.contents);
    }

    // Generate the wiring inside the new project, so it is runnable as
    // created rather than one command short of it.
    runPrepare(
      BeakCliEnvironment(
        out: environment.out,
        rootDirectory: Directory(projectPath),
        now: environment.now,
        probe: environment.probe,
        runProcess: environment.runProcess,
      ),
    );

    environment.out
      ..writeln()
      ..writeln('  cd $name && beak dev');
    return 0;
  }

  /// The files a new project starts with, relative to its root.
  ///
  /// Kept as a pure function so the scaffold can be asserted on without
  /// touching a file system. [beakPath] points the generated pubspec at a
  /// local Beak checkout; without it the project depends on Beak by git.
  static List<BeakScaffoldFile> scaffoldFiles(
    String name, {
    String? beakPath,
  }) => [
    BeakScaffoldFile(
      path: '$name/pubspec.yaml',
      contents: _pubspec(name, beakPath: beakPath),
    ),
    BeakScaffoldFile(path: '$name/beak.yaml', contents: _beakYaml(name)),
    BeakScaffoldFile(
      path: '$name/lib/models/note.dart',
      contents: _exampleModel,
    ),
    BeakScaffoldFile(path: '$name/.gitignore', contents: _gitignore),
    BeakScaffoldFile(
      path: '$name/analysis_options.yaml',
      contents: _analysisOptions,
    ),
    BeakScaffoldFile(path: '$name/AGENTS.md', contents: _agentsMd(name)),
  ];

  /// Files written *after* `flutter create`, so its own scaffold does not
  /// win. Kept pure for the same reason as [scaffoldFiles].
  static List<BeakScaffoldFile> postScaffoldFiles(String name) => [
    BeakScaffoldFile(
      path: '$name/test/widget_test.dart',
      contents: _smokeTest.replaceAll('_PACKAGE_', name),
    ),
  ];

  static const String _smokeTest = '''
import 'package:beak/panel.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:_PACKAGE_/beak/app.g.dart';
import 'package:_PACKAGE_/beak/registry.g.dart';

/// A data source with nothing in it, so the panel renders its empty states.
final class _EmptyDataSource implements BeakDataSource {
  const _EmptyDataSource();

  @override
  Future<BeakPage<BeakRecord>> query(BeakQuerySpec spec) async =>
      const BeakPage(items: [], total: 0, page: 1, perPage: 25);

  @override
  Future<BeakRecord?> getOne(String table, Object id) async => null;

  @override
  Future<BeakRecord> create(String table, BeakRecord data) async => data;

  @override
  Future<BeakRecord> update(String table, Object id, BeakRecord data) async =>
      data;

  @override
  Future<void> delete(String table, Object id, {bool force = false}) async {}

  @override
  Future<List<BeakRecord>> batchGet(String table, List<Object> ids) async => [];

  @override
  Future<void> attach(
    String table,
    Object id,
    String relationKey,
    List<Object> relatedIds,
  ) async {}

  @override
  Future<void> detach(
    String table,
    Object id,
    String relationKey,
    List<Object> relatedIds,
  ) async {}

  @override
  Future<num> aggregate(BeakAggregateSpec spec) async => 0;
}

void main() {
  testWidgets('the panel boots with every declared model registered', (
    tester,
  ) async {
    await tester.pumpWidget(const BeakApp(dataSource: _EmptyDataSource()));
    await tester.pumpAndSettle();

    expect(beakModels, isNotEmpty, reason: 'no model was discovered');
    for (final model in beakModels) {
      expect(
        buildBeakRegistry().byTable(model.table),
        isNotNull,
        reason: '\${model.table} is not registered',
      );
    }
  });
}
''';

  /// The Beak packages a generated project depends on.
  ///
  /// One: the umbrella re-exports the panel, the server, the migration DSL,
  /// the testing toolkit and obers_ui as separate libraries, so a project
  /// never has to keep five version constraints in step by hand.
  static const List<String> beakPackages = ['beak'];

  static String _pubspec(String name, {String? beakPath}) {
    final buffer = StringBuffer('''
name: $name
description: A Beak admin panel.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.0
  flutter: '>=3.41.0'

dependencies:
''');
    for (final package in beakPackages) {
      buffer.writeln('  $package:');
      if (beakPath != null) {
        buffer.writeln('    path: $beakPath/packages/$package');
      } else {
        buffer
          ..writeln('    git:')
          ..writeln('      url: https://github.com/SimonErich/beak.git')
          ..writeln('      path: packages/$package');
      }
    }
    buffer.write('''
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
''');
    return buffer.toString();
  }

  static String _beakYaml(String name) =>
      '''
# Beak project configuration. Every key is optional — delete this file and
# Beak still boots, titling the panel after the package.
name: ${BeakProjectConfig.titleCase(name)}

api:
  # The origin the panel calls. Use `auto` to call the origin the panel was
  # served from, which is what a single-host deployment wants.
  baseUrl: http://localhost:8080

# Presentation for a discovered resource. Anything not listed here is still
# discovered — it just uses the default icon and a title-cased label.
resources:
  notes:
    icon: fileText
    section: Content
''';

  static const String _exampleModel = '''
import 'package:beak/beak.dart';
import 'package:beak/schema.dart';

part 'note.beak.dart';

/// A note.
///
/// Declared once. `beak prepare` generates the typed columns, the model, the
/// relationships (both sides), and a typed record view into `note.beak.dart`
/// — there is no registry to edit and no resource to register.
@Resource(timestamps: true)
final class Note extends BeakSchema {
  /// What the note is called.
  ///
  /// Non-nullable, so it is required: the form validator, the API and the
  /// schema all derive that from the type rather than restating it.
  @Display()
  @Column(searchable: true, sortable: true, rules: [BeakMaxLength(255)])
  late final String title;

  /// The note itself.
  @Column(visibleOn: {BeakContext.form, BeakContext.detail})
  late final BeakText? body;

  /// Whether the note is pinned to the top of the list.
  @Column(filterable: true)
  late final bool pinned;
}
''';

  static const String _gitignore = '''
# Dart / Flutter
.dart_tool/
build/
.packages
pubspec.lock

# Beak generates these at their canonical paths so `flutter run`, IDE run
# buttons and `dart compile exe` work with no flags. They are regenerated by
# every `beak` command, so they are not worth reviewing.
# Run `beak eject main` if you would rather commit them.
/lib/main.dart
/bin/serve.dart
/bin/migrate.dart

# Secrets
.env
''';

  static const String _analysisOptions = '''
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
''';

  static String _agentsMd(String name) =>
      '''
# ${BeakProjectConfig.titleCase(name)} — notes for coding agents

This is a [Beak](https://github.com/SimonErich/beak) admin panel. Beak is
configuration-driven: you declare models and screens, and it generates the
API, the router, the tables, the forms and the detail views.

## Where things go

| What | Where |
| --- | --- |
| A resource | `lib/models/<name>.dart` — one `@Resource` class per file |
| A custom page | `lib/screens/<name>.dart` — a top-level `BeakScreen` |
| Panel title, icons, sections | `beak.yaml` |
| Theme / auth / dashboard / server overrides | `lib/{theme,auth,dashboard,server}.dart` |
| Generated wiring | `lib/beak/*.g.dart` — do not edit |

Nothing needs registering. `beak prepare` reads each schema class and
generates its columns, model, relationships (both sides) and a typed record
view into a `.beak.dart` part beside it, then wires everything up.

A field's Dart type picks its column: `String`, `BeakText`, `BeakRichText`,
`int`, `double`, `bool`, `DateTime`, an enum, `BeakHexColor`, `BeakImageRef`,
`BeakFileRef`. Nullability decides whether it is required.

## Invariants

- Never write a column key or table name as a string. Reference the column
  constant (`NoteColumns.title`) and the model (`const NoteModel().query()`).
- Never import `package:flutter/material.dart` or `cupertino.dart`. Beak's UI
  is obers_ui.
- Widgets are `HookWidget`; `StatefulWidget` is not used.
- Read record values through the generated record view: `record.asNote.title`
  is a `String`, `record.asNote.body` a `String?` — matching what the schema
  declared. `NoteColumns.title.readFrom(record)` is the lower-level form.

## Commands

```bash
beak dev        # generate, serve the API, run the panel
beak prepare    # regenerate the wiring only
beak migrate    # apply migrations
beak seed       # run seeders
beak doctor     # diagnose the project
```
''';
}

/// One file the scaffolder writes.
final class BeakScaffoldFile {
  /// Creates a scaffold file.
  const BeakScaffoldFile({required this.path, required this.contents});

  /// Path relative to the directory `beak create` runs in.
  final String path;

  /// The file's full text.
  final String contents;
}
