import 'dart:io';

import 'package:args/command_runner.dart';

import '../agents/beak_block_renderer.dart';
import '../agents/beak_claude_md.dart';
import '../agents/beak_managed_block.dart';
import '../agents/beak_workspace.dart';
import '../cli_runner.dart';
import '../project/beak_discovery.dart';
import '../project/beak_emitters.dart';
import '../project/beak_project_config.dart';
import '../templates.dart';
import '../version.dart';
import 'agents_command.dart';
import 'eject_command.dart';
import 'prepare_command.dart';

/// Scaffolds a new Beak project.
///
/// The output is deliberately tiny: a pubspec, a `beak.yaml`, one example
/// schema class, the files git needs, and the `AGENTS.md` and `CLAUDE.md` a
/// coding agent starts from. Everything else (the registry, the API host, the
/// migration, the entrypoints) is generated by `beak prepare` and stays out
/// of the way.
///
/// By default the panel is generated too: `lib/main.dart` boots the panel
/// Beak builds from every model. `--authored` instead writes a `lib/main.dart`
/// the project owns, a `BeakPanel(resources: [...])` listing a `NoteResource`
/// class, which is what `beak eject main` switches an existing project to.
///
/// ```console
/// $ beak create acme_admin
/// $ cd acme_admin
/// $ beak migrate
/// $ beak dev
/// ```
final class CreateCommand extends Command<int> {
  /// Creates the command against [environment].
  CreateCommand(this.environment) {
    argParser
      ..addOption(
        'beak-path',
        help:
            'Depend on a local Beak checkout at this path instead of git. '
            'Use it when developing Beak itself.',
        valueHelp: 'path/to/beak',
      )
      ..addOption(
        'beak-ref',
        help: 'The git ref of Beak to depend on.',
        valueHelp: 'ref',
        defaultsTo: beakReleaseRef,
      )
      ..addFlag(
        'authored',
        help:
            'Write a lib/main.dart the project owns, composing the panel from '
            'resource classes, instead of the generated one.',
        negatable: false,
      );
  }

  /// The injected seams (output sink, target directory).
  final BeakCliEnvironment environment;

  @override
  String get name => 'create';

  @override
  String get description => 'Scaffold a new Beak project.';

  @override
  String get invocation =>
      'beak create <name> [--authored] [--beak-ref <ref> | --beak-path <path>]';

  @override
  Future<int> run() async {
    final List<String> rest = argResults?.rest ?? const [];
    if (rest.length != 1) {
      throw UsageException('Expected exactly one project name.', invocation);
    }
    final String name = rest.single;
    if (!RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(name)) {
      throw UsageException(
        '"$name" is not a valid Dart package name — use lower_snake_case.',
        invocation,
      );
    }
    final Object? beakPath = argResults?['beak-path'];
    // A local checkout replaces the git dependency, so a ref would silently
    // mean nothing.
    if (beakPath is String && (argResults?.wasParsed('beak-ref') ?? false)) {
      throw UsageException(
        '--beak-ref pins the git dependency and --beak-path replaces it; '
        'pass one of them.',
        invocation,
      );
    }
    final String beakRef = switch (argResults?['beak-ref']) {
      final String ref => ref,
      _ => beakReleaseRef,
    };
    final bool authored = argResults?['authored'] == true;

    // lib/main.dart is among these, written before `flutter create` runs:
    // that fills in a counter app where there is no entrypoint, and
    // `prepare` keeps any entrypoint without the generated header.
    for (final file in scaffoldFiles(
      name,
      beakPath: beakPath is String ? beakPath : null,
      beakRef: beakRef,
      authored: authored,
    )) {
      environment.writeFile(file.path, file.contents);
    }

    final String projectPath = '${environment.rootDirectory.path}/$name';

    // `web/` is Flutter's to own — index.html, the manifest, and the icon set
    // change between releases, so scaffolding a copy here would rot. Failure
    // is not fatal: the project still builds for every other platform, and
    // `beak doctor` reports the gap.
    //
    // `--no-pub` matters: only the `web/` assets are wanted here, and letting
    // `flutter create` resolve first makes scaffolding fail whenever the
    // dependencies cannot be fetched yet — offline, or behind a proxy — for a
    // step that never needed the network.
    final int webExit = await environment.runProcess('flutter', [
      'create',
      '--platforms=web',
      '--no-pub',
      '--project-name',
      name,
      '.',
    ], workingDirectory: projectPath);
    if (webExit != 0) {
      environment.out.writeln(
        '  skipped   web/ — `flutter create --platforms=web .` failed '
        '(exit $webExit). Run it in the project to build for the web.',
      );
    }

    // `flutter create` leaves a counter-app widget test referencing a MyApp
    // this project does not have. Replace it with one that exercises the
    // panel through the data-source seam.
    for (final file in postScaffoldFiles(name, authored: authored)) {
      environment.writeFile(file.path, file.contents);
    }

    // Generate the wiring inside the new project, so it is runnable as
    // created rather than one command short of it. The agent files follow:
    // the scaffold wrote them from the CLI's own templates, and once
    // `flutter pub get` has run, the docs of the resolved version replace
    // what they point at.
    final projectEnvironment = BeakCliEnvironment(
      out: environment.out,
      rootDirectory: Directory(projectPath),
      now: environment.now,
      probe: environment.probe,
      runProcess: environment.runProcess,
    );
    runPrepare(projectEnvironment);
    refreshAgentFiles(projectEnvironment);

    // Migrate before dev: the API serves the tables the migration creates,
    // and a first `beak dev` without them fails every request.
    environment.out
      ..writeln()
      ..writeln('  next:')
      ..writeln('    cd $name')
      ..writeln('    beak migrate')
      ..writeln('    beak dev');
    return 0;
  }

  /// The files a new project starts with, relative to its root.
  ///
  /// Kept as a pure function so the scaffold can be asserted on without
  /// touching a file system. [beakPath] points the generated pubspec at a
  /// local Beak checkout; without it the project depends on Beak by git, at
  /// [beakRef]. [authored] writes an entrypoint the project owns, and the
  /// resource class it lists, in place of the generated entrypoint.
  static List<BeakScaffoldFile> scaffoldFiles(
    String name, {
    String? beakPath,
    String beakRef = beakReleaseRef,
    bool authored = false,
  }) => [
    BeakScaffoldFile(
      path: '$name/pubspec.yaml',
      contents: _pubspec(name, beakPath: beakPath, beakRef: beakRef),
    ),
    BeakScaffoldFile(
      path: '$name/beak.yaml',
      contents: _beakYaml(name, authored: authored),
    ),
    BeakScaffoldFile(path: '$name/$_noteSchemaPath', contents: _exampleModel),
    if (authored) ...[
      BeakScaffoldFile(
        path: '$name/$_noteResourcePath',
        contents: BeakEmitters.format(_noteResource),
      ),
      BeakScaffoldFile(
        path: '$name/lib/main.dart',
        contents: BeakEmitters.format(_authoredMain(name)),
      ),
    ] else
      BeakScaffoldFile(
        path: '$name/lib/main.dart',
        contents: BeakEmitters.format(BeakEmitters.mainEntrypoint(name)),
      ),
    BeakScaffoldFile(
      path: '$name/.gitignore',
      contents: authored
          ? EjectCommand.withoutMainIgnore(_gitignore)
          : _gitignore,
    ),
    BeakScaffoldFile(
      path: '$name/analysis_options.yaml',
      contents: _analysisOptions,
    ),
    BeakScaffoldFile(
      path: '$name/AGENTS.md',
      contents: _agentsMd(name, authored: authored),
    ),
    BeakScaffoldFile(
      path: '$name/CLAUDE.md',
      contents: BeakClaudeMd.importOnly,
    ),
  ];

  /// Files written *after* `flutter create`, so its own scaffold does not
  /// win. Kept pure for the same reason as [scaffoldFiles].
  static List<BeakScaffoldFile> postScaffoldFiles(
    String name, {
    bool authored = false,
  }) => [
    BeakScaffoldFile(
      path: '$name/test/widget_test.dart',
      contents: (authored ? _authoredSmokeTest : _smokeTest).replaceAll(
        '_PACKAGE_',
        name,
      ),
    ),
    // `flutter create` leaves its own README, which describes Flutter rather
    // than this project, and it is the first file anyone opens.
    BeakScaffoldFile(
      path: '$name/README.md',
      contents: _readme(name, authored: authored),
    ),
  ];

  /// Where the example schema class lives: the feature-folder layout every
  /// scaffold uses, `lib/resources/<plural>/models/<name>.dart`.
  static const String _noteSchemaPath = 'lib/resources/notes/models/note.dart';

  /// Where `--authored` writes the example's resource class, beside the
  /// folder holding its schema.
  static const String _noteResourcePath =
      'lib/resources/notes/note_resource.dart';

  /// The example's resource class, presented as the generated panel would
  /// present the default.
  static String get _noteResource => generateResourceClass(
    className: 'NoteResource',
    modelClass: 'NoteModel',
    modelImport: 'models/note.dart',
    table: 'notes',
    icon: 'fileText',
    navigationGroup: 'Content',
    authored: true,
  );

  /// The authored entrypoint, written by the same emitter `beak eject main`
  /// uses, over the one model and resource class the scaffold declares.
  static String _authoredMain(String name) => BeakEmitters.authoredMain(
    config: BeakProjectConfig(name: BeakProjectConfig.titleCase(name)),
    discovery: const BeakDiscovery(
      models: [
        BeakDiscoveredSymbol(
          name: 'NoteModel',
          importPath: 'resources/notes/models/note.dart',
          isConstructible: true,
          table: 'notes',
        ),
      ],
      resources: [
        BeakDiscoveredResource(
          className: 'NoteResource',
          importPath: 'resources/notes/note_resource.dart',
          isConst: true,
          modelClass: 'NoteModel',
        ),
      ],
    ),
  );

  static String _readme(String name, {required bool authored}) =>
      '''
# ${BeakProjectConfig.titleCase(name)}

A [Beak](https://github.com/SimonErich/beak) admin panel: declare a resource,
get its API, its table, its form and its detail page.

## Run it

```console
beak migrate    # create the tables, in a SQLite file beside this README
beak dev        # regenerate the wiring, then serve the API on :8080
```

`beak dev` prints the `flutter run -d chrome` line that starts the panel; run
it in a second terminal. Set `DATABASE_URL` when you want Postgres instead of
the SQLite file.

## Adding a resource

```console
beak make:resource Product --fields name:string!,price:decimal!
beak migrate
```

`make:resource` writes the schema class
`lib/resources/products/models/product.dart` and its resource class
`lib/resources/products/product_resource.dart`, then runs `beak prepare`,
which generates the columns, the model, both sides of every relationship, a
typed record view and the create-table migration. `beak migrate` applies it.

## Where things go

| What | Where |
| --- | --- |
| A resource's schema | `lib/resources/<plural>/models/<name>.dart` |
| How the panel presents it | `lib/resources/<plural>/<name>_resource.dart`, a `BeakResource` subclass |
| A custom page | `lib/screens/<name>.dart`, a top-level `BeakScreen` |
| Panel title and API origin | `beak.yaml` |
| Theme, auth, server | `lib/{theme,auth,server}.dart`: `beak eject <part>` writes the starter |
| Generated wiring | `lib/beak/*.g.dart`, `*.beak.dart`: committed, never edited |

## The entrypoint

${authored ? _authoredEntrypointNote : _generatedEntrypointNote}

`beak doctor` checks the project; `beak prepare` regenerates after any change.
''';

  static const String _generatedEntrypointNote = '''
`lib/main.dart` boots the panel Beak generates from every model: each one
gets a default resource, presented as `beak.yaml` says, and a `BeakResource`
class you write replaces the default for its model. `beak prepare` rewrites
the file, so it is git-ignored.

Run `beak eject main` to compose the panel yourself instead. It rewrites
`lib/main.dart` as a `BeakPanel(resources: [...])` you own and commit, and
`beak prepare` leaves it alone from then on.''';

  static const String _authoredEntrypointNote = '''
`lib/main.dart` is yours: a `BeakPanel(resources: [...])` listing every
resource class. `beak prepare` never rewrites it, so add each new resource
class to `resources` (`beak make:resource` prints the line to add).''';

  static const String _smokeTest = '''
import 'package:beak/testing.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:_PACKAGE_/beak/app.g.dart';
import 'package:_PACKAGE_/beak/registry.g.dart';

void main() {
  testWidgets('the panel boots with every declared model registered', (
    tester,
  ) async {
    // An empty in-memory source: the panel renders its empty states, and
    // seeding one is `source.seed(const NoteModel(), [record])`.
    final source = InMemoryBeakDataSource(registry: buildBeakRegistry());
    await tester.pumpWidget(BeakApp(dataSource: source));
    await tester.pumpAndSettle();

    expect(beakModels, isNotEmpty, reason: 'no model was discovered');
    for (final model in beakModels) {
      expect(
        buildBeakRegistry().byTable(model.table),
        isNotNull,
        reason: '\${model.table} is not registered',
      );
    }
  });
}
''';

  static const String _authoredSmokeTest = '''
import 'package:beak/testing.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:_PACKAGE_/beak/registry.g.dart';
import 'package:_PACKAGE_/main.dart';

void main() {
  testWidgets('the panel boots with every declared model registered', (
    tester,
  ) async {
    // An empty in-memory source: the panel renders its empty states, and
    // seeding one is `source.seed(const NoteModel(), [record])`.
    final source = InMemoryBeakDataSource(registry: buildBeakRegistry());
    await tester.pumpWidget(buildPanel(dataSource: source));
    await tester.pumpAndSettle();

    expect(beakModels, isNotEmpty, reason: 'no model was discovered');
    for (final model in beakModels) {
      expect(
        buildBeakRegistry().byTable(model.table),
        isNotNull,
        reason: '\${model.table} is not registered',
      );
    }
  });
}
''';

  /// The Beak packages a generated project depends on.
  ///
  /// One: the umbrella re-exports the panel, the server, the migration DSL,
  /// the testing toolkit and obers_ui as separate libraries, so a project
  /// never has to keep five version constraints in step by hand.
  static const List<String> beakPackages = ['beak'];

  static String _pubspec(
    String name, {
    required String? beakPath,
    required String beakRef,
  }) {
    final buffer = StringBuffer('''
name: $name
description: A Beak admin panel.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.0
  flutter: '>=3.41.0'

dependencies:
''');
    for (final package in beakPackages) {
      buffer.writeln('  $package:');
      if (beakPath != null) {
        buffer.writeln('    path: $beakPath/packages/$package');
      } else {
        buffer
          ..writeln('    git:')
          ..writeln('      url: https://github.com/SimonErich/beak.git')
          ..writeln('      ref: $beakRef')
          ..writeln('      path: packages/$package');
      }
    }
    buffer.write('''
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
''');
    return buffer.toString();
  }

  static String _beakYaml(String name, {required bool authored}) {
    final buffer = StringBuffer('''
# Beak project configuration. Every key is optional: delete this file and
# Beak still boots, titling the panel after the package.
name: ${BeakProjectConfig.titleCase(name)}

api:
  # The origin the panel calls. Use `auto` to call the origin the panel was
  # served from, which is what a single-host deployment wants.
  baseUrl: http://localhost:8080
''');
    // An authored panel takes its presentation from its resource classes,
    // so a `resources:` block would be a second place to look that does
    // nothing for them.
    if (!authored) {
      buffer.write('''

# Presentation for the default resource of a discovered model. Anything not
# listed here is still discovered: it just uses the default icon and a
# title-cased label. A BeakResource class for a model replaces its default.
resources:
  notes:
    icon: fileText
    section: Content
''');
    }
    return buffer.toString();
  }

  static const String _exampleModel = '''
import 'package:beak/beak.dart';
import 'package:beak/schema.dart';

part 'note.beak.dart';

/// A note.
///
/// Declared once. `beak prepare` generates the typed columns, the model, the
/// relationships (both sides), and a typed record view into `note.beak.dart`,
/// so there is no registry to edit.
@Resource(timestamps: true)
final class Note extends BeakSchema {
  /// What the note is called.
  ///
  /// Non-nullable, so it is required: the form validator, the API and the
  /// schema all derive that from the type rather than restating it.
  @Display()
  @Column(searchable: true, sortable: true, rules: [BeakMaxLength(255)])
  late final String title;

  /// The note itself.
  @Column(visibleOn: {BeakContext.form, BeakContext.detail})
  late final BeakText? body;

  /// Whether the note is pinned to the top of the list.
  @Column(filterable: true)
  late final bool pinned;
}
''';

  static const String _gitignore = '''
# Dart / Flutter
.dart_tool/
build/
.packages

# Beak writes these entrypoints at the paths `flutter run`, IDE run buttons
# and `dart compile exe` expect, and rewrites them on every `beak` command,
# so they are not worth reviewing.
# `beak eject main` hands lib/main.dart over to you, and un-ignores it.
/lib/main.dart
/bin/serve.dart
/bin/migrate.dart

# Secrets
.env

# Uploads land here until BEAK_STORAGE_DRIVER points somewhere else.
/storage/

# The default SQLite database, so the first `beak dev` needs no setup. A real
# deployment sets DATABASE_URL and this file never appears.
/*.db
/*.db-journal
/*.db-wal
/*.db-shm
''';

  static const String _analysisOptions = '''
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - web/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
''';

  /// The `AGENTS.md` of a new project: the managed block from the CLI's own
  /// template, so the file needs neither `pub get` nor the docs bundle.
  ///
  /// Written with the values `beak agents` computes for the project it
  /// creates, so the first `beak prepare` finds it current and changes
  /// nothing.
  static String _agentsMd(String name, {required bool authored}) =>
      BeakManagedBlock.newFile(
        BeakProjectConfig.titleCase(name),
        renderBlock(
          BeakBlockKind.standalone.fallbackTemplate,
          BeakBlockValues(
            version: beakCliVersion,
            docsIndex: '${BeakWorkspace.docsPath}/ai-index.md',
            skills: 'run `beak agents` to install them',
            schemaGlob: 'lib/resources/*/models/*.dart',
            panelEntry: BeakPanelSettings.defaultEntrypoint,
            mainIsGenerated: !authored,
          ),
        ),
      );
}

/// One file the scaffolder writes.
final class BeakScaffoldFile {
  /// Creates a scaffold file.
  const BeakScaffoldFile({required this.path, required this.contents});

  /// Path relative to the directory `beak create` runs in.
  final String path;

  /// The file's full text.
  final String contents;
}
