// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'habitat.dart';

/// Typed column constants of the habitats resource.
abstract final class HabitatColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The exhibit's name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired(), BeakMaxLength(120)],
    searchable: true,
    sortable: true,
    maxLength: 120,
  );

  /// ISO 3166-1 alpha-2 code of the country the birds come from.
  static const BeakStringColumn countryCode = BeakStringColumn(
    key: 'country_code',
    label: 'Country Code',
    rules: [BeakRequired(), BeakMinLength(2), BeakMaxLength(2)],
    filterable: true,
    maxLength: 2,
  );

  /// How many birds the exhibit holds at most.
  static const BeakIntColumn capacity = BeakIntColumn(
    key: 'capacity',
    label: 'Capacity',
    rules: [BeakRequired(), BeakMin(0)],
    sortable: true,
    min: 0,
  );

  /// Latitude of the wild range's centre.
  static const BeakDecimalColumn latitude = BeakDecimalColumn(
    key: 'latitude',
    label: 'Latitude',
    rules: [BeakRequired()],
    precision: 4,
  );

  /// Longitude of the wild range's centre.
  static const BeakDecimalColumn longitude = BeakDecimalColumn(
    key: 'longitude',
    label: 'Longitude',
    rules: [BeakRequired()],
    precision: 4,
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    countryCode,
    capacity,
    latitude,
    longitude,
    createdAt,
    updatedAt,
  ];
}

/// Typed relationship constants of the habitats resource.
abstract final class HabitatRelations {
  /// The birds that live here (has-many relationship).
  static const BeakHasMany specimens = BeakHasMany(
    key: 'specimens',
    label: 'Specimens',
    relatedTable: 'specimens',
    displayColumnKey: 'common_name',
    foreignKey: 'habitat_id',
    searchColumnKeys: ['common_name'],
    onDelete: BeakOnDelete.setNull,
  );

  /// The keepers who look after it (many-to-many, through a pivot table).
  static const BeakBelongsToMany keepers = BeakBelongsToMany(
    key: 'keepers',
    label: 'Keepers',
    relatedTable: 'keepers',
    displayColumnKey: 'name',
    pivotTable: 'habitat_keeper',
    foreignPivotKey: 'habitat_id',
    relatedPivotKey: 'keeper_id',
    searchColumnKeys: ['name'],
  );
}

/// Typed configuration references for Habitat.
final class HabitatFields {
  /// Creates the fields of Habitat, rooted at its own model.
  const HabitatFields() : _model = const HabitatModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const HabitatFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: HabitatColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: HabitatColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Country Code.
  BeakScalarField<String> get countryCode => BeakScalarField<String>(
    model: _model,
    column: HabitatColumns.countryCode,
    path: _path,
    isRequired: true,
  );

  /// Capacity.
  BeakScalarField<int> get capacity => BeakScalarField<int>(
    model: _model,
    column: HabitatColumns.capacity,
    path: _path,
    isRequired: true,
  );

  /// Latitude.
  BeakScalarField<double> get latitude => BeakScalarField<double>(
    model: _model,
    column: HabitatColumns.latitude,
    path: _path,
    isRequired: true,
  );

  /// Longitude.
  BeakScalarField<double> get longitude => BeakScalarField<double>(
    model: _model,
    column: HabitatColumns.longitude,
    path: _path,
    isRequired: true,
  );

  /// Created.
  BeakScalarField<DateTime> get createdAt => BeakScalarField<DateTime>(
    model: _model,
    column: HabitatColumns.createdAt,
    path: _path,
    isRequired: false,
  );

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => BeakScalarField<DateTime>(
    model: _model,
    column: HabitatColumns.updatedAt,
    path: _path,
    isRequired: false,
  );

  /// Specimens.
  BeakToManyField get specimens => BeakToManyField(
    model: _model,
    relation: HabitatRelations.specimens,
    target: const SpecimenModel(),
    path: _path,
    isRequired: false,
  );

  /// Keepers.
  BeakToManyField get keepers => BeakToManyField(
    model: _model,
    relation: HabitatRelations.keepers,
    target: const KeeperModel(),
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to Habitat, retaining its root owner.
final class HabitatToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const HabitatToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const HabitatModel());

  /// Every target field, including names reserved by the path API.
  HabitatFields get fields => HabitatFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Country Code.
  BeakScalarField<String> get countryCode => fields.countryCode;

  /// Capacity.
  BeakScalarField<int> get capacity => fields.capacity;

  /// Latitude.
  BeakScalarField<double> get latitude => fields.latitude;

  /// Longitude.
  BeakScalarField<double> get longitude => fields.longitude;

  /// Created.
  BeakScalarField<DateTime> get createdAt => fields.createdAt;

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => fields.updatedAt;

  /// Specimens.
  BeakToManyField get specimens => fields.specimens;

  /// Keepers.
  BeakToManyField get keepers => fields.keepers;
}

/// A biome the aviary keeps, with the place its birds come from.
final class HabitatModel extends BeakModel {
  /// Creates the habitats model.
  const HabitatModel();

  /// Typed field and relation references, including reserved names.
  static const HabitatFields fields = HabitatFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [countryCode] in this model.
  static final countryCode = fields.countryCode;

  /// Typed reference to [capacity] in this model.
  static final capacity = fields.capacity;

  /// Typed reference to [latitude] in this model.
  static final latitude = fields.latitude;

  /// Typed reference to [longitude] in this model.
  static final longitude = fields.longitude;

  /// Typed reference to [createdAt] in this model.
  static final createdAt = fields.createdAt;

  /// Typed reference to [updatedAt] in this model.
  static final updatedAt = fields.updatedAt;

  /// Typed reference to [specimens] in this model.
  static final specimens = fields.specimens;

  /// Typed reference to [keepers] in this model.
  static final keepers = fields.keepers;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const HabitatModel(),
    query: const HabitatModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const HabitatModel(),
        query: const HabitatModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'habitats';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => HabitatColumns.values;
  @override
  List<BeakModel> get relatedModels => const [SpecimenModel(), KeeperModel()];

  @override
  List<BeakRelationship> get relationships => const [
    HabitatRelations.specimens,
    HabitatRelations.keepers,
  ];

  @override
  List<Enum> get formSlots => _HabitatModelFormSlot.values;
}

/// Form-field slots of HabitatModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Habitat can put on a form.
enum _HabitatModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
}

/// A live, nullable view of an incomplete Habitat draft.
final class HabitatDraft {
  /// Reads values through the session so dependencies stay observable.
  const HabitatDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(HabitatModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(HabitatModel.fields.name);

  /// Country Code, or null while incomplete.
  String? get countryCode => _reader.read(HabitatModel.fields.countryCode);

  /// Capacity, or null while incomplete.
  int? get capacity => _reader.read(HabitatModel.fields.capacity);

  /// Latitude, or null while incomplete.
  double? get latitude => _reader.read(HabitatModel.fields.latitude);

  /// Longitude, or null while incomplete.
  double? get longitude => _reader.read(HabitatModel.fields.longitude);

  /// Created, or null while incomplete.
  DateTime? get createdAt => _reader.read(HabitatModel.fields.createdAt);

  /// Updated, or null while incomplete.
  DateTime? get updatedAt => _reader.read(HabitatModel.fields.updatedAt);

  /// The selected specimens.
  List<SpecimenRecord> get specimens => [
    for (final row
        in _reader.read(HabitatModel.fields.specimens) ?? const <BeakRecord>[])
      SpecimenRecord.of(row),
  ];

  /// The selected keepers.
  List<KeeperRecord> get keepers => [
    for (final row
        in _reader.read(HabitatModel.fields.keepers) ?? const <BeakRecord>[])
      KeeperRecord.of(row),
  ];
}

/// Typed access to live Habitat form values.
extension HabitatDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  HabitatDraft get asHabitat => HabitatDraft(this);
}

/// A typed, zero-cost view over a habitats record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const HabitatRecord._(BeakRecord record) {
  /// Views [record] as a habitats row.
  const HabitatRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => HabitatColumns.id.readFrom(record);

  /// The exhibit's name.
  String get name => HabitatColumns.name.require(record);

  /// ISO 3166-1 alpha-2 code of the country the birds come from.
  String get countryCode => HabitatColumns.countryCode.require(record);

  /// How many birds the exhibit holds at most.
  int get capacity => HabitatColumns.capacity.require(record);

  /// Latitude of the wild range's centre.
  double get latitude => HabitatColumns.latitude.require(record);

  /// Longitude of the wild range's centre.
  double get longitude => HabitatColumns.longitude.require(record);

  /// When the record was created.
  DateTime? get createdAt => HabitatColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => HabitatColumns.updatedAt.readFrom(record);

  /// The eager-loaded specimens.
  List<SpecimenRecord> get specimens => [
    for (final row in record.relations['specimens'] ?? const <BeakRecord>[])
      SpecimenRecord.of(row),
  ];

  /// The eager-loaded keepers.
  List<KeeperRecord> get keepers => [
    for (final row in record.relations['keepers'] ?? const <BeakRecord>[])
      KeeperRecord.of(row),
  ];
}

/// Views any record as a habitats row.
extension HabitatRecordAccess on BeakRecord {
  /// This record, typed as a habitats row.
  HabitatRecord get asHabitat => HabitatRecord.of(this);
}
