// GENERATED BY `beak prepare` — DO NOT EDIT.
// Run `beak prepare` after changing lib/models, lib/screens or beak.yaml.
library;

import 'package:beak/beak.dart';
import '../models/note.dart';

/// Every model discovered under `lib/models/`, in path order.
const List<BeakModel> beakModels = <BeakModel>[NoteModel()];

/// A registry populated with every model in [beakModels].
BeakModelRegistry buildBeakRegistry() {
  final registry = BeakModelRegistry();
  for (final model in beakModels) {
    registry.register(model);
  }
  return registry;
}
