// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'event_category.dart';

/// Typed column constants of the event_categories resource.
abstract final class EventCategoryColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Category key, e.g. `business`.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired(), BeakMaxLength(40)],
    searchable: true,
  );

  /// Display label.
  static const BeakStringColumn label = BeakStringColumn(
    key: 'label',
    label: 'Label',
    rules: [BeakRequired(), BeakMaxLength(40)],
  );

  /// Calendar color for events in this category.
  static const BeakColorColumn color = BeakColorColumn(
    key: 'color',
    label: 'Color',
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [id, name, label, color];
}

/// Typed relationship constants of the event_categories resource.
abstract final class EventCategoryRelations {
  /// Events in this category.
  static const BeakHasMany events = BeakHasMany(
    key: 'events',
    label: 'Events',
    relatedTable: 'calendar_events',
    displayColumnKey: 'title',
    foreignKey: 'category_id',
    searchColumnKeys: ['title'],
  );
}

/// The event-categories resource — colored calendar buckets.
final class EventCategoryModel extends BeakModel {
  /// Creates the event_categories model.
  const EventCategoryModel();

  @override
  String get table => 'event_categories';

  @override
  String get displayColumnKey => 'label';

  @override
  List<BeakColumn> get columns => EventCategoryColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    EventCategoryRelations.events,
  ];

  @override
  List<Enum> get formSlots => _EventCategoryModelFormSlot.values;
}

/// Form-field slots of EventCategoryModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field EventCategory can put on a form.
enum _EventCategoryModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
}

/// A typed, zero-cost view over a event_categories record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const EventCategoryRecord._(BeakRecord record) {
  /// Views [record] as a event_categories row.
  const EventCategoryRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => EventCategoryColumns.id.readFrom(record);

  /// Category key, e.g. `business`.
  String get name => EventCategoryColumns.name.require(record);

  /// Display label.
  String get label => EventCategoryColumns.label.require(record);

  /// Calendar color for events in this category.
  String? get color => EventCategoryColumns.color.readFrom(record);

  /// The eager-loaded events.
  List<CalendarEventRecord> get events => [
    for (final row in record.relations['events'] ?? const <BeakRecord>[])
      CalendarEventRecord.of(row),
  ];
}

/// Views any record as a event_categories row.
extension EventCategoryRecordAccess on BeakRecord {
  /// This record, typed as a event_categories row.
  EventCategoryRecord get asEventCategory => EventCategoryRecord.of(this);
}
