// GENERATED BY `beak prepare` — DO NOT EDIT.
// Run `beak prepare` after changing lib/models, lib/screens or beak.yaml.
library;

import 'package:beak/server.dart';
import '../migrations/analytics_migrations.dart';
import '../migrations/calendar_migrations.dart';
import '../migrations/chat_migrations.dart';
import '../migrations/commerce_migrations.dart';
import '../migrations/content_migrations.dart';
import '../migrations/email_migrations.dart';
import '../migrations/files_migrations.dart';
import '../migrations/invoices_migrations.dart';
import '../migrations/kanban_migrations.dart';
import '../migrations/people_migrations.dart';
import '../seeders/demo_database_seeder.dart';
import 'registry.g.dart';
import '../server.dart' as server;

/// The configured backend for this project.
///
/// Reads `.env`, connects the database, resolves storage and
/// serves the generated API for every registered model.
///
/// [environment] overrides what the process supplies, so a
/// test can point the real host at `sqlite::memory:` and a
/// temporary upload directory without touching the machine.
BeakServeHost beakHost({Map<String, String>? environment}) => BeakServeHost(
  environment: {'PORT': '8180', ...environment ?? BeakEnv.resolve()},
  registry: buildBeakRegistry(),
  migrations: const [
    CreatePeopleTables(),
    CreateCommerceTables(),
    CreateAnalyticsTables(),
    CreateEmailTables(),
    CreateChatTables(),
    CreateCalendarTables(),
    CreateFilesTables(),
    CreateInvoicesTables(),
    CreateKanbanTables(),
    CreateContentTables(),
  ],
  seeders: const [DemoDatabaseSeeder()],
  configure: server.beakServer,
  storageRegistry: server.beakStorageRegistry,
);
