// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'delivery_slot.dart';

/// Typed column constants of the delivery_slots resource.
abstract final class DeliverySlotColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// Date.
  static const BeakStringColumn date = BeakStringColumn(
    key: 'date',
    label: 'Date',
    rules: [BeakRequired()],
    semantic: BeakSemantic.calendarDate(),
    sortable: true,
    filterable: true,
  );

  /// Start minute.
  static const BeakIntColumn startMinute = BeakIntColumn(
    key: 'start_minute',
    label: 'Start Minute',
    rules: [BeakRequired(), BeakMin(0), BeakMax(1439)],
    defaultValue: 0,
    min: 0,
    max: 1439,
  );

  /// End minute.
  static const BeakIntColumn endMinute = BeakIntColumn(
    key: 'end_minute',
    label: 'End Minute',
    rules: [BeakRequired(), BeakMin(1), BeakMax(1440)],
    defaultValue: 30,
    min: 1,
    max: 1440,
  );

  /// Capacity.
  static const BeakIntColumn capacity = BeakIntColumn(
    key: 'capacity',
    label: 'Capacity',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 120,
    min: 0,
  );

  /// Reserved orders.
  static const BeakIntColumn reservedOrders = BeakIntColumn(
    key: 'reserved_orders',
    label: 'Reserved Orders',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 0,
    min: 0,
  );

  /// Route code.
  static const BeakStringColumn routeCode = BeakStringColumn(
    key: 'route_code',
    label: 'Route Code',
    defaultValue: '',
  );

  /// Method.
  static const BeakStringColumn method = BeakStringColumn(
    key: 'method',
    label: 'Method',
    rules: [BeakRequired()],
    defaultValue: 'office',
  );

  /// Active.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
    rules: [BeakRequired()],
    defaultValue: true,
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    date,
    startMinute,
    endMinute,
    capacity,
    reservedOrders,
    routeCode,
    method,
    active,
    createdAt,
    updatedAt,
  ];
}

/// Typed configuration references for DeliverySlot.
final class DeliverySlotFields {
  /// Creates the fields of DeliverySlot, rooted at its own model.
  const DeliverySlotFields()
    : _model = const DeliverySlotModel(),
      _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const DeliverySlotFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: DeliverySlotColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: DeliverySlotColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Date.
  BeakScalarField<BeakDate> get date => BeakScalarField<BeakDate>(
    model: _model,
    column: DeliverySlotColumns.date,
    path: _path,
    isRequired: true,
  );

  /// Start Minute.
  BeakScalarField<int> get startMinute => BeakScalarField<int>(
    model: _model,
    column: DeliverySlotColumns.startMinute,
    path: _path,
    isRequired: true,
  );

  /// End Minute.
  BeakScalarField<int> get endMinute => BeakScalarField<int>(
    model: _model,
    column: DeliverySlotColumns.endMinute,
    path: _path,
    isRequired: true,
  );

  /// Capacity.
  BeakScalarField<int> get capacity => BeakScalarField<int>(
    model: _model,
    column: DeliverySlotColumns.capacity,
    path: _path,
    isRequired: true,
  );

  /// Reserved Orders.
  BeakScalarField<int> get reservedOrders => BeakScalarField<int>(
    model: _model,
    column: DeliverySlotColumns.reservedOrders,
    path: _path,
    isRequired: true,
  );

  /// Route Code.
  BeakScalarField<String> get routeCode => BeakScalarField<String>(
    model: _model,
    column: DeliverySlotColumns.routeCode,
    path: _path,
    isRequired: false,
  );

  /// Method.
  BeakScalarField<String> get method => BeakScalarField<String>(
    model: _model,
    column: DeliverySlotColumns.method,
    path: _path,
    isRequired: true,
  );

  /// Active.
  BeakScalarField<bool> get active => BeakScalarField<bool>(
    model: _model,
    column: DeliverySlotColumns.active,
    path: _path,
    isRequired: true,
  );

  /// Created.
  BeakScalarField<DateTime> get createdAt => BeakScalarField<DateTime>(
    model: _model,
    column: DeliverySlotColumns.createdAt,
    path: _path,
    isRequired: false,
  );

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => BeakScalarField<DateTime>(
    model: _model,
    column: DeliverySlotColumns.updatedAt,
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to DeliverySlot, retaining its root owner.
final class DeliverySlotToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const DeliverySlotToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const DeliverySlotModel());

  /// Every target field, including names reserved by the path API.
  DeliverySlotFields get fields =>
      DeliverySlotFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Date.
  BeakScalarField<BeakDate> get date => fields.date;

  /// Start Minute.
  BeakScalarField<int> get startMinute => fields.startMinute;

  /// End Minute.
  BeakScalarField<int> get endMinute => fields.endMinute;

  /// Capacity.
  BeakScalarField<int> get capacity => fields.capacity;

  /// Reserved Orders.
  BeakScalarField<int> get reservedOrders => fields.reservedOrders;

  /// Route Code.
  BeakScalarField<String> get routeCode => fields.routeCode;

  /// Method.
  BeakScalarField<String> get method => fields.method;

  /// Active.
  BeakScalarField<bool> get active => fields.active;

  /// Created.
  BeakScalarField<DateTime> get createdAt => fields.createdAt;

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => fields.updatedAt;
}

/// DeliverySlot configuration shared by the panel and authoritative API.
final class DeliverySlotModel extends BeakModel {
  /// Creates the delivery_slots model.
  const DeliverySlotModel();

  /// Typed field and relation references, including reserved names.
  static const DeliverySlotFields fields = DeliverySlotFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [date] in this model.
  static final date = fields.date;

  /// Typed reference to [startMinute] in this model.
  static final startMinute = fields.startMinute;

  /// Typed reference to [endMinute] in this model.
  static final endMinute = fields.endMinute;

  /// Typed reference to [capacity] in this model.
  static final capacity = fields.capacity;

  /// Typed reference to [reservedOrders] in this model.
  static final reservedOrders = fields.reservedOrders;

  /// Typed reference to [routeCode] in this model.
  static final routeCode = fields.routeCode;

  /// Typed reference to [method] in this model.
  static final method = fields.method;

  /// Typed reference to [active] in this model.
  static final active = fields.active;

  /// Typed reference to [createdAt] in this model.
  static final createdAt = fields.createdAt;

  /// Typed reference to [updatedAt] in this model.
  static final updatedAt = fields.updatedAt;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const DeliverySlotModel(),
    query: const DeliverySlotModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const DeliverySlotModel(),
        query: const DeliverySlotModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'delivery_slots';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => DeliverySlotColumns.values;

  @override
  List<Enum> get formSlots => _DeliverySlotModelFormSlot.values;
}

/// Form-field slots of DeliverySlotModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field DeliverySlot can put on a form.
enum _DeliverySlotModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
}

/// A live, nullable view of an incomplete DeliverySlot draft.
final class DeliverySlotDraft {
  /// Reads values through the session so dependencies stay observable.
  const DeliverySlotDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(DeliverySlotModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(DeliverySlotModel.fields.name);

  /// Date, or null while incomplete.
  BeakDate? get date => _reader.read(DeliverySlotModel.fields.date);

  /// Start Minute, or null while incomplete.
  int? get startMinute => _reader.read(DeliverySlotModel.fields.startMinute);

  /// End Minute, or null while incomplete.
  int? get endMinute => _reader.read(DeliverySlotModel.fields.endMinute);

  /// Capacity, or null while incomplete.
  int? get capacity => _reader.read(DeliverySlotModel.fields.capacity);

  /// Reserved Orders, or null while incomplete.
  int? get reservedOrders =>
      _reader.read(DeliverySlotModel.fields.reservedOrders);

  /// Route Code, or null while incomplete.
  String? get routeCode => _reader.read(DeliverySlotModel.fields.routeCode);

  /// Method, or null while incomplete.
  String? get method => _reader.read(DeliverySlotModel.fields.method);

  /// Active, or null while incomplete.
  bool? get active => _reader.read(DeliverySlotModel.fields.active);

  /// Created, or null while incomplete.
  DateTime? get createdAt => _reader.read(DeliverySlotModel.fields.createdAt);

  /// Updated, or null while incomplete.
  DateTime? get updatedAt => _reader.read(DeliverySlotModel.fields.updatedAt);
}

/// Typed access to live DeliverySlot form values.
extension DeliverySlotDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  DeliverySlotDraft get asDeliverySlot => DeliverySlotDraft(this);
}

/// A typed, zero-cost view over a delivery_slots record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const DeliverySlotRecord._(BeakRecord record) {
  /// Views [record] as a delivery_slots row.
  const DeliverySlotRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => DeliverySlotColumns.id.readFrom(record);

  /// Name.
  String get name => DeliverySlotColumns.name.require(record);

  /// Date.
  BeakDate get date => DeliverySlotModel.fields.date.require(record);

  /// Start minute.
  int get startMinute => DeliverySlotColumns.startMinute.require(record);

  /// End minute.
  int get endMinute => DeliverySlotColumns.endMinute.require(record);

  /// Capacity.
  int get capacity => DeliverySlotColumns.capacity.require(record);

  /// Reserved orders.
  int get reservedOrders => DeliverySlotColumns.reservedOrders.require(record);

  /// Route code.
  String? get routeCode => DeliverySlotColumns.routeCode.readFrom(record);

  /// Method.
  String get method => DeliverySlotColumns.method.require(record);

  /// Active.
  bool get active => DeliverySlotColumns.active.require(record);

  /// When the record was created.
  DateTime? get createdAt => DeliverySlotColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => DeliverySlotColumns.updatedAt.readFrom(record);
}

/// Views any record as a delivery_slots row.
extension DeliverySlotRecordAccess on BeakRecord {
  /// This record, typed as a delivery_slots row.
  DeliverySlotRecord get asDeliverySlot => DeliverySlotRecord.of(this);
}
