// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'order_item.dart';

/// Typed column constants of the order_items resource.
abstract final class OrderItemColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Label.
  static const BeakStringColumn label = BeakStringColumn(
    key: 'label',
    label: 'Label',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// Quantity.
  static const BeakIntColumn quantity = BeakIntColumn(
    key: 'quantity',
    label: 'Quantity',
    rules: [BeakRequired(), BeakMin(1)],
    defaultValue: 1,
    min: 1,
  );

  /// Position.
  static const BeakIntColumn position = BeakIntColumn(
    key: 'position',
    label: 'Position',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 0,
    min: 0,
  );

  /// Unit price cents.
  static const BeakIntColumn unitPriceCents = BeakIntColumn(
    key: 'unit_price_cents',
    label: 'Unit Price Cents',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 0,
    min: 0,
  );

  /// Options price cents.
  static const BeakIntColumn optionsPriceCents = BeakIntColumn(
    key: 'options_price_cents',
    label: 'Options Price Cents',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 0,
    min: 0,
  );

  /// Tax basis points.
  static const BeakIntColumn taxBasisPoints = BeakIntColumn(
    key: 'tax_basis_points',
    label: 'Tax Basis Points',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 1000,
    min: 0,
  );

  /// Variant name.
  static const BeakStringColumn variantName = BeakStringColumn(
    key: 'variant_name',
    label: 'Variant Name',
    defaultValue: '',
  );

  /// Allergens.
  static const BeakStringColumn allergens = BeakStringColumn(
    key: 'allergens',
    label: 'Allergens',
    defaultValue: '',
  );

  /// Food.
  static const BeakBoolColumn food = BeakBoolColumn(
    key: 'food',
    label: 'Food',
    rules: [BeakRequired()],
    defaultValue: true,
  );

  /// Note.
  static const BeakStringColumn note = BeakStringColumn(
    key: 'note',
    label: 'Note',
    defaultValue: '',
  );

  /// Gross cents.
  static const BeakIntColumn grossCents = BeakIntColumn(
    key: 'gross_cents',
    label: 'Gross Cents',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 0,
    min: 0,
  );

  /// Discount cents.
  static const BeakIntColumn discountCents = BeakIntColumn(
    key: 'discount_cents',
    label: 'Discount Cents',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 0,
    min: 0,
  );

  /// Net cents.
  static const BeakIntColumn netCents = BeakIntColumn(
    key: 'net_cents',
    label: 'Net Cents',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 0,
    min: 0,
  );

  /// Tax cents.
  static const BeakIntColumn taxCents = BeakIntColumn(
    key: 'tax_cents',
    label: 'Tax Cents',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 0,
    min: 0,
  );

  /// Foreign key backing [order].
  static const BeakStringColumn orderId = BeakStringColumn(
    key: 'order_id',
    label: 'Order',
    rules: [BeakRequired()],
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [dish].
  static const BeakStringColumn dishId = BeakStringColumn(
    key: 'dish_id',
    label: 'Dish',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [variant].
  static const BeakStringColumn variantId = BeakStringColumn(
    key: 'variant_id',
    label: 'Variant',
    visibleOn: {BeakContext.form},
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    label,
    quantity,
    position,
    unitPriceCents,
    optionsPriceCents,
    taxBasisPoints,
    variantName,
    allergens,
    food,
    note,
    grossCents,
    discountCents,
    netCents,
    taxCents,
    orderId,
    dishId,
    variantId,
    createdAt,
    updatedAt,
  ];
}

/// Typed relationship constants of the order_items resource.
abstract final class OrderItemRelations {
  /// Order.
  static const BeakBelongsTo order = BeakBelongsTo(
    key: 'order',
    label: 'Order',
    relatedTable: 'orders',
    displayColumnKey: 'reference',
    foreignKey: 'order_id',
    searchColumnKeys: ['reference'],
    onDelete: BeakOnDelete.cascade,
  );

  /// Dish.
  static const BeakBelongsTo dish = BeakBelongsTo(
    key: 'dish',
    label: 'Dish',
    relatedTable: 'dishes',
    displayColumnKey: 'name',
    foreignKey: 'dish_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );

  /// Variant.
  static const BeakBelongsTo variant = BeakBelongsTo(
    key: 'variant',
    label: 'Variant',
    relatedTable: 'dish_variants',
    displayColumnKey: 'name',
    foreignKey: 'variant_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );

  /// Options.
  static const BeakHasMany options = BeakHasMany(
    key: 'options',
    label: 'Options',
    relatedTable: 'order_item_options',
    displayColumnKey: 'label',
    foreignKey: 'order_item_id',
    searchColumnKeys: ['label'],
    owned: true,
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for OrderItem.
final class OrderItemFields {
  /// Creates fields rooted at [model], optionally through [path].
  const OrderItemFields({
    BeakModel model = const OrderItemModel(),
    List<BeakRelationship> path = const [],
  }) : _model = model,
       _path = path;
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Label.
  BeakScalarField<String> get label => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.label,
    path: _path,
    isRequired: true,
  );

  /// Quantity.
  BeakScalarField<int> get quantity => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.quantity,
    path: _path,
    isRequired: true,
  );

  /// Position.
  BeakScalarField<int> get position => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.position,
    path: _path,
    isRequired: true,
  );

  /// Unit Price Cents.
  BeakScalarField<int> get unitPriceCents => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.unitPriceCents,
    path: _path,
    isRequired: true,
  );

  /// Options Price Cents.
  BeakScalarField<int> get optionsPriceCents => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.optionsPriceCents,
    path: _path,
    isRequired: true,
  );

  /// Tax Basis Points.
  BeakScalarField<int> get taxBasisPoints => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.taxBasisPoints,
    path: _path,
    isRequired: true,
  );

  /// Variant Name.
  BeakScalarField<String> get variantName => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.variantName,
    path: _path,
    isRequired: false,
  );

  /// Allergens.
  BeakScalarField<String> get allergens => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.allergens,
    path: _path,
    isRequired: false,
  );

  /// Food.
  BeakScalarField<bool> get food => BeakScalarField<bool>(
    model: _model,
    column: OrderItemColumns.food,
    path: _path,
    isRequired: true,
  );

  /// Note.
  BeakScalarField<String> get note => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.note,
    path: _path,
    isRequired: false,
  );

  /// Gross Cents.
  BeakScalarField<int> get grossCents => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.grossCents,
    path: _path,
    isRequired: true,
  );

  /// Discount Cents.
  BeakScalarField<int> get discountCents => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.discountCents,
    path: _path,
    isRequired: true,
  );

  /// Net Cents.
  BeakScalarField<int> get netCents => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.netCents,
    path: _path,
    isRequired: true,
  );

  /// Tax Cents.
  BeakScalarField<int> get taxCents => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.taxCents,
    path: _path,
    isRequired: true,
  );

  /// Order.
  BeakScalarField<String> get orderId => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.orderId,
    path: _path,
    isRequired: true,
  );

  /// Dish.
  BeakScalarField<String> get dishId => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.dishId,
    path: _path,
    isRequired: false,
  );

  /// Variant.
  BeakScalarField<String> get variantId => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.variantId,
    path: _path,
    isRequired: false,
  );

  /// Created.
  BeakScalarField<DateTime> get createdAt => BeakScalarField<DateTime>(
    model: _model,
    column: OrderItemColumns.createdAt,
    path: _path,
    isRequired: false,
  );

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => BeakScalarField<DateTime>(
    model: _model,
    column: OrderItemColumns.updatedAt,
    path: _path,
    isRequired: false,
  );

  /// Order.
  OrderToOneField get order => OrderToOneField(
    model: _model,
    relation: OrderItemRelations.order,
    path: _path,
    isRequired: true,
  );

  /// Dish.
  DishToOneField get dish => DishToOneField(
    model: _model,
    relation: OrderItemRelations.dish,
    path: _path,
    isRequired: false,
  );

  /// Variant.
  DishVariantToOneField get variant => DishVariantToOneField(
    model: _model,
    relation: OrderItemRelations.variant,
    path: _path,
    isRequired: false,
  );

  /// Options.
  BeakToManyField get options => BeakToManyField(
    model: _model,
    relation: OrderItemRelations.options,
    target: const OrderItemOptionModel(),
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to OrderItem, retaining its root owner.
final class OrderItemToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const OrderItemToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const OrderItemModel());

  /// Every target field, including names reserved by the path API.
  OrderItemFields get fields =>
      OrderItemFields(model: model, path: [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Quantity.
  BeakScalarField<int> get quantity => fields.quantity;

  /// Position.
  BeakScalarField<int> get position => fields.position;

  /// Unit Price Cents.
  BeakScalarField<int> get unitPriceCents => fields.unitPriceCents;

  /// Options Price Cents.
  BeakScalarField<int> get optionsPriceCents => fields.optionsPriceCents;

  /// Tax Basis Points.
  BeakScalarField<int> get taxBasisPoints => fields.taxBasisPoints;

  /// Variant Name.
  BeakScalarField<String> get variantName => fields.variantName;

  /// Allergens.
  BeakScalarField<String> get allergens => fields.allergens;

  /// Food.
  BeakScalarField<bool> get food => fields.food;

  /// Note.
  BeakScalarField<String> get note => fields.note;

  /// Gross Cents.
  BeakScalarField<int> get grossCents => fields.grossCents;

  /// Discount Cents.
  BeakScalarField<int> get discountCents => fields.discountCents;

  /// Net Cents.
  BeakScalarField<int> get netCents => fields.netCents;

  /// Tax Cents.
  BeakScalarField<int> get taxCents => fields.taxCents;

  /// Order.
  BeakScalarField<String> get orderId => fields.orderId;

  /// Dish.
  BeakScalarField<String> get dishId => fields.dishId;

  /// Variant.
  BeakScalarField<String> get variantId => fields.variantId;

  /// Created.
  BeakScalarField<DateTime> get createdAt => fields.createdAt;

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => fields.updatedAt;

  /// Order.
  OrderToOneField get order => fields.order;

  /// Dish.
  DishToOneField get dish => fields.dish;

  /// Variant.
  DishVariantToOneField get variant => fields.variant;
}

/// OrderItem configuration shared by the panel and authoritative API.
final class OrderItemModel extends BeakModel {
  /// Creates the order_items model.
  const OrderItemModel();

  /// Typed field and relation references, including reserved names.
  static const OrderItemFields fields = OrderItemFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [label] in this model.
  static final label = fields.label;

  /// Typed reference to [quantity] in this model.
  static final quantity = fields.quantity;

  /// Typed reference to [position] in this model.
  static final position = fields.position;

  /// Typed reference to [unitPriceCents] in this model.
  static final unitPriceCents = fields.unitPriceCents;

  /// Typed reference to [optionsPriceCents] in this model.
  static final optionsPriceCents = fields.optionsPriceCents;

  /// Typed reference to [taxBasisPoints] in this model.
  static final taxBasisPoints = fields.taxBasisPoints;

  /// Typed reference to [variantName] in this model.
  static final variantName = fields.variantName;

  /// Typed reference to [allergens] in this model.
  static final allergens = fields.allergens;

  /// Typed reference to [food] in this model.
  static final food = fields.food;

  /// Typed reference to [note] in this model.
  static final note = fields.note;

  /// Typed reference to [grossCents] in this model.
  static final grossCents = fields.grossCents;

  /// Typed reference to [discountCents] in this model.
  static final discountCents = fields.discountCents;

  /// Typed reference to [netCents] in this model.
  static final netCents = fields.netCents;

  /// Typed reference to [taxCents] in this model.
  static final taxCents = fields.taxCents;

  /// Typed reference to [orderId] in this model.
  static final orderId = fields.orderId;

  /// Typed reference to [dishId] in this model.
  static final dishId = fields.dishId;

  /// Typed reference to [variantId] in this model.
  static final variantId = fields.variantId;

  /// Typed reference to [createdAt] in this model.
  static final createdAt = fields.createdAt;

  /// Typed reference to [updatedAt] in this model.
  static final updatedAt = fields.updatedAt;

  /// Typed reference to [order] in this model.
  static final order = fields.order;

  /// Typed reference to [dish] in this model.
  static final dish = fields.dish;

  /// Typed reference to [variant] in this model.
  static final variant = fields.variant;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const OrderItemModel(),
    query: const OrderItemModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const OrderItemModel(),
        query: const OrderItemModel().query(
          filter: filter,
          search: BeakSearch(term, const ['label']),
        ),
      );

  @override
  String get table => 'order_items';

  @override
  String get displayColumnKey => 'label';

  @override
  List<BeakColumn> get columns => OrderItemColumns.values;
  @override
  List<BeakRecordRule> get validationRules => OrderItem.validationRules;
  @override
  BeakModelBehavior get behavior => OrderItem.behavior;
  @override
  List<BeakModel> get relatedModels => const [
    OrderModel(),
    DishModel(),
    DishVariantModel(),
    OrderItemOptionModel(),
  ];

  @override
  List<BeakRelationship> get relationships => const [
    OrderItemRelations.order,
    OrderItemRelations.dish,
    OrderItemRelations.variant,
    OrderItemRelations.options,
  ];

  @override
  List<Enum> get formSlots => _OrderItemModelFormSlot.values;
}

/// Form-field slots of OrderItemModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field OrderItem can put on a form.
enum _OrderItemModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
  s15,
  s16,
  s17,
  s18,
  s19,
  s20,
  s21,
  s22,
  s23,
}

/// A live, nullable view of an incomplete OrderItem draft.
final class OrderItemDraft {
  /// Reads values through the session so dependencies stay observable.
  const OrderItemDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(OrderItemModel.fields.id);

  /// Label, or null while incomplete.
  String? get label => _reader.read(OrderItemModel.fields.label);

  /// Quantity, or null while incomplete.
  int? get quantity => _reader.read(OrderItemModel.fields.quantity);

  /// Position, or null while incomplete.
  int? get position => _reader.read(OrderItemModel.fields.position);

  /// Unit Price Cents, or null while incomplete.
  int? get unitPriceCents => _reader.read(OrderItemModel.fields.unitPriceCents);

  /// Options Price Cents, or null while incomplete.
  int? get optionsPriceCents =>
      _reader.read(OrderItemModel.fields.optionsPriceCents);

  /// Tax Basis Points, or null while incomplete.
  int? get taxBasisPoints => _reader.read(OrderItemModel.fields.taxBasisPoints);

  /// Variant Name, or null while incomplete.
  String? get variantName => _reader.read(OrderItemModel.fields.variantName);

  /// Allergens, or null while incomplete.
  String? get allergens => _reader.read(OrderItemModel.fields.allergens);

  /// Food, or null while incomplete.
  bool? get food => _reader.read(OrderItemModel.fields.food);

  /// Note, or null while incomplete.
  String? get note => _reader.read(OrderItemModel.fields.note);

  /// Gross Cents, or null while incomplete.
  int? get grossCents => _reader.read(OrderItemModel.fields.grossCents);

  /// Discount Cents, or null while incomplete.
  int? get discountCents => _reader.read(OrderItemModel.fields.discountCents);

  /// Net Cents, or null while incomplete.
  int? get netCents => _reader.read(OrderItemModel.fields.netCents);

  /// Tax Cents, or null while incomplete.
  int? get taxCents => _reader.read(OrderItemModel.fields.taxCents);

  /// Order, or null while incomplete.
  String? get orderId => _reader.read(OrderItemModel.fields.orderId);

  /// Dish, or null while incomplete.
  String? get dishId => _reader.read(OrderItemModel.fields.dishId);

  /// Variant, or null while incomplete.
  String? get variantId => _reader.read(OrderItemModel.fields.variantId);

  /// Created, or null while incomplete.
  DateTime? get createdAt => _reader.read(OrderItemModel.fields.createdAt);

  /// Updated, or null while incomplete.
  DateTime? get updatedAt => _reader.read(OrderItemModel.fields.updatedAt);

  /// The selected order.
  OrderRecord? get order => switch (_reader.read(OrderItemModel.fields.order)) {
    final BeakRecord record => OrderRecord.of(record),
    null => null,
  };

  /// The selected dish.
  DishRecord? get dish => switch (_reader.read(OrderItemModel.fields.dish)) {
    final BeakRecord record => DishRecord.of(record),
    null => null,
  };

  /// The selected variant.
  DishVariantRecord? get variant =>
      switch (_reader.read(OrderItemModel.fields.variant)) {
        final BeakRecord record => DishVariantRecord.of(record),
        null => null,
      };

  /// The selected options.
  List<OrderItemOptionRecord> get options => [
    for (final row
        in _reader.read(OrderItemModel.fields.options) ?? const <BeakRecord>[])
      OrderItemOptionRecord.of(row),
  ];
}

/// Typed access to live OrderItem form values.
extension OrderItemDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  OrderItemDraft get asOrderItem => OrderItemDraft(this);
}

/// A typed, zero-cost view over a order_items record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const OrderItemRecord._(BeakRecord record) {
  /// Views [record] as a order_items row.
  const OrderItemRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => OrderItemColumns.id.readFrom(record);

  /// Label.
  String get label => OrderItemColumns.label.require(record);

  /// Quantity.
  int get quantity => OrderItemColumns.quantity.require(record);

  /// Position.
  int get position => OrderItemColumns.position.require(record);

  /// Unit price cents.
  int get unitPriceCents => OrderItemColumns.unitPriceCents.require(record);

  /// Options price cents.
  int get optionsPriceCents =>
      OrderItemColumns.optionsPriceCents.require(record);

  /// Tax basis points.
  int get taxBasisPoints => OrderItemColumns.taxBasisPoints.require(record);

  /// Variant name.
  String? get variantName => OrderItemColumns.variantName.readFrom(record);

  /// Allergens.
  String? get allergens => OrderItemColumns.allergens.readFrom(record);

  /// Food.
  bool get food => OrderItemColumns.food.require(record);

  /// Note.
  String? get note => OrderItemColumns.note.readFrom(record);

  /// Gross cents.
  int get grossCents => OrderItemColumns.grossCents.require(record);

  /// Discount cents.
  int get discountCents => OrderItemColumns.discountCents.require(record);

  /// Net cents.
  int get netCents => OrderItemColumns.netCents.require(record);

  /// Tax cents.
  int get taxCents => OrderItemColumns.taxCents.require(record);

  /// Foreign key backing [order].
  String get orderId => OrderItemColumns.orderId.require(record);

  /// Foreign key backing [dish].
  String? get dishId => OrderItemColumns.dishId.readFrom(record);

  /// Foreign key backing [variant].
  String? get variantId => OrderItemColumns.variantId.readFrom(record);

  /// When the record was created.
  DateTime? get createdAt => OrderItemColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => OrderItemColumns.updatedAt.readFrom(record);

  /// The eager-loaded order, or null when unloaded or unset.
  OrderRecord? get order => switch (record.relations['order']) {
    [final BeakRecord first, ...] => OrderRecord.of(first),
    _ => null,
  };

  /// The eager-loaded dish, or null when unloaded or unset.
  DishRecord? get dish => switch (record.relations['dish']) {
    [final BeakRecord first, ...] => DishRecord.of(first),
    _ => null,
  };

  /// The eager-loaded variant, or null when unloaded or unset.
  DishVariantRecord? get variant => switch (record.relations['variant']) {
    [final BeakRecord first, ...] => DishVariantRecord.of(first),
    _ => null,
  };

  /// The eager-loaded options.
  List<OrderItemOptionRecord> get options => [
    for (final row in record.relations['options'] ?? const <BeakRecord>[])
      OrderItemOptionRecord.of(row),
  ];
}

/// Views any record as a order_items row.
extension OrderItemRecordAccess on BeakRecord {
  /// This record, typed as a order_items row.
  OrderItemRecord get asOrderItem => OrderItemRecord.of(this);
}
