// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'organization.dart';

/// Typed column constants of the organizations resource.
abstract final class OrganizationColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// Legal name.
  static const BeakStringColumn legalName = BeakStringColumn(
    key: 'legal_name',
    label: 'Legal Name',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// Billing email.
  static const BeakStringColumn billingEmail = BeakStringColumn(
    key: 'billing_email',
    label: 'Billing Email',
    rules: [BeakRequired(), BeakEmail()],
  );

  /// Billing address.
  static const BeakStringColumn billingAddress = BeakStringColumn(
    key: 'billing_address',
    label: 'Billing Address',
    rules: [BeakRequired()],
  );

  /// Invoice frequency.
  static const BeakStringColumn invoiceFrequency = BeakStringColumn(
    key: 'invoice_frequency',
    label: 'Invoice Frequency',
    rules: [BeakRequired()],
    defaultValue: 'monthly',
  );

  /// Cost centers.
  static const BeakStringColumn costCenters = BeakStringColumn(
    key: 'cost_centers',
    label: 'Cost Centers',
    rules: [BeakRequired()],
    defaultValue: '4100 Marketing,4200 Sales,1100 Administration',
  );

  /// Default budget cents.
  static const BeakIntColumn defaultBudgetCents = BeakIntColumn(
    key: 'default_budget_cents',
    label: 'Default Budget Cents',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 12000,
  );

  /// Approval threshold cents.
  static const BeakIntColumn approvalThresholdCents = BeakIntColumn(
    key: 'approval_threshold_cents',
    label: 'Approval Threshold Cents',
    rules: [BeakRequired(), BeakMin(0)],
    defaultValue: 4000,
  );

  /// Active.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
    rules: [BeakRequired()],
    defaultValue: true,
  );

  /// Foreign key backing [approver].
  static const BeakStringColumn approverId = BeakStringColumn(
    key: 'approver_id',
    label: 'Approver',
    visibleOn: {BeakContext.form},
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    legalName,
    billingEmail,
    billingAddress,
    invoiceFrequency,
    costCenters,
    defaultBudgetCents,
    approvalThresholdCents,
    active,
    approverId,
    createdAt,
    updatedAt,
  ];
}

/// Typed relationship constants of the organizations resource.
abstract final class OrganizationRelations {
  /// Collective invoices let order previews identify an existing draft period.
  static const BeakHasMany invoices = BeakHasMany(
    key: 'invoices',
    label: 'Invoices',
    relatedTable: 'invoices',
    displayColumnKey: 'reference',
    foreignKey: 'organization_id',
    searchColumnKeys: ['reference'],
  );

  /// Approver.
  static const BeakBelongsTo approver = BeakBelongsTo(
    key: 'approver',
    label: 'Approver',
    relatedTable: 'staff_members',
    displayColumnKey: 'name',
    foreignKey: 'approver_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );
}

/// Typed configuration references for Organization.
final class OrganizationFields {
  /// Creates fields rooted at [model], optionally through [path].
  const OrganizationFields({
    BeakModel model = const OrganizationModel(),
    List<BeakRelationship> path = const [],
  }) : _model = model,
       _path = path;
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: OrganizationColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: OrganizationColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Legal Name.
  BeakScalarField<String> get legalName => BeakScalarField<String>(
    model: _model,
    column: OrganizationColumns.legalName,
    path: _path,
    isRequired: true,
  );

  /// Billing Email.
  BeakScalarField<String> get billingEmail => BeakScalarField<String>(
    model: _model,
    column: OrganizationColumns.billingEmail,
    path: _path,
    isRequired: true,
  );

  /// Billing Address.
  BeakScalarField<String> get billingAddress => BeakScalarField<String>(
    model: _model,
    column: OrganizationColumns.billingAddress,
    path: _path,
    isRequired: true,
  );

  /// Invoice Frequency.
  BeakScalarField<String> get invoiceFrequency => BeakScalarField<String>(
    model: _model,
    column: OrganizationColumns.invoiceFrequency,
    path: _path,
    isRequired: true,
  );

  /// Cost Centers.
  BeakScalarField<String> get costCenters => BeakScalarField<String>(
    model: _model,
    column: OrganizationColumns.costCenters,
    path: _path,
    isRequired: true,
  );

  /// Default Budget Cents.
  BeakScalarField<int> get defaultBudgetCents => BeakScalarField<int>(
    model: _model,
    column: OrganizationColumns.defaultBudgetCents,
    path: _path,
    isRequired: true,
  );

  /// Approval Threshold Cents.
  BeakScalarField<int> get approvalThresholdCents => BeakScalarField<int>(
    model: _model,
    column: OrganizationColumns.approvalThresholdCents,
    path: _path,
    isRequired: true,
  );

  /// Active.
  BeakScalarField<bool> get active => BeakScalarField<bool>(
    model: _model,
    column: OrganizationColumns.active,
    path: _path,
    isRequired: true,
  );

  /// Approver.
  BeakScalarField<String> get approverId => BeakScalarField<String>(
    model: _model,
    column: OrganizationColumns.approverId,
    path: _path,
    isRequired: false,
  );

  /// Created.
  BeakScalarField<DateTime> get createdAt => BeakScalarField<DateTime>(
    model: _model,
    column: OrganizationColumns.createdAt,
    path: _path,
    isRequired: false,
  );

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => BeakScalarField<DateTime>(
    model: _model,
    column: OrganizationColumns.updatedAt,
    path: _path,
    isRequired: false,
  );

  /// Invoices.
  BeakToManyField get invoices => BeakToManyField(
    model: _model,
    relation: OrganizationRelations.invoices,
    target: const InvoiceModel(),
    path: _path,
    isRequired: false,
  );

  /// Approver.
  StaffMemberToOneField get approver => StaffMemberToOneField(
    model: _model,
    relation: OrganizationRelations.approver,
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to Organization, retaining its root owner.
final class OrganizationToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const OrganizationToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const OrganizationModel());

  /// Every target field, including names reserved by the path API.
  OrganizationFields get fields =>
      OrganizationFields(model: model, path: [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Legal Name.
  BeakScalarField<String> get legalName => fields.legalName;

  /// Billing Email.
  BeakScalarField<String> get billingEmail => fields.billingEmail;

  /// Billing Address.
  BeakScalarField<String> get billingAddress => fields.billingAddress;

  /// Invoice Frequency.
  BeakScalarField<String> get invoiceFrequency => fields.invoiceFrequency;

  /// Cost Centers.
  BeakScalarField<String> get costCenters => fields.costCenters;

  /// Default Budget Cents.
  BeakScalarField<int> get defaultBudgetCents => fields.defaultBudgetCents;

  /// Approval Threshold Cents.
  BeakScalarField<int> get approvalThresholdCents =>
      fields.approvalThresholdCents;

  /// Active.
  BeakScalarField<bool> get active => fields.active;

  /// Approver.
  BeakScalarField<String> get approverId => fields.approverId;

  /// Created.
  BeakScalarField<DateTime> get createdAt => fields.createdAt;

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => fields.updatedAt;

  /// Invoices.
  BeakToManyField get invoices => fields.invoices;

  /// Approver.
  StaffMemberToOneField get approver => fields.approver;
}

/// Organization configuration shared by the panel and authoritative API.
final class OrganizationModel extends BeakModel {
  /// Creates the organizations model.
  const OrganizationModel();

  /// Typed field and relation references, including reserved names.
  static const OrganizationFields fields = OrganizationFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [legalName] in this model.
  static final legalName = fields.legalName;

  /// Typed reference to [billingEmail] in this model.
  static final billingEmail = fields.billingEmail;

  /// Typed reference to [billingAddress] in this model.
  static final billingAddress = fields.billingAddress;

  /// Typed reference to [invoiceFrequency] in this model.
  static final invoiceFrequency = fields.invoiceFrequency;

  /// Typed reference to [costCenters] in this model.
  static final costCenters = fields.costCenters;

  /// Typed reference to [defaultBudgetCents] in this model.
  static final defaultBudgetCents = fields.defaultBudgetCents;

  /// Typed reference to [approvalThresholdCents] in this model.
  static final approvalThresholdCents = fields.approvalThresholdCents;

  /// Typed reference to [active] in this model.
  static final active = fields.active;

  /// Typed reference to [approverId] in this model.
  static final approverId = fields.approverId;

  /// Typed reference to [createdAt] in this model.
  static final createdAt = fields.createdAt;

  /// Typed reference to [updatedAt] in this model.
  static final updatedAt = fields.updatedAt;

  /// Typed reference to [invoices] in this model.
  static final invoices = fields.invoices;

  /// Typed reference to [approver] in this model.
  static final approver = fields.approver;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const OrganizationModel(),
    query: const OrganizationModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const OrganizationModel(),
        query: const OrganizationModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name', 'legal_name']),
        ),
      );

  @override
  String get table => 'organizations';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => OrganizationColumns.values;
  @override
  List<BeakModel> get relatedModels => const [
    InvoiceModel(),
    StaffMemberModel(),
  ];

  @override
  List<BeakRelationship> get relationships => const [
    OrganizationRelations.invoices,
    OrganizationRelations.approver,
  ];

  @override
  List<Enum> get formSlots => _OrganizationModelFormSlot.values;
}

/// Form-field slots of OrganizationModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Organization can put on a form.
enum _OrganizationModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
}

/// A live, nullable view of an incomplete Organization draft.
final class OrganizationDraft {
  /// Reads values through the session so dependencies stay observable.
  const OrganizationDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(OrganizationModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(OrganizationModel.fields.name);

  /// Legal Name, or null while incomplete.
  String? get legalName => _reader.read(OrganizationModel.fields.legalName);

  /// Billing Email, or null while incomplete.
  String? get billingEmail =>
      _reader.read(OrganizationModel.fields.billingEmail);

  /// Billing Address, or null while incomplete.
  String? get billingAddress =>
      _reader.read(OrganizationModel.fields.billingAddress);

  /// Invoice Frequency, or null while incomplete.
  String? get invoiceFrequency =>
      _reader.read(OrganizationModel.fields.invoiceFrequency);

  /// Cost Centers, or null while incomplete.
  String? get costCenters => _reader.read(OrganizationModel.fields.costCenters);

  /// Default Budget Cents, or null while incomplete.
  int? get defaultBudgetCents =>
      _reader.read(OrganizationModel.fields.defaultBudgetCents);

  /// Approval Threshold Cents, or null while incomplete.
  int? get approvalThresholdCents =>
      _reader.read(OrganizationModel.fields.approvalThresholdCents);

  /// Active, or null while incomplete.
  bool? get active => _reader.read(OrganizationModel.fields.active);

  /// Approver, or null while incomplete.
  String? get approverId => _reader.read(OrganizationModel.fields.approverId);

  /// Created, or null while incomplete.
  DateTime? get createdAt => _reader.read(OrganizationModel.fields.createdAt);

  /// Updated, or null while incomplete.
  DateTime? get updatedAt => _reader.read(OrganizationModel.fields.updatedAt);

  /// The selected invoices.
  List<InvoiceRecord> get invoices => [
    for (final row
        in _reader.read(OrganizationModel.fields.invoices) ??
            const <BeakRecord>[])
      InvoiceRecord.of(row),
  ];

  /// The selected approver.
  StaffMemberRecord? get approver =>
      switch (_reader.read(OrganizationModel.fields.approver)) {
        final BeakRecord record => StaffMemberRecord.of(record),
        null => null,
      };
}

/// Typed access to live Organization form values.
extension OrganizationDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  OrganizationDraft get asOrganization => OrganizationDraft(this);
}

/// A typed, zero-cost view over a organizations record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const OrganizationRecord._(BeakRecord record) {
  /// Views [record] as a organizations row.
  const OrganizationRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => OrganizationColumns.id.readFrom(record);

  /// Name.
  String get name => OrganizationColumns.name.require(record);

  /// Legal name.
  String get legalName => OrganizationColumns.legalName.require(record);

  /// Billing email.
  String get billingEmail => OrganizationColumns.billingEmail.require(record);

  /// Billing address.
  String get billingAddress =>
      OrganizationColumns.billingAddress.require(record);

  /// Invoice frequency.
  String get invoiceFrequency =>
      OrganizationColumns.invoiceFrequency.require(record);

  /// Cost centers.
  String get costCenters => OrganizationColumns.costCenters.require(record);

  /// Default budget cents.
  int get defaultBudgetCents =>
      OrganizationColumns.defaultBudgetCents.require(record);

  /// Approval threshold cents.
  int get approvalThresholdCents =>
      OrganizationColumns.approvalThresholdCents.require(record);

  /// Active.
  bool get active => OrganizationColumns.active.require(record);

  /// Foreign key backing [approver].
  String? get approverId => OrganizationColumns.approverId.readFrom(record);

  /// When the record was created.
  DateTime? get createdAt => OrganizationColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => OrganizationColumns.updatedAt.readFrom(record);

  /// The eager-loaded invoices.
  List<InvoiceRecord> get invoices => [
    for (final row in record.relations['invoices'] ?? const <BeakRecord>[])
      InvoiceRecord.of(row),
  ];

  /// The eager-loaded approver, or null when unloaded or unset.
  StaffMemberRecord? get approver => switch (record.relations['approver']) {
    [final BeakRecord first, ...] => StaffMemberRecord.of(first),
    _ => null,
  };
}

/// Views any record as a organizations row.
extension OrganizationRecordAccess on BeakRecord {
  /// This record, typed as a organizations row.
  OrganizationRecord get asOrganization => OrganizationRecord.of(this);
}
