// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'payment_method.dart';

/// Typed column constants of the payment_methods resource.
abstract final class PaymentMethodColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// Kind.
  static const BeakStringColumn kind = BeakStringColumn(
    key: 'kind',
    label: 'Kind',
    rules: [BeakRequired()],
    defaultValue: 'card',
  );

  /// Last four.
  static const BeakStringColumn lastFour = BeakStringColumn(
    key: 'last_four',
    label: 'Last Four',
    rules: [BeakRequired()],
    defaultValue: '4242',
  );

  /// Provider token.
  static const BeakStringColumn providerToken = BeakStringColumn(
    key: 'provider_token',
    label: 'Provider Token',
    rules: [BeakRequired()],
    defaultValue: 'demo_visa_4242',
  );

  /// Demo outcome.
  static const BeakStringColumn demoOutcome = BeakStringColumn(
    key: 'demo_outcome',
    label: 'Demo Outcome',
    rules: [BeakRequired()],
    defaultValue: 'succeeded',
  );

  /// Is default.
  static const BeakBoolColumn isDefault = BeakBoolColumn(
    key: 'is_default',
    label: 'Is Default',
    rules: [BeakRequired()],
    defaultValue: true,
  );

  /// Active.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
    rules: [BeakRequired()],
    defaultValue: true,
  );

  /// Foreign key backing [customer].
  static const BeakStringColumn customerId = BeakStringColumn(
    key: 'customer_id',
    label: 'Customer',
    rules: [BeakRequired()],
    visibleOn: {BeakContext.form},
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    kind,
    lastFour,
    providerToken,
    demoOutcome,
    isDefault,
    active,
    customerId,
    createdAt,
    updatedAt,
  ];
}

/// Typed relationship constants of the payment_methods resource.
abstract final class PaymentMethodRelations {
  /// Customer.
  static const BeakBelongsTo customer = BeakBelongsTo(
    key: 'customer',
    label: 'Customer',
    relatedTable: 'customers',
    displayColumnKey: 'name',
    foreignKey: 'customer_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );
}

/// Typed configuration references for PaymentMethod.
final class PaymentMethodFields {
  /// Creates the fields of PaymentMethod, rooted at its own model.
  const PaymentMethodFields()
    : _model = const PaymentMethodModel(),
      _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const PaymentMethodFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: PaymentMethodColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: PaymentMethodColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Kind.
  BeakScalarField<String> get kind => BeakScalarField<String>(
    model: _model,
    column: PaymentMethodColumns.kind,
    path: _path,
    isRequired: true,
  );

  /// Last Four.
  BeakScalarField<String> get lastFour => BeakScalarField<String>(
    model: _model,
    column: PaymentMethodColumns.lastFour,
    path: _path,
    isRequired: true,
  );

  /// Provider Token.
  BeakScalarField<String> get providerToken => BeakScalarField<String>(
    model: _model,
    column: PaymentMethodColumns.providerToken,
    path: _path,
    isRequired: true,
  );

  /// Demo Outcome.
  BeakScalarField<String> get demoOutcome => BeakScalarField<String>(
    model: _model,
    column: PaymentMethodColumns.demoOutcome,
    path: _path,
    isRequired: true,
  );

  /// Is Default.
  BeakScalarField<bool> get isDefault => BeakScalarField<bool>(
    model: _model,
    column: PaymentMethodColumns.isDefault,
    path: _path,
    isRequired: true,
  );

  /// Active.
  BeakScalarField<bool> get active => BeakScalarField<bool>(
    model: _model,
    column: PaymentMethodColumns.active,
    path: _path,
    isRequired: true,
  );

  /// Customer.
  BeakScalarField<String> get customerId => BeakScalarField<String>(
    model: _model,
    column: PaymentMethodColumns.customerId,
    path: _path,
    isRequired: true,
  );

  /// Created.
  BeakScalarField<DateTime> get createdAt => BeakScalarField<DateTime>(
    model: _model,
    column: PaymentMethodColumns.createdAt,
    path: _path,
    isRequired: false,
  );

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => BeakScalarField<DateTime>(
    model: _model,
    column: PaymentMethodColumns.updatedAt,
    path: _path,
    isRequired: false,
  );

  /// Customer.
  CustomerToOneField get customer => CustomerToOneField(
    model: _model,
    relation: PaymentMethodRelations.customer,
    path: _path,
    isRequired: true,
  );
}

/// A to-one path to PaymentMethod, retaining its root owner.
final class PaymentMethodToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const PaymentMethodToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const PaymentMethodModel());

  /// Every target field, including names reserved by the path API.
  PaymentMethodFields get fields =>
      PaymentMethodFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Kind.
  BeakScalarField<String> get kind => fields.kind;

  /// Last Four.
  BeakScalarField<String> get lastFour => fields.lastFour;

  /// Provider Token.
  BeakScalarField<String> get providerToken => fields.providerToken;

  /// Demo Outcome.
  BeakScalarField<String> get demoOutcome => fields.demoOutcome;

  /// Is Default.
  BeakScalarField<bool> get isDefault => fields.isDefault;

  /// Active.
  BeakScalarField<bool> get active => fields.active;

  /// Customer.
  BeakScalarField<String> get customerId => fields.customerId;

  /// Created.
  BeakScalarField<DateTime> get createdAt => fields.createdAt;

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => fields.updatedAt;

  /// Customer.
  CustomerToOneField get customer => fields.customer;
}

/// PaymentMethod configuration shared by the panel and authoritative API.
final class PaymentMethodModel extends BeakModel {
  /// Creates the payment_methods model.
  const PaymentMethodModel();

  /// Typed field and relation references, including reserved names.
  static const PaymentMethodFields fields = PaymentMethodFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [kind] in this model.
  static final kind = fields.kind;

  /// Typed reference to [lastFour] in this model.
  static final lastFour = fields.lastFour;

  /// Typed reference to [providerToken] in this model.
  static final providerToken = fields.providerToken;

  /// Typed reference to [demoOutcome] in this model.
  static final demoOutcome = fields.demoOutcome;

  /// Typed reference to [isDefault] in this model.
  static final isDefault = fields.isDefault;

  /// Typed reference to [active] in this model.
  static final active = fields.active;

  /// Typed reference to [customerId] in this model.
  static final customerId = fields.customerId;

  /// Typed reference to [createdAt] in this model.
  static final createdAt = fields.createdAt;

  /// Typed reference to [updatedAt] in this model.
  static final updatedAt = fields.updatedAt;

  /// Typed reference to [customer] in this model.
  static final customer = fields.customer;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const PaymentMethodModel(),
    query: const PaymentMethodModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const PaymentMethodModel(),
        query: const PaymentMethodModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'payment_methods';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => PaymentMethodColumns.values;
  @override
  List<BeakModel> get relatedModels => const [CustomerModel()];

  @override
  List<BeakRelationship> get relationships => const [
    PaymentMethodRelations.customer,
  ];

  @override
  List<Enum> get formSlots => _PaymentMethodModelFormSlot.values;
}

/// Form-field slots of PaymentMethodModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field PaymentMethod can put on a form.
enum _PaymentMethodModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
}

/// A live, nullable view of an incomplete PaymentMethod draft.
final class PaymentMethodDraft {
  /// Reads values through the session so dependencies stay observable.
  const PaymentMethodDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(PaymentMethodModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(PaymentMethodModel.fields.name);

  /// Kind, or null while incomplete.
  String? get kind => _reader.read(PaymentMethodModel.fields.kind);

  /// Last Four, or null while incomplete.
  String? get lastFour => _reader.read(PaymentMethodModel.fields.lastFour);

  /// Provider Token, or null while incomplete.
  String? get providerToken =>
      _reader.read(PaymentMethodModel.fields.providerToken);

  /// Demo Outcome, or null while incomplete.
  String? get demoOutcome =>
      _reader.read(PaymentMethodModel.fields.demoOutcome);

  /// Is Default, or null while incomplete.
  bool? get isDefault => _reader.read(PaymentMethodModel.fields.isDefault);

  /// Active, or null while incomplete.
  bool? get active => _reader.read(PaymentMethodModel.fields.active);

  /// Customer, or null while incomplete.
  String? get customerId => _reader.read(PaymentMethodModel.fields.customerId);

  /// Created, or null while incomplete.
  DateTime? get createdAt => _reader.read(PaymentMethodModel.fields.createdAt);

  /// Updated, or null while incomplete.
  DateTime? get updatedAt => _reader.read(PaymentMethodModel.fields.updatedAt);

  /// The selected customer.
  CustomerRecord? get customer =>
      switch (_reader.read(PaymentMethodModel.fields.customer)) {
        final BeakRecord record => CustomerRecord.of(record),
        null => null,
      };
}

/// Typed access to live PaymentMethod form values.
extension PaymentMethodDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  PaymentMethodDraft get asPaymentMethod => PaymentMethodDraft(this);
}

/// A typed, zero-cost view over a payment_methods record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const PaymentMethodRecord._(BeakRecord record) {
  /// Views [record] as a payment_methods row.
  const PaymentMethodRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => PaymentMethodColumns.id.readFrom(record);

  /// Name.
  String get name => PaymentMethodColumns.name.require(record);

  /// Kind.
  String get kind => PaymentMethodColumns.kind.require(record);

  /// Last four.
  String get lastFour => PaymentMethodColumns.lastFour.require(record);

  /// Provider token.
  String get providerToken =>
      PaymentMethodColumns.providerToken.require(record);

  /// Demo outcome.
  String get demoOutcome => PaymentMethodColumns.demoOutcome.require(record);

  /// Is default.
  bool get isDefault => PaymentMethodColumns.isDefault.require(record);

  /// Active.
  bool get active => PaymentMethodColumns.active.require(record);

  /// Foreign key backing [customer].
  String get customerId => PaymentMethodColumns.customerId.require(record);

  /// When the record was created.
  DateTime? get createdAt => PaymentMethodColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => PaymentMethodColumns.updatedAt.readFrom(record);

  /// The eager-loaded customer, or null when unloaded or unset.
  CustomerRecord? get customer => switch (record.relations['customer']) {
    [final BeakRecord first, ...] => CustomerRecord.of(first),
    _ => null,
  };
}

/// Views any record as a payment_methods row.
extension PaymentMethodRecordAccess on BeakRecord {
  /// This record, typed as a payment_methods row.
  PaymentMethodRecord get asPaymentMethod => PaymentMethodRecord.of(this);
}
