// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'staff_member.dart';

/// Typed column constants of the staff_members resource.
abstract final class StaffMemberColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// Email.
  static const BeakStringColumn email = BeakStringColumn(
    key: 'email',
    label: 'Email',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// Role.
  static const BeakStringColumn role = BeakStringColumn(
    key: 'role',
    label: 'Role',
    rules: [BeakRequired()],
    defaultValue: 'administrator',
  );

  /// Active.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
    rules: [BeakRequired()],
    defaultValue: true,
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    email,
    role,
    active,
    createdAt,
    updatedAt,
  ];
}

/// Typed configuration references for StaffMember.
final class StaffMemberFields {
  /// Creates the fields of StaffMember, rooted at its own model.
  const StaffMemberFields()
    : _model = const StaffMemberModel(),
      _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const StaffMemberFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: StaffMemberColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: StaffMemberColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Email.
  BeakScalarField<String> get email => BeakScalarField<String>(
    model: _model,
    column: StaffMemberColumns.email,
    path: _path,
    isRequired: true,
  );

  /// Role.
  BeakScalarField<String> get role => BeakScalarField<String>(
    model: _model,
    column: StaffMemberColumns.role,
    path: _path,
    isRequired: true,
  );

  /// Active.
  BeakScalarField<bool> get active => BeakScalarField<bool>(
    model: _model,
    column: StaffMemberColumns.active,
    path: _path,
    isRequired: true,
  );

  /// Created.
  BeakScalarField<DateTime> get createdAt => BeakScalarField<DateTime>(
    model: _model,
    column: StaffMemberColumns.createdAt,
    path: _path,
    isRequired: false,
  );

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => BeakScalarField<DateTime>(
    model: _model,
    column: StaffMemberColumns.updatedAt,
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to StaffMember, retaining its root owner.
final class StaffMemberToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const StaffMemberToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const StaffMemberModel());

  /// Every target field, including names reserved by the path API.
  StaffMemberFields get fields =>
      StaffMemberFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Email.
  BeakScalarField<String> get email => fields.email;

  /// Role.
  BeakScalarField<String> get role => fields.role;

  /// Active.
  BeakScalarField<bool> get active => fields.active;

  /// Created.
  BeakScalarField<DateTime> get createdAt => fields.createdAt;

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => fields.updatedAt;
}

/// StaffMember configuration shared by the panel and authoritative API.
final class StaffMemberModel extends BeakModel {
  /// Creates the staff_members model.
  const StaffMemberModel();

  /// Typed field and relation references, including reserved names.
  static const StaffMemberFields fields = StaffMemberFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [email] in this model.
  static final email = fields.email;

  /// Typed reference to [role] in this model.
  static final role = fields.role;

  /// Typed reference to [active] in this model.
  static final active = fields.active;

  /// Typed reference to [createdAt] in this model.
  static final createdAt = fields.createdAt;

  /// Typed reference to [updatedAt] in this model.
  static final updatedAt = fields.updatedAt;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const StaffMemberModel(),
    query: const StaffMemberModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const StaffMemberModel(),
        query: const StaffMemberModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name', 'email']),
        ),
      );

  @override
  String get table => 'staff_members';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => StaffMemberColumns.values;

  @override
  List<Enum> get formSlots => _StaffMemberModelFormSlot.values;
}

/// Form-field slots of StaffMemberModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field StaffMember can put on a form.
enum _StaffMemberModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
}

/// A live, nullable view of an incomplete StaffMember draft.
final class StaffMemberDraft {
  /// Reads values through the session so dependencies stay observable.
  const StaffMemberDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(StaffMemberModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(StaffMemberModel.fields.name);

  /// Email, or null while incomplete.
  String? get email => _reader.read(StaffMemberModel.fields.email);

  /// Role, or null while incomplete.
  String? get role => _reader.read(StaffMemberModel.fields.role);

  /// Active, or null while incomplete.
  bool? get active => _reader.read(StaffMemberModel.fields.active);

  /// Created, or null while incomplete.
  DateTime? get createdAt => _reader.read(StaffMemberModel.fields.createdAt);

  /// Updated, or null while incomplete.
  DateTime? get updatedAt => _reader.read(StaffMemberModel.fields.updatedAt);
}

/// Typed access to live StaffMember form values.
extension StaffMemberDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  StaffMemberDraft get asStaffMember => StaffMemberDraft(this);
}

/// A typed, zero-cost view over a staff_members record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const StaffMemberRecord._(BeakRecord record) {
  /// Views [record] as a staff_members row.
  const StaffMemberRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => StaffMemberColumns.id.readFrom(record);

  /// Name.
  String get name => StaffMemberColumns.name.require(record);

  /// Email.
  String get email => StaffMemberColumns.email.require(record);

  /// Role.
  String get role => StaffMemberColumns.role.require(record);

  /// Active.
  bool get active => StaffMemberColumns.active.require(record);

  /// When the record was created.
  DateTime? get createdAt => StaffMemberColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => StaffMemberColumns.updatedAt.readFrom(record);
}

/// Views any record as a staff_members row.
extension StaffMemberRecordAccess on BeakRecord {
  /// This record, typed as a staff_members row.
  StaffMemberRecord get asStaffMember => StaffMemberRecord.of(this);
}
