// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'profile.dart';

/// Typed column constants of the profiles resource.
abstract final class ProfileColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// A reusable delivery profile.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired(), BeakMaxLength(120)],
    searchable: true,
    maxLength: 120,
  );

  /// Delivery address for this profile.
  static const BeakStringColumn address = BeakStringColumn(
    key: 'address',
    label: 'Address',
    rules: [BeakRequired()],
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [id, name, address];
}

/// Typed configuration references for Profile.
final class ProfileFields {
  /// Creates the fields of Profile, rooted at its own model.
  const ProfileFields() : _model = const ProfileModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const ProfileFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: ProfileColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: ProfileColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Address.
  BeakScalarField<String> get address => BeakScalarField<String>(
    model: _model,
    column: ProfileColumns.address,
    path: _path,
    isRequired: true,
  );
}

/// A to-one path to Profile, retaining its root owner.
final class ProfileToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const ProfileToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const ProfileModel());

  /// Every target field, including names reserved by the path API.
  ProfileFields get fields => ProfileFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Address.
  BeakScalarField<String> get address => fields.address;
}

/// Profile schema; all metadata and typed helpers are generated.
final class ProfileModel extends BeakModel {
  /// Creates the profiles model.
  const ProfileModel();

  /// Typed field and relation references, including reserved names.
  static const ProfileFields fields = ProfileFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [address] in this model.
  static final address = fields.address;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const ProfileModel(),
    query: const ProfileModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const ProfileModel(),
        query: const ProfileModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'profiles';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => ProfileColumns.values;

  @override
  List<Enum> get formSlots => _ProfileModelFormSlot.values;
}

/// Form-field slots of ProfileModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Profile can put on a form.
enum _ProfileModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
}

/// A live, nullable view of an incomplete Profile draft.
final class ProfileDraft {
  /// Reads values through the session so dependencies stay observable.
  const ProfileDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(ProfileModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(ProfileModel.fields.name);

  /// Address, or null while incomplete.
  String? get address => _reader.read(ProfileModel.fields.address);
}

/// Typed access to live Profile form values.
extension ProfileDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  ProfileDraft get asProfile => ProfileDraft(this);
}

/// A typed, zero-cost view over a profiles record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const ProfileRecord._(BeakRecord record) {
  /// Views [record] as a profiles row.
  const ProfileRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => ProfileColumns.id.readFrom(record);

  /// A reusable delivery profile.
  String get name => ProfileColumns.name.require(record);

  /// Delivery address for this profile.
  String get address => ProfileColumns.address.require(record);
}

/// Views any record as a profiles row.
extension ProfileRecordAccess on BeakRecord {
  /// This record, typed as a profiles row.
  ProfileRecord get asProfile => ProfileRecord.of(this);
}
