// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'file_share.dart';

/// Typed column constants of the file_shares resource.
abstract final class FileShareColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The granted permission.
  static const BeakEnumColumn<SharePermission> permission =
      BeakEnumColumn<SharePermission>(
        key: 'permission',
        label: 'Permission',
        filterable: true,
        defaultValue: SharePermission.view,
        badgeColors: {
          SharePermission.view: BeakColor.muted,
          SharePermission.comment: BeakColor.info,
          SharePermission.edit: BeakColor.success,
        },
        values: SharePermission.values,
      );

  /// When the file was shared.
  static const BeakDateTimeColumn sharedAt = BeakDateTimeColumn(
    key: 'shared_at',
    label: 'Shared',
    format: BeakDateFormat.relative,
    sortable: true,
  );

  /// Foreign key backing [file].
  static const BeakStringColumn fileId = BeakStringColumn(
    key: 'file_id',
    label: 'File',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [sharedWith].
  static const BeakStringColumn sharedWithId = BeakStringColumn(
    key: 'shared_with_id',
    label: 'Shared with',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    permission,
    sharedAt,
    fileId,
    sharedWithId,
  ];
}

/// Typed relationship constants of the file_shares resource.
abstract final class FileShareRelations {
  /// The shared file.
  static const BeakBelongsTo file = BeakBelongsTo(
    key: 'file',
    label: 'File',
    relatedTable: 'files',
    displayColumnKey: 'name',
    foreignKey: 'file_id',
    searchColumnKeys: ['name'],
  );

  /// The user the file is shared with.
  static const BeakBelongsTo sharedWith = BeakBelongsTo(
    key: 'sharedWith',
    label: 'Shared with',
    relatedTable: 'users',
    displayColumnKey: 'name',
    foreignKey: 'shared_with_id',
    searchColumnKeys: ['name'],
  );
}

/// The file-shares resource — a file granted to a user with a permission.
final class FileShareModel extends BeakModel {
  /// Creates the file_shares model.
  const FileShareModel();

  @override
  String get table => 'file_shares';

  @override
  String get displayColumnKey => 'permission';

  @override
  List<BeakColumn> get columns => FileShareColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    FileShareRelations.file,
    FileShareRelations.sharedWith,
  ];

  @override
  List<Enum> get formSlots => _FileShareModelFormSlot.values;
}

/// Form-field slots of FileShareModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field FileShare can put on a form.
enum _FileShareModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
}

/// A typed, zero-cost view over a file_shares record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const FileShareRecord._(BeakRecord record) {
  /// Views [record] as a file_shares row.
  const FileShareRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => FileShareColumns.id.readFrom(record);

  /// The granted permission.
  SharePermission? get permission =>
      FileShareColumns.permission.readFrom(record);

  /// When the file was shared.
  DateTime? get sharedAt => FileShareColumns.sharedAt.readFrom(record);

  /// Foreign key backing [file].
  String? get fileId => FileShareColumns.fileId.readFrom(record);

  /// Foreign key backing [sharedWith].
  String? get sharedWithId => FileShareColumns.sharedWithId.readFrom(record);

  /// The eager-loaded file, or null when unloaded or unset.
  ManagedFileRecord? get file => switch (record.relations['file']) {
    [final BeakRecord first, ...] => ManagedFileRecord.of(first),
    _ => null,
  };

  /// The eager-loaded shared with, or null when unloaded or unset.
  UserRecord? get sharedWith => switch (record.relations['sharedWith']) {
    [final BeakRecord first, ...] => UserRecord.of(first),
    _ => null,
  };
}

/// Views any record as a file_shares row.
extension FileShareRecordAccess on BeakRecord {
  /// This record, typed as a file_shares row.
  FileShareRecord get asFileShare => FileShareRecord.of(this);
}
