// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'order_item.dart';

/// Typed column constants of the order_items resource.
abstract final class OrderItemColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Optional label overriding the product name.
  static const BeakStringColumn label = BeakStringColumn(
    key: 'label',
    label: 'Label',
  );

  /// Positive quantity of the selected product.
  static const BeakIntColumn quantity = BeakIntColumn(
    key: 'quantity',
    label: 'Quantity',
    rules: [BeakRequired(), BeakMin(1)],
    min: 1,
  );

  /// Optional negotiated unit price, exact and in euros.
  static const BeakIntColumn overwritePrice = BeakIntColumn(
    key: 'overwrite_price',
    label: 'Overwrite Price',
    rules: [BeakMin(0)],
    semantic: BeakSemantic.money(currency: 'EUR'),
  );

  /// Optional discount on the complete line, exact and in euros.
  static const BeakIntColumn discount = BeakIntColumn(
    key: 'discount',
    label: 'Discount',
    rules: [BeakMin(0)],
    semantic: BeakSemantic.money(currency: 'EUR'),
  );

  /// Foreign key backing [order].
  static const BeakStringColumn orderId = BeakStringColumn(
    key: 'order_id',
    label: 'Order',
    rules: [BeakRequired()],
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [product].
  static const BeakStringColumn productId = BeakStringColumn(
    key: 'product_id',
    label: 'Product',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [variant].
  static const BeakStringColumn variantId = BeakStringColumn(
    key: 'variant_id',
    label: 'Variant',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [taxRate].
  static const BeakStringColumn taxRateId = BeakStringColumn(
    key: 'tax_rate_id',
    label: 'Tax Rate',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    label,
    quantity,
    overwritePrice,
    discount,
    orderId,
    productId,
    variantId,
    taxRateId,
  ];
}

/// Typed relationship constants of the order_items resource.
abstract final class OrderItemRelations {
  /// Owning order; wired automatically when the graph is saved.
  static const BeakBelongsTo order = BeakBelongsTo(
    key: 'order',
    label: 'Order',
    relatedTable: 'orders',
    displayColumnKey: 'reference',
    foreignKey: 'order_id',
    searchColumnKeys: ['reference'],
    onDelete: BeakOnDelete.cascade,
  );

  /// Catalog product for this row.
  static const BeakBelongsTo product = BeakBelongsTo(
    key: 'product',
    label: 'Product',
    relatedTable: 'products',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );

  /// Optional variant belonging to the selected catalog product.
  static const BeakBelongsTo variant = BeakBelongsTo(
    key: 'variant',
    label: 'Variant',
    relatedTable: 'product_variants',
    displayColumnKey: 'name',
    foreignKey: 'variant_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );

  /// Optional tax rate for the order line.
  static const BeakBelongsTo taxRate = BeakBelongsTo(
    key: 'taxRate',
    label: 'Tax Rate',
    relatedTable: 'tax_rates',
    displayColumnKey: 'name',
    foreignKey: 'tax_rate_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );
}

/// Typed configuration references for OrderItem.
final class OrderItemFields {
  /// Creates the fields of OrderItem, rooted at its own model.
  const OrderItemFields() : _model = const OrderItemModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const OrderItemFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Label.
  BeakScalarField<String> get label => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.label,
    path: _path,
    isRequired: false,
  );

  /// Quantity.
  BeakScalarField<int> get quantity => BeakScalarField<int>(
    model: _model,
    column: OrderItemColumns.quantity,
    path: _path,
    isRequired: true,
  );

  /// Overwrite Price.
  BeakScalarField<BeakDecimal> get overwritePrice =>
      BeakScalarField<BeakDecimal>(
        model: _model,
        column: OrderItemColumns.overwritePrice,
        path: _path,
        isRequired: false,
      );

  /// Discount.
  BeakScalarField<BeakDecimal> get discount => BeakScalarField<BeakDecimal>(
    model: _model,
    column: OrderItemColumns.discount,
    path: _path,
    isRequired: false,
  );

  /// Order.
  BeakScalarField<String> get orderId => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.orderId,
    path: _path,
    isRequired: true,
  );

  /// Product.
  BeakScalarField<String> get productId => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.productId,
    path: _path,
    isRequired: false,
  );

  /// Variant.
  BeakScalarField<String> get variantId => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.variantId,
    path: _path,
    isRequired: false,
  );

  /// Tax Rate.
  BeakScalarField<String> get taxRateId => BeakScalarField<String>(
    model: _model,
    column: OrderItemColumns.taxRateId,
    path: _path,
    isRequired: false,
  );

  /// Order.
  OrderToOneField get order => OrderToOneField(
    model: _model,
    relation: OrderItemRelations.order,
    path: _path,
    isRequired: true,
  );

  /// Product.
  ProductToOneField get product => ProductToOneField(
    model: _model,
    relation: OrderItemRelations.product,
    path: _path,
    isRequired: false,
  );

  /// Variant.
  ProductVariantToOneField get variant => ProductVariantToOneField(
    model: _model,
    relation: OrderItemRelations.variant,
    path: _path,
    isRequired: false,
  );

  /// Tax Rate.
  TaxRateToOneField get taxRate => TaxRateToOneField(
    model: _model,
    relation: OrderItemRelations.taxRate,
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to OrderItem, retaining its root owner.
final class OrderItemToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const OrderItemToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const OrderItemModel());

  /// Every target field, including names reserved by the path API.
  OrderItemFields get fields => OrderItemFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Quantity.
  BeakScalarField<int> get quantity => fields.quantity;

  /// Overwrite Price.
  BeakScalarField<BeakDecimal> get overwritePrice => fields.overwritePrice;

  /// Discount.
  BeakScalarField<BeakDecimal> get discount => fields.discount;

  /// Order.
  BeakScalarField<String> get orderId => fields.orderId;

  /// Product.
  BeakScalarField<String> get productId => fields.productId;

  /// Variant.
  BeakScalarField<String> get variantId => fields.variantId;

  /// Tax Rate.
  BeakScalarField<String> get taxRateId => fields.taxRateId;

  /// Order.
  OrderToOneField get order => fields.order;

  /// Product.
  ProductToOneField get product => fields.product;

  /// Variant.
  ProductVariantToOneField get variant => fields.variant;

  /// Tax Rate.
  TaxRateToOneField get taxRate => fields.taxRate;
}

/// OrderItem schema; all metadata and typed helpers are generated.
final class OrderItemModel extends BeakModel {
  /// Creates the order_items model.
  const OrderItemModel();

  /// Typed field and relation references, including reserved names.
  static const OrderItemFields fields = OrderItemFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [label] in this model.
  static final label = fields.label;

  /// Typed reference to [quantity] in this model.
  static final quantity = fields.quantity;

  /// Typed reference to [overwritePrice] in this model.
  static final overwritePrice = fields.overwritePrice;

  /// Typed reference to [discount] in this model.
  static final discount = fields.discount;

  /// Typed reference to [orderId] in this model.
  static final orderId = fields.orderId;

  /// Typed reference to [productId] in this model.
  static final productId = fields.productId;

  /// Typed reference to [variantId] in this model.
  static final variantId = fields.variantId;

  /// Typed reference to [taxRateId] in this model.
  static final taxRateId = fields.taxRateId;

  /// Typed reference to [order] in this model.
  static final order = fields.order;

  /// Typed reference to [product] in this model.
  static final product = fields.product;

  /// Typed reference to [variant] in this model.
  static final variant = fields.variant;

  /// Typed reference to [taxRate] in this model.
  static final taxRate = fields.taxRate;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const OrderItemModel(),
    query: const OrderItemModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const OrderItemModel(),
        query: const OrderItemModel().query(
          filter: filter,
          search: BeakSearch(term, const ['label']),
        ),
      );

  @override
  String get table => 'order_items';

  @override
  String get displayColumnKey => 'label';

  @override
  List<BeakColumn> get columns => OrderItemColumns.values;
  @override
  List<BeakRecordRule> get validationRules => OrderItem.validationRules;
  @override
  BeakModelBehavior get behavior => OrderItem.behavior;
  @override
  List<BeakModel> get relatedModels => const [
    OrderModel(),
    ProductModel(),
    ProductVariantModel(),
    TaxRateModel(),
  ];

  @override
  List<BeakRelationship> get relationships => const [
    OrderItemRelations.order,
    OrderItemRelations.product,
    OrderItemRelations.variant,
    OrderItemRelations.taxRate,
  ];

  @override
  List<Enum> get formSlots => _OrderItemModelFormSlot.values;
}

/// Form-field slots of OrderItemModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field OrderItem can put on a form.
enum _OrderItemModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
}

/// A live, nullable view of an incomplete OrderItem draft.
final class OrderItemDraft {
  /// Reads values through the session so dependencies stay observable.
  const OrderItemDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(OrderItemModel.fields.id);

  /// Label, or null while incomplete.
  String? get label => _reader.read(OrderItemModel.fields.label);

  /// Quantity, or null while incomplete.
  int? get quantity => _reader.read(OrderItemModel.fields.quantity);

  /// Overwrite Price, or null while incomplete.
  BeakDecimal? get overwritePrice =>
      _reader.read(OrderItemModel.fields.overwritePrice);

  /// Discount, or null while incomplete.
  BeakDecimal? get discount => _reader.read(OrderItemModel.fields.discount);

  /// Order, or null while incomplete.
  String? get orderId => _reader.read(OrderItemModel.fields.orderId);

  /// Product, or null while incomplete.
  String? get productId => _reader.read(OrderItemModel.fields.productId);

  /// Variant, or null while incomplete.
  String? get variantId => _reader.read(OrderItemModel.fields.variantId);

  /// Tax Rate, or null while incomplete.
  String? get taxRateId => _reader.read(OrderItemModel.fields.taxRateId);

  /// The selected order.
  OrderRecord? get order => switch (_reader.read(OrderItemModel.fields.order)) {
    final BeakRecord record => OrderRecord.of(record),
    null => null,
  };

  /// The selected product.
  ProductRecord? get product =>
      switch (_reader.read(OrderItemModel.fields.product)) {
        final BeakRecord record => ProductRecord.of(record),
        null => null,
      };

  /// The selected variant.
  ProductVariantRecord? get variant =>
      switch (_reader.read(OrderItemModel.fields.variant)) {
        final BeakRecord record => ProductVariantRecord.of(record),
        null => null,
      };

  /// The selected tax rate.
  TaxRateRecord? get taxRate =>
      switch (_reader.read(OrderItemModel.fields.taxRate)) {
        final BeakRecord record => TaxRateRecord.of(record),
        null => null,
      };
}

/// Typed access to live OrderItem form values.
extension OrderItemDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  OrderItemDraft get asOrderItem => OrderItemDraft(this);
}

/// A typed, zero-cost view over a order_items record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const OrderItemRecord._(BeakRecord record) {
  /// Views [record] as a order_items row.
  const OrderItemRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => OrderItemColumns.id.readFrom(record);

  /// Optional label overriding the product name.
  String? get label => OrderItemColumns.label.readFrom(record);

  /// Positive quantity of the selected product.
  int get quantity => OrderItemColumns.quantity.require(record);

  /// Optional negotiated unit price, exact and in euros.
  BeakDecimal? get overwritePrice =>
      OrderItemModel.fields.overwritePrice.readFrom(record);

  /// Optional discount on the complete line, exact and in euros.
  BeakDecimal? get discount => OrderItemModel.fields.discount.readFrom(record);

  /// Foreign key backing [order].
  String get orderId => OrderItemColumns.orderId.require(record);

  /// Foreign key backing [product].
  String? get productId => OrderItemColumns.productId.readFrom(record);

  /// Foreign key backing [variant].
  String? get variantId => OrderItemColumns.variantId.readFrom(record);

  /// Foreign key backing [taxRate].
  String? get taxRateId => OrderItemColumns.taxRateId.readFrom(record);

  /// The eager-loaded order, or null when unloaded or unset.
  OrderRecord? get order => switch (record.relations['order']) {
    [final BeakRecord first, ...] => OrderRecord.of(first),
    _ => null,
  };

  /// The eager-loaded product, or null when unloaded or unset.
  ProductRecord? get product => switch (record.relations['product']) {
    [final BeakRecord first, ...] => ProductRecord.of(first),
    _ => null,
  };

  /// The eager-loaded variant, or null when unloaded or unset.
  ProductVariantRecord? get variant => switch (record.relations['variant']) {
    [final BeakRecord first, ...] => ProductVariantRecord.of(first),
    _ => null,
  };

  /// The eager-loaded tax rate, or null when unloaded or unset.
  TaxRateRecord? get taxRate => switch (record.relations['taxRate']) {
    [final BeakRecord first, ...] => TaxRateRecord.of(first),
    _ => null,
  };
}

/// Views any record as a order_items row.
extension OrderItemRecordAccess on BeakRecord {
  /// This record, typed as a order_items row.
  OrderItemRecord get asOrderItem => OrderItemRecord.of(this);
}
