// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'asset.dart';

/// Typed column constants of the assets resource.
abstract final class AssetColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The name shown under it.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// A caption for the carousel and the gallery.
  static const BeakStringColumn caption = BeakStringColumn(
    key: 'caption',
    label: 'Caption',
  );

  /// Where the media is served from: a bundled asset path or a URL.
  static const BeakStringColumn url = BeakStringColumn(
    key: 'url',
    label: 'Url',
    rules: [BeakRequired()],
  );

  /// Which block shows it.
  static const BeakEnumColumn<AssetCollection> collection =
      BeakEnumColumn<AssetCollection>(
        key: 'collection',
        label: 'Collection',
        rules: [BeakRequired()],
        defaultValue: AssetCollection.file,
        filterable: true,
        values: AssetCollection.values,
      );

  /// Whether it is a folder in the file manager.
  static const BeakBoolColumn isFolder = BeakBoolColumn(
    key: 'is_folder',
    label: 'Is Folder',
    rules: [BeakRequired()],
  );

  /// Its size in bytes.
  static const BeakIntColumn sizeInBytes = BeakIntColumn(
    key: 'size_in_bytes',
    label: 'Size In Bytes',
    rules: [BeakRequired(), BeakMin(0)],
    semantic: BeakSemantic.fileSize(),
    min: 0,
  );

  /// When it last changed.
  static const BeakDateTimeColumn modifiedAt = BeakDateTimeColumn(
    key: 'modified_at',
    label: 'Modified At',
    rules: [BeakRequired()],
  );

  /// The display order inside its collection.
  static const BeakIntColumn position = BeakIntColumn(
    key: 'position',
    label: 'Position',
    rules: [BeakRequired()],
    sortable: true,
    defaultValue: 0,
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    caption,
    url,
    collection,
    isFolder,
    sizeInBytes,
    modifiedAt,
    position,
  ];
}

/// Typed configuration references for Asset.
final class AssetFields {
  /// Creates the fields of Asset, rooted at its own model.
  const AssetFields() : _model = const AssetModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const AssetFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: AssetColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: AssetColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Caption.
  BeakScalarField<String> get caption => BeakScalarField<String>(
    model: _model,
    column: AssetColumns.caption,
    path: _path,
    isRequired: false,
  );

  /// Url.
  BeakScalarField<String> get url => BeakScalarField<String>(
    model: _model,
    column: AssetColumns.url,
    path: _path,
    isRequired: true,
  );

  /// Collection.
  BeakScalarField<AssetCollection> get collection =>
      BeakScalarField<AssetCollection>(
        model: _model,
        column: AssetColumns.collection,
        path: _path,
        isRequired: true,
      );

  /// Is Folder.
  BeakScalarField<bool> get isFolder => BeakScalarField<bool>(
    model: _model,
    column: AssetColumns.isFolder,
    path: _path,
    isRequired: true,
  );

  /// Size In Bytes.
  BeakScalarField<int> get sizeInBytes => BeakScalarField<int>(
    model: _model,
    column: AssetColumns.sizeInBytes,
    path: _path,
    isRequired: true,
  );

  /// Modified At.
  BeakScalarField<DateTime> get modifiedAt => BeakScalarField<DateTime>(
    model: _model,
    column: AssetColumns.modifiedAt,
    path: _path,
    isRequired: true,
  );

  /// Position.
  BeakScalarField<int> get position => BeakScalarField<int>(
    model: _model,
    column: AssetColumns.position,
    path: _path,
    isRequired: true,
  );
}

/// A to-one path to Asset, retaining its root owner.
final class AssetToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const AssetToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const AssetModel());

  /// Every target field, including names reserved by the path API.
  AssetFields get fields => AssetFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Caption.
  BeakScalarField<String> get caption => fields.caption;

  /// Url.
  BeakScalarField<String> get url => fields.url;

  /// Collection.
  BeakScalarField<AssetCollection> get collection => fields.collection;

  /// Is Folder.
  BeakScalarField<bool> get isFolder => fields.isFolder;

  /// Size In Bytes.
  BeakScalarField<int> get sizeInBytes => fields.sizeInBytes;

  /// Modified At.
  BeakScalarField<DateTime> get modifiedAt => fields.modifiedAt;

  /// Position.
  BeakScalarField<int> get position => fields.position;
}

/// A photo, clip or document the aviary keeps.
final class AssetModel extends BeakModel {
  /// Creates the assets model.
  const AssetModel();

  /// Typed field and relation references, including reserved names.
  static const AssetFields fields = AssetFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [caption] in this model.
  static final caption = fields.caption;

  /// Typed reference to [url] in this model.
  static final url = fields.url;

  /// Typed reference to [collection] in this model.
  static final collection = fields.collection;

  /// Typed reference to [isFolder] in this model.
  static final isFolder = fields.isFolder;

  /// Typed reference to [sizeInBytes] in this model.
  static final sizeInBytes = fields.sizeInBytes;

  /// Typed reference to [modifiedAt] in this model.
  static final modifiedAt = fields.modifiedAt;

  /// Typed reference to [position] in this model.
  static final position = fields.position;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const AssetModel(),
    query: const AssetModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const AssetModel(),
        query: const AssetModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'assets';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => AssetColumns.values;

  @override
  List<Enum> get formSlots => _AssetModelFormSlot.values;
}

/// Form-field slots of AssetModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Asset can put on a form.
enum _AssetModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
}

/// A live, nullable view of an incomplete Asset draft.
final class AssetDraft {
  /// Reads values through the session so dependencies stay observable.
  const AssetDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(AssetModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(AssetModel.fields.name);

  /// Caption, or null while incomplete.
  String? get caption => _reader.read(AssetModel.fields.caption);

  /// Url, or null while incomplete.
  String? get url => _reader.read(AssetModel.fields.url);

  /// Collection, or null while incomplete.
  AssetCollection? get collection => _reader.read(AssetModel.fields.collection);

  /// Is Folder, or null while incomplete.
  bool? get isFolder => _reader.read(AssetModel.fields.isFolder);

  /// Size In Bytes, or null while incomplete.
  int? get sizeInBytes => _reader.read(AssetModel.fields.sizeInBytes);

  /// Modified At, or null while incomplete.
  DateTime? get modifiedAt => _reader.read(AssetModel.fields.modifiedAt);

  /// Position, or null while incomplete.
  int? get position => _reader.read(AssetModel.fields.position);
}

/// Typed access to live Asset form values.
extension AssetDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  AssetDraft get asAsset => AssetDraft(this);
}

/// A typed, zero-cost view over a assets record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const AssetRecord._(BeakRecord record) {
  /// Views [record] as a assets row.
  const AssetRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => AssetColumns.id.readFrom(record);

  /// The name shown under it.
  String get name => AssetColumns.name.require(record);

  /// A caption for the carousel and the gallery.
  String? get caption => AssetColumns.caption.readFrom(record);

  /// Where the media is served from: a bundled asset path or a URL.
  String get url => AssetColumns.url.require(record);

  /// Which block shows it.
  AssetCollection get collection => AssetColumns.collection.require(record);

  /// Whether it is a folder in the file manager.
  bool get isFolder => AssetColumns.isFolder.require(record);

  /// Its size in bytes.
  int get sizeInBytes => AssetColumns.sizeInBytes.require(record);

  /// When it last changed.
  DateTime get modifiedAt => AssetColumns.modifiedAt.require(record);

  /// The display order inside its collection.
  int get position => AssetColumns.position.require(record);
}

/// Views any record as a assets row.
extension AssetRecordAccess on BeakRecord {
  /// This record, typed as a assets row.
  AssetRecord get asAsset => AssetRecord.of(this);
}
