// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'order.dart';

/// Typed column constants of the orders resource.
abstract final class OrderColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Human-readable order reference (unique).
  static const BeakStringColumn reference = BeakStringColumn(
    key: 'reference',
    label: 'Reference',
    rules: [BeakRequired(), BeakMaxLength(40)],
    searchable: true,
    sortable: true,
  );

  /// Fulfilment state, shown as a colored badge.
  static const BeakEnumColumn<OrderStatus> status = BeakEnumColumn<OrderStatus>(
    key: 'status',
    label: 'Status',
    defaultValue: OrderStatus.pending,
    filterable: true,
    badgeColors: {
      OrderStatus.pending: BeakColor.warning,
      OrderStatus.processing: BeakColor.info,
      OrderStatus.shipped: BeakColor.primary,
      OrderStatus.delivered: BeakColor.success,
      OrderStatus.cancelled: BeakColor.muted,
      OrderStatus.refunded: BeakColor.error,
    },
    values: OrderStatus.values,
  );

  /// Payment settlement state.
  static const BeakEnumColumn<PaymentStatus> paymentStatus =
      BeakEnumColumn<PaymentStatus>(
        key: 'payment_status',
        label: 'Payment',
        defaultValue: PaymentStatus.pending,
        filterable: true,
        badgeColors: {
          PaymentStatus.pending: BeakColor.warning,
          PaymentStatus.paid: BeakColor.success,
          PaymentStatus.failed: BeakColor.error,
          PaymentStatus.refunded: BeakColor.muted,
        },
        values: PaymentStatus.values,
      );

  /// Where the purchase originated (feeds the dashboard donut).
  static const BeakEnumColumn<PurchaseChannel> source =
      BeakEnumColumn<PurchaseChannel>(
        key: 'source',
        label: 'Source',
        defaultValue: PurchaseChannel.direct,
        filterable: true,
        badgeColors: {
          PurchaseChannel.direct: BeakColor.primary,
          PurchaseChannel.social: BeakColor.info,
          PurchaseChannel.email: BeakColor.success,
          PurchaseChannel.affiliate: BeakColor.warning,
          PurchaseChannel.search: BeakColor.secondary,
        },
        values: PurchaseChannel.values,
      );

  /// Line-item subtotal.
  static const BeakDecimalColumn subtotal = BeakDecimalColumn(
    key: 'subtotal',
    label: 'Subtotal',
    prefix: r'$',
    sortable: true,
  );

  /// Shipping charge.
  static const BeakDecimalColumn shipping = BeakDecimalColumn(
    key: 'shipping',
    label: 'Shipping',
    prefix: r'$',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Tax amount.
  static const BeakDecimalColumn tax = BeakDecimalColumn(
    key: 'tax',
    label: 'Tax',
    prefix: r'$',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Grand total.
  static const BeakDecimalColumn total = BeakDecimalColumn(
    key: 'total',
    label: 'Total',
    prefix: r'$',
    sortable: true,
  );

  /// When the order was placed.
  static const BeakDateTimeColumn placedAt = BeakDateTimeColumn(
    key: 'placed_at',
    label: 'Placed',
    format: BeakDateFormat.relative,
    sortable: true,
  );

  /// Foreign key backing [user].
  static const BeakStringColumn userId = BeakStringColumn(
    key: 'user_id',
    label: 'Customer',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    reference,
    status,
    paymentStatus,
    source,
    subtotal,
    shipping,
    tax,
    total,
    placedAt,
    userId,
  ];
}

/// Typed relationship constants of the orders resource.
abstract final class OrderRelations {
  /// The customer who placed the order.
  static const BeakBelongsTo user = BeakBelongsTo(
    key: 'user',
    label: 'Customer',
    relatedTable: 'users',
    displayColumnKey: 'name',
    foreignKey: 'user_id',
    searchColumnKeys: ['name', 'email'],
  );

  /// The line items on the order.
  static const BeakHasMany items = BeakHasMany(
    key: 'items',
    label: 'Items',
    relatedTable: 'order_items',
    displayColumnKey: 'label',
    foreignKey: 'order_id',
    searchColumnKeys: ['label'],
  );

  /// The settling transaction.
  static const BeakHasOne transaction = BeakHasOne(
    key: 'transaction',
    label: 'Transaction',
    relatedTable: 'transactions',
    displayColumnKey: 'reference',
    foreignKey: 'order_id',
    searchColumnKeys: ['reference'],
  );

  /// The order's lifecycle/history timeline.
  static const BeakHasMany events = BeakHasMany(
    key: 'events',
    label: 'History',
    relatedTable: 'order_events',
    displayColumnKey: 'description',
    foreignKey: 'order_id',
    searchColumnKeys: ['description'],
  );

  /// Internal and customer-facing notes on the order.
  static const BeakHasMany comments = BeakHasMany(
    key: 'comments',
    label: 'Comments',
    relatedTable: 'order_comments',
    displayColumnKey: 'body',
    foreignKey: 'order_id',
    searchColumnKeys: ['body'],
  );
}

/// The orders resource — a customer's purchase.
final class OrderModel extends BeakModel {
  /// Creates the orders model.
  const OrderModel();

  @override
  String get table => 'orders';

  @override
  String get displayColumnKey => 'reference';

  @override
  List<BeakColumn> get columns => OrderColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    OrderRelations.user,
    OrderRelations.items,
    OrderRelations.transaction,
    OrderRelations.events,
    OrderRelations.comments,
  ];

  @override
  List<Enum> get formSlots => _OrderModelFormSlot.values;
}

/// Form-field slots of OrderModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Order can put on a form.
enum _OrderModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
  s15,
}

/// A typed, zero-cost view over a orders record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const OrderRecord._(BeakRecord record) {
  /// Views [record] as a orders row.
  const OrderRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => OrderColumns.id.readFrom(record);

  /// Human-readable order reference (unique).
  String get reference => OrderColumns.reference.require(record);

  /// Fulfilment state, shown as a colored badge.
  OrderStatus? get status => OrderColumns.status.readFrom(record);

  /// Payment settlement state.
  PaymentStatus? get paymentStatus =>
      OrderColumns.paymentStatus.readFrom(record);

  /// Where the purchase originated (feeds the dashboard donut).
  PurchaseChannel? get source => OrderColumns.source.readFrom(record);

  /// Line-item subtotal.
  double? get subtotal => OrderColumns.subtotal.readFrom(record);

  /// Shipping charge.
  double? get shipping => OrderColumns.shipping.readFrom(record);

  /// Tax amount.
  double? get tax => OrderColumns.tax.readFrom(record);

  /// Grand total.
  double? get total => OrderColumns.total.readFrom(record);

  /// When the order was placed.
  DateTime? get placedAt => OrderColumns.placedAt.readFrom(record);

  /// Foreign key backing [user].
  String? get userId => OrderColumns.userId.readFrom(record);

  /// The eager-loaded customer, or null when unloaded or unset.
  UserRecord? get user => switch (record.relations['user']) {
    [final BeakRecord first, ...] => UserRecord.of(first),
    _ => null,
  };

  /// The eager-loaded items.
  List<OrderItemRecord> get items => [
    for (final row in record.relations['items'] ?? const <BeakRecord>[])
      OrderItemRecord.of(row),
  ];

  /// The eager-loaded transaction, or null when unloaded or unset.
  TransactionRecord? get transaction =>
      switch (record.relations['transaction']) {
        [final BeakRecord first, ...] => TransactionRecord.of(first),
        _ => null,
      };

  /// The eager-loaded history.
  List<OrderEventRecord> get events => [
    for (final row in record.relations['events'] ?? const <BeakRecord>[])
      OrderEventRecord.of(row),
  ];

  /// The eager-loaded comments.
  List<OrderCommentRecord> get comments => [
    for (final row in record.relations['comments'] ?? const <BeakRecord>[])
      OrderCommentRecord.of(row),
  ];
}

/// Views any record as a orders row.
extension OrderRecordAccess on BeakRecord {
  /// This record, typed as a orders row.
  OrderRecord get asOrder => OrderRecord.of(this);
}
