// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'order_event.dart';

/// Typed column constants of the order_events resource.
abstract final class OrderEventColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The kind of event.
  static const BeakEnumColumn<OrderEventKind> kind =
      BeakEnumColumn<OrderEventKind>(
        key: 'kind',
        label: 'Event',
        defaultValue: OrderEventKind.note,
        filterable: true,
        badgeColors: {
          OrderEventKind.placed: BeakColor.info,
          OrderEventKind.paid: BeakColor.success,
          OrderEventKind.packed: BeakColor.secondary,
          OrderEventKind.shipped: BeakColor.primary,
          OrderEventKind.delivered: BeakColor.success,
          OrderEventKind.cancelled: BeakColor.error,
          OrderEventKind.refunded: BeakColor.warning,
          OrderEventKind.note: BeakColor.muted,
        },
        values: OrderEventKind.values,
      );

  /// What happened.
  static const BeakTextColumn description = BeakTextColumn(
    key: 'description',
    label: 'Description',
    searchable: true,
  );

  /// Who or what performed the event.
  static const BeakStringColumn actor = BeakStringColumn(
    key: 'actor',
    label: 'By',
  );

  /// When the event occurred.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'When',
    sortable: true,
  );

  /// Foreign key backing [order].
  static const BeakStringColumn orderId = BeakStringColumn(
    key: 'order_id',
    label: 'Order',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    kind,
    description,
    actor,
    createdAt,
    orderId,
  ];
}

/// Typed relationship constants of the order_events resource.
abstract final class OrderEventRelations {
  /// The owning order.
  static const BeakBelongsTo order = BeakBelongsTo(
    key: 'order',
    label: 'Order',
    relatedTable: 'orders',
    displayColumnKey: 'reference',
    foreignKey: 'order_id',
    searchColumnKeys: ['reference'],
  );
}

/// The order-events resource — one entry in an order's history timeline.
final class OrderEventModel extends BeakModel {
  /// Creates the order_events model.
  const OrderEventModel();

  @override
  String get table => 'order_events';

  @override
  String get displayColumnKey => 'description';

  @override
  List<BeakColumn> get columns => OrderEventColumns.values;

  @override
  List<BeakRelationship> get relationships => const [OrderEventRelations.order];

  @override
  List<Enum> get formSlots => _OrderEventModelFormSlot.values;
}

/// Form-field slots of OrderEventModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field OrderEvent can put on a form.
enum _OrderEventModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
}

/// A typed, zero-cost view over a order_events record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const OrderEventRecord._(BeakRecord record) {
  /// Views [record] as a order_events row.
  const OrderEventRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => OrderEventColumns.id.readFrom(record);

  /// The kind of event.
  OrderEventKind? get kind => OrderEventColumns.kind.readFrom(record);

  /// What happened.
  String? get description => OrderEventColumns.description.readFrom(record);

  /// Who or what performed the event.
  String? get actor => OrderEventColumns.actor.readFrom(record);

  /// When the event occurred.
  DateTime? get createdAt => OrderEventColumns.createdAt.readFrom(record);

  /// Foreign key backing [order].
  String? get orderId => OrderEventColumns.orderId.readFrom(record);

  /// The eager-loaded order, or null when unloaded or unset.
  OrderRecord? get order => switch (record.relations['order']) {
    [final BeakRecord first, ...] => OrderRecord.of(first),
    _ => null,
  };
}

/// Views any record as a order_events row.
extension OrderEventRecordAccess on BeakRecord {
  /// This record, typed as a order_events row.
  OrderEventRecord get asOrderEvent => OrderEventRecord.of(this);
}
