// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'price_rule.dart';

/// Typed column constants of the price_rules resource.
abstract final class PriceRuleColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Rule name, e.g. "Bulk 10+".
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Rule',
    rules: [BeakRequired(), BeakMaxLength(120)],
    searchable: true,
  );

  /// How the adjustment applies.
  static const BeakEnumColumn<PriceRuleKind> kind =
      BeakEnumColumn<PriceRuleKind>(
        key: 'kind',
        label: 'Kind',
        defaultValue: PriceRuleKind.percentage,
        filterable: true,
        badgeColors: {
          PriceRuleKind.percentage: BeakColor.info,
          PriceRuleKind.fixed: BeakColor.secondary,
          PriceRuleKind.override: BeakColor.warning,
        },
        values: PriceRuleKind.values,
      );

  /// The adjustment value (percent, or dollars).
  static const BeakDecimalColumn value = BeakDecimalColumn(
    key: 'value',
    label: 'Value',
    rules: [BeakRequired(), BeakMin(0)],
  );

  /// Minimum quantity for the rule to apply.
  static const BeakIntColumn minQuantity = BeakIntColumn(
    key: 'min_quantity',
    label: 'Min qty',
    min: 1,
  );

  /// When the rule starts applying.
  static const BeakDateTimeColumn startsAt = BeakDateTimeColumn(
    key: 'starts_at',
    label: 'Starts',
    sortable: true,
  );

  /// When the rule stops applying.
  static const BeakDateTimeColumn endsAt = BeakDateTimeColumn(
    key: 'ends_at',
    label: 'Ends',
  );

  /// Whether the rule is currently active.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
  );

  /// Foreign key backing [product].
  static const BeakStringColumn productId = BeakStringColumn(
    key: 'product_id',
    label: 'Product',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    kind,
    value,
    minQuantity,
    startsAt,
    endsAt,
    active,
    productId,
  ];
}

/// Typed relationship constants of the price_rules resource.
abstract final class PriceRuleRelations {
  /// The owning product.
  static const BeakBelongsTo product = BeakBelongsTo(
    key: 'product',
    label: 'Product',
    relatedTable: 'products',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
  );
}

/// The price-rules resource — a conditional pricing adjustment on a product.
final class PriceRuleModel extends BeakModel {
  /// Creates the price_rules model.
  const PriceRuleModel();

  @override
  String get table => 'price_rules';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => PriceRuleColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    PriceRuleRelations.product,
  ];

  @override
  List<Enum> get formSlots => _PriceRuleModelFormSlot.values;
}

/// Form-field slots of PriceRuleModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field PriceRule can put on a form.
enum _PriceRuleModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
}

/// A typed, zero-cost view over a price_rules record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const PriceRuleRecord._(BeakRecord record) {
  /// Views [record] as a price_rules row.
  const PriceRuleRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => PriceRuleColumns.id.readFrom(record);

  /// Rule name, e.g. "Bulk 10+".
  String get name => PriceRuleColumns.name.require(record);

  /// How the adjustment applies.
  PriceRuleKind? get kind => PriceRuleColumns.kind.readFrom(record);

  /// The adjustment value (percent, or dollars).
  double get value => PriceRuleColumns.value.require(record);

  /// Minimum quantity for the rule to apply.
  int? get minQuantity => PriceRuleColumns.minQuantity.readFrom(record);

  /// When the rule starts applying.
  DateTime? get startsAt => PriceRuleColumns.startsAt.readFrom(record);

  /// When the rule stops applying.
  DateTime? get endsAt => PriceRuleColumns.endsAt.readFrom(record);

  /// Whether the rule is currently active.
  bool? get active => PriceRuleColumns.active.readFrom(record);

  /// Foreign key backing [product].
  String? get productId => PriceRuleColumns.productId.readFrom(record);

  /// The eager-loaded product, or null when unloaded or unset.
  ProductRecord? get product => switch (record.relations['product']) {
    [final BeakRecord first, ...] => ProductRecord.of(first),
    _ => null,
  };
}

/// Views any record as a price_rules row.
extension PriceRuleRecordAccess on BeakRecord {
  /// This record, typed as a price_rules row.
  PriceRuleRecord get asPriceRule => PriceRuleRecord.of(this);
}
