// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'product.dart';

/// Typed column constants of the products resource.
abstract final class ProductColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Display name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired(), BeakMaxLength(255)],
    searchable: true,
    sortable: true,
  );

  /// Stock-keeping unit.
  static const BeakStringColumn sku = BeakStringColumn(
    key: 'sku',
    label: 'SKU',
    rules: [BeakMaxLength(40)],
    searchable: true,
  );

  /// Long-form description.
  static const BeakTextColumn description = BeakTextColumn(
    key: 'description',
    label: 'Description',
    searchable: true,
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Sale price in dollars.
  static const BeakDecimalColumn price = BeakDecimalColumn(
    key: 'price',
    label: 'Price',
    rules: [BeakRequired(), BeakMin(0)],
    prefix: r'$',
    sortable: true,
    filterable: true,
  );

  /// Unit cost in dollars.
  static const BeakDecimalColumn cost = BeakDecimalColumn(
    key: 'cost',
    label: 'Cost',
    rules: [BeakMin(0)],
    prefix: r'$',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Units in stock.
  static const BeakIntColumn stock = BeakIntColumn(
    key: 'stock',
    label: 'Stock',
    rules: [BeakMin(0)],
    min: 0,
    sortable: true,
  );

  /// Lifecycle state, shown as a colored badge.
  static const BeakEnumColumn<ProductStatus> status =
      BeakEnumColumn<ProductStatus>(
        key: 'status',
        label: 'Status',
        defaultValue: ProductStatus.draft,
        filterable: true,
        badgeColors: {
          ProductStatus.draft: BeakColor.muted,
          ProductStatus.published: BeakColor.success,
          ProductStatus.scheduled: BeakColor.info,
          ProductStatus.inactive: BeakColor.warning,
        },
        values: ProductStatus.values,
      );

  /// Product photo: max 5 MB, raster formats, thumbnail + webp on upload.
  static const BeakImageColumn image = BeakImageColumn(
    key: 'image',
    label: 'Image',
    storagePath: 'products',
    maxSizeInBytes: 5 * 1024 * 1024,
    allowedTypes: [BeakFileType.jpeg, BeakFileType.png, BeakFileType.webp],
    thumbnail: BeakDimensions(widthInPixels: 160, heightInPixels: 160),
    transforms: [
      BeakThumbnailTransform(
        size: BeakDimensions(widthInPixels: 160, heightInPixels: 160),
      ),
      BeakFormatTransform.webp(),
    ],
  );

  /// Foreign key backing [category].
  static const BeakStringColumn categoryId = BeakStringColumn(
    key: 'category_id',
    label: 'Category',
    visibleOn: {BeakContext.form},
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// When the record was soft-deleted, if it was.
  static const BeakDateTimeColumn deletedAt = BeakDateTimeColumn(
    key: 'deleted_at',
    label: 'Deleted',
    visibleOn: {BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    sku,
    description,
    price,
    cost,
    stock,
    status,
    image,
    categoryId,
    createdAt,
    updatedAt,
    deletedAt,
  ];
}

/// Typed relationship constants of the products resource.
abstract final class ProductRelations {
  /// The category a product is filed under.
  static const BeakBelongsTo category = BeakBelongsTo(
    key: 'category',
    label: 'Category',
    relatedTable: 'categories',
    displayColumnKey: 'name',
    foreignKey: 'category_id',
    searchColumnKeys: ['name'],
  );

  /// The tags attached to a product.
  static const BeakBelongsToMany tags = BeakBelongsToMany(
    key: 'tags',
    label: 'Tags',
    relatedTable: 'tags',
    displayColumnKey: 'name',
    pivotTable: 'product_tag',
    foreignPivotKey: 'product_id',
    relatedPivotKey: 'tag_id',
    searchColumnKeys: ['name'],
  );

  /// The order line items referencing this product.
  static const BeakHasMany items = BeakHasMany(
    key: 'items',
    label: 'Order items',
    relatedTable: 'order_items',
    displayColumnKey: 'label',
    foreignKey: 'product_id',
    searchColumnKeys: ['label'],
  );

  /// The purchasable variations of this product.
  static const BeakHasMany variants = BeakHasMany(
    key: 'variants',
    label: 'Variants',
    relatedTable: 'product_variants',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
  );

  /// The gallery images of this product.
  static const BeakHasMany images = BeakHasMany(
    key: 'images',
    label: 'Gallery',
    relatedTable: 'product_images',
    displayColumnKey: 'alt',
    foreignKey: 'product_id',
    searchColumnKeys: ['alt'],
  );

  /// The customer reviews of this product.
  static const BeakHasMany reviews = BeakHasMany(
    key: 'reviews',
    label: 'Reviews',
    relatedTable: 'product_reviews',
    displayColumnKey: 'title',
    foreignKey: 'product_id',
    searchColumnKeys: ['title'],
  );

  /// The conditional pricing rules on this product.
  static const BeakHasMany priceRules = BeakHasMany(
    key: 'priceRules',
    label: 'Price rules',
    relatedTable: 'price_rules',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
  );
}

/// The products resource — the showcase model (soft-deleting, every column
/// kind, belongs-to + belongs-to-many + has-many).
final class ProductModel extends BeakModel {
  /// Creates the products model.
  const ProductModel();

  @override
  String get table => 'products';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => ProductColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    ProductRelations.category,
    ProductRelations.tags,
    ProductRelations.items,
    ProductRelations.variants,
    ProductRelations.images,
    ProductRelations.reviews,
    ProductRelations.priceRules,
  ];

  @override
  bool get softDeletes => true;

  @override
  List<Enum> get formSlots => _ProductModelFormSlot.values;
}

/// Form-field slots of ProductModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Product can put on a form.
enum _ProductModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
  s15,
  s16,
  s17,
  s18,
  s19,
}

/// A typed, zero-cost view over a products record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const ProductRecord._(BeakRecord record) {
  /// Views [record] as a products row.
  const ProductRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => ProductColumns.id.readFrom(record);

  /// Display name.
  String get name => ProductColumns.name.require(record);

  /// Stock-keeping unit.
  String? get sku => ProductColumns.sku.readFrom(record);

  /// Long-form description.
  String? get description => ProductColumns.description.readFrom(record);

  /// Sale price in dollars.
  double get price => ProductColumns.price.require(record);

  /// Unit cost in dollars.
  double? get cost => ProductColumns.cost.readFrom(record);

  /// Units in stock.
  int? get stock => ProductColumns.stock.readFrom(record);

  /// Lifecycle state, shown as a colored badge.
  ProductStatus? get status => ProductColumns.status.readFrom(record);

  /// Product photo: max 5 MB, raster formats, thumbnail + webp on upload.
  String? get image => ProductColumns.image.readFrom(record);

  /// Foreign key backing [category].
  String? get categoryId => ProductColumns.categoryId.readFrom(record);

  /// When the record was created.
  DateTime? get createdAt => ProductColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => ProductColumns.updatedAt.readFrom(record);

  /// When the record was soft-deleted, if it was.
  DateTime? get deletedAt => ProductColumns.deletedAt.readFrom(record);

  /// The eager-loaded category, or null when unloaded or unset.
  CategoryRecord? get category => switch (record.relations['category']) {
    [final BeakRecord first, ...] => CategoryRecord.of(first),
    _ => null,
  };

  /// The eager-loaded tags.
  List<TagRecord> get tags => [
    for (final row in record.relations['tags'] ?? const <BeakRecord>[])
      TagRecord.of(row),
  ];

  /// The eager-loaded order items.
  List<OrderItemRecord> get items => [
    for (final row in record.relations['items'] ?? const <BeakRecord>[])
      OrderItemRecord.of(row),
  ];

  /// The eager-loaded variants.
  List<ProductVariantRecord> get variants => [
    for (final row in record.relations['variants'] ?? const <BeakRecord>[])
      ProductVariantRecord.of(row),
  ];

  /// The eager-loaded gallery.
  List<ProductImageRecord> get images => [
    for (final row in record.relations['images'] ?? const <BeakRecord>[])
      ProductImageRecord.of(row),
  ];

  /// The eager-loaded reviews.
  List<ProductReviewRecord> get reviews => [
    for (final row in record.relations['reviews'] ?? const <BeakRecord>[])
      ProductReviewRecord.of(row),
  ];

  /// The eager-loaded price rules.
  List<PriceRuleRecord> get priceRules => [
    for (final row in record.relations['priceRules'] ?? const <BeakRecord>[])
      PriceRuleRecord.of(row),
  ];
}

/// Views any record as a products row.
extension ProductRecordAccess on BeakRecord {
  /// This record, typed as a products row.
  ProductRecord get asProduct => ProductRecord.of(this);
}
