// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'product_image.dart';

/// Typed column constants of the product_images resource.
abstract final class ProductImageColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The image URL.
  static const BeakImageColumn url = BeakImageColumn(
    key: 'url',
    label: 'Image',
    rules: [BeakRequired()],
    storagePath: 'product-images',
  );

  /// Alt text / caption.
  static const BeakStringColumn alt = BeakStringColumn(
    key: 'alt',
    label: 'Caption',
    rules: [BeakMaxLength(160)],
    searchable: true,
  );

  /// Ordering within the gallery.
  static const BeakIntColumn sortIndex = BeakIntColumn(
    key: 'sort_index',
    label: 'Order',
    min: 0,
    sortable: true,
  );

  /// Whether this is the primary (hero) image.
  static const BeakBoolColumn isPrimary = BeakBoolColumn(
    key: 'is_primary',
    label: 'Primary',
  );

  /// Foreign key backing [product].
  static const BeakStringColumn productId = BeakStringColumn(
    key: 'product_id',
    label: 'Product',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    url,
    alt,
    sortIndex,
    isPrimary,
    productId,
  ];
}

/// Typed relationship constants of the product_images resource.
abstract final class ProductImageRelations {
  /// The owning product.
  static const BeakBelongsTo product = BeakBelongsTo(
    key: 'product',
    label: 'Product',
    relatedTable: 'products',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
  );
}

/// The product-images resource — one image in a product's gallery.
final class ProductImageModel extends BeakModel {
  /// Creates the product_images model.
  const ProductImageModel();

  @override
  String get table => 'product_images';

  @override
  String get displayColumnKey => 'alt';

  @override
  List<BeakColumn> get columns => ProductImageColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    ProductImageRelations.product,
  ];

  @override
  List<Enum> get formSlots => _ProductImageModelFormSlot.values;
}

/// Form-field slots of ProductImageModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field ProductImage can put on a form.
enum _ProductImageModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
}

/// A typed, zero-cost view over a product_images record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const ProductImageRecord._(BeakRecord record) {
  /// Views [record] as a product_images row.
  const ProductImageRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => ProductImageColumns.id.readFrom(record);

  /// The image URL.
  String get url => ProductImageColumns.url.require(record);

  /// Alt text / caption.
  String? get alt => ProductImageColumns.alt.readFrom(record);

  /// Ordering within the gallery.
  int? get sortIndex => ProductImageColumns.sortIndex.readFrom(record);

  /// Whether this is the primary (hero) image.
  bool? get isPrimary => ProductImageColumns.isPrimary.readFrom(record);

  /// Foreign key backing [product].
  String? get productId => ProductImageColumns.productId.readFrom(record);

  /// The eager-loaded product, or null when unloaded or unset.
  ProductRecord? get product => switch (record.relations['product']) {
    [final BeakRecord first, ...] => ProductRecord.of(first),
    _ => null,
  };
}

/// Views any record as a product_images row.
extension ProductImageRecordAccess on BeakRecord {
  /// This record, typed as a product_images row.
  ProductImageRecord get asProductImage => ProductImageRecord.of(this);
}
