// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'tag.dart';

/// Typed column constants of the tags resource.
abstract final class TagColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Tag name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired(), BeakMaxLength(60)],
    searchable: true,
    sortable: true,
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [id, name];
}

/// Typed relationship constants of the tags resource.
abstract final class TagRelations {
  /// Products carrying this tag, via the `product_tag` pivot.
  static const BeakBelongsToMany products = BeakBelongsToMany(
    key: 'products',
    label: 'Products',
    relatedTable: 'products',
    displayColumnKey: 'name',
    pivotTable: 'product_tag',
    foreignPivotKey: 'tag_id',
    relatedPivotKey: 'product_id',
    searchColumnKeys: ['name'],
  );
}

/// The tags resource — free-form product labels.
final class TagModel extends BeakModel {
  /// Creates the tags model.
  const TagModel();

  @override
  String get table => 'tags';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => TagColumns.values;

  @override
  List<BeakRelationship> get relationships => const [TagRelations.products];

  @override
  List<Enum> get formSlots => _TagModelFormSlot.values;
}

/// Form-field slots of TagModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Tag can put on a form.
enum _TagModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
}

/// A typed, zero-cost view over a tags record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const TagRecord._(BeakRecord record) {
  /// Views [record] as a tags row.
  const TagRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => TagColumns.id.readFrom(record);

  /// Tag name.
  String get name => TagColumns.name.require(record);

  /// The eager-loaded products.
  List<ProductRecord> get products => [
    for (final row in record.relations['products'] ?? const <BeakRecord>[])
      ProductRecord.of(row),
  ];
}

/// Views any record as a tags row.
extension TagRecordAccess on BeakRecord {
  /// This record, typed as a tags row.
  TagRecord get asTag => TagRecord.of(this);
}
