// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'transaction.dart';

/// Typed column constants of the transactions resource.
abstract final class TransactionColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Human-readable reference.
  static const BeakStringColumn reference = BeakStringColumn(
    key: 'reference',
    label: 'Reference',
    rules: [BeakMaxLength(40)],
    searchable: true,
  );

  /// Payment method.
  static const BeakEnumColumn<PaymentMethod> method =
      BeakEnumColumn<PaymentMethod>(
        key: 'method',
        label: 'Method',
        defaultValue: PaymentMethod.card,
        filterable: true,
        badgeColors: {
          PaymentMethod.card: BeakColor.primary,
          PaymentMethod.paypal: BeakColor.info,
          PaymentMethod.bankTransfer: BeakColor.secondary,
          PaymentMethod.wallet: BeakColor.success,
        },
        values: PaymentMethod.values,
      );

  /// Card network.
  static const BeakEnumColumn<CardBrand> brand = BeakEnumColumn<CardBrand>(
    key: 'brand',
    label: 'Brand',
    defaultValue: CardBrand.visa,
    visibleOn: {BeakContext.form, BeakContext.detail},
    badgeColors: {
      CardBrand.visa: BeakColor.primary,
      CardBrand.mastercard: BeakColor.warning,
      CardBrand.amex: BeakColor.info,
      CardBrand.paypal: BeakColor.secondary,
    },
    values: CardBrand.values,
  );

  /// Transaction amount in dollars.
  static const BeakDecimalColumn amount = BeakDecimalColumn(
    key: 'amount',
    label: 'Amount',
    prefix: r'$',
    sortable: true,
  );

  /// Settlement state.
  static const BeakEnumColumn<PaymentStatus> status =
      BeakEnumColumn<PaymentStatus>(
        key: 'status',
        label: 'Status',
        defaultValue: PaymentStatus.paid,
        filterable: true,
        badgeColors: {
          PaymentStatus.pending: BeakColor.warning,
          PaymentStatus.paid: BeakColor.success,
          PaymentStatus.failed: BeakColor.error,
          PaymentStatus.refunded: BeakColor.muted,
        },
        values: PaymentStatus.values,
      );

  /// Money direction.
  static const BeakEnumColumn<TxDirection> direction =
      BeakEnumColumn<TxDirection>(
        key: 'direction',
        label: 'Direction',
        defaultValue: TxDirection.incoming,
        filterable: true,
        badgeColors: {
          TxDirection.incoming: BeakColor.success,
          TxDirection.outgoing: BeakColor.error,
        },
        values: TxDirection.values,
      );

  /// When the transaction occurred.
  static const BeakDateTimeColumn occurredAt = BeakDateTimeColumn(
    key: 'occurred_at',
    label: 'When',
    format: BeakDateFormat.relative,
    sortable: true,
  );

  /// Foreign key backing [user].
  static const BeakStringColumn userId = BeakStringColumn(
    key: 'user_id',
    label: 'User',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [order].
  static const BeakStringColumn orderId = BeakStringColumn(
    key: 'order_id',
    label: 'Order',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    reference,
    method,
    brand,
    amount,
    status,
    direction,
    occurredAt,
    userId,
    orderId,
  ];
}

/// Typed relationship constants of the transactions resource.
abstract final class TransactionRelations {
  /// The paying/receiving user.
  static const BeakBelongsTo user = BeakBelongsTo(
    key: 'user',
    label: 'User',
    relatedTable: 'users',
    displayColumnKey: 'name',
    foreignKey: 'user_id',
    searchColumnKeys: ['name', 'email'],
  );

  /// The related order, if any.
  static const BeakBelongsTo order = BeakBelongsTo(
    key: 'order',
    label: 'Order',
    relatedTable: 'orders',
    displayColumnKey: 'reference',
    foreignKey: 'order_id',
    searchColumnKeys: ['reference'],
  );
}

/// The transactions resource — a single payment event.
final class TransactionModel extends BeakModel {
  /// Creates the transactions model.
  const TransactionModel();

  @override
  String get table => 'transactions';

  @override
  String get displayColumnKey => 'reference';

  @override
  List<BeakColumn> get columns => TransactionColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    TransactionRelations.user,
    TransactionRelations.order,
  ];

  @override
  List<Enum> get formSlots => _TransactionModelFormSlot.values;
}

/// Form-field slots of TransactionModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Transaction can put on a form.
enum _TransactionModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
}

/// A typed, zero-cost view over a transactions record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const TransactionRecord._(BeakRecord record) {
  /// Views [record] as a transactions row.
  const TransactionRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => TransactionColumns.id.readFrom(record);

  /// Human-readable reference.
  String? get reference => TransactionColumns.reference.readFrom(record);

  /// Payment method.
  PaymentMethod? get method => TransactionColumns.method.readFrom(record);

  /// Card network.
  CardBrand? get brand => TransactionColumns.brand.readFrom(record);

  /// Transaction amount in dollars.
  double? get amount => TransactionColumns.amount.readFrom(record);

  /// Settlement state.
  PaymentStatus? get status => TransactionColumns.status.readFrom(record);

  /// Money direction.
  TxDirection? get direction => TransactionColumns.direction.readFrom(record);

  /// When the transaction occurred.
  DateTime? get occurredAt => TransactionColumns.occurredAt.readFrom(record);

  /// Foreign key backing [user].
  String? get userId => TransactionColumns.userId.readFrom(record);

  /// Foreign key backing [order].
  String? get orderId => TransactionColumns.orderId.readFrom(record);

  /// The eager-loaded user, or null when unloaded or unset.
  UserRecord? get user => switch (record.relations['user']) {
    [final BeakRecord first, ...] => UserRecord.of(first),
    _ => null,
  };

  /// The eager-loaded order, or null when unloaded or unset.
  OrderRecord? get order => switch (record.relations['order']) {
    [final BeakRecord first, ...] => OrderRecord.of(first),
    _ => null,
  };
}

/// Views any record as a transactions row.
extension TransactionRecordAccess on BeakRecord {
  /// This record, typed as a transactions row.
  TransactionRecord get asTransaction => TransactionRecord.of(this);
}
