// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'invoice_item.dart';

/// Typed column constants of the invoice_items resource.
abstract final class InvoiceItemColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Saved description; required for a custom line, otherwise catalog-derived.
  static const BeakStringColumn label = BeakStringColumn(
    key: 'label',
    label: 'Label',
  );

  /// Whole units sold.
  static const BeakIntColumn quantity = BeakIntColumn(
    key: 'quantity',
    label: 'Quantity',
    rules: [BeakRequired(), BeakMin(1)],
    min: 1,
  );

  /// Net unit price; blank derives a catalog price before saving.
  static const BeakDecimalColumn unitPrice = BeakDecimalColumn(
    key: 'unit_price',
    label: 'Unit Price',
    rules: [BeakMin(0)],
    prefix: '€',
  );

  /// Net reduction on the whole line, before vouchers.
  static const BeakDecimalColumn discount = BeakDecimalColumn(
    key: 'discount',
    label: 'Discount',
    rules: [BeakMin(0)],
    prefix: '€',
  );

  /// Saved percentage independent of subsequent tax-rate changes.
  static const BeakDecimalColumn taxPercent = BeakDecimalColumn(
    key: 'tax_percent',
    label: 'Tax Percent',
    visibleOn: {BeakContext.detail},
  );

  /// Saved net line amount after vouchers, in cents.
  static const BeakIntColumn netCents = BeakIntColumn(
    key: 'net_cents',
    label: 'Net Cents',
    visibleOn: {BeakContext.detail},
  );

  /// Saved rounded tax amount, in cents.
  static const BeakIntColumn taxCents = BeakIntColumn(
    key: 'tax_cents',
    label: 'Tax Cents',
    visibleOn: {BeakContext.detail},
  );

  /// Saved line payable amount, in cents.
  static const BeakIntColumn totalCents = BeakIntColumn(
    key: 'total_cents',
    label: 'Total Cents',
    visibleOn: {BeakContext.detail},
  );

  /// Foreign key backing [product].
  static const BeakStringColumn productId = BeakStringColumn(
    key: 'product_id',
    label: 'Product',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [variant].
  static const BeakStringColumn variantId = BeakStringColumn(
    key: 'variant_id',
    label: 'Variant',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [taxRate].
  static const BeakStringColumn taxRateId = BeakStringColumn(
    key: 'tax_rate_id',
    label: 'Tax Rate',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [invoice].
  static const BeakStringColumn invoiceId = BeakStringColumn(
    key: 'invoice_id',
    label: 'Invoice',
    rules: [BeakRequired()],
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    label,
    quantity,
    unitPrice,
    discount,
    taxPercent,
    netCents,
    taxCents,
    totalCents,
    productId,
    variantId,
    taxRateId,
    invoiceId,
  ];
}

/// Typed relationship constants of the invoice_items resource.
abstract final class InvoiceItemRelations {
  /// Optional catalog product.
  static const BeakBelongsTo product = BeakBelongsTo(
    key: 'product',
    label: 'Product',
    relatedTable: 'products',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );

  /// Optional variant belonging to the selected product.
  static const BeakBelongsTo variant = BeakBelongsTo(
    key: 'variant',
    label: 'Variant',
    relatedTable: 'product_variants',
    displayColumnKey: 'name',
    foreignKey: 'variant_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );

  /// Optional selected rate; blank uses the product rate or zero.
  static const BeakBelongsTo taxRate = BeakBelongsTo(
    key: 'taxRate',
    label: 'Tax Rate',
    relatedTable: 'tax_rates',
    displayColumnKey: 'name',
    foreignKey: 'tax_rate_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.restrict,
  );

  /// Owning invoice.
  static const BeakBelongsTo invoice = BeakBelongsTo(
    key: 'invoice',
    label: 'Invoice',
    relatedTable: 'invoices',
    displayColumnKey: 'number',
    foreignKey: 'invoice_id',
    searchColumnKeys: ['number'],
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for InvoiceItem.
final class InvoiceItemFields {
  /// Creates fields rooted at [model], optionally through [path].
  const InvoiceItemFields({
    BeakModel model = const InvoiceItemModel(),
    List<BeakRelationship> path = const [],
  }) : _model = model,
       _path = path;
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: InvoiceItemColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Label.
  BeakScalarField<String> get label => BeakScalarField<String>(
    model: _model,
    column: InvoiceItemColumns.label,
    path: _path,
    isRequired: false,
  );

  /// Quantity.
  BeakScalarField<int> get quantity => BeakScalarField<int>(
    model: _model,
    column: InvoiceItemColumns.quantity,
    path: _path,
    isRequired: true,
  );

  /// Unit Price.
  BeakScalarField<double> get unitPrice => BeakScalarField<double>(
    model: _model,
    column: InvoiceItemColumns.unitPrice,
    path: _path,
    isRequired: false,
  );

  /// Discount.
  BeakScalarField<double> get discount => BeakScalarField<double>(
    model: _model,
    column: InvoiceItemColumns.discount,
    path: _path,
    isRequired: false,
  );

  /// Tax Percent.
  BeakScalarField<double> get taxPercent => BeakScalarField<double>(
    model: _model,
    column: InvoiceItemColumns.taxPercent,
    path: _path,
    isRequired: false,
  );

  /// Net Cents.
  BeakScalarField<int> get netCents => BeakScalarField<int>(
    model: _model,
    column: InvoiceItemColumns.netCents,
    path: _path,
    isRequired: false,
  );

  /// Tax Cents.
  BeakScalarField<int> get taxCents => BeakScalarField<int>(
    model: _model,
    column: InvoiceItemColumns.taxCents,
    path: _path,
    isRequired: false,
  );

  /// Total Cents.
  BeakScalarField<int> get totalCents => BeakScalarField<int>(
    model: _model,
    column: InvoiceItemColumns.totalCents,
    path: _path,
    isRequired: false,
  );

  /// Product.
  BeakScalarField<String> get productId => BeakScalarField<String>(
    model: _model,
    column: InvoiceItemColumns.productId,
    path: _path,
    isRequired: false,
  );

  /// Variant.
  BeakScalarField<String> get variantId => BeakScalarField<String>(
    model: _model,
    column: InvoiceItemColumns.variantId,
    path: _path,
    isRequired: false,
  );

  /// Tax Rate.
  BeakScalarField<String> get taxRateId => BeakScalarField<String>(
    model: _model,
    column: InvoiceItemColumns.taxRateId,
    path: _path,
    isRequired: false,
  );

  /// Invoice.
  BeakScalarField<String> get invoiceId => BeakScalarField<String>(
    model: _model,
    column: InvoiceItemColumns.invoiceId,
    path: _path,
    isRequired: true,
  );

  /// Product.
  ProductToOneField get product => ProductToOneField(
    model: _model,
    relation: InvoiceItemRelations.product,
    path: _path,
    isRequired: false,
  );

  /// Variant.
  ProductVariantToOneField get variant => ProductVariantToOneField(
    model: _model,
    relation: InvoiceItemRelations.variant,
    path: _path,
    isRequired: false,
  );

  /// Tax Rate.
  TaxRateToOneField get taxRate => TaxRateToOneField(
    model: _model,
    relation: InvoiceItemRelations.taxRate,
    path: _path,
    isRequired: false,
  );

  /// Invoice.
  InvoiceToOneField get invoice => InvoiceToOneField(
    model: _model,
    relation: InvoiceItemRelations.invoice,
    path: _path,
    isRequired: true,
  );
}

/// A to-one path to InvoiceItem, retaining its root owner.
final class InvoiceItemToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const InvoiceItemToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const InvoiceItemModel());

  /// Every target field, including names reserved by the path API.
  InvoiceItemFields get fields =>
      InvoiceItemFields(model: model, path: [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Quantity.
  BeakScalarField<int> get quantity => fields.quantity;

  /// Unit Price.
  BeakScalarField<double> get unitPrice => fields.unitPrice;

  /// Discount.
  BeakScalarField<double> get discount => fields.discount;

  /// Tax Percent.
  BeakScalarField<double> get taxPercent => fields.taxPercent;

  /// Net Cents.
  BeakScalarField<int> get netCents => fields.netCents;

  /// Tax Cents.
  BeakScalarField<int> get taxCents => fields.taxCents;

  /// Total Cents.
  BeakScalarField<int> get totalCents => fields.totalCents;

  /// Product.
  BeakScalarField<String> get productId => fields.productId;

  /// Variant.
  BeakScalarField<String> get variantId => fields.variantId;

  /// Tax Rate.
  BeakScalarField<String> get taxRateId => fields.taxRateId;

  /// Invoice.
  BeakScalarField<String> get invoiceId => fields.invoiceId;

  /// Product.
  ProductToOneField get product => fields.product;

  /// Variant.
  ProductVariantToOneField get variant => fields.variant;

  /// Tax Rate.
  TaxRateToOneField get taxRate => fields.taxRate;

  /// Invoice.
  InvoiceToOneField get invoice => fields.invoice;
}

/// One invoice line; catalog references are optional for custom work.
final class InvoiceItemModel extends BeakModel {
  /// Creates the invoice_items model.
  const InvoiceItemModel();

  /// Typed field and relation references, including reserved names.
  static const InvoiceItemFields fields = InvoiceItemFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [label] in this model.
  static final label = fields.label;

  /// Typed reference to [quantity] in this model.
  static final quantity = fields.quantity;

  /// Typed reference to [unitPrice] in this model.
  static final unitPrice = fields.unitPrice;

  /// Typed reference to [discount] in this model.
  static final discount = fields.discount;

  /// Typed reference to [taxPercent] in this model.
  static final taxPercent = fields.taxPercent;

  /// Typed reference to [netCents] in this model.
  static final netCents = fields.netCents;

  /// Typed reference to [taxCents] in this model.
  static final taxCents = fields.taxCents;

  /// Typed reference to [totalCents] in this model.
  static final totalCents = fields.totalCents;

  /// Typed reference to [productId] in this model.
  static final productId = fields.productId;

  /// Typed reference to [variantId] in this model.
  static final variantId = fields.variantId;

  /// Typed reference to [taxRateId] in this model.
  static final taxRateId = fields.taxRateId;

  /// Typed reference to [invoiceId] in this model.
  static final invoiceId = fields.invoiceId;

  /// Typed reference to [product] in this model.
  static final product = fields.product;

  /// Typed reference to [variant] in this model.
  static final variant = fields.variant;

  /// Typed reference to [taxRate] in this model.
  static final taxRate = fields.taxRate;

  /// Typed reference to [invoice] in this model.
  static final invoice = fields.invoice;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const InvoiceItemModel(),
    query: const InvoiceItemModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const InvoiceItemModel(),
        query: const InvoiceItemModel().query(
          filter: filter,
          search: BeakSearch(term, const ['label']),
        ),
      );

  @override
  String get table => 'invoice_items';

  @override
  String get displayColumnKey => 'label';

  @override
  List<BeakColumn> get columns => InvoiceItemColumns.values;
  @override
  List<BeakRecordRule> get validationRules => InvoiceItem.validationRules;
  @override
  List<BeakModel> get relatedModels => const [
    ProductModel(),
    ProductVariantModel(),
    TaxRateModel(),
    InvoiceModel(),
  ];

  @override
  List<BeakRelationship> get relationships => const [
    InvoiceItemRelations.product,
    InvoiceItemRelations.variant,
    InvoiceItemRelations.taxRate,
    InvoiceItemRelations.invoice,
  ];

  @override
  List<Enum> get formSlots => _InvoiceItemModelFormSlot.values;
}

/// Form-field slots of InvoiceItemModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field InvoiceItem can put on a form.
enum _InvoiceItemModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
  s15,
  s16,
}

/// A live, nullable view of an incomplete InvoiceItem draft.
final class InvoiceItemDraft {
  /// Reads values through the session so dependencies stay observable.
  const InvoiceItemDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(InvoiceItemModel.fields.id);

  /// Label, or null while incomplete.
  String? get label => _reader.read(InvoiceItemModel.fields.label);

  /// Quantity, or null while incomplete.
  int? get quantity => _reader.read(InvoiceItemModel.fields.quantity);

  /// Unit Price, or null while incomplete.
  double? get unitPrice => _reader.read(InvoiceItemModel.fields.unitPrice);

  /// Discount, or null while incomplete.
  double? get discount => _reader.read(InvoiceItemModel.fields.discount);

  /// Tax Percent, or null while incomplete.
  double? get taxPercent => _reader.read(InvoiceItemModel.fields.taxPercent);

  /// Net Cents, or null while incomplete.
  int? get netCents => _reader.read(InvoiceItemModel.fields.netCents);

  /// Tax Cents, or null while incomplete.
  int? get taxCents => _reader.read(InvoiceItemModel.fields.taxCents);

  /// Total Cents, or null while incomplete.
  int? get totalCents => _reader.read(InvoiceItemModel.fields.totalCents);

  /// Product, or null while incomplete.
  String? get productId => _reader.read(InvoiceItemModel.fields.productId);

  /// Variant, or null while incomplete.
  String? get variantId => _reader.read(InvoiceItemModel.fields.variantId);

  /// Tax Rate, or null while incomplete.
  String? get taxRateId => _reader.read(InvoiceItemModel.fields.taxRateId);

  /// Invoice, or null while incomplete.
  String? get invoiceId => _reader.read(InvoiceItemModel.fields.invoiceId);

  /// The selected product.
  ProductRecord? get product =>
      switch (_reader.read(InvoiceItemModel.fields.product)) {
        final BeakRecord record => ProductRecord.of(record),
        null => null,
      };

  /// The selected variant.
  ProductVariantRecord? get variant =>
      switch (_reader.read(InvoiceItemModel.fields.variant)) {
        final BeakRecord record => ProductVariantRecord.of(record),
        null => null,
      };

  /// The selected tax rate.
  TaxRateRecord? get taxRate =>
      switch (_reader.read(InvoiceItemModel.fields.taxRate)) {
        final BeakRecord record => TaxRateRecord.of(record),
        null => null,
      };

  /// The selected invoice.
  InvoiceRecord? get invoice =>
      switch (_reader.read(InvoiceItemModel.fields.invoice)) {
        final BeakRecord record => InvoiceRecord.of(record),
        null => null,
      };
}

/// Typed access to live InvoiceItem form values.
extension InvoiceItemDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  InvoiceItemDraft get asInvoiceItem => InvoiceItemDraft(this);
}

/// A typed, zero-cost view over a invoice_items record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const InvoiceItemRecord._(BeakRecord record) {
  /// Views [record] as a invoice_items row.
  const InvoiceItemRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => InvoiceItemColumns.id.readFrom(record);

  /// Saved description; required for a custom line, otherwise catalog-derived.
  String? get label => InvoiceItemColumns.label.readFrom(record);

  /// Whole units sold.
  int get quantity => InvoiceItemColumns.quantity.require(record);

  /// Net unit price; blank derives a catalog price before saving.
  double? get unitPrice => InvoiceItemColumns.unitPrice.readFrom(record);

  /// Net reduction on the whole line, before vouchers.
  double? get discount => InvoiceItemColumns.discount.readFrom(record);

  /// Saved percentage independent of subsequent tax-rate changes.
  double? get taxPercent => InvoiceItemColumns.taxPercent.readFrom(record);

  /// Saved net line amount after vouchers, in cents.
  int? get netCents => InvoiceItemColumns.netCents.readFrom(record);

  /// Saved rounded tax amount, in cents.
  int? get taxCents => InvoiceItemColumns.taxCents.readFrom(record);

  /// Saved line payable amount, in cents.
  int? get totalCents => InvoiceItemColumns.totalCents.readFrom(record);

  /// Foreign key backing [product].
  String? get productId => InvoiceItemColumns.productId.readFrom(record);

  /// Foreign key backing [variant].
  String? get variantId => InvoiceItemColumns.variantId.readFrom(record);

  /// Foreign key backing [taxRate].
  String? get taxRateId => InvoiceItemColumns.taxRateId.readFrom(record);

  /// Foreign key backing [invoice].
  String get invoiceId => InvoiceItemColumns.invoiceId.require(record);

  /// The eager-loaded product, or null when unloaded or unset.
  ProductRecord? get product => switch (record.relations['product']) {
    [final BeakRecord first, ...] => ProductRecord.of(first),
    _ => null,
  };

  /// The eager-loaded variant, or null when unloaded or unset.
  ProductVariantRecord? get variant => switch (record.relations['variant']) {
    [final BeakRecord first, ...] => ProductVariantRecord.of(first),
    _ => null,
  };

  /// The eager-loaded tax rate, or null when unloaded or unset.
  TaxRateRecord? get taxRate => switch (record.relations['taxRate']) {
    [final BeakRecord first, ...] => TaxRateRecord.of(first),
    _ => null,
  };

  /// The eager-loaded invoice, or null when unloaded or unset.
  InvoiceRecord? get invoice => switch (record.relations['invoice']) {
    [final BeakRecord first, ...] => InvoiceRecord.of(first),
    _ => null,
  };
}

/// Views any record as a invoice_items row.
extension InvoiceItemRecordAccess on BeakRecord {
  /// This record, typed as a invoice_items row.
  InvoiceItemRecord get asInvoiceItem => InvoiceItemRecord.of(this);
}
