/// Top-level orchestrator for `*.worm.dart` file generation.
library;

import 'companion_generator.dart';
import 'hydration_generator.dart';
import 'model_descriptor.dart';
import 'query_starter_generator.dart';
import 'scope_generator.dart';

/// Combines the companion, hydration, query-starter, and
/// scope generators into a single `*.worm.dart` source.
///
/// The output begins with a generated-file header and
/// imports of `package:worm/worm.dart`.
final class WormFileGenerator {
  /// Creates a [WormFileGenerator] for [descriptor].
  const WormFileGenerator(this.descriptor);

  /// The model the file is generated for.
  final ModelDescriptor descriptor;

  /// Renders the full file source.
  String generate() {
    final buffer = StringBuffer()
      ..writeln(_header)
      ..writeln(_imports)
      ..writeln()
      ..writeln(CompanionGenerator(descriptor).generate())
      ..writeln(HydrationGenerator(descriptor).generate())
      ..writeln(QueryStarterGenerator(descriptor).generate())
      ..writeln(ScopeGenerator(descriptor).generate());
    return buffer.toString();
  }

  static const String _header =
      '// GENERATED CODE - DO NOT MODIFY BY HAND.\n'
      '// Generated by `worm gen` (worm_generator).\n'
      '// ignore_for_file: directives_ordering, '
      'lines_longer_than_80_chars\n';

  String get _imports {
    final source = descriptor.partOfImport;
    if (source != null) {
      return 'part of \'$source\';';
    }
    return 'import \'package:worm/worm.dart\';';
  }
}
