// GENERATED BY `beak prepare` — DO NOT EDIT.
// Run `beak prepare` after changing lib/models, lib/screens or beak.yaml.
library;

import 'package:beak/panel.dart';
import 'package:beak/ui.dart';
import 'package:flutter/foundation.dart';
import '../models/legacy_account.dart';
import '../models/ticket.dart';

/// The panel configuration for this project.
///
/// Assembled from `beak.yaml`, the models under `lib/models/`, and
/// the screens under `lib/screens/`.
BeakPanelConfig buildBeakPanel() {
  final config = BeakPanelConfig(
    title: 'Embedded',
    apiBaseUrl: kIsWeb ? Uri.base.origin : 'http://localhost:8080',
    sidebarCollapsible: true,
    sidebarDefaultCollapsed: false,
    resources: [
      BeakResource(
        model: const LegacyAccountModel(),
        icon: BeakIconToken(OiIcons.building),
      ),
      BeakResource(
        model: const TicketModel(),
        icon: BeakIconToken(OiIcons.lifeBuoy),
      ),
    ],
  );
  return config;
}
