// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'product.dart';

/// Typed column constants of the products resource.
abstract final class ProductColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// What the product is called.
  ///
  /// Non-nullable, so it is required — the form validator, the API's
  /// validation and the column's `NOT NULL` all follow from the type.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired(), BeakMaxLength(255)],
    searchable: true,
    sortable: true,
    indexed: true,
  );

  /// The stock-keeping unit, unique across the catalog.
  static const BeakStringColumn sku = BeakStringColumn(
    key: 'sku',
    label: 'SKU',
    rules: [BeakRequired(), BeakMaxLength(40)],
    searchable: true,
    unique: true,
  );

  /// The short description shown in listings.
  static const BeakTextColumn summary = BeakTextColumn(
    key: 'summary',
    label: 'Summary',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// The long description, edited as rich text.
  static const BeakRichTextColumn description = BeakRichTextColumn(
    key: 'description',
    label: 'Description',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Sale price in euros.
  static const BeakDecimalColumn price = BeakDecimalColumn(
    key: 'price',
    label: 'Price',
    rules: [BeakRequired(), BeakMin(0)],
    prefix: '€',
    sortable: true,
    filterable: true,
  );

  /// Units in stock.
  static const BeakIntColumn stock = BeakIntColumn(
    key: 'stock',
    label: 'Stock',
    rules: [BeakRequired()],
    suffix: ' pcs',
    min: 0,
    sortable: true,
  );

  /// Whether the product is featured on the storefront.
  static const BeakBoolColumn featured = BeakBoolColumn(
    key: 'featured',
    label: 'Featured',
    rules: [BeakRequired()],
    filterable: true,
  );

  /// Lifecycle state, rendered as a coloured badge.
  static const BeakEnumColumn<ProductStatus> status =
      BeakEnumColumn<ProductStatus>(
        key: 'status',
        label: 'Status',
        rules: [BeakRequired()],
        filterable: true,
        badgeColors: {
          ProductStatus.draft: BeakColor.muted,
          ProductStatus.published: BeakColor.success,
          ProductStatus.archived: BeakColor.warning,
        },
        values: ProductStatus.values,
      );

  /// When the product went on sale.
  static const BeakDateTimeColumn publishedAt = BeakDateTimeColumn(
    key: 'published_at',
    label: 'Published At',
    sortable: true,
    format: BeakDateFormat.relative,
  );

  /// The swatch shown beside the name.
  static const BeakColorColumn swatch = BeakColorColumn(
    key: 'swatch',
    label: 'Swatch',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Storefront metadata the catalog importer round-trips untouched.
  static const BeakJsonColumn metadata = BeakJsonColumn(
    key: 'metadata',
    label: 'Metadata',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// The product photo.
  ///
  /// The rules are enforced twice from this one declaration: in the browser
  /// before the upload starts, and again in the API — a client that skips the
  /// panel does not skip the check.
  static const BeakImageColumn image = BeakImageColumn(
    key: 'image',
    label: 'Image',
    storagePath: 'products',
    maxSizeInBytes: 5 * 1024 * 1024,
    allowedTypes: [BeakFileType.jpeg, BeakFileType.png, BeakFileType.webp],
    thumbnail: BeakDimensions(widthInPixels: 160, heightInPixels: 160),
    transforms: [
      BeakThumbnailTransform(
        size: BeakDimensions(widthInPixels: 160, heightInPixels: 160),
      ),
      BeakFormatTransform.webp(),
    ],
  );

  /// The spec sheet customers download.
  static const BeakFileColumn specSheet = BeakFileColumn(
    key: 'spec_sheet',
    label: 'Spec Sheet',
    storagePath: 'products/specs',
    maxSizeInBytes: 10 * 1024 * 1024,
    allowedTypes: [BeakFileType.pdf],
  );

  /// The stock indicator, drawn by the panel's registered renderer.
  static const BeakCustomColumn stockLevel = BeakCustomColumn(
    key: 'stock_level',
    label: 'Stock Level',
    visibleOn: {BeakContext.table},
    tag: BeakColumnTag('stock_bar'),
  );

  /// Foreign key backing [category].
  static const BeakStringColumn categoryId = BeakStringColumn(
    key: 'category_id',
    label: 'Category',
    visibleOn: {BeakContext.form},
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// When the record was soft-deleted, if it was.
  static const BeakDateTimeColumn deletedAt = BeakDateTimeColumn(
    key: 'deleted_at',
    label: 'Deleted',
    visibleOn: {BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    sku,
    summary,
    description,
    price,
    stock,
    featured,
    status,
    publishedAt,
    swatch,
    metadata,
    image,
    specSheet,
    stockLevel,
    categoryId,
    createdAt,
    updatedAt,
    deletedAt,
  ];
}

/// Typed relationship constants of the products resource.
abstract final class ProductRelations {
  /// The category this product is filed under.
  static const BeakBelongsTo category = BeakBelongsTo(
    key: 'category',
    label: 'Category',
    relatedTable: 'categories',
    displayColumnKey: 'name',
    foreignKey: 'category_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.setNull,
  );

  /// The roast profile for this product, if it is coffee.
  static const BeakHasOne roastProfile = BeakHasOne(
    key: 'roastProfile',
    label: 'Roast Profile',
    relatedTable: 'roast_profiles',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
  );

  /// The tags attached to this product.
  static const BeakBelongsToMany tags = BeakBelongsToMany(
    key: 'tags',
    label: 'Tags',
    relatedTable: 'tags',
    displayColumnKey: 'name',
    pivotTable: 'product_tag',
    foreignPivotKey: 'product_id',
    relatedPivotKey: 'tag_id',
    searchColumnKeys: ['name'],
    allowCreate: true,
  );

  /// The order lines that sold this product.
  static const BeakHasMany orderItems = BeakHasMany(
    key: 'orderItems',
    label: 'Order Items',
    relatedTable: 'order_items',
    displayColumnKey: 'label',
    foreignKey: 'product_id',
    searchColumnKeys: ['label'],
    onDelete: BeakOnDelete.restrict,
  );
}

/// A product in the catalog — the showcase schema.
///
/// Every column kind Beak has appears here once, together with all four
/// relationship kinds, soft deletes and timestamps. Nothing below is repeated
/// anywhere else: `beak prepare` derives the columns, the model, both sides of
/// every relationship, the typed record view and the migration from it.
final class ProductModel extends BeakModel {
  /// Creates the products model.
  const ProductModel();

  @override
  String get table => 'products';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => ProductColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    ProductRelations.category,
    ProductRelations.roastProfile,
    ProductRelations.tags,
    ProductRelations.orderItems,
  ];

  @override
  bool get softDeletes => true;
}

/// A typed, zero-cost view over a products record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const ProductRecord._(BeakRecord record) {
  /// Views [record] as a products row.
  const ProductRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => ProductColumns.id.readFrom(record);

  /// What the product is called.
  ///
  /// Non-nullable, so it is required — the form validator, the API's
  /// validation and the column's `NOT NULL` all follow from the type.
  String get name => ProductColumns.name.require(record);

  /// The stock-keeping unit, unique across the catalog.
  String get sku => ProductColumns.sku.require(record);

  /// The short description shown in listings.
  String? get summary => ProductColumns.summary.readFrom(record);

  /// The long description, edited as rich text.
  String? get description => ProductColumns.description.readFrom(record);

  /// Sale price in euros.
  double get price => ProductColumns.price.require(record);

  /// Units in stock.
  int get stock => ProductColumns.stock.require(record);

  /// Whether the product is featured on the storefront.
  bool get featured => ProductColumns.featured.require(record);

  /// Lifecycle state, rendered as a coloured badge.
  ProductStatus get status => ProductColumns.status.require(record);

  /// When the product went on sale.
  DateTime? get publishedAt => ProductColumns.publishedAt.readFrom(record);

  /// The swatch shown beside the name.
  String? get swatch => ProductColumns.swatch.readFrom(record);

  /// Storefront metadata the catalog importer round-trips untouched.
  String? get metadata => ProductColumns.metadata.readFrom(record);

  /// The product photo.
  ///
  /// The rules are enforced twice from this one declaration: in the browser
  /// before the upload starts, and again in the API — a client that skips the
  /// panel does not skip the check.
  String? get image => ProductColumns.image.readFrom(record);

  /// The spec sheet customers download.
  String? get specSheet => ProductColumns.specSheet.readFrom(record);

  /// The stock indicator, drawn by the panel's registered renderer.
  Object? get stockLevel => ProductColumns.stockLevel.readFrom(record);

  /// Foreign key backing [category].
  String? get categoryId => ProductColumns.categoryId.readFrom(record);

  /// When the record was created.
  DateTime? get createdAt => ProductColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => ProductColumns.updatedAt.readFrom(record);

  /// When the record was soft-deleted, if it was.
  DateTime? get deletedAt => ProductColumns.deletedAt.readFrom(record);

  /// The eager-loaded category, or null when unloaded or unset.
  CategoryRecord? get category => switch (record.relations['category']) {
    [final BeakRecord first, ...] => CategoryRecord.of(first),
    _ => null,
  };

  /// The eager-loaded roast profile, or null when unloaded or unset.
  RoastProfileRecord? get roastProfile =>
      switch (record.relations['roastProfile']) {
        [final BeakRecord first, ...] => RoastProfileRecord.of(first),
        _ => null,
      };

  /// The eager-loaded tags.
  List<TagRecord> get tags => [
    for (final row in record.relations['tags'] ?? const <BeakRecord>[])
      TagRecord.of(row),
  ];

  /// The eager-loaded order items.
  List<OrderItemRecord> get orderItems => [
    for (final row in record.relations['orderItems'] ?? const <BeakRecord>[])
      OrderItemRecord.of(row),
  ];
}

/// Views any record as a products row.
extension ProductRecordAccess on BeakRecord {
  /// This record, typed as a products row.
  ProductRecord get asProduct => ProductRecord.of(this);
}
