// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'team_member.dart';

/// Typed column constants of the team_members resource.
abstract final class TeamMemberColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The member's team role, e.g. "Frontend Dev".
  static const BeakStringColumn role = BeakStringColumn(
    key: 'role',
    label: 'Role',
    rules: [BeakRequired(), BeakMaxLength(80)],
    searchable: true,
  );

  /// Membership state, shown as a colored badge.
  static const BeakEnumColumn<MembershipStatus> status =
      BeakEnumColumn<MembershipStatus>(
        key: 'status',
        label: 'Status',
        filterable: true,
        defaultValue: MembershipStatus.active,
        badgeColors: {
          MembershipStatus.active: BeakColor.success,
          MembershipStatus.pending: BeakColor.warning,
          MembershipStatus.banned: BeakColor.error,
        },
        values: MembershipStatus.values,
      );

  /// When the member joined.
  static const BeakDateTimeColumn joinedAt = BeakDateTimeColumn(
    key: 'joined_at',
    label: 'Joined',
    sortable: true,
    format: BeakDateFormat.relative,
  );

  /// Foreign key backing [user].
  static const BeakStringColumn userId = BeakStringColumn(
    key: 'user_id',
    label: 'User',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [id, role, status, joinedAt, userId];
}

/// Typed relationship constants of the team_members resource.
abstract final class TeamMemberRelations {
  /// The underlying user.
  static const BeakBelongsTo user = BeakBelongsTo(
    key: 'user',
    label: 'User',
    relatedTable: 'users',
    displayColumnKey: 'name',
    foreignKey: 'user_id',
    searchColumnKeys: ['name', 'email'],
  );
}

/// The team-members resource — users in their team-role context.
final class TeamMemberModel extends BeakModel {
  /// Creates the team_members model.
  const TeamMemberModel();

  @override
  String get table => 'team_members';

  @override
  String get displayColumnKey => 'role';

  @override
  List<BeakColumn> get columns => TeamMemberColumns.values;

  @override
  List<BeakRelationship> get relationships => const [TeamMemberRelations.user];

  @override
  List<Enum> get formSlots => _TeamMemberModelFormSlot.values;
}

/// Form-field slots of TeamMemberModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field TeamMember can put on a form.
enum _TeamMemberModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
}

/// A typed, zero-cost view over a team_members record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const TeamMemberRecord._(BeakRecord record) {
  /// Views [record] as a team_members row.
  const TeamMemberRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => TeamMemberColumns.id.readFrom(record);

  /// The member's team role, e.g. "Frontend Dev".
  String get role => TeamMemberColumns.role.require(record);

  /// Membership state, shown as a colored badge.
  MembershipStatus? get status => TeamMemberColumns.status.readFrom(record);

  /// When the member joined.
  DateTime? get joinedAt => TeamMemberColumns.joinedAt.readFrom(record);

  /// Foreign key backing [user].
  String? get userId => TeamMemberColumns.userId.readFrom(record);

  /// The eager-loaded user, or null when unloaded or unset.
  UserRecord? get user => switch (record.relations['user']) {
    [final BeakRecord first, ...] => UserRecord.of(first),
    _ => null,
  };
}

/// Views any record as a team_members row.
extension TeamMemberRecordAccess on BeakRecord {
  /// This record, typed as a team_members row.
  TeamMemberRecord get asTeamMember => TeamMemberRecord.of(this);
}
