// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'voucher.dart';

/// Typed column constants of the vouchers resource.
abstract final class VoucherColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Code entered by an administrator or customer.
  static const BeakStringColumn code = BeakStringColumn(
    key: 'code',
    label: 'Code',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
    unique: true,
  );

  /// Human-readable description.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// Fixed euro value or percentage reduction.
  static const BeakEnumColumn<VoucherKind> kind = BeakEnumColumn<VoucherKind>(
    key: 'kind',
    label: 'Kind',
    rules: [BeakRequired()],
    defaultValue: VoucherKind.fixed,
    values: VoucherKind.values,
  );

  /// Euro amount for fixed vouchers, percentage for percentage vouchers.
  static const BeakIntColumn value = BeakIntColumn(
    key: 'value',
    label: 'Value',
    rules: [BeakRequired(), BeakMin(0)],
    semantic: BeakSemantic.exactDecimal(scale: 2),
  );

  /// Whether new invoices may use this voucher.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
    rules: [BeakRequired()],
  );

  /// Optional first eligible instant, inclusive.
  static const BeakDateTimeColumn startsAt = BeakDateTimeColumn(
    key: 'starts_at',
    label: 'Starts At',
  );

  /// Optional last eligible instant, exclusive.
  static const BeakDateTimeColumn endsAt = BeakDateTimeColumn(
    key: 'ends_at',
    label: 'Ends At',
  );

  /// Minimum net subtotal before vouchers, exact and in euros.
  static const BeakIntColumn minimumSubtotal = BeakIntColumn(
    key: 'minimum_subtotal',
    label: 'Minimum Subtotal',
    rules: [BeakMin(0)],
    semantic: BeakSemantic.money(currency: 'EUR'),
  );

  /// Optional cap on this voucher's discount, exact and in euros.
  static const BeakIntColumn maximumDiscount = BeakIntColumn(
    key: 'maximum_discount',
    label: 'Maximum Discount',
    rules: [BeakMin(0)],
    semantic: BeakSemantic.money(currency: 'EUR'),
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    code,
    name,
    kind,
    value,
    active,
    startsAt,
    endsAt,
    minimumSubtotal,
    maximumDiscount,
  ];
}

/// Typed configuration references for Voucher.
final class VoucherFields {
  /// Creates the fields of Voucher, rooted at its own model.
  const VoucherFields() : _model = const VoucherModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const VoucherFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: VoucherColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Code.
  BeakScalarField<String> get code => BeakScalarField<String>(
    model: _model,
    column: VoucherColumns.code,
    path: _path,
    isRequired: true,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: VoucherColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Kind.
  BeakScalarField<VoucherKind> get kind => BeakScalarField<VoucherKind>(
    model: _model,
    column: VoucherColumns.kind,
    path: _path,
    isRequired: true,
  );

  /// Value.
  BeakScalarField<BeakDecimal> get value => BeakScalarField<BeakDecimal>(
    model: _model,
    column: VoucherColumns.value,
    path: _path,
    isRequired: true,
  );

  /// Active.
  BeakScalarField<bool> get active => BeakScalarField<bool>(
    model: _model,
    column: VoucherColumns.active,
    path: _path,
    isRequired: true,
  );

  /// Starts At.
  BeakScalarField<DateTime> get startsAt => BeakScalarField<DateTime>(
    model: _model,
    column: VoucherColumns.startsAt,
    path: _path,
    isRequired: false,
  );

  /// Ends At.
  BeakScalarField<DateTime> get endsAt => BeakScalarField<DateTime>(
    model: _model,
    column: VoucherColumns.endsAt,
    path: _path,
    isRequired: false,
  );

  /// Minimum Subtotal.
  BeakScalarField<BeakDecimal> get minimumSubtotal =>
      BeakScalarField<BeakDecimal>(
        model: _model,
        column: VoucherColumns.minimumSubtotal,
        path: _path,
        isRequired: false,
      );

  /// Maximum Discount.
  BeakScalarField<BeakDecimal> get maximumDiscount =>
      BeakScalarField<BeakDecimal>(
        model: _model,
        column: VoucherColumns.maximumDiscount,
        path: _path,
        isRequired: false,
      );
}

/// A to-one path to Voucher, retaining its root owner.
final class VoucherToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const VoucherToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const VoucherModel());

  /// Every target field, including names reserved by the path API.
  VoucherFields get fields => VoucherFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Code.
  BeakScalarField<String> get code => fields.code;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Kind.
  BeakScalarField<VoucherKind> get kind => fields.kind;

  /// Value.
  BeakScalarField<BeakDecimal> get value => fields.value;

  /// Active.
  BeakScalarField<bool> get active => fields.active;

  /// Starts At.
  BeakScalarField<DateTime> get startsAt => fields.startsAt;

  /// Ends At.
  BeakScalarField<DateTime> get endsAt => fields.endsAt;

  /// Minimum Subtotal.
  BeakScalarField<BeakDecimal> get minimumSubtotal => fields.minimumSubtotal;

  /// Maximum Discount.
  BeakScalarField<BeakDecimal> get maximumDiscount => fields.maximumDiscount;
}

/// A reusable discount definition; applied invoices retain their own snapshot.
final class VoucherModel extends BeakModel {
  /// Creates the vouchers model.
  const VoucherModel();

  /// Typed field and relation references, including reserved names.
  static const VoucherFields fields = VoucherFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [code] in this model.
  static final code = fields.code;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [kind] in this model.
  static final kind = fields.kind;

  /// Typed reference to [value] in this model.
  static final value = fields.value;

  /// Typed reference to [active] in this model.
  static final active = fields.active;

  /// Typed reference to [startsAt] in this model.
  static final startsAt = fields.startsAt;

  /// Typed reference to [endsAt] in this model.
  static final endsAt = fields.endsAt;

  /// Typed reference to [minimumSubtotal] in this model.
  static final minimumSubtotal = fields.minimumSubtotal;

  /// Typed reference to [maximumDiscount] in this model.
  static final maximumDiscount = fields.maximumDiscount;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const VoucherModel(),
    query: const VoucherModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const VoucherModel(),
        query: const VoucherModel().query(
          filter: filter,
          search: BeakSearch(term, const ['code', 'name']),
        ),
      );

  @override
  String get table => 'vouchers';

  @override
  String get displayColumnKey => 'code';

  @override
  List<BeakColumn> get columns => VoucherColumns.values;
  @override
  List<BeakRecordRule> get validationRules => Voucher.validationRules;

  @override
  List<Enum> get formSlots => _VoucherModelFormSlot.values;
}

/// Form-field slots of VoucherModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Voucher can put on a form.
enum _VoucherModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
}

/// A live, nullable view of an incomplete Voucher draft.
final class VoucherDraft {
  /// Reads values through the session so dependencies stay observable.
  const VoucherDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(VoucherModel.fields.id);

  /// Code, or null while incomplete.
  String? get code => _reader.read(VoucherModel.fields.code);

  /// Name, or null while incomplete.
  String? get name => _reader.read(VoucherModel.fields.name);

  /// Kind, or null while incomplete.
  VoucherKind? get kind => _reader.read(VoucherModel.fields.kind);

  /// Value, or null while incomplete.
  BeakDecimal? get value => _reader.read(VoucherModel.fields.value);

  /// Active, or null while incomplete.
  bool? get active => _reader.read(VoucherModel.fields.active);

  /// Starts At, or null while incomplete.
  DateTime? get startsAt => _reader.read(VoucherModel.fields.startsAt);

  /// Ends At, or null while incomplete.
  DateTime? get endsAt => _reader.read(VoucherModel.fields.endsAt);

  /// Minimum Subtotal, or null while incomplete.
  BeakDecimal? get minimumSubtotal =>
      _reader.read(VoucherModel.fields.minimumSubtotal);

  /// Maximum Discount, or null while incomplete.
  BeakDecimal? get maximumDiscount =>
      _reader.read(VoucherModel.fields.maximumDiscount);
}

/// Typed access to live Voucher form values.
extension VoucherDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  VoucherDraft get asVoucher => VoucherDraft(this);
}

/// A typed, zero-cost view over a vouchers record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const VoucherRecord._(BeakRecord record) {
  /// Views [record] as a vouchers row.
  const VoucherRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => VoucherColumns.id.readFrom(record);

  /// Code entered by an administrator or customer.
  String get code => VoucherColumns.code.require(record);

  /// Human-readable description.
  String get name => VoucherColumns.name.require(record);

  /// Fixed euro value or percentage reduction.
  VoucherKind get kind => VoucherColumns.kind.require(record);

  /// Euro amount for fixed vouchers, percentage for percentage vouchers.
  BeakDecimal get value => VoucherModel.fields.value.require(record);

  /// Whether new invoices may use this voucher.
  bool get active => VoucherColumns.active.require(record);

  /// Optional first eligible instant, inclusive.
  DateTime? get startsAt => VoucherColumns.startsAt.readFrom(record);

  /// Optional last eligible instant, exclusive.
  DateTime? get endsAt => VoucherColumns.endsAt.readFrom(record);

  /// Minimum net subtotal before vouchers, exact and in euros.
  BeakDecimal? get minimumSubtotal =>
      VoucherModel.fields.minimumSubtotal.readFrom(record);

  /// Optional cap on this voucher's discount, exact and in euros.
  BeakDecimal? get maximumDiscount =>
      VoucherModel.fields.maximumDiscount.readFrom(record);
}

/// Views any record as a vouchers row.
extension VoucherRecordAccess on BeakRecord {
  /// This record, typed as a vouchers row.
  VoucherRecord get asVoucher => VoucherRecord.of(this);
}
