// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'ticket.dart';

/// Typed column constants of the tickets resource.
abstract final class TicketColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// One-line summary.
  static const BeakStringColumn subject = BeakStringColumn(
    key: 'subject',
    label: 'Subject',
    rules: [BeakRequired(), BeakMaxLength(160)],
    searchable: true,
    sortable: true,
  );

  /// What the customer wrote.
  static const BeakTextColumn body = BeakTextColumn(
    key: 'body',
    label: 'Body',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// How far along it is.
  static const BeakEnumColumn<TicketStatus> status =
      BeakEnumColumn<TicketStatus>(
        key: 'status',
        label: 'Status',
        rules: [BeakRequired()],
        filterable: true,
        badgeColors: {
          TicketStatus.open: BeakColor.warning,
          TicketStatus.pending: BeakColor.info,
          TicketStatus.closed: BeakColor.success,
        },
        values: TicketStatus.values,
      );

  /// Foreign key backing [account].
  static const BeakStringColumn accountId = BeakStringColumn(
    key: 'account_id',
    label: 'Account',
    visibleOn: {BeakContext.form},
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    subject,
    body,
    status,
    accountId,
    createdAt,
    updatedAt,
  ];
}

/// Typed relationship constants of the tickets resource.
abstract final class TicketRelations {
  /// The account that raised it.
  static const BeakBelongsTo account = BeakBelongsTo(
    key: 'account',
    label: 'Account',
    relatedTable: 'accounts',
    displayColumnKey: 'name',
    foreignKey: 'account_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.cascade,
  );
}

/// A support ticket — a table this app owns outright.
final class TicketModel extends BeakModel {
  /// Creates the tickets model.
  const TicketModel();

  @override
  String get table => 'tickets';

  @override
  String get displayColumnKey => 'subject';

  @override
  List<BeakColumn> get columns => TicketColumns.values;

  @override
  List<BeakRelationship> get relationships => const [TicketRelations.account];
}

/// A typed, zero-cost view over a tickets record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const TicketRecord._(BeakRecord record) {
  /// Views [record] as a tickets row.
  const TicketRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => TicketColumns.id.readFrom(record);

  /// One-line summary.
  String get subject => TicketColumns.subject.require(record);

  /// What the customer wrote.
  String? get body => TicketColumns.body.readFrom(record);

  /// How far along it is.
  TicketStatus get status => TicketColumns.status.require(record);

  /// Foreign key backing [account].
  String? get accountId => TicketColumns.accountId.readFrom(record);

  /// When the record was created.
  DateTime? get createdAt => TicketColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => TicketColumns.updatedAt.readFrom(record);

  /// The eager-loaded account, or null when unloaded or unset.
  LegacyAccountRecord? get account => switch (record.relations['account']) {
    [final BeakRecord first, ...] => LegacyAccountRecord.of(first),
    _ => null,
  };
}

/// Views any record as a tickets row.
extension TicketRecordAccess on BeakRecord {
  /// This record, typed as a tickets row.
  TicketRecord get asTicket => TicketRecord.of(this);
}
