import 'dart:io';

import '../../support/beak_cli_internals.dart';
import 'package:test/test.dart';

/// The two commands that meet an authored `lib/main.dart`, which Beak never
/// rewrites: `beak doctor` warns about a resource class its list is missing,
/// and `beak make:resource` prints the line to add in the form that compiles
/// cleanly where it is pasted.
void main() {
  late Directory root;
  late StringBuffer out;

  void write(String path, String contents) => File('${root.path}/$path')
    ..createSync(recursive: true)
    ..writeAsStringSync(contents);

  setUp(() {
    root = Directory.systemTemp.createTempSync('beak_authored_resources_');
    addTearDown(() => root.deleteSync(recursive: true));
    out = StringBuffer();
    write('pubspec.yaml', '''
name: shop
dependencies:
  beak:
    path: ../beak
''');
  });

  BeakCliEnvironment environment() => BeakCliEnvironment(
    out: out,
    rootDirectory: root,
    now: () => DateTime.utc(2026),
    probe: (host, port) async => false,
  );

  const schema = '''
import 'package:beak/beak.dart';
import 'package:beak/schema.dart';

part '{file}.beak.dart';

@Resource()
final class {name} extends BeakSchema {
  @Display()
  late final String title;
}
''';

  const resourceClass = '''
import 'package:beak/panel.dart';

import 'models/{file}.dart';

final class {name}Resource extends BeakResource {
  const {name}Resource() : super(model: const {name}Model());
}
''';

  /// A feature folder for [name]: its schema class and its resource class.
  void feature(String table, String name, String file) {
    write(
      'lib/resources/$table/models/$file.dart',
      schema.replaceAll('{file}', file).replaceAll('{name}', name),
    );
    write(
      'lib/resources/$table/${file}_resource.dart',
      resourceClass.replaceAll('{file}', file).replaceAll('{name}', name),
    );
  }

  String mainListing(String resources) =>
      '''
import 'package:beak/panel.dart';

BeakPanel buildPanel() => BeakPanel(resources: $resources);
''';

  Future<List<BeakCheck>> diagnoseProject() => diagnose(
    environment(),
    readSchema: (url, {schema = 'public'}) async => [],
  );

  Iterable<BeakCheck> unlisted(List<BeakCheck> checks) => checks.where(
    (check) => check.label.contains('is not listed in lib/main.dart'),
  );

  group('beak doctor', () {
    test(
      'warns for every resource class the entrypoint does not list',
      () async {
        feature('notes', 'Note', 'note');
        feature('tags', 'Tag', 'tag');
        feature('users', 'User', 'user');
        write('lib/main.dart', mainListing('[const NoteResource()]'));

        final Iterable<BeakCheck> warnings = unlisted(await diagnoseProject());

        expect(
          warnings.map((check) => check.status),
          everyElement(BeakCheckStatus.warn),
        );
        expect(warnings, hasLength(2));
        final String labels = warnings.map((check) => check.label).join('\n');
        expect(labels, contains('TagResource'));
        expect(labels, contains('lib/resources/tags/tag_resource.dart'));
        expect(labels, contains('UserResource'));
        expect(labels, contains('lib/resources/users/user_resource.dart'));
        expect(labels, isNot(contains('NoteResource')));
        expect(
          warnings.first.remedy,
          allOf(contains('resources'), contains('lib/main.dart')),
        );
      },
    );

    test('says so when the list is complete', () async {
      feature('notes', 'Note', 'note');
      feature('tags', 'Tag', 'tag');
      write('lib/main.dart', mainListing('[NoteResource(), TagResource()]'));

      final List<BeakCheck> checks = await diagnoseProject();

      expect(unlisted(checks), isEmpty);
      expect(
        checks.where(
          (check) => check.label.contains('lists every resource class'),
        ),
        isNotEmpty,
      );
    });

    test('the const config form is read the same way', () async {
      feature('notes', 'Note', 'note');
      feature('tags', 'Tag', 'tag');
      write('lib/main.dart', '''
import 'package:beak/panel.dart';

BeakPanel buildPanel() => BeakPanel(
  config: const BeakPanelConfig(resources: [NoteResource()]),
);
''');

      final Iterable<BeakCheck> warnings = unlisted(await diagnoseProject());

      expect(warnings.single.label, contains('TagResource'));
    });

    test('a generated entrypoint is left to beak prepare', () async {
      feature('notes', 'Note', 'note');
      write('lib/main.dart', '// GENERATED BY `beak prepare` — DO NOT EDIT.\n');

      final List<BeakCheck> checks = await diagnoseProject();

      expect(unlisted(checks), isEmpty);
      expect(
        checks.where(
          (check) => check.label.contains('lists every resource class'),
        ),
        isEmpty,
      );
    });

    test('a list it cannot read is not second-guessed', () async {
      feature('notes', 'Note', 'note');
      write('lib/main.dart', mainListing('allResources'));

      final List<BeakCheck> checks = await diagnoseProject();

      expect(unlisted(checks), isEmpty);
    });

    test('a project with no resource classes has nothing to report', () async {
      write('lib/main.dart', mainListing('[]'));

      final List<BeakCheck> checks = await diagnoseProject();

      expect(unlisted(checks), isEmpty);
      expect(
        checks.where(
          (check) => check.label.contains('lists every resource class'),
        ),
        isEmpty,
      );
    });
  });

  group('beak make:resource in an authored project', () {
    Future<int> makeWidget() async =>
        await createBeakRunner(
          environment(),
        ).run(['make:resource', 'Widget', '--fields', 'name:string!']) ??
        0;

    test('prints a const entry for a list that is not constant', () async {
      write('lib/main.dart', mainListing('[]'));

      expect(await makeWidget(), 0);

      expect(out.toString(), contains('    const WidgetResource(),'));
    });

    test('prints it without const inside a const BeakPanelConfig', () async {
      write('lib/main.dart', '''
import 'package:beak/panel.dart';

BeakPanel buildPanel() => BeakPanel(
  config: const BeakPanelConfig(resources: []),
);
''');

      expect(await makeWidget(), 0);

      final String printed = out.toString();
      expect(printed, contains('    WidgetResource(),'));
      expect(printed, isNot(contains('const WidgetResource()')));
      expect(
        printed,
        contains("import 'resources/widgets/widget_resource.dart';"),
      );
    });

    test('falls back to const when the entrypoint holds no panel', () async {
      write('lib/main.dart', 'void main() {}\n');

      expect(await makeWidget(), 0);

      expect(out.toString(), contains('    const WidgetResource(),'));
    });
  });
}
