import 'dart:io';

import 'package:args/command_runner.dart';
import '../../support/beak_cli_internals.dart';
import 'package:test/test.dart';

void main() {
  late Directory root;
  late StringBuffer out;
  late List<List<String>> spawned;

  setUp(() {
    root = Directory.systemTemp.createTempSync('beak_create_');
    addTearDown(() => root.deleteSync(recursive: true));
    out = StringBuffer();
    spawned = [];
  });

  BeakCliEnvironment environment({int webExitCode = 0}) => BeakCliEnvironment(
    out: out,
    rootDirectory: root,
    now: () => DateTime.utc(2026, 7, 26, 12),
    probe: (host, port) async => false,
    runProcess: (executable, arguments, {workingDirectory}) async {
      spawned.add([executable, ...arguments]);
      // What the real `flutter create .` does: it fills in the files a
      // Flutter app needs and keeps any that already exist.
      if (webExitCode == 0 && workingDirectory != null) {
        final counterApp = File('$workingDirectory/lib/main.dart');
        if (!counterApp.existsSync()) {
          counterApp
            ..createSync(recursive: true)
            ..writeAsStringSync(
              "import 'package:flutter/material.dart';\n"
              'void main() => runApp(const MyApp());\n',
            );
        }
      }
      return webExitCode;
    },
  );

  Future<int> create(List<String> args, {int webExitCode = 0}) async =>
      await createBeakRunner(
        environment(webExitCode: webExitCode),
      ).run(['create', ...args]) ??
      0;

  String read(String path) => File('${root.path}/$path').readAsStringSync();

  bool exists(String path) => File('${root.path}/$path').existsSync();

  group('scaffold', () {
    test('writes only the files a user actually owns', () async {
      expect(await create(['acme_admin']), 0);

      // What the user writes.
      expect(exists('acme_admin/pubspec.yaml'), isTrue);
      expect(exists('acme_admin/beak.yaml'), isTrue);
      expect(exists('acme_admin/lib/resources/notes/models/note.dart'), isTrue);
      expect(exists('acme_admin/AGENTS.md'), isTrue);
      // The generated panel shows the default resource; a class is written
      // only when the project composes the panel itself.
      expect(
        exists('acme_admin/lib/resources/notes/note_resource.dart'),
        isFalse,
      );

      // What Beak generates, so the project runs as created.
      expect(exists('acme_admin/lib/beak/registry.g.dart'), isTrue);
      expect(exists('acme_admin/lib/main.dart'), isTrue);
      expect(exists('acme_admin/bin/serve.dart'), isTrue);
      expect(exists('acme_admin/bin/migrate.dart'), isTrue);
    });

    test('generates the wiring in the new project, not the parent', () async {
      await create(['acme_admin']);
      expect(exists('lib/beak/registry.g.dart'), isFalse);
      expect(
        read('acme_admin/lib/beak/registry.g.dart'),
        contains('NoteModel'),
      );
    });

    test('git-ignores the entrypoints but not the wiring', () async {
      await create(['acme_admin']);
      final ignored = read('acme_admin/.gitignore');
      expect(ignored, contains('/lib/main.dart'));
      expect(ignored, contains('/bin/serve.dart'));
      expect(ignored, contains('/bin/migrate.dart'));
      expect(ignored, isNot(contains('lib/beak/')));
    });

    test(
      'the entrypoint is Beak\'s, not flutter create\'s counter app',
      () async {
        // `flutter create .` writes lib/main.dart when there is none, and
        // `prepare` keeps any entrypoint without the generated header, so a
        // new project used to boot a Material counter app.
        await create(['acme_admin']);

        final String main = read('acme_admin/lib/main.dart');
        expect(main, startsWith('// GENERATED BY'));
        expect(main, contains('BeakApp'));
        expect(main, isNot(contains('material.dart')));
      },
    );

    test('ends by pointing at migrate, then dev', () async {
      // `beak dev` on a fresh project served an API whose every request
      // failed on a missing table.
      await create(['acme_admin']);

      final String printed = out.toString();
      final int migrate = printed.indexOf('beak migrate');
      final int dev = printed.indexOf('beak dev');
      expect(printed, contains('cd acme_admin'));
      expect(migrate, greaterThan(-1));
      expect(dev, greaterThan(migrate));
    });

    test('delegates web/ to flutter create, without resolving', () async {
      // `--no-pub`: only the web assets are wanted, and resolving here would
      // make scaffolding fail offline for a step that needs no network.
      await create(['acme_admin']);
      expect(spawned.single, [
        'flutter',
        'create',
        '--platforms=web',
        '--no-pub',
        '--project-name',
        'acme_admin',
        '.',
      ]);
    });

    test('a failed web scaffold warns but still produces a project', () async {
      expect(await create(['acme_admin'], webExitCode: 1), 0);
      expect(out.toString(), contains('skipped   web/'));
      expect(exists('acme_admin/lib/beak/registry.g.dart'), isTrue);
    });

    test('replaces the flutter counter test with a real smoke test', () async {
      await create(['acme_admin']);
      final smoke = read('acme_admin/test/widget_test.dart');
      expect(smoke, contains('package:acme_admin/beak/app.g.dart'));
      expect(smoke, contains('BeakApp(dataSource:'));
      expect(smoke, isNot(contains('_PACKAGE_')));
      expect(smoke, isNot(contains('MyApp')));
    });
  });

  group('gitignore', () {
    test('ignores the default SQLite database', () async {
      // The zero-setup default writes a file beside the project; committing
      // it would put a developer's scratch data in everyone's checkout.
      await create(['acme_admin']);

      expect(read('acme_admin/.gitignore'), contains('/*.db'));
    });

    test('commits the lockfile', () async {
      // An application pins what it was tested against.
      await create(['acme_admin']);

      expect(read('acme_admin/.gitignore'), isNot(contains('pubspec.lock')));
    });
  });

  group('--authored', () {
    test(
      'writes an entrypoint the project owns, listing its resource',
      () async {
        expect(await create(['acme_admin', '--authored']), 0);

        final String main = read('acme_admin/lib/main.dart');
        expect(main, isNot(contains('GENERATED')));
        expect(main, contains('BeakPanel('));
        expect(main, contains('resources: ['));
        expect(main, contains('NoteResource()'));
        expect(main, contains("import 'resources/notes/note_resource.dart';"));
      },
    );

    test('writes the resource class beside its schema', () async {
      await create(['acme_admin', '--authored']);

      final String resource = read(
        'acme_admin/lib/resources/notes/note_resource.dart',
      );
      expect(
        resource,
        contains('final class NoteResource extends BeakResource'),
      );
      expect(resource, contains('model: const NoteModel()'));
      expect(resource, contains("import 'models/note.dart';"));
      expect(resource, contains('OiIcons.fileText'));
      expect(resource, contains("navigationGroup: 'Content'"));
      // Nothing generates a panel around it here: lib/main.dart lists it.
      expect(resource, contains('`resources: [...]` list in `lib/main.dart`'));
      expect(resource, isNot(contains('`beak prepare` finds this class')));
      expect(resource, isNot(contains('stays as Beak generates it')));
    });

    test('prepare leaves the entrypoint alone, and finds the class', () async {
      await create(['acme_admin', '--authored']);

      expect(read('acme_admin/lib/main.dart'), isNot(contains('GENERATED')));
      expect(
        read('acme_admin/lib/beak/panel.g.dart'),
        contains('NoteResource()'),
      );
    });

    test(
      'commits the entrypoint but still ignores the generated bin/',
      () async {
        await create(['acme_admin', '--authored']);

        final ignored = read('acme_admin/.gitignore');
        expect(ignored, isNot(contains('/lib/main.dart')));
        expect(ignored, contains('/bin/serve.dart'));
        expect(ignored, contains('/bin/migrate.dart'));
      },
    );

    test('the smoke test pumps the authored panel', () async {
      await create(['acme_admin', '--authored']);

      final smoke = read('acme_admin/test/widget_test.dart');
      expect(smoke, contains('package:acme_admin/main.dart'));
      expect(smoke, contains('buildPanel(dataSource:'));
      expect(smoke, isNot(contains('BeakApp')));
    });

    test('beak.yaml leaves presentation to the resource class', () async {
      await create(['acme_admin', '--authored']);

      expect(read('acme_admin/beak.yaml'), isNot(contains('resources:')));
    });
  });

  group('dependencies', () {
    test('default to git, so a project resolves anywhere', () async {
      await create(['acme_admin']);
      final pubspec = read('acme_admin/pubspec.yaml');
      expect(pubspec, contains('github.com/SimonErich/beak.git'));
      // Pinned to the release this CLI belongs to, so a scaffold does not
      // silently track whatever the default branch holds today.
      expect(pubspec, contains('ref: $beakReleaseRef'));
      expect(beakReleaseRef, 'v$beakCliVersion');
      for (final package in CreateCommand.beakPackages) {
        expect(pubspec, contains('  $package:'));
      }
      // One line, not five: the umbrella re-exports the panel, the server,
      // the migration DSL, the testing toolkit and obers_ui.
      expect(CreateCommand.beakPackages, ['beak']);
      expect(pubspec, isNot(contains('obers_ui:')));
    });

    test('--beak-path points at a local checkout instead', () async {
      await create(['acme_admin', '--beak-path', '/opt/beak']);
      final pubspec = read('acme_admin/pubspec.yaml');
      expect(pubspec, contains('path: /opt/beak/packages/beak'));
      expect(pubspec, isNot(contains('github.com/SimonErich/beak.git')));
      expect(pubspec, isNot(contains('ref:')));
    });

    test('--beak-ref pins another ref', () async {
      await create(['acme_admin', '--beak-ref', 'main']);

      final pubspec = read('acme_admin/pubspec.yaml');
      expect(pubspec, contains('ref: main'));
      expect(pubspec, isNot(contains('ref: $beakReleaseRef')));
    });
  });

  group('docs', () {
    String agents() => CreateCommand.scaffoldFiles(
      'acme_admin',
    ).firstWhere((file) => file.path.endsWith('AGENTS.md')).contents;

    String readme() => CreateCommand.postScaffoldFiles(
      'acme_admin',
    ).firstWhere((file) => file.path.endsWith('README.md')).contents;

    test('the README describes what beak dev actually does', () {
      // `beak dev` serves the API and prints the `flutter run` line; it
      // never served a panel on :3000.
      expect(readme(), isNot(contains('3000')));
      expect(readme(), contains('flutter run'));
      expect(readme(), contains('beak migrate'));
      expect(readme(), contains('lib/resources/<plural>/models/'));
    });

    test('AGENTS.md shows field references, not column constants', () {
      expect(agents(), isNot(contains('NoteColumns')));
      expect(agents(), contains('NoteModel.title'));
      expect(agents(), isNot(contains('run the panel')));
      expect(agents(), contains('flutter run'));
    });

    test('both say how to switch to an authored entrypoint', () {
      expect(agents(), contains('beak eject main'));
      expect(readme(), contains('beak eject main'));
    });
  });

  group('usage', () {
    test('rejects a missing or extra name', () {
      expect(create([]), throwsA(isA<UsageException>()));
      expect(create(['a', 'b']), throwsA(isA<UsageException>()));
    });

    test('rejects a ref for a dependency that is not git', () {
      // A local checkout replaces the git dependency, so the ref would
      // silently mean nothing.
      expect(
        create([
          'acme_admin',
          '--beak-path',
          '/opt/beak',
          '--beak-ref',
          'main',
        ]),
        throwsA(isA<UsageException>()),
      );
    });

    test('rejects a name that is not a Dart package name', () {
      expect(create(['AcmeAdmin']), throwsA(isA<UsageException>()));
      expect(create(['acme-admin']), throwsA(isA<UsageException>()));
      expect(create(['1acme']), throwsA(isA<UsageException>()));
    });
  });

  group('scaffoldFiles is pure', () {
    test('so the scaffold can be asserted without a file system', () {
      final files = CreateCommand.scaffoldFiles('acme_admin');
      expect(files.map((file) => file.path), contains('acme_admin/beak.yaml'));
      expect(
        files.firstWhere((file) => file.path.endsWith('AGENTS.md')).contents,
        contains('Never write a column key or table name as a string'),
      );
    });
  });
}
