import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:beak_cli/beak_cli.dart';
import 'package:test/test.dart';

void main() {
  late Directory root;
  late StringBuffer out;

  setUp(() {
    root = Directory.systemTemp.createTempSync('beak_eject');
    addTearDown(() => root.deleteSync(recursive: true));
    out = StringBuffer();
  });

  Future<int> eject(List<String> args) async =>
      await createBeakRunner(
        BeakCliEnvironment(
          out: out,
          rootDirectory: root,
          now: () => DateTime.utc(2026),
          probe: (host, port) async => false,
        ),
      ).run(['eject', ...args]) ??
      0;

  File file(String path) => File('${root.path}/$path');

  group('an override target', () {
    test('writes a file that compiles and changes nothing', () async {
      expect(await eject(['panel']), 0);

      final String source = file('lib/panel.dart').readAsStringSync();
      expect(source, contains('BeakPanelConfig beakPanel('));
      expect(source, contains('=> defaults;'));
      expect(out.toString(), contains('run `beak prepare`'));
    });

    test('names the symbol discovery looks for, for every target', () async {
      for (final target in BeakEjectTarget.values) {
        if (target.override case final BeakOverrideKind kind) {
          final environment = BeakCliEnvironment(
            out: StringBuffer(),
            rootDirectory: root,
            now: () => DateTime.utc(2026),
            probe: (host, port) async => false,
          );
          await createBeakRunner(
            environment,
          ).run(['eject', target.name, '--force']);

          expect(
            file('lib/${kind.path}').readAsStringSync(),
            contains(kind.symbol),
            reason: '`beak eject ${target.name}` must declare ${kind.symbol}',
          );
        }
      }
    });

    test('refuses to clobber an existing file, and says so', () async {
      file('lib/theme.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('// mine');

      expect(await eject(['theme']), 1);
      expect(file('lib/theme.dart').readAsStringSync(), '// mine');
      expect(out.toString(), contains('already exists'));
    });

    test('--force replaces it', () async {
      file('lib/theme.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('// mine');

      expect(await eject(['theme', '--force']), 0);
      expect(
        file('lib/theme.dart').readAsStringSync(),
        contains('OiThemeData'),
      );
    });
  });

  group('eject main', () {
    test('un-ignores the entrypoints and drops the comment about them', () {
      // The comment tells the reader to run this command, so leaving it would
      // be advice they have already taken.
      const gitignore = '''
# Dart / Flutter
.dart_tool/

# Beak generates these at their canonical paths so `flutter run`, IDE run
# buttons and `dart compile exe` work with no flags. They are regenerated by
# every `beak` command, so they are not worth reviewing.
# Run `beak eject main` if you would rather commit them.
/lib/main.dart
/bin/serve.dart
/bin/migrate.dart

# Secrets
.env
''';

      final String rewritten = EjectCommand.withoutEntrypointRules(gitignore);

      expect(rewritten, isNot(contains('/lib/main.dart')));
      expect(rewritten, isNot(contains('/bin/serve.dart')));
      expect(rewritten, isNot(contains('beak eject main')));
      expect(rewritten, contains('.dart_tool/'));
      expect(rewritten, contains('.env'));
      // No blank-line scar where the block used to be.
      expect(rewritten, isNot(contains('\n\n\n')));
    });

    test('rewrites the project .gitignore', () async {
      file('.gitignore').writeAsStringSync('.dart_tool/\n/lib/main.dart\n');

      expect(await eject(['main']), 0);
      expect(
        file('.gitignore').readAsStringSync(),
        isNot(contains('/lib/main.dart')),
      );
      expect(out.toString(), contains('updated .gitignore'));
    });

    test('is idempotent', () async {
      file('.gitignore').writeAsStringSync('.dart_tool/\n');

      expect(await eject(['main']), 0);
      expect(out.toString(), contains('already committed'));
    });

    test('a project with no .gitignore is already ejected', () async {
      expect(await eject(['main']), 0);
      expect(out.toString(), contains('already committed'));
    });
  });

  group('usage', () {
    test('rejects a missing target, listing what is available', () {
      expect(
        eject([]),
        throwsA(
          isA<UsageException>().having(
            (error) => error.message,
            'message',
            allOf(contains('dashboard'), contains('lib/theme.dart')),
          ),
        ),
      );
    });

    test('rejects an unknown target', () {
      expect(eject(['everything']), throwsA(isA<UsageException>()));
    });
  });
}
