import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../../support/beak_cli_internals.dart';

const String _pubspec = '''
name: shop_models
description: Beak models, shared by a server and an admin.
publish_to: none
environment:
  sdk: ^3.12.0
dependencies:
  beak_core: any
''';

const String _author = '''
import 'package:beak_core/beak_core.dart';
import 'package:beak_core/schema.dart';

import 'book.dart';

part 'author.beak.dart';

/// Someone whose books the shop sells.
@Resource()
final class Author extends BeakSchema {
  /// The name printed on the cover.
  @Display()
  late final String name;

  /// Every book this author wrote.
  @HasMany(foreignKey: 'authorId')
  late final List<Book>? books;
}
''';

const String _book = '''
import 'package:beak_core/beak_core.dart';
import 'package:beak_core/schema.dart';

import 'author.dart';

part 'book.beak.dart';

/// A book on the shelf.
@Resource()
final class Book extends BeakSchema {
  /// The title.
  @Display()
  late final String title;

  /// The author.
  @BelongsTo()
  late final Author author;
}
''';

const String _handWritten = '''
import 'package:beak_core/beak_core.dart';

final class NoteModel extends BeakModel {
  const NoteModel();
  @override
  String get table => 'notes';
  @override
  String get displayColumnKey => 'title';
  @override
  List<BeakColumn> get columns => const [];
}
''';

/// The files of [root], relative to it, in path order.
List<String> _filesOf(Directory root) => [
  for (final entity in root.listSync(recursive: true))
    if (entity is File)
      p.posix.joinAll(p.split(p.relative(entity.path, from: root.path))),
]..sort();

void main() {
  late Directory root;
  late StringBuffer out;

  Directory project(Map<String, String> files) {
    root = Directory.systemTemp.createTempSync('beak_models_only_');
    addTearDown(() => root.deleteSync(recursive: true));
    for (final MapEntry(key: path, value: contents) in {
      'pubspec.yaml': _pubspec,
      ...files,
    }.entries) {
      final file = File(p.join(root.path, path));
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(contents);
    }
    return root;
  }

  BeakCliEnvironment environment() => BeakCliEnvironment(
    out: out,
    rootDirectory: root,
    now: () => DateTime.utc(2026, 7, 26, 12),
    probe: (host, port) async => false,
  );

  Future<int> beak(List<String> args) async =>
      await createBeakRunner(environment()).run(args) ?? 0;

  String read(String path) => File(p.join(root.path, path)).readAsStringSync();

  setUp(() {
    out = StringBuffer();
    project({'lib/models/author.dart': _author, 'lib/models/book.dart': _book});
  });

  group('prepare', () {
    test('writes the schema parts and the registry, and nothing else', () {
      final BeakPrepareResult result = runPrepare(environment());

      expect(result.isSuccess, isTrue);
      expect(result.written, [
        'lib/models/author.beak.dart',
        'lib/models/book.beak.dart',
        'lib/beak/registry.g.dart',
      ]);
      expect(_filesOf(root), [
        'lib/beak/registry.g.dart',
        'lib/models/author.beak.dart',
        'lib/models/author.dart',
        'lib/models/book.beak.dart',
        'lib/models/book.dart',
        'pubspec.yaml',
      ]);
    });

    test('registers the models through beak_core, without Flutter or IO', () {
      runPrepare(environment());

      final String registry = read('lib/beak/registry.g.dart');
      expect(registry, contains("import 'package:beak_core/beak_core.dart';"));
      expect(registry, contains("import '../models/author.dart';"));
      expect(registry, contains('AuthorModel(), BookModel()'));
      expect(registry, contains('BeakModelRegistry buildBeakRegistry()'));
      for (final forbidden in [
        'package:beak/',
        'package:flutter/',
        'dart:io',
        'beak_frontend',
        'beak_backend',
      ]) {
        expect(registry, isNot(contains(forbidden)), reason: forbidden);
      }
    });

    test('carries a header that names the schema class, not beak.yaml', () {
      runPrepare(environment());

      final String registry = read('lib/beak/registry.g.dart');
      expect(registry, startsWith('// GENERATED BY `beak prepare`'));
      expect(registry, isNot(contains('beak.yaml')));
    });

    test('registers a hand-written model beside the schema classes', () {
      File(
        p.join(root.path, 'lib/models/note.dart'),
      ).writeAsStringSync(_handWritten);

      runPrepare(environment());

      expect(read('lib/beak/registry.g.dart'), contains('NoteModel()'));
    });

    test('is formatted, so `dart format` on the package is a no-op', () {
      final BeakPrepareResult result = runPrepare(environment());

      final String registry = read(result.written.last);
      expect(BeakEmitters.format(registry), registry);
    });

    test('says what it did, in the words of a models-only package', () {
      runPrepare(environment());

      expect(out.toString().split('\n'), [
        '  2 models · models-only package',
        '  generated  3 of 3 files',
        '',
      ]);
    });

    test('is idempotent: a second run writes nothing', () {
      runPrepare(environment());
      final Map<String, DateTime> before = {
        for (final path in _filesOf(root))
          path: File(p.join(root.path, path)).lastModifiedSync(),
      };
      out.clear();

      final BeakPrepareResult result = runPrepare(environment());

      expect(result.written, isEmpty);
      expect(result.unchanged.length, 3);
      expect(out.toString(), contains('generated  up to date (3 files)'));
      expect({
        for (final path in _filesOf(root))
          path: File(p.join(root.path, path)).lastModifiedSync(),
      }, before);
    });

    test('does not need a beak.yaml, and does not read one', () {
      expect(File(p.join(root.path, 'beak.yaml')).existsSync(), isFalse);
      File(p.join(root.path, 'beak.yaml')).writeAsStringSync('panel: [oops\n');

      final BeakPrepareResult result = runPrepare(environment());

      expect(result.isSuccess, isTrue);
      expect(result.config.name, 'Shop Models');
    });

    test('writes no create-table migration and no entrypoint', () {
      runPrepare(environment());

      expect(
        Directory(p.join(root.path, 'lib/migrations')).existsSync(),
        isFalse,
      );
      expect(Directory(p.join(root.path, 'bin')).existsSync(), isFalse);
      expect(File(p.join(root.path, 'lib/main.dart')).existsSync(), isFalse);
      for (final name in ['app', 'panel', 'server']) {
        expect(
          File(p.join(root.path, 'lib/beak/$name.g.dart')).existsSync(),
          isFalse,
        );
      }
    });

    test('a package with no models still gets an empty registry', () {
      File(p.join(root.path, 'lib/models/author.dart')).deleteSync();
      File(p.join(root.path, 'lib/models/book.dart')).deleteSync();

      final BeakPrepareResult result = runPrepare(environment());

      expect(result.written, ['lib/beak/registry.g.dart']);
      expect(read('lib/beak/registry.g.dart'), contains('<BeakModel>[]'));
      expect(out.toString(), contains('0 models · models-only package'));
    });

    test('refuses a schema class it cannot read, and writes nothing', () {
      File(p.join(root.path, 'lib/models/book.dart')).writeAsStringSync(
        _book.replaceAll(
          'late final String title;',
          'late final Object title;',
        ),
      );

      final BeakPrepareResult result = runPrepare(environment());

      expect(result.isSuccess, isFalse);
      expect(result.exitCode, 1);
      expect(result.written, isEmpty);
      expect(out.toString(), contains('Cannot generate'));
      expect(
        File(p.join(root.path, 'lib/beak/registry.g.dart')).existsSync(),
        isFalse,
      );
    });

    test('refuses two models of one name', () {
      File(
        p.join(root.path, 'lib/models/note.dart'),
      ).writeAsStringSync(_handWritten);
      File(
        p.join(root.path, 'lib/models/other_note.dart'),
      ).writeAsStringSync(_handWritten);

      final BeakPrepareResult result = runPrepare(environment());

      expect(result.isSuccess, isFalse);
      expect(out.toString(), contains('NoteModel'));
    });

    test('the command skips the agent files with one line', () async {
      expect(await beak(['prepare']), 0);

      expect(
        out.toString(),
        contains('  agents     skipped: ${BeakProjectKind.modelsOnlyPackage}'),
      );
      expect(File(p.join(root.path, 'AGENTS.md')).existsSync(), isFalse);
      expect(File(p.join(root.path, 'CLAUDE.md')).existsSync(), isFalse);
      expect(File(p.join(root.path, '.dart_tool/beak')).existsSync(), isFalse);
    });

    test(
      'the command fails on a schema it cannot read, without agent lines',
      () async {
        File(p.join(root.path, 'lib/models/book.dart')).writeAsStringSync(
          _book.replaceAll(
            'late final String title;',
            'late final Object title;',
          ),
        );

        expect(await beak(['prepare']), 1);

        expect(out.toString(), isNot(contains('agents')));
      },
    );
  });

  group('doctor', () {
    Future<List<BeakCheck>> diagnoseAfterPrepare() async {
      runPrepare(environment());
      return diagnose(environment());
    }

    test('passes on a prepared package, and asks only what applies', () async {
      final List<BeakCheck> checks = await diagnoseAfterPrepare();

      expect(
        checks.where((check) => check.status == BeakCheckStatus.fail),
        isEmpty,
      );
      expect(checks.map((check) => check.label), [
        'models-only package: depends on beak_core, no app',
        'discovered 2 models',
        'schema classes read cleanly',
        'generated files up to date',
        'no file imports the server, the panel or Flutter',
      ]);
    });

    test('never fails for a missing panel, beak.yaml or main.dart', () async {
      final List<BeakCheck> checks = await diagnoseAfterPrepare();

      final String labels = checks.map((check) => check.label).join('\n');
      for (final mention in [
        'beak.yaml',
        'main.dart',
        'entrypoint',
        'panel.g',
        'migration',
        'web/',
        'database',
        'agent',
      ]) {
        expect(labels, isNot(contains(mention)), reason: mention);
      }
    });

    test('names what is missing before the first prepare', () async {
      final List<BeakCheck> checks = await diagnose(environment());

      final BeakCheck stale = checks.singleWhere(
        (check) => check.status == BeakCheckStatus.fail,
      );
      expect(stale.label, 'generated files out of date (3 missing, 0 stale)');
      expect(stale.remedy, 'beak prepare');
    });

    test('names a stale registry', () async {
      runPrepare(environment());
      File(p.join(root.path, 'lib/beak/registry.g.dart')).writeAsStringSync(
        read('lib/beak/registry.g.dart').replaceAll('BookModel()', ''),
      );

      final List<BeakCheck> checks = await diagnose(environment());

      expect(
        checks.map((check) => check.label),
        contains('generated files out of date (0 missing, 1 stale)'),
      );
    });

    test('names a stale part file', () async {
      runPrepare(environment());
      File(
        p.join(root.path, 'lib/models/book.beak.dart'),
      ).writeAsStringSync('${read('lib/models/book.beak.dart')}// edited\n');

      final List<BeakCheck> checks = await diagnose(environment());

      expect(
        checks.map((check) => check.label),
        contains('generated files out of date (0 missing, 1 stale)'),
      );
    });

    test('fails a schema class it cannot read', () async {
      File(p.join(root.path, 'lib/models/book.dart')).writeAsStringSync(
        _book.replaceAll(
          'late final String title;',
          'late final Object title;',
        ),
      );

      final List<BeakCheck> checks = await diagnose(environment());

      final Iterable<BeakCheck> failures = checks.where(
        (check) => check.status == BeakCheckStatus.fail,
      );
      expect(failures.map((check) => check.label), [
        contains('lib/models/book.dart'),
      ]);
      expect(
        checks.map((check) => check.label),
        isNot(contains('schema classes read cleanly')),
      );
    });

    test('fails a file that reaches the server, the panel or Flutter', () async {
      runPrepare(environment());
      for (final (path, import) in [
        ('lib/reaches_beak.dart', "import 'package:beak/beak.dart';"),
        (
          'lib/reaches_server.dart',
          "import 'package:beak_backend/beak_backend.dart';",
        ),
        (
          'lib/reaches_panel.dart',
          "export 'package:beak_frontend/beak_frontend.dart';",
        ),
        ('lib/reaches_flutter.dart', "import 'package:flutter/widgets.dart';"),
        ('lib/reaches_io.dart', "import 'dart:io';"),
      ]) {
        File(p.join(root.path, path)).writeAsStringSync('$import\n');
      }
      File(p.join(root.path, 'lib/quiet.dart')).writeAsStringSync(
        "/// Mentions 'package:beak/beak.dart' in prose only.\nimport 'dart:async';\n",
      );

      final List<BeakCheck> checks = await diagnose(environment());

      final failures = [
        for (final check in checks)
          if (check.status == BeakCheckStatus.fail) check.label,
      ];
      expect(failures, hasLength(5));
      expect(
        failures,
        containsAll([
          contains('lib/reaches_beak.dart imports package:beak/beak.dart'),
          contains('lib/reaches_server.dart imports package:beak_backend/'),
          contains('lib/reaches_panel.dart imports package:beak_frontend/'),
          contains('lib/reaches_flutter.dart imports package:flutter/'),
          contains('lib/reaches_io.dart imports dart:io'),
        ]),
      );
    });

    test('warns when the package holds no model', () async {
      File(p.join(root.path, 'lib/models/author.dart')).deleteSync();
      File(p.join(root.path, 'lib/models/book.dart')).deleteSync();
      runPrepare(environment());

      final List<BeakCheck> checks = await diagnose(environment());

      final BeakCheck none = checks.singleWhere(
        (check) => check.status == BeakCheckStatus.warn,
      );
      expect(none.label, 'no models found under lib/');
      expect(none.remedy, contains('@Resource'));
    });

    test('the command exits 0 on a prepared package and prints JSON', () async {
      runPrepare(environment());
      out.clear();

      expect(await beak(['doctor', '--json']), 0);

      expect(jsonDecode(out.toString()), containsPair('healthy', true));
    });

    test('the command exits 1 before the first prepare', () async {
      expect(await beak(['doctor']), 1);

      expect(out.toString(), contains('generated files out of date'));
    });
  });

  group('agents and docs', () {
    test('agents skips, exits 0, and writes nothing', () async {
      expect(await beak(['agents']), 0);

      expect(out.toString().trim(), BeakProjectKind.modelsOnlyPackage);
      expect(_filesOf(root), [
        'lib/models/author.dart',
        'lib/models/book.dart',
        'pubspec.yaml',
      ]);
    });

    test('agents --check has nothing to check, so it passes', () async {
      expect(await beak(['agents', '--check']), 0);

      expect(out.toString().trim(), BeakProjectKind.modelsOnlyPackage);
    });

    test('syncAgentFiles reports no project', () {
      expect(syncAgentFiles(root), isNull);
    });

    test('docs skips with the same line', () async {
      expect(await beak(['docs']), 0);

      expect(out.toString().trim(), BeakProjectKind.modelsOnlyPackage);
    });

    test(
      'a project without Beak still gets the old message and exit 1',
      () async {
        File(
          p.join(root.path, 'pubspec.yaml'),
        ).writeAsStringSync('name: plain\n');

        expect(await beak(['agents']), 1);
        expect(out.toString().trim(), BeakProjectKind.notABeakProject);
        out.clear();
        expect(await beak(['docs']), 1);
        expect(out.toString().trim(), BeakProjectKind.notABeakProject);
      },
    );
  });
}
