import 'dart:io';

import 'package:beak_cli/beak_cli.dart';
import 'package:test/test.dart';

/// A project directory seeded with [files], plus a pubspec naming it.
Directory projectWith(Map<String, String> files, {String name = 'acme_admin'}) {
  final root = Directory.systemTemp.createTempSync('beak_prepare_');
  addTearDown(() => root.deleteSync(recursive: true));
  final all = {'pubspec.yaml': 'name: $name\n', ...files};
  for (final MapEntry(key: path, value: contents) in all.entries) {
    final file = File('${root.path}/$path');
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(contents);
  }
  return root;
}

BeakCliEnvironment environmentFor(Directory root, {StringSink? out}) =>
    BeakCliEnvironment(
      out: out ?? StringBuffer(),
      rootDirectory: root,
      now: () => DateTime.utc(2026, 7, 26, 12),
      probe: (host, port) async => false,
    );

const String noteModel = '''
import 'package:beak_core/beak_core.dart';

final class NoteModel extends BeakModel {
  const NoteModel();
  @override
  String get table => 'notes';
  @override
  String get displayColumnKey => 'title';
  @override
  List<BeakColumn> get columns => const [];
}
''';

String read(Directory root, String path) =>
    File('${root.path}/$path').readAsStringSync();

void main() {
  group('generated files', () {
    late Directory root;
    late BeakPrepareResult result;

    setUp(() {
      root = projectWith({'lib/models/note.dart': noteModel});
      result = runPrepare(environmentFor(root));
    });

    test('cover the wiring and the three entrypoints', () {
      expect(result.isSuccess, isTrue);
      expect(result.exitCode, 0);
      expect(result.written, [
        // The migration comes first: it must exist before the scan that
        // lists it on the generated host.
        'lib/migrations/create_notes_table.dart',
        'lib/beak/registry.g.dart',
        'lib/beak/panel.g.dart',
        'lib/beak/app.g.dart',
        'lib/beak/server.g.dart',
        'lib/main.dart',
        'bin/serve.dart',
        'bin/migrate.dart',
      ]);
    });

    test('register every discovered model without a registry to edit', () {
      final registry = read(root, 'lib/beak/registry.g.dart');
      expect(registry, contains('NoteModel()'));
      expect(registry, contains('BeakModelRegistry buildBeakRegistry()'));
      expect(registry, contains("import '../models/note.dart';"));
    });

    test('surface every model as a resource in the panel', () {
      // Assert on the pieces, not the layout: the emitter formats its output,
      // so line breaks are the formatter's business, not this test's.
      final panel = read(root, 'lib/beak/panel.g.dart');
      expect(panel, contains('Resource('));
      expect(panel, contains('model: const NoteModel()'));
      expect(panel, contains("title: 'Acme Admin'"));
    });

    test('keep the dataSource seam widget tests rely on', () {
      expect(read(root, 'lib/beak/app.g.dart'), contains('this.dataSource'));
    });

    test('are formatted, so `dart format` on the project is a no-op', () {
      for (final path in result.written) {
        final String contents = read(root, path);
        expect(
          BeakEmitters.format(contents),
          contents,
          reason: '$path is not formatted',
        );
      }
    });

    test('carry a do-not-edit header — except the migration', () {
      // A migration is written once and then owned by the project: it is a
      // starting point, not an artefact Beak keeps rewriting, so telling the
      // reader not to edit it would be wrong.
      for (final path in result.written) {
        final bool isMigration = path.startsWith('lib/migrations/');
        expect(
          read(root, path).startsWith('// GENERATED BY'),
          isMigration ? isFalse : isTrue,
          reason: path,
        );
      }
    });
  });

  group('idempotence', () {
    test('a second run rewrites nothing', () {
      final root = projectWith({'lib/models/note.dart': noteModel});
      runPrepare(environmentFor(root));

      final second = runPrepare(environmentFor(root));
      expect(second.written, isEmpty);
      expect(second.unchanged, hasLength(7));
    });

    test('adding a model rewrites only what changed', () {
      final root = projectWith({'lib/models/note.dart': noteModel});
      runPrepare(environmentFor(root));

      File('${root.path}/lib/models/task.dart').writeAsStringSync(
        noteModel
            .replaceAll('NoteModel', 'TaskModel')
            .replaceAll("'notes'", "'tasks'"),
      );
      final second = runPrepare(environmentFor(root));

      // The new model needs a table; the registry, panel and host name it.
      // The entrypoints do not, so they are left alone.
      expect(second.written, <String>[
        'lib/migrations/create_tasks_table.dart',
        'lib/beak/registry.g.dart',
        'lib/beak/panel.g.dart',
        'lib/beak/server.g.dart',
      ]);
      expect(read(root, 'lib/beak/registry.g.dart'), contains('TaskModel()'));
    });
  });

  group('failure', () {
    test('reports the issue and writes nothing', () {
      final root = projectWith({
        'lib/models/note.dart': '''
import 'package:beak_core/beak_core.dart';

final class NoteModel extends BeakModel {
  NoteModel(this.table);
  @override
  final String table;
}
''',
      });
      final out = StringBuffer();
      final result = runPrepare(environmentFor(root, out: out));

      expect(result.isSuccess, isFalse);
      expect(result.exitCode, 1);
      expect(result.written, isEmpty);
      expect(out.toString(), contains('Cannot generate'));
      expect(out.toString(), contains('const NoteModel()'));
      expect(File('${root.path}/lib/main.dart').existsSync(), isFalse);
    });
  });

  group('migrations', () {
    const category = """
import 'package:beak/beak.dart';
import 'package:beak/schema.dart';

part 'category.beak.dart';

/// A grouping.
@Resource()
final class Category extends BeakSchema {
  /// Its name.
  @Display()
  @Column()
  late final String name;
}
""";
    const product = """
import 'package:beak/beak.dart';
import 'package:beak/schema.dart';

import 'category.dart';

part 'product.beak.dart';

/// Something for sale.
@Resource()
final class Product extends BeakSchema {
  /// Its name.
  @Display()
  @Column()
  late final String name;

  /// What it is filed under.
  @BelongsTo()
  late final Category? category;
}
""";

    List<String> migrationNames(Directory root) => [
      for (final file in Directory(
        '${root.path}/lib/migrations',
      ).listSync().whereType<File>())
        file.uri.pathSegments.last,
    ]..sort();

    test('a model with no table gets one', () {
      // `beak create x && beak dev` used to start a server whose every
      // endpoint failed on a missing table, and doctor said all clear.
      final root = projectWith({'lib/models/note.dart': noteModel});

      runPrepare(environmentFor(root));

      expect(migrationNames(root), <String>['create_notes_table.dart']);
      expect(
        read(root, 'lib/migrations/create_notes_table.dart'),
        contains('BeakBlueprint.defineColumns(table, const NoteModel())'),
      );
    });

    test('a referenced table is created before the table referencing it', () {
      // worm runs migrations in registration order and prepare registers them
      // by declared name, so the timestamps carry the dependency order.
      final root = projectWith({
        'lib/models/product.dart': product,
        'lib/models/category.dart': category,
      });

      runPrepare(environmentFor(root));

      final categoryName = RegExp("'([^']+)'")
          .firstMatch(
            read(
              root,
              'lib/migrations/create_categories_table.dart',
            ).split('String get name =>')[1],
          )!
          .group(1)!;
      final productName = RegExp("'([^']+)'")
          .firstMatch(
            read(
              root,
              'lib/migrations/create_products_table.dart',
            ).split('String get name =>')[1],
          )!
          .group(1)!;
      expect(categoryName.compareTo(productName), isNegative);
    });

    test('a many-to-many gets its pivot, once', () {
      final root = projectWith({
        'lib/models/tag.dart': category.replaceAll('Category', 'Tag'),
        'lib/models/product.dart': """
import 'package:beak/beak.dart';
import 'package:beak/schema.dart';

import 'tag.dart';

part 'product.beak.dart';

/// Something for sale.
@Resource()
final class Product extends BeakSchema {
  /// Its name.
  @Display()
  @Column()
  late final String name;

  /// Its tags.
  @BelongsToMany(pivotTable: 'product_tag')
  late final List<Tag> tags;
}
""",
      });

      runPrepare(environmentFor(root));

      expect(
        migrationNames(root),
        containsAll(<String>[
          'create_product_tag_table.dart',
          'create_products_table.dart',
          'create_tags_table.dart',
        ]),
      );
      expect(
        read(root, 'lib/migrations/create_product_tag_table.dart'),
        contains('BeakBlueprint.createPivot'),
      );
    });

    test('a second run writes nothing and does not duplicate', () {
      // Written once, committed, then the project owns it. Regenerating would
      // discard whatever the project edited.
      final root = projectWith({'lib/models/note.dart': noteModel});
      runPrepare(environmentFor(root));
      final first = read(root, 'lib/migrations/create_notes_table.dart');

      final second = runPrepare(environmentFor(root));

      expect(migrationNames(root), hasLength(1));
      expect(read(root, 'lib/migrations/create_notes_table.dart'), first);
      expect(
        second.written,
        isNot(contains('lib/migrations/create_notes_table.dart')),
      );
    });

    test('an existing migration for the table suppresses generation', () {
      // Coverage is read from the AST, so one migration creating several
      // tables is understood — a filename convention would write duplicates.
      final root = projectWith({
        'lib/models/note.dart': noteModel,
        'lib/migrations/everything.dart': """
import 'package:beak/migrations.dart';

/// Creates every table at once.
final class CreateEverything extends Migration {
  /// Creates the migration.
  const CreateEverything();

  @override
  String get name => '20260101_000000_create_everything';

  @override
  Future<void> upSchema(Schema schema) async {
    await schema.create('notes', (table) => table.idUuid());
  }
}
""",
      });

      runPrepare(environmentFor(root));

      expect(migrationNames(root), <String>['everything.dart']);
    });

    test('managesSchema: false gets no migration', () {
      final root = projectWith({
        'lib/models/category.dart': category.replaceAll(
          '@Resource()',
          '@Resource(managesSchema: false)',
        ),
      });

      runPrepare(environmentFor(root));

      expect(
        Directory('${root.path}/lib/migrations').existsSync(),
        isFalse,
        reason: 'another system already migrates that table',
      );
    });
  });

  group('the table name', () {
    const person = """
import 'package:beak/beak.dart';
import 'package:beak/schema.dart';

part 'person.beak.dart';

/// Someone in the directory.
@Resource(table: 'people')
final class Person extends BeakSchema {
  /// Their name.
  @Display()
  @Column()
  late final String name;
}
""";

    test('an explicit @Resource(table:) drives the beak.yaml lookup', () {
      // The emitter used to pluralise the CLASS name — `Person` -> `persons`
      // — so a resources block keyed by the real table silently applied to
      // nothing and the icon was quietly the default.
      final root = projectWith({
        'lib/models/person.dart': person,
        'beak.yaml': '''
name: Directory
resources:
  people:
    icon: users
    section: People
''',
      });

      final result = runPrepare(environmentFor(root));

      expect(result.isSuccess, isTrue);
      final panel = read(root, 'lib/beak/panel.g.dart');
      expect(panel, contains('OiIcons.users'));
      expect(panel, contains("section: 'People'"));
    });

    test('a key naming no table fails, and suggests the near miss', () {
      // beak.yaml is written before the models exist and outlives renames,
      // so a stale key is the likely case, not the exotic one.
      final root = projectWith({
        'lib/models/note.dart': noteModel,
        'beak.yaml': '''
resources:
  note:
    icon: fileText
''',
      });

      final result = runPrepare(environmentFor(root));

      expect(result.isSuccess, isFalse);
      expect(
        result.discovery.issues.single.message,
        allOf(contains('resources.note'), contains('did you mean notes?')),
      );
    });

    test('a hand-written model reports its own declared table', () {
      final root = projectWith({'lib/models/note.dart': noteModel});

      final discovery = BeakProjectScanner(root).scan();

      expect(discovery.models.single.table, 'notes');
    });
  });

  group('beak.yaml', () {
    test('drives the title, icon and section of a resource', () {
      final root = projectWith({
        'lib/models/note.dart': noteModel,
        'beak.yaml': '''
name: Notebook
resources:
  notes:
    icon: fileText
    section: Content
''',
      });
      runPrepare(environmentFor(root));

      final panel = read(root, 'lib/beak/panel.g.dart');
      expect(panel, contains("title: 'Notebook'"));
      expect(panel, contains('OiIcons.fileText'));
      expect(panel, contains("section: 'Content'"));
    });

    test('an absent file still generates, using defaults', () {
      final root = projectWith({'lib/models/note.dart': noteModel});
      runPrepare(environmentFor(root));
      expect(read(root, 'lib/beak/panel.g.dart'), contains('OiIcons.table'));
    });
  });

  group('overrides', () {
    test('a panel override gets the last word', () {
      final root = projectWith({
        'lib/models/note.dart': noteModel,
        'lib/panel.dart': '''
import 'package:beak_frontend/beak_frontend.dart';

BeakPanelConfig beakPanel(BeakPanelConfig defaults) => defaults;
''',
      });
      runPrepare(environmentFor(root));

      final panel = read(root, 'lib/beak/panel.g.dart');
      expect(panel, contains('return panel.beakPanel(config);'));
    });

    test('a server override is threaded into the host', () {
      final root = projectWith({
        'lib/models/note.dart': noteModel,
        'lib/server.dart': '''
import 'package:beak_backend/beak_backend.dart';

BeakServer beakServer(BeakServerDefaults defaults) => defaults.build();
''',
      });
      runPrepare(environmentFor(root));

      expect(
        read(root, 'lib/beak/server.g.dart'),
        contains('configure: server.beakServer'),
      );
    });
  });
}
