import 'dart:io';

import 'package:beak_cli/beak_cli.dart';
import 'package:test/test.dart';

/// A project directory seeded with [files], plus a pubspec naming it.
Directory projectWith(Map<String, String> files, {String name = 'acme_admin'}) {
  final root = Directory.systemTemp.createTempSync('beak_prepare_');
  addTearDown(() => root.deleteSync(recursive: true));
  final all = {'pubspec.yaml': 'name: $name\n', ...files};
  for (final MapEntry(key: path, value: contents) in all.entries) {
    final file = File('${root.path}/$path');
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(contents);
  }
  return root;
}

BeakCliEnvironment environmentFor(Directory root, {StringSink? out}) =>
    BeakCliEnvironment(
      out: out ?? StringBuffer(),
      rootDirectory: root,
      now: () => DateTime.utc(2026, 7, 26, 12),
      probe: (host, port) async => false,
    );

const String noteModel = '''
import 'package:beak_core/beak_core.dart';

final class NoteModel extends BeakModel {
  const NoteModel();
  @override
  String get table => 'notes';
  @override
  String get displayColumnKey => 'title';
  @override
  List<BeakColumn> get columns => const [];
}
''';

String read(Directory root, String path) =>
    File('${root.path}/$path').readAsStringSync();

void main() {
  group('generated files', () {
    late Directory root;
    late BeakPrepareResult result;

    setUp(() {
      root = projectWith({'lib/models/note.dart': noteModel});
      result = runPrepare(environmentFor(root));
    });

    test('cover the wiring and the three entrypoints', () {
      expect(result.isSuccess, isTrue);
      expect(result.exitCode, 0);
      expect(result.written, [
        'lib/beak/registry.g.dart',
        'lib/beak/panel.g.dart',
        'lib/beak/app.g.dart',
        'lib/beak/server.g.dart',
        'lib/main.dart',
        'bin/serve.dart',
        'bin/migrate.dart',
      ]);
    });

    test('register every discovered model without a registry to edit', () {
      final registry = read(root, 'lib/beak/registry.g.dart');
      expect(registry, contains('NoteModel()'));
      expect(registry, contains('BeakModelRegistry buildBeakRegistry()'));
      expect(registry, contains("import '../models/note.dart';"));
    });

    test('surface every model as a resource in the panel', () {
      // Assert on the pieces, not the layout: the emitter formats its output,
      // so line breaks are the formatter's business, not this test's.
      final panel = read(root, 'lib/beak/panel.g.dart');
      expect(panel, contains('Resource('));
      expect(panel, contains('model: const NoteModel()'));
      expect(panel, contains("title: 'Acme Admin'"));
    });

    test('keep the dataSource seam widget tests rely on', () {
      expect(read(root, 'lib/beak/app.g.dart'), contains('this.dataSource'));
    });

    test('are formatted, so `dart format` on the project is a no-op', () {
      for (final path in result.written) {
        final String contents = read(root, path);
        expect(
          BeakEmitters.format(contents),
          contents,
          reason: '$path is not formatted',
        );
      }
    });

    test('carry a do-not-edit header', () {
      for (final path in result.written) {
        expect(read(root, path), startsWith('// GENERATED BY'));
      }
    });
  });

  group('idempotence', () {
    test('a second run rewrites nothing', () {
      final root = projectWith({'lib/models/note.dart': noteModel});
      runPrepare(environmentFor(root));

      final second = runPrepare(environmentFor(root));
      expect(second.written, isEmpty);
      expect(second.unchanged, hasLength(7));
    });

    test('adding a model rewrites only what changed', () {
      final root = projectWith({'lib/models/note.dart': noteModel});
      runPrepare(environmentFor(root));

      File('${root.path}/lib/models/task.dart').writeAsStringSync(
        noteModel
            .replaceAll('NoteModel', 'TaskModel')
            .replaceAll("'notes'", "'tasks'"),
      );
      final second = runPrepare(environmentFor(root));

      // The registry and panel name the models; the entrypoints do not.
      expect(second.written, [
        'lib/beak/registry.g.dart',
        'lib/beak/panel.g.dart',
      ]);
      expect(read(root, 'lib/beak/registry.g.dart'), contains('TaskModel()'));
    });
  });

  group('failure', () {
    test('reports the issue and writes nothing', () {
      final root = projectWith({
        'lib/models/note.dart': '''
import 'package:beak_core/beak_core.dart';

final class NoteModel extends BeakModel {
  NoteModel(this.table);
  @override
  final String table;
}
''',
      });
      final out = StringBuffer();
      final result = runPrepare(environmentFor(root, out: out));

      expect(result.isSuccess, isFalse);
      expect(result.exitCode, 1);
      expect(result.written, isEmpty);
      expect(out.toString(), contains('Cannot generate'));
      expect(out.toString(), contains('const NoteModel()'));
      expect(File('${root.path}/lib/main.dart').existsSync(), isFalse);
    });
  });

  group('beak.yaml', () {
    test('drives the title, icon and section of a resource', () {
      final root = projectWith({
        'lib/models/note.dart': noteModel,
        'beak.yaml': '''
name: Notebook
resources:
  notes:
    icon: fileText
    section: Content
''',
      });
      runPrepare(environmentFor(root));

      final panel = read(root, 'lib/beak/panel.g.dart');
      expect(panel, contains("title: 'Notebook'"));
      expect(panel, contains('OiIcons.fileText'));
      expect(panel, contains("section: 'Content'"));
    });

    test('an absent file still generates, using defaults', () {
      final root = projectWith({'lib/models/note.dart': noteModel});
      runPrepare(environmentFor(root));
      expect(read(root, 'lib/beak/panel.g.dart'), contains('OiIcons.table'));
    });
  });

  group('overrides', () {
    test('a panel override gets the last word', () {
      final root = projectWith({
        'lib/models/note.dart': noteModel,
        'lib/panel.dart': '''
import 'package:beak_frontend/beak_frontend.dart';

BeakPanelConfig beakPanel(BeakPanelConfig defaults) => defaults;
''',
      });
      runPrepare(environmentFor(root));

      final panel = read(root, 'lib/beak/panel.g.dart');
      expect(panel, contains('return panel.beakPanel(config);'));
    });

    test('a server override is threaded into the host', () {
      final root = projectWith({
        'lib/models/note.dart': noteModel,
        'lib/server.dart': '''
import 'package:beak_backend/beak_backend.dart';

BeakServer beakServer(BeakServerDefaults defaults) => defaults.build();
''',
      });
      runPrepare(environmentFor(root));

      expect(
        read(root, 'lib/beak/server.g.dart'),
        contains('configure: server.beakServer'),
      );
    });
  });
}
