// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'invoice.dart';

/// Typed column constants of the invoices resource.
abstract final class InvoiceColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Invoice number (unique).
  static const BeakStringColumn number = BeakStringColumn(
    key: 'number',
    label: 'Number',
    rules: [BeakRequired(), BeakMaxLength(30)],
    searchable: true,
    sortable: true,
  );

  /// Settlement state, shown as a colored badge.
  static const BeakEnumColumn<InvoiceStatus> status =
      BeakEnumColumn<InvoiceStatus>(
        key: 'status',
        label: 'Status',
        filterable: true,
        defaultValue: InvoiceStatus.draft,
        badgeColors: {
          InvoiceStatus.draft: BeakColor.muted,
          InvoiceStatus.sent: BeakColor.info,
          InvoiceStatus.paid: BeakColor.success,
          InvoiceStatus.partial: BeakColor.warning,
          InvoiceStatus.overdue: BeakColor.error,
          InvoiceStatus.cancelled: BeakColor.secondary,
        },
        values: InvoiceStatus.values,
      );

  /// Issue date.
  static const BeakDateTimeColumn issueDate = BeakDateTimeColumn(
    key: 'issue_date',
    label: 'Issued',
    sortable: true,
  );

  /// Due date.
  static const BeakDateTimeColumn dueDate = BeakDateTimeColumn(
    key: 'due_date',
    label: 'Due',
    sortable: true,
  );

  /// Line-item subtotal.
  static const BeakDecimalColumn subtotal = BeakDecimalColumn(
    key: 'subtotal',
    label: 'Subtotal',
    prefix: r'$',
  );

  /// Discount amount.
  static const BeakDecimalColumn discount = BeakDecimalColumn(
    key: 'discount',
    label: 'Discount',
    prefix: r'$',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Shipping charge.
  static const BeakDecimalColumn shipping = BeakDecimalColumn(
    key: 'shipping',
    label: 'Shipping',
    prefix: r'$',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Tax amount.
  static const BeakDecimalColumn tax = BeakDecimalColumn(
    key: 'tax',
    label: 'Tax',
    prefix: r'$',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Grand total.
  static const BeakDecimalColumn total = BeakDecimalColumn(
    key: 'total',
    label: 'Total',
    prefix: r'$',
    sortable: true,
  );

  /// Outstanding balance.
  static const BeakDecimalColumn balanceDue = BeakDecimalColumn(
    key: 'balance_due',
    label: 'Balance due',
    prefix: r'$',
    sortable: true,
  );

  /// Free-form note.
  static const BeakTextColumn note = BeakTextColumn(
    key: 'note',
    label: 'Note',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Foreign key backing [user].
  static const BeakStringColumn userId = BeakStringColumn(
    key: 'user_id',
    label: 'Bill to',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    number,
    status,
    issueDate,
    dueDate,
    subtotal,
    discount,
    shipping,
    tax,
    total,
    balanceDue,
    note,
    userId,
  ];
}

/// Typed relationship constants of the invoices resource.
abstract final class InvoiceRelations {
  /// The billed user.
  static const BeakBelongsTo user = BeakBelongsTo(
    key: 'user',
    label: 'Bill to',
    relatedTable: 'users',
    displayColumnKey: 'name',
    foreignKey: 'user_id',
    searchColumnKeys: ['name', 'email'],
  );

  /// The line items.
  static const BeakHasMany items = BeakHasMany(
    key: 'items',
    label: 'Items',
    relatedTable: 'invoice_items',
    displayColumnKey: 'item',
    foreignKey: 'invoice_id',
    searchColumnKeys: ['item'],
  );
}

/// The invoices resource — a bill to a customer.
final class InvoiceModel extends BeakModel {
  /// Creates the invoices model.
  const InvoiceModel();

  @override
  String get table => 'invoices';

  @override
  String get displayColumnKey => 'number';

  @override
  List<BeakColumn> get columns => InvoiceColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    InvoiceRelations.user,
    InvoiceRelations.items,
  ];

  @override
  List<Enum> get formSlots => _InvoiceModelFormSlot.values;
}

/// Form-field slots of InvoiceModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Invoice can put on a form.
enum _InvoiceModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
}

/// A typed, zero-cost view over a invoices record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const InvoiceRecord._(BeakRecord record) {
  /// Views [record] as a invoices row.
  const InvoiceRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => InvoiceColumns.id.readFrom(record);

  /// Invoice number (unique).
  String get number => InvoiceColumns.number.require(record);

  /// Settlement state, shown as a colored badge.
  InvoiceStatus? get status => InvoiceColumns.status.readFrom(record);

  /// Issue date.
  DateTime? get issueDate => InvoiceColumns.issueDate.readFrom(record);

  /// Due date.
  DateTime? get dueDate => InvoiceColumns.dueDate.readFrom(record);

  /// Line-item subtotal.
  double? get subtotal => InvoiceColumns.subtotal.readFrom(record);

  /// Discount amount.
  double? get discount => InvoiceColumns.discount.readFrom(record);

  /// Shipping charge.
  double? get shipping => InvoiceColumns.shipping.readFrom(record);

  /// Tax amount.
  double? get tax => InvoiceColumns.tax.readFrom(record);

  /// Grand total.
  double? get total => InvoiceColumns.total.readFrom(record);

  /// Outstanding balance.
  double? get balanceDue => InvoiceColumns.balanceDue.readFrom(record);

  /// Free-form note.
  String? get note => InvoiceColumns.note.readFrom(record);

  /// Foreign key backing [user].
  String? get userId => InvoiceColumns.userId.readFrom(record);

  /// The eager-loaded bill to, or null when unloaded or unset.
  UserRecord? get user => switch (record.relations['user']) {
    [final BeakRecord first, ...] => UserRecord.of(first),
    _ => null,
  };

  /// The eager-loaded items.
  List<InvoiceItemRecord> get items => [
    for (final row in record.relations['items'] ?? const <BeakRecord>[])
      InvoiceItemRecord.of(row),
  ];
}

/// Views any record as a invoices row.
extension InvoiceRecordAccess on BeakRecord {
  /// This record, typed as a invoices row.
  InvoiceRecord get asInvoice => InvoiceRecord.of(this);
}
