// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'sighting.dart';

/// Typed column constants of the sightings resource.
abstract final class SightingColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The day of the count.
  static const BeakDateTimeColumn spottedOn = BeakDateTimeColumn(
    key: 'spotted_on',
    label: 'Spotted On',
    rules: [BeakRequired()],
    sortable: true,
  );

  /// How many birds were counted.
  static const BeakIntColumn birdsSeen = BeakIntColumn(
    key: 'birds_seen',
    label: 'Birds Seen',
    rules: [BeakRequired(), BeakMin(0)],
    sortable: true,
    min: 0,
  );

  /// Foreign key backing [habitat].
  static const BeakStringColumn habitatId = BeakStringColumn(
    key: 'habitat_id',
    label: 'Habitat',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [id, spottedOn, birdsSeen, habitatId];
}

/// Typed relationship constants of the sightings resource.
abstract final class SightingRelations {
  /// The habitat whose visitors were counted.
  static const BeakBelongsTo habitat = BeakBelongsTo(
    key: 'habitat',
    label: 'Habitat',
    relatedTable: 'habitats',
    displayColumnKey: 'name',
    foreignKey: 'habitat_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.setNull,
  );
}

/// Typed configuration references for Sighting.
final class SightingFields {
  /// Creates the fields of Sighting, rooted at its own model.
  const SightingFields() : _model = const SightingModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const SightingFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: SightingColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Spotted On.
  BeakScalarField<DateTime> get spottedOn => BeakScalarField<DateTime>(
    model: _model,
    column: SightingColumns.spottedOn,
    path: _path,
    isRequired: true,
  );

  /// Birds Seen.
  BeakScalarField<int> get birdsSeen => BeakScalarField<int>(
    model: _model,
    column: SightingColumns.birdsSeen,
    path: _path,
    isRequired: true,
  );

  /// Habitat.
  BeakScalarField<String> get habitatId => BeakScalarField<String>(
    model: _model,
    column: SightingColumns.habitatId,
    path: _path,
    isRequired: false,
  );

  /// Habitat.
  HabitatToOneField get habitat => HabitatToOneField(
    model: _model,
    relation: SightingRelations.habitat,
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to Sighting, retaining its root owner.
final class SightingToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const SightingToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const SightingModel());

  /// Every target field, including names reserved by the path API.
  SightingFields get fields => SightingFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Spotted On.
  BeakScalarField<DateTime> get spottedOn => fields.spottedOn;

  /// Birds Seen.
  BeakScalarField<int> get birdsSeen => fields.birdsSeen;

  /// Habitat.
  BeakScalarField<String> get habitatId => fields.habitatId;

  /// Habitat.
  HabitatToOneField get habitat => fields.habitat;
}

/// Wild birds counted from the aviary's roof, one row per day.
///
/// The charts page reads these rows: a line and an area chart over the days,
/// and a heat map of weekdays against weeks.
final class SightingModel extends BeakModel {
  /// Creates the sightings model.
  const SightingModel();

  /// Typed field and relation references, including reserved names.
  static const SightingFields fields = SightingFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [spottedOn] in this model.
  static final spottedOn = fields.spottedOn;

  /// Typed reference to [birdsSeen] in this model.
  static final birdsSeen = fields.birdsSeen;

  /// Typed reference to [habitatId] in this model.
  static final habitatId = fields.habitatId;

  /// Typed reference to [habitat] in this model.
  static final habitat = fields.habitat;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const SightingModel(),
    query: const SightingModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const SightingModel(),
        query: const SightingModel().query(
          filter: filter,
          search: BeakSearch(term, const ['spotted_on']),
        ),
      );

  @override
  String get table => 'sightings';

  @override
  String get displayColumnKey => 'spotted_on';

  @override
  List<BeakColumn> get columns => SightingColumns.values;
  @override
  List<BeakModel> get relatedModels => const [HabitatModel()];

  @override
  List<BeakRelationship> get relationships => const [SightingRelations.habitat];

  @override
  List<Enum> get formSlots => _SightingModelFormSlot.values;
}

/// Form-field slots of SightingModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Sighting can put on a form.
enum _SightingModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
}

/// A live, nullable view of an incomplete Sighting draft.
final class SightingDraft {
  /// Reads values through the session so dependencies stay observable.
  const SightingDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(SightingModel.fields.id);

  /// Spotted On, or null while incomplete.
  DateTime? get spottedOn => _reader.read(SightingModel.fields.spottedOn);

  /// Birds Seen, or null while incomplete.
  int? get birdsSeen => _reader.read(SightingModel.fields.birdsSeen);

  /// Habitat, or null while incomplete.
  String? get habitatId => _reader.read(SightingModel.fields.habitatId);

  /// The selected habitat.
  HabitatRecord? get habitat =>
      switch (_reader.read(SightingModel.fields.habitat)) {
        final BeakRecord record => HabitatRecord.of(record),
        null => null,
      };
}

/// Typed access to live Sighting form values.
extension SightingDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  SightingDraft get asSighting => SightingDraft(this);
}

/// A typed, zero-cost view over a sightings record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const SightingRecord._(BeakRecord record) {
  /// Views [record] as a sightings row.
  const SightingRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => SightingColumns.id.readFrom(record);

  /// The day of the count.
  DateTime get spottedOn => SightingColumns.spottedOn.require(record);

  /// How many birds were counted.
  int get birdsSeen => SightingColumns.birdsSeen.require(record);

  /// Foreign key backing [habitat].
  String? get habitatId => SightingColumns.habitatId.readFrom(record);

  /// The eager-loaded habitat, or null when unloaded or unset.
  HabitatRecord? get habitat => switch (record.relations['habitat']) {
    [final BeakRecord first, ...] => HabitatRecord.of(first),
    _ => null,
  };
}

/// Views any record as a sightings row.
extension SightingRecordAccess on BeakRecord {
  /// This record, typed as a sightings row.
  SightingRecord get asSighting => SightingRecord.of(this);
}
