// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'mail_folder.dart';

/// Typed column constants of the mail_folders resource.
abstract final class MailFolderColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Folder key, e.g. `inbox`.
  static const BeakStringColumn key = BeakStringColumn(
    key: 'key',
    label: 'Key',
    rules: [BeakRequired(), BeakMaxLength(30)],
  );

  /// Display label.
  static const BeakStringColumn label = BeakStringColumn(
    key: 'label',
    label: 'Label',
    rules: [BeakRequired(), BeakMaxLength(40)],
  );

  /// Icon name.
  static const BeakStringColumn icon = BeakStringColumn(
    key: 'icon',
    label: 'Icon',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Folder accent color.
  static const BeakColorColumn color = BeakColorColumn(
    key: 'color',
    label: 'Color',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Unread message count (recomputed by the seeder).
  static const BeakIntColumn unreadCount = BeakIntColumn(
    key: 'unread_count',
    label: 'Unread',
    sortable: true,
    min: 0,
  );

  /// Sidebar ordering.
  static const BeakIntColumn sortIndex = BeakIntColumn(
    key: 'sort_index',
    label: 'Order',
    sortable: true,
    min: 0,
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    key,
    label,
    icon,
    color,
    unreadCount,
    sortIndex,
  ];
}

/// Typed relationship constants of the mail_folders resource.
abstract final class MailFolderRelations {
  /// Emails in this folder.
  static const BeakHasMany emails = BeakHasMany(
    key: 'emails',
    label: 'Emails',
    relatedTable: 'emails',
    displayColumnKey: 'subject',
    foreignKey: 'folder_id',
    searchColumnKeys: ['subject'],
  );
}

/// The mail-folders resource — the inbox sidebar.
final class MailFolderModel extends BeakModel {
  /// Creates the mail_folders model.
  const MailFolderModel();

  @override
  String get table => 'mail_folders';

  @override
  String get displayColumnKey => 'label';

  @override
  List<BeakColumn> get columns => MailFolderColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    MailFolderRelations.emails,
  ];

  @override
  List<Enum> get formSlots => _MailFolderModelFormSlot.values;
}

/// Form-field slots of MailFolderModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field MailFolder can put on a form.
enum _MailFolderModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
}

/// A typed, zero-cost view over a mail_folders record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const MailFolderRecord._(BeakRecord record) {
  /// Views [record] as a mail_folders row.
  const MailFolderRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => MailFolderColumns.id.readFrom(record);

  /// Folder key, e.g. `inbox`.
  String get key => MailFolderColumns.key.require(record);

  /// Display label.
  String get label => MailFolderColumns.label.require(record);

  /// Icon name.
  String? get icon => MailFolderColumns.icon.readFrom(record);

  /// Folder accent color.
  String? get color => MailFolderColumns.color.readFrom(record);

  /// Unread message count (recomputed by the seeder).
  int? get unreadCount => MailFolderColumns.unreadCount.readFrom(record);

  /// Sidebar ordering.
  int? get sortIndex => MailFolderColumns.sortIndex.readFrom(record);

  /// The eager-loaded emails.
  List<EmailRecord> get emails => [
    for (final row in record.relations['emails'] ?? const <BeakRecord>[])
      EmailRecord.of(row),
  ];
}

/// Views any record as a mail_folders row.
extension MailFolderRecordAccess on BeakRecord {
  /// This record, typed as a mail_folders row.
  MailFolderRecord get asMailFolder => MailFolderRecord.of(this);
}
