import '../project/beak_discovery.dart';
import 'beak_schema_emitter.dart';

/// Orders the migrations a host registers so a table is created after the
/// tables its foreign keys point at.
///
/// Migrations run in the order they are registered, and `beak prepare`
/// registers them by declared name, which starts with a timestamp. That is the
/// right order for a migration that did not exist yet when the table it refers
/// to was created, and the wrong one for the rest: a create-table migration
/// reads its model as it is now, so a table created in week one can point at a
/// table created in week three. A fresh database replays week one first, and a
/// `CREATE TABLE` naming a table that is not there is an error on Postgres
/// (SQLite tolerates it, which is how it went unnoticed).
///
/// A migration file is the project's once written, so its name cannot change.
/// The registration order can, and it is regenerated by every `beak prepare`.
abstract final class BeakMigrationOrder {
  /// [discovery] with its migrations in the order a host should register them.
  ///
  /// [tablesReferencedBy] comes from the schemas, see
  /// [BeakSchemaEmitter.foreignKeyTargets]. The one call `beak prepare` and
  /// `beak doctor` both make, so the generated host and the check that
  /// compares it read the same order.
  static BeakDiscovery orderedIn(
    BeakDiscovery discovery, {
    required Map<String, Set<String>> tablesReferencedBy,
  }) => discovery.withMigrations(
    of(
      migrations: discovery.migrations,
      tablesCreatedBy: discovery.tablesCreatedByMigration,
      declaresKeys: discovery.migrationsDeclaringKeys,
      tablesReferencedBy: tablesReferencedBy,
    ),
  );

  /// [migrations], which arrive in name order, with the migration that
  /// creates a table pulled ahead of the first migration whose tables point at
  /// it.
  ///
  /// [tablesCreatedBy] names the tables each migration creates, by migration
  /// class; [declaresKeys] the migrations whose tables take their foreign keys
  /// from the model, since a migration frozen to a table's first columns names
  /// none; [tablesReferencedBy] the tables each table has a foreign key to.
  /// Only the migration that creates the referenced table moves, and it
  /// moves forward, so everything else keeps its place relative to everything
  /// else: an `alter` of a table still follows the migration that creates it,
  /// and a pivot still follows both of its tables.
  ///
  /// A migration that creates no table, a reference to a table no migration
  /// creates, and a reference inside one migration leave the order of names
  /// alone, and so does a cycle, which no order can satisfy.
  static List<BeakDiscoveredSymbol> of({
    required List<BeakDiscoveredSymbol> migrations,
    required Map<String, Set<String>> tablesCreatedBy,
    required Set<String> declaresKeys,
    required Map<String, Set<String>> tablesReferencedBy,
  }) {
    final creatorOf = <String, int>{};
    for (var index = 0; index < migrations.length; index++) {
      for (final table
          in tablesCreatedBy[migrations[index].name] ?? const <String>{}) {
        creatorOf.putIfAbsent(table, () => index);
      }
    }

    // The migrations each migration's tables point at, by index.
    final needs = <int, Set<int>>{
      for (var index = 0; index < migrations.length; index++)
        index: {
          if (declaresKeys.contains(migrations[index].name))
            for (final table
                in tablesCreatedBy[migrations[index].name] ?? const <String>{})
              for (final referenced
                  in tablesReferencedBy[table] ?? const <String>{})
                if (creatorOf[referenced] case final int creator
                    when creator != index)
                  creator,
        },
    };
    _dropCycles(needs);

    final ordered = <BeakDiscoveredSymbol>[];
    final placed = <int>{};
    void place(int index) {
      if (!placed.add(index)) {
        return;
      }
      for (final need in needs[index]!.toList()..sort()) {
        place(need);
      }
      ordered.add(migrations[index]);
    }

    for (var index = 0; index < migrations.length; index++) {
      place(index);
    }
    return ordered;
  }

  /// Removes from [needs] every edge that lies on a cycle.
  static void _dropCycles(Map<int, Set<int>> needs) {
    Set<int> reachableFrom(int start) {
      final seen = <int>{};
      final pending = [...needs[start]!];
      while (pending.isNotEmpty) {
        final int next = pending.removeLast();
        if (seen.add(next)) {
          pending.addAll(needs[next]!);
        }
      }
      return seen;
    }

    final reach = {for (final index in needs.keys) index: reachableFrom(index)};
    for (final MapEntry(key: index, value: edges) in needs.entries) {
      edges.removeWhere((need) => reach[need]!.contains(index));
    }
  }
}
