// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'plan.dart';

/// Typed column constants of the plans resource.
abstract final class PlanColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The plan's name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// A one-line pitch.
  static const BeakStringColumn tagline = BeakStringColumn(
    key: 'tagline',
    label: 'Tagline',
    rules: [BeakRequired()],
  );

  /// Monthly price.
  static const BeakDecimalColumn monthlyPrice = BeakDecimalColumn(
    key: 'monthly_price',
    label: 'Monthly Price',
    rules: [BeakRequired(), BeakMin(0)],
    prefix: '€',
    precision: 2,
  );

  /// Yearly price.
  static const BeakDecimalColumn yearlyPrice = BeakDecimalColumn(
    key: 'yearly_price',
    label: 'Yearly Price',
    rules: [BeakRequired(), BeakMin(0)],
    prefix: '€',
    precision: 2,
  );

  /// Whether to highlight the plan.
  static const BeakBoolColumn featured = BeakBoolColumn(
    key: 'featured',
    label: 'Featured',
    rules: [BeakRequired()],
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    tagline,
    monthlyPrice,
    yearlyPrice,
    featured,
  ];
}

/// Typed relationship constants of the plans resource.
abstract final class PlanRelations {
  /// What the plan includes.
  static const BeakHasMany perks = BeakHasMany(
    key: 'perks',
    label: 'Perks',
    relatedTable: 'plan_perks',
    displayColumnKey: 'label',
    foreignKey: 'plan_id',
    searchColumnKeys: ['label'],
    owned: true,
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for Plan.
final class PlanFields {
  /// Creates the fields of Plan, rooted at its own model.
  const PlanFields() : _model = const PlanModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const PlanFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: PlanColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: PlanColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Tagline.
  BeakScalarField<String> get tagline => BeakScalarField<String>(
    model: _model,
    column: PlanColumns.tagline,
    path: _path,
    isRequired: true,
  );

  /// Monthly Price.
  BeakScalarField<double> get monthlyPrice => BeakScalarField<double>(
    model: _model,
    column: PlanColumns.monthlyPrice,
    path: _path,
    isRequired: true,
  );

  /// Yearly Price.
  BeakScalarField<double> get yearlyPrice => BeakScalarField<double>(
    model: _model,
    column: PlanColumns.yearlyPrice,
    path: _path,
    isRequired: true,
  );

  /// Featured.
  BeakScalarField<bool> get featured => BeakScalarField<bool>(
    model: _model,
    column: PlanColumns.featured,
    path: _path,
    isRequired: true,
  );

  /// Perks.
  BeakToManyField get perks => BeakToManyField(
    model: _model,
    relation: PlanRelations.perks,
    target: const PlanPerkModel(),
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to Plan, retaining its root owner.
final class PlanToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const PlanToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const PlanModel());

  /// Every target field, including names reserved by the path API.
  PlanFields get fields => PlanFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Tagline.
  BeakScalarField<String> get tagline => fields.tagline;

  /// Monthly Price.
  BeakScalarField<double> get monthlyPrice => fields.monthlyPrice;

  /// Yearly Price.
  BeakScalarField<double> get yearlyPrice => fields.yearlyPrice;

  /// Featured.
  BeakScalarField<bool> get featured => fields.featured;

  /// Perks.
  BeakToManyField get perks => fields.perks;
}

/// A sponsorship plan, drawn by the pricing block.
final class PlanModel extends BeakModel {
  /// Creates the plans model.
  const PlanModel();

  /// Typed field and relation references, including reserved names.
  static const PlanFields fields = PlanFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [tagline] in this model.
  static final tagline = fields.tagline;

  /// Typed reference to [monthlyPrice] in this model.
  static final monthlyPrice = fields.monthlyPrice;

  /// Typed reference to [yearlyPrice] in this model.
  static final yearlyPrice = fields.yearlyPrice;

  /// Typed reference to [featured] in this model.
  static final featured = fields.featured;

  /// Typed reference to [perks] in this model.
  static final perks = fields.perks;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const PlanModel(),
    query: const PlanModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const PlanModel(),
        query: const PlanModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'plans';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => PlanColumns.values;
  @override
  List<BeakModel> get relatedModels => const [PlanPerkModel()];

  @override
  List<BeakRelationship> get relationships => const [PlanRelations.perks];

  @override
  List<Enum> get formSlots => _PlanModelFormSlot.values;
}

/// Form-field slots of PlanModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Plan can put on a form.
enum _PlanModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
}

/// A live, nullable view of an incomplete Plan draft.
final class PlanDraft {
  /// Reads values through the session so dependencies stay observable.
  const PlanDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(PlanModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(PlanModel.fields.name);

  /// Tagline, or null while incomplete.
  String? get tagline => _reader.read(PlanModel.fields.tagline);

  /// Monthly Price, or null while incomplete.
  double? get monthlyPrice => _reader.read(PlanModel.fields.monthlyPrice);

  /// Yearly Price, or null while incomplete.
  double? get yearlyPrice => _reader.read(PlanModel.fields.yearlyPrice);

  /// Featured, or null while incomplete.
  bool? get featured => _reader.read(PlanModel.fields.featured);

  /// The selected perks.
  List<PlanPerkRecord> get perks => [
    for (final row
        in _reader.read(PlanModel.fields.perks) ?? const <BeakRecord>[])
      PlanPerkRecord.of(row),
  ];
}

/// Typed access to live Plan form values.
extension PlanDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  PlanDraft get asPlan => PlanDraft(this);
}

/// A typed, zero-cost view over a plans record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const PlanRecord._(BeakRecord record) {
  /// Views [record] as a plans row.
  const PlanRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => PlanColumns.id.readFrom(record);

  /// The plan's name.
  String get name => PlanColumns.name.require(record);

  /// A one-line pitch.
  String get tagline => PlanColumns.tagline.require(record);

  /// Monthly price.
  double get monthlyPrice => PlanColumns.monthlyPrice.require(record);

  /// Yearly price.
  double get yearlyPrice => PlanColumns.yearlyPrice.require(record);

  /// Whether to highlight the plan.
  bool get featured => PlanColumns.featured.require(record);

  /// The eager-loaded perks.
  List<PlanPerkRecord> get perks => [
    for (final row in record.relations['perks'] ?? const <BeakRecord>[])
      PlanPerkRecord.of(row),
  ];
}

/// Views any record as a plans row.
extension PlanRecordAccess on BeakRecord {
  /// This record, typed as a plans row.
  PlanRecord get asPlan => PlanRecord.of(this);
}
