// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'conversation_participant.dart';

/// Typed column constants of the conversation_participants resource.
abstract final class ConversationParticipantColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Membership role, e.g. `owner` or `member`.
  static const BeakStringColumn role = BeakStringColumn(
    key: 'role',
    label: 'Role',
    rules: [BeakMaxLength(30)],
  );

  /// Unread message count for this participant.
  static const BeakIntColumn unreadCount = BeakIntColumn(
    key: 'unread_count',
    label: 'Unread',
    min: 0,
    sortable: true,
  );

  /// When this participant last read the conversation.
  static const BeakDateTimeColumn lastReadAt = BeakDateTimeColumn(
    key: 'last_read_at',
    label: 'Last read',
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.detail},
  );

  /// Foreign key backing [conversation].
  static const BeakStringColumn conversationId = BeakStringColumn(
    key: 'conversation_id',
    label: 'Conversation',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [user].
  static const BeakStringColumn userId = BeakStringColumn(
    key: 'user_id',
    label: 'User',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    role,
    unreadCount,
    lastReadAt,
    conversationId,
    userId,
  ];
}

/// Typed relationship constants of the conversation_participants resource.
abstract final class ConversationParticipantRelations {
  /// The conversation.
  static const BeakBelongsTo conversation = BeakBelongsTo(
    key: 'conversation',
    label: 'Conversation',
    relatedTable: 'conversations',
    displayColumnKey: 'title',
    foreignKey: 'conversation_id',
    searchColumnKeys: ['title'],
  );

  /// The participating user.
  static const BeakBelongsTo user = BeakBelongsTo(
    key: 'user',
    label: 'User',
    relatedTable: 'users',
    displayColumnKey: 'name',
    foreignKey: 'user_id',
    searchColumnKeys: ['name'],
  );
}

/// The conversation-participants resource — a chat membership.
final class ConversationParticipantModel extends BeakModel {
  /// Creates the conversation_participants model.
  const ConversationParticipantModel();

  @override
  String get table => 'conversation_participants';

  @override
  String get displayColumnKey => 'role';

  @override
  List<BeakColumn> get columns => ConversationParticipantColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    ConversationParticipantRelations.conversation,
    ConversationParticipantRelations.user,
  ];

  @override
  List<Enum> get formSlots => _ConversationParticipantModelFormSlot.values;
}

/// Form-field slots of ConversationParticipantModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field ConversationParticipant can put on a form.
enum _ConversationParticipantModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
}

/// A typed, zero-cost view over a conversation_participants record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const ConversationParticipantRecord._(BeakRecord record) {
  /// Views [record] as a conversation_participants row.
  const ConversationParticipantRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => ConversationParticipantColumns.id.readFrom(record);

  /// Membership role, e.g. `owner` or `member`.
  String? get role => ConversationParticipantColumns.role.readFrom(record);

  /// Unread message count for this participant.
  int? get unreadCount =>
      ConversationParticipantColumns.unreadCount.readFrom(record);

  /// When this participant last read the conversation.
  DateTime? get lastReadAt =>
      ConversationParticipantColumns.lastReadAt.readFrom(record);

  /// Foreign key backing [conversation].
  String? get conversationId =>
      ConversationParticipantColumns.conversationId.readFrom(record);

  /// Foreign key backing [user].
  String? get userId => ConversationParticipantColumns.userId.readFrom(record);

  /// The eager-loaded conversation, or null when unloaded or unset.
  ConversationRecord? get conversation =>
      switch (record.relations['conversation']) {
        [final BeakRecord first, ...] => ConversationRecord.of(first),
        _ => null,
      };

  /// The eager-loaded user, or null when unloaded or unset.
  UserRecord? get user => switch (record.relations['user']) {
    [final BeakRecord first, ...] => UserRecord.of(first),
    _ => null,
  };
}

/// Views any record as a conversation_participants row.
extension ConversationParticipantRecordAccess on BeakRecord {
  /// This record, typed as a conversation_participants row.
  ConversationParticipantRecord get asConversationParticipant =>
      ConversationParticipantRecord.of(this);
}
