// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'conversation.dart';

/// Typed column constants of the conversations resource.
abstract final class ConversationColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Direct or group.
  static const BeakEnumColumn<ConversationType> type =
      BeakEnumColumn<ConversationType>(
        key: 'type',
        label: 'Type',
        filterable: true,
        defaultValue: ConversationType.direct,
        badgeColors: {
          ConversationType.direct: BeakColor.primary,
          ConversationType.group: BeakColor.info,
        },
        values: ConversationType.values,
      );

  /// Group title (null for direct conversations).
  static const BeakStringColumn title = BeakStringColumn(
    key: 'title',
    label: 'Title',
    rules: [BeakMaxLength(120)],
    searchable: true,
  );

  /// Group description.
  static const BeakTextColumn description = BeakTextColumn(
    key: 'description',
    label: 'Description',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Group avatar image.
  static const BeakImageColumn avatar = BeakImageColumn(
    key: 'avatar',
    label: 'Avatar',
    visibleOn: {BeakContext.form, BeakContext.detail},
    storagePath: 'chat/avatars',
    maxSizeInBytes: 5 * 1024 * 1024,
    allowedTypes: [BeakFileType.jpeg, BeakFileType.png, BeakFileType.webp],
  );

  /// Timestamp of the most recent message.
  static const BeakDateTimeColumn lastMessageAt = BeakDateTimeColumn(
    key: 'last_message_at',
    label: 'Last message',
    format: BeakDateFormat.relative,
    sortable: true,
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    type,
    title,
    description,
    avatar,
    lastMessageAt,
    createdAt,
    updatedAt,
  ];
}

/// Typed relationship constants of the conversations resource.
abstract final class ConversationRelations {
  /// The messages in this conversation.
  static const BeakHasMany messages = BeakHasMany(
    key: 'messages',
    label: 'Messages',
    relatedTable: 'chat_messages',
    displayColumnKey: 'body',
    foreignKey: 'conversation_id',
    searchColumnKeys: ['body'],
  );

  /// The participants (as first-class membership records carrying role and
  /// unread state).
  static const BeakHasMany participants = BeakHasMany(
    key: 'participants',
    label: 'Participants',
    relatedTable: 'conversation_participants',
    displayColumnKey: 'role',
    foreignKey: 'conversation_id',
    searchColumnKeys: ['role'],
  );
}

/// The conversations resource — a direct or group chat thread.
final class ConversationModel extends BeakModel {
  /// Creates the conversations model.
  const ConversationModel();

  @override
  String get table => 'conversations';

  @override
  String get displayColumnKey => 'title';

  @override
  List<BeakColumn> get columns => ConversationColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    ConversationRelations.messages,
    ConversationRelations.participants,
  ];

  @override
  List<Enum> get formSlots => _ConversationModelFormSlot.values;
}

/// Form-field slots of ConversationModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Conversation can put on a form.
enum _ConversationModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
}

/// A typed, zero-cost view over a conversations record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const ConversationRecord._(BeakRecord record) {
  /// Views [record] as a conversations row.
  const ConversationRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => ConversationColumns.id.readFrom(record);

  /// Direct or group.
  ConversationType? get type => ConversationColumns.type.readFrom(record);

  /// Group title (null for direct conversations).
  String? get title => ConversationColumns.title.readFrom(record);

  /// Group description.
  String? get description => ConversationColumns.description.readFrom(record);

  /// Group avatar image.
  String? get avatar => ConversationColumns.avatar.readFrom(record);

  /// Timestamp of the most recent message.
  DateTime? get lastMessageAt =>
      ConversationColumns.lastMessageAt.readFrom(record);

  /// When the record was created.
  DateTime? get createdAt => ConversationColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => ConversationColumns.updatedAt.readFrom(record);

  /// The eager-loaded messages.
  List<ChatMessageRecord> get messages => [
    for (final row in record.relations['messages'] ?? const <BeakRecord>[])
      ChatMessageRecord.of(row),
  ];

  /// The eager-loaded participants.
  List<ConversationParticipantRecord> get participants => [
    for (final row in record.relations['participants'] ?? const <BeakRecord>[])
      ConversationParticipantRecord.of(row),
  ];
}

/// Views any record as a conversations row.
extension ConversationRecordAccess on BeakRecord {
  /// This record, typed as a conversations row.
  ConversationRecord get asConversation => ConversationRecord.of(this);
}
