// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'board.dart';

/// Typed column constants of the boards resource.
abstract final class BoardColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Board name.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired(), BeakMaxLength(120)],
    sortable: true,
    searchable: true,
  );

  /// Board description.
  static const BeakTextColumn description = BeakTextColumn(
    key: 'description',
    label: 'Description',
    visibleOn: {BeakContext.form, BeakContext.detail},
  );

  /// Foreign key backing [owner].
  static const BeakStringColumn ownerId = BeakStringColumn(
    key: 'owner_id',
    label: 'Owner',
    visibleOn: {BeakContext.form},
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    description,
    ownerId,
    createdAt,
    updatedAt,
  ];
}

/// Typed relationship constants of the boards resource.
abstract final class BoardRelations {
  /// The owning user.
  static const BeakBelongsTo owner = BeakBelongsTo(
    key: 'owner',
    label: 'Owner',
    relatedTable: 'users',
    displayColumnKey: 'name',
    foreignKey: 'owner_id',
    searchColumnKeys: ['name'],
  );

  /// The columns on this board.
  static const BeakHasMany columns = BeakHasMany(
    key: 'columns',
    label: 'Columns',
    relatedTable: 'board_columns',
    displayColumnKey: 'name',
    foreignKey: 'board_id',
    searchColumnKeys: ['name'],
  );
}

/// The boards resource — a kanban project board.
final class BoardModel extends BeakModel {
  /// Creates the boards model.
  const BoardModel();

  @override
  String get table => 'boards';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => BoardColumns.values;

  @override
  List<BeakRelationship> get relationships => const [
    BoardRelations.owner,
    BoardRelations.columns,
  ];

  @override
  List<Enum> get formSlots => _BoardModelFormSlot.values;
}

/// Form-field slots of BoardModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Board can put on a form.
enum _BoardModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
}

/// A typed, zero-cost view over a boards record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const BoardRecord._(BeakRecord record) {
  /// Views [record] as a boards row.
  const BoardRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => BoardColumns.id.readFrom(record);

  /// Board name.
  String get name => BoardColumns.name.require(record);

  /// Board description.
  String? get description => BoardColumns.description.readFrom(record);

  /// Foreign key backing [owner].
  String? get ownerId => BoardColumns.ownerId.readFrom(record);

  /// When the record was created.
  DateTime? get createdAt => BoardColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => BoardColumns.updatedAt.readFrom(record);

  /// The eager-loaded owner, or null when unloaded or unset.
  UserRecord? get owner => switch (record.relations['owner']) {
    [final BeakRecord first, ...] => UserRecord.of(first),
    _ => null,
  };

  /// The eager-loaded columns.
  List<BoardColumnRecord> get columns => [
    for (final row in record.relations['columns'] ?? const <BeakRecord>[])
      BoardColumnRecord.of(row),
  ];
}

/// Views any record as a boards row.
extension BoardRecordAccess on BeakRecord {
  /// This record, typed as a boards row.
  BoardRecord get asBoard => BoardRecord.of(this);
}
