// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'product_variant.dart';

/// Typed column constants of the product_variants resource.
abstract final class ProductVariantColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Canonical server-derived combination identity; null for unconfigured variants.
  static const BeakStringColumn combinationKey = BeakStringColumn(
    key: 'combination_key',
    label: 'Combination Key',
    visibleOn: {},
  );

  /// Choice title, such as 1 kg whole bean.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// Unique stock-keeping identifier.
  static const BeakStringColumn sku = BeakStringColumn(
    key: 'sku',
    label: 'Sku',
    rules: [BeakRequired()],
    searchable: true,
    unique: true,
  );

  /// Net unit price in euros.
  static const BeakDecimalColumn price = BeakDecimalColumn(
    key: 'price',
    label: 'Net price',
    rules: [BeakRequired(), BeakMin(0)],
    prefix: '€',
    sortable: true,
  );

  /// Available units in this demonstration inventory.
  static const BeakIntColumn stock = BeakIntColumn(
    key: 'stock',
    label: 'Stock',
    rules: [BeakRequired(), BeakMin(0)],
    sortable: true,
    min: 0,
  );

  /// Whether this variant can be added to a new invoice.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
    rules: [BeakRequired()],
  );

  /// Foreign key backing [product].
  static const BeakStringColumn productId = BeakStringColumn(
    key: 'product_id',
    label: 'Product',
    rules: [BeakRequired()],
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    combinationKey,
    name,
    sku,
    price,
    stock,
    active,
    productId,
  ];
}

/// Typed relationship constants of the product_variants resource.
abstract final class ProductVariantRelations {
  /// Catalog product this variant belongs to.
  static const BeakBelongsTo product = BeakBelongsTo(
    key: 'product',
    label: 'Product',
    relatedTable: 'products',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.cascade,
  );

  /// Values distinguishing this choice from the parent product.
  static const BeakHasMany attributes = BeakHasMany(
    key: 'attributes',
    label: 'Attributes',
    relatedTable: 'variant_attributes',
    displayColumnKey: 'name',
    foreignKey: 'variant_id',
    searchColumnKeys: ['name'],
    owned: true,
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for ProductVariant.
final class ProductVariantFields {
  /// Creates fields rooted at [model], optionally through [path].
  const ProductVariantFields({
    BeakModel model = const ProductVariantModel(),
    List<BeakRelationship> path = const [],
  }) : _model = model,
       _path = path;
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: ProductVariantColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Combination Key.
  BeakScalarField<String> get combinationKey => BeakScalarField<String>(
    model: _model,
    column: ProductVariantColumns.combinationKey,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: ProductVariantColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Sku.
  BeakScalarField<String> get sku => BeakScalarField<String>(
    model: _model,
    column: ProductVariantColumns.sku,
    path: _path,
    isRequired: true,
  );

  /// Net price.
  BeakScalarField<double> get price => BeakScalarField<double>(
    model: _model,
    column: ProductVariantColumns.price,
    path: _path,
    isRequired: true,
  );

  /// Stock.
  BeakScalarField<int> get stock => BeakScalarField<int>(
    model: _model,
    column: ProductVariantColumns.stock,
    path: _path,
    isRequired: true,
  );

  /// Active.
  BeakScalarField<bool> get active => BeakScalarField<bool>(
    model: _model,
    column: ProductVariantColumns.active,
    path: _path,
    isRequired: true,
  );

  /// Product.
  BeakScalarField<String> get productId => BeakScalarField<String>(
    model: _model,
    column: ProductVariantColumns.productId,
    path: _path,
    isRequired: true,
  );

  /// Product.
  ProductToOneField get product => ProductToOneField(
    model: _model,
    relation: ProductVariantRelations.product,
    path: _path,
    isRequired: true,
  );

  /// Attributes.
  BeakToManyField get attributes => BeakToManyField(
    model: _model,
    relation: ProductVariantRelations.attributes,
    target: const VariantAttributeModel(),
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to ProductVariant, retaining its root owner.
final class ProductVariantToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const ProductVariantToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const ProductVariantModel());

  /// Every target field, including names reserved by the path API.
  ProductVariantFields get fields =>
      ProductVariantFields(model: model, path: [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Combination Key.
  BeakScalarField<String> get combinationKey => fields.combinationKey;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Sku.
  BeakScalarField<String> get sku => fields.sku;

  /// Net price.
  BeakScalarField<double> get price => fields.price;

  /// Stock.
  BeakScalarField<int> get stock => fields.stock;

  /// Active.
  BeakScalarField<bool> get active => fields.active;

  /// Product.
  BeakScalarField<String> get productId => fields.productId;

  /// Product.
  ProductToOneField get product => fields.product;

  /// Attributes.
  BeakToManyField get attributes => fields.attributes;
}

/// A sellable product choice with its own price, SKU and inventory.
final class ProductVariantModel extends BeakModel {
  /// Creates the product_variants model.
  const ProductVariantModel();

  /// Typed field and relation references, including reserved names.
  static const ProductVariantFields fields = ProductVariantFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [combinationKey] in this model.
  static final combinationKey = fields.combinationKey;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [sku] in this model.
  static final sku = fields.sku;

  /// Typed reference to [price] in this model.
  static final price = fields.price;

  /// Typed reference to [stock] in this model.
  static final stock = fields.stock;

  /// Typed reference to [active] in this model.
  static final active = fields.active;

  /// Typed reference to [productId] in this model.
  static final productId = fields.productId;

  /// Typed reference to [product] in this model.
  static final product = fields.product;

  /// Typed reference to [attributes] in this model.
  static final attributes = fields.attributes;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const ProductVariantModel(),
    query: const ProductVariantModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const ProductVariantModel(),
        query: const ProductVariantModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name', 'sku']),
        ),
      );

  @override
  String get table => 'product_variants';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => ProductVariantColumns.values;
  @override
  List<BeakRecordRule> get validationRules => ProductVariant.validationRules;
  @override
  List<BeakModel> get relatedModels => const [
    ProductModel(),
    VariantAttributeModel(),
  ];

  @override
  List<BeakRelationship> get relationships => const [
    ProductVariantRelations.product,
    ProductVariantRelations.attributes,
  ];

  @override
  List<Enum> get formSlots => _ProductVariantModelFormSlot.values;
}

/// Form-field slots of ProductVariantModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field ProductVariant can put on a form.
enum _ProductVariantModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
}

/// A live, nullable view of an incomplete ProductVariant draft.
final class ProductVariantDraft {
  /// Reads values through the session so dependencies stay observable.
  const ProductVariantDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(ProductVariantModel.fields.id);

  /// Combination Key, or null while incomplete.
  String? get combinationKey =>
      _reader.read(ProductVariantModel.fields.combinationKey);

  /// Name, or null while incomplete.
  String? get name => _reader.read(ProductVariantModel.fields.name);

  /// Sku, or null while incomplete.
  String? get sku => _reader.read(ProductVariantModel.fields.sku);

  /// Net price, or null while incomplete.
  double? get price => _reader.read(ProductVariantModel.fields.price);

  /// Stock, or null while incomplete.
  int? get stock => _reader.read(ProductVariantModel.fields.stock);

  /// Active, or null while incomplete.
  bool? get active => _reader.read(ProductVariantModel.fields.active);

  /// Product, or null while incomplete.
  String? get productId => _reader.read(ProductVariantModel.fields.productId);

  /// The selected product.
  ProductRecord? get product =>
      switch (_reader.read(ProductVariantModel.fields.product)) {
        final BeakRecord record => ProductRecord.of(record),
        null => null,
      };

  /// The selected attributes.
  List<VariantAttributeRecord> get attributes => [
    for (final row
        in _reader.read(ProductVariantModel.fields.attributes) ??
            const <BeakRecord>[])
      VariantAttributeRecord.of(row),
  ];
}

/// Typed access to live ProductVariant form values.
extension ProductVariantDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  ProductVariantDraft get asProductVariant => ProductVariantDraft(this);
}

/// A typed, zero-cost view over a product_variants record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const ProductVariantRecord._(BeakRecord record) {
  /// Views [record] as a product_variants row.
  const ProductVariantRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => ProductVariantColumns.id.readFrom(record);

  /// Canonical server-derived combination identity; null for unconfigured variants.
  String? get combinationKey =>
      ProductVariantColumns.combinationKey.readFrom(record);

  /// Choice title, such as 1 kg whole bean.
  String get name => ProductVariantColumns.name.require(record);

  /// Unique stock-keeping identifier.
  String get sku => ProductVariantColumns.sku.require(record);

  /// Net unit price in euros.
  double get price => ProductVariantColumns.price.require(record);

  /// Available units in this demonstration inventory.
  int get stock => ProductVariantColumns.stock.require(record);

  /// Whether this variant can be added to a new invoice.
  bool get active => ProductVariantColumns.active.require(record);

  /// Foreign key backing [product].
  String get productId => ProductVariantColumns.productId.require(record);

  /// The eager-loaded product, or null when unloaded or unset.
  ProductRecord? get product => switch (record.relations['product']) {
    [final BeakRecord first, ...] => ProductRecord.of(first),
    _ => null,
  };

  /// The eager-loaded attributes.
  List<VariantAttributeRecord> get attributes => [
    for (final row in record.relations['attributes'] ?? const <BeakRecord>[])
      VariantAttributeRecord.of(row),
  ];
}

/// Views any record as a product_variants row.
extension ProductVariantRecordAccess on BeakRecord {
  /// This record, typed as a product_variants row.
  ProductVariantRecord get asProductVariant => ProductVariantRecord.of(this);
}
