// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'product.dart';

/// Typed column constants of the products resource.
abstract final class ProductColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Product name used in picker suggestions.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// Current catalog unit price in euros.
  static const BeakDecimalColumn price = BeakDecimalColumn(
    key: 'price',
    label: 'Net price',
    rules: [BeakRequired(), BeakMin(0)],
    prefix: '€',
    sortable: true,
  );

  /// Optional stock-keeping identifier for the base product.
  static const BeakStringColumn sku = BeakStringColumn(
    key: 'sku',
    label: 'Sku',
    searchable: true,
  );

  /// Catalog description.
  static const BeakStringColumn description = BeakStringColumn(
    key: 'description',
    label: 'Description',
  );

  /// Whether this product can be sold.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
    rules: [BeakRequired()],
    defaultValue: true,
  );

  /// Foreign key backing [category].
  static const BeakStringColumn categoryId = BeakStringColumn(
    key: 'category_id',
    label: 'Category',
    visibleOn: {BeakContext.form},
  );

  /// Foreign key backing [taxRate].
  static const BeakStringColumn taxRateId = BeakStringColumn(
    key: 'tax_rate_id',
    label: 'Tax Rate',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    price,
    sku,
    description,
    active,
    categoryId,
    taxRateId,
  ];
}

/// Typed relationship constants of the products resource.
abstract final class ProductRelations {
  /// Category and its attribute definitions.
  static const BeakBelongsTo category = BeakBelongsTo(
    key: 'category',
    label: 'Category',
    relatedTable: 'categories',
    displayColumnKey: 'name',
    foreignKey: 'category_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.setNull,
  );

  /// Default exclusive tax rate.
  static const BeakBelongsTo taxRate = BeakBelongsTo(
    key: 'taxRate',
    label: 'Tax Rate',
    relatedTable: 'tax_rates',
    displayColumnKey: 'name',
    foreignKey: 'tax_rate_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.setNull,
  );

  /// Product-specific attribute values.
  static const BeakHasMany attributes = BeakHasMany(
    key: 'attributes',
    label: 'Attributes',
    relatedTable: 'product_attributes',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
    owned: true,
    onDelete: BeakOnDelete.cascade,
  );

  /// Ordered product gallery, saved with the product draft.
  static const BeakHasMany images = BeakHasMany(
    key: 'images',
    label: 'Images',
    relatedTable: 'product_images',
    displayColumnKey: 'caption',
    foreignKey: 'product_id',
    searchColumnKeys: ['caption'],
    owned: true,
    onDelete: BeakOnDelete.cascade,
  );

  /// Sellable variants with separate prices and stock.
  static const BeakHasMany variants = BeakHasMany(
    key: 'variants',
    label: 'Variants',
    relatedTable: 'product_variants',
    displayColumnKey: 'name',
    foreignKey: 'product_id',
    searchColumnKeys: ['name'],
    owned: true,
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for Product.
final class ProductFields {
  /// Creates fields rooted at [model], optionally through [path].
  const ProductFields({
    BeakModel model = const ProductModel(),
    List<BeakRelationship> path = const [],
  }) : _model = model,
       _path = path;
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: ProductColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: ProductColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Net price.
  BeakScalarField<double> get price => BeakScalarField<double>(
    model: _model,
    column: ProductColumns.price,
    path: _path,
    isRequired: true,
  );

  /// Sku.
  BeakScalarField<String> get sku => BeakScalarField<String>(
    model: _model,
    column: ProductColumns.sku,
    path: _path,
    isRequired: false,
  );

  /// Description.
  BeakScalarField<String> get description => BeakScalarField<String>(
    model: _model,
    column: ProductColumns.description,
    path: _path,
    isRequired: false,
  );

  /// Active.
  BeakScalarField<bool> get active => BeakScalarField<bool>(
    model: _model,
    column: ProductColumns.active,
    path: _path,
    isRequired: true,
  );

  /// Category.
  BeakScalarField<String> get categoryId => BeakScalarField<String>(
    model: _model,
    column: ProductColumns.categoryId,
    path: _path,
    isRequired: false,
  );

  /// Tax Rate.
  BeakScalarField<String> get taxRateId => BeakScalarField<String>(
    model: _model,
    column: ProductColumns.taxRateId,
    path: _path,
    isRequired: false,
  );

  /// Category.
  CategoryToOneField get category => CategoryToOneField(
    model: _model,
    relation: ProductRelations.category,
    path: _path,
    isRequired: false,
  );

  /// Tax Rate.
  TaxRateToOneField get taxRate => TaxRateToOneField(
    model: _model,
    relation: ProductRelations.taxRate,
    path: _path,
    isRequired: false,
  );

  /// Attributes.
  BeakToManyField get attributes => BeakToManyField(
    model: _model,
    relation: ProductRelations.attributes,
    target: const ProductAttributeModel(),
    path: _path,
    isRequired: false,
  );

  /// Images.
  BeakToManyField get images => BeakToManyField(
    model: _model,
    relation: ProductRelations.images,
    target: const ProductImageModel(),
    path: _path,
    isRequired: false,
  );

  /// Variants.
  BeakToManyField get variants => BeakToManyField(
    model: _model,
    relation: ProductRelations.variants,
    target: const ProductVariantModel(),
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to Product, retaining its root owner.
final class ProductToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const ProductToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const ProductModel());

  /// Every target field, including names reserved by the path API.
  ProductFields get fields =>
      ProductFields(model: model, path: [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Net price.
  BeakScalarField<double> get price => fields.price;

  /// Sku.
  BeakScalarField<String> get sku => fields.sku;

  /// Description.
  BeakScalarField<String> get description => fields.description;

  /// Active.
  BeakScalarField<bool> get active => fields.active;

  /// Category.
  BeakScalarField<String> get categoryId => fields.categoryId;

  /// Tax Rate.
  BeakScalarField<String> get taxRateId => fields.taxRateId;

  /// Category.
  CategoryToOneField get category => fields.category;

  /// Tax Rate.
  TaxRateToOneField get taxRate => fields.taxRate;

  /// Attributes.
  BeakToManyField get attributes => fields.attributes;

  /// Images.
  BeakToManyField get images => fields.images;

  /// Variants.
  BeakToManyField get variants => fields.variants;
}

/// Product schema; all metadata and typed helpers are generated.
final class ProductModel extends BeakModel {
  /// Creates the products model.
  const ProductModel();

  /// Typed field and relation references, including reserved names.
  static const ProductFields fields = ProductFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [price] in this model.
  static final price = fields.price;

  /// Typed reference to [sku] in this model.
  static final sku = fields.sku;

  /// Typed reference to [description] in this model.
  static final description = fields.description;

  /// Typed reference to [active] in this model.
  static final active = fields.active;

  /// Typed reference to [categoryId] in this model.
  static final categoryId = fields.categoryId;

  /// Typed reference to [taxRateId] in this model.
  static final taxRateId = fields.taxRateId;

  /// Typed reference to [category] in this model.
  static final category = fields.category;

  /// Typed reference to [taxRate] in this model.
  static final taxRate = fields.taxRate;

  /// Typed reference to [attributes] in this model.
  static final attributes = fields.attributes;

  /// Typed reference to [images] in this model.
  static final images = fields.images;

  /// Typed reference to [variants] in this model.
  static final variants = fields.variants;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const ProductModel(),
    query: const ProductModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const ProductModel(),
        query: const ProductModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name', 'sku']),
        ),
      );

  @override
  String get table => 'products';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => ProductColumns.values;
  @override
  List<BeakModel> get relatedModels => const [
    CategoryModel(),
    TaxRateModel(),
    ProductAttributeModel(),
    ProductImageModel(),
    ProductVariantModel(),
  ];

  @override
  List<BeakRelationship> get relationships => const [
    ProductRelations.category,
    ProductRelations.taxRate,
    ProductRelations.attributes,
    ProductRelations.images,
    ProductRelations.variants,
  ];

  @override
  List<Enum> get formSlots => _ProductModelFormSlot.values;
}

/// Form-field slots of ProductModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Product can put on a form.
enum _ProductModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
}

/// A live, nullable view of an incomplete Product draft.
final class ProductDraft {
  /// Reads values through the session so dependencies stay observable.
  const ProductDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(ProductModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(ProductModel.fields.name);

  /// Net price, or null while incomplete.
  double? get price => _reader.read(ProductModel.fields.price);

  /// Sku, or null while incomplete.
  String? get sku => _reader.read(ProductModel.fields.sku);

  /// Description, or null while incomplete.
  String? get description => _reader.read(ProductModel.fields.description);

  /// Active, or null while incomplete.
  bool? get active => _reader.read(ProductModel.fields.active);

  /// Category, or null while incomplete.
  String? get categoryId => _reader.read(ProductModel.fields.categoryId);

  /// Tax Rate, or null while incomplete.
  String? get taxRateId => _reader.read(ProductModel.fields.taxRateId);

  /// The selected category.
  CategoryRecord? get category =>
      switch (_reader.read(ProductModel.fields.category)) {
        final BeakRecord record => CategoryRecord.of(record),
        null => null,
      };

  /// The selected tax rate.
  TaxRateRecord? get taxRate =>
      switch (_reader.read(ProductModel.fields.taxRate)) {
        final BeakRecord record => TaxRateRecord.of(record),
        null => null,
      };

  /// The selected attributes.
  List<ProductAttributeRecord> get attributes => [
    for (final row
        in _reader.read(ProductModel.fields.attributes) ?? const <BeakRecord>[])
      ProductAttributeRecord.of(row),
  ];

  /// The selected images.
  List<ProductImageRecord> get images => [
    for (final row
        in _reader.read(ProductModel.fields.images) ?? const <BeakRecord>[])
      ProductImageRecord.of(row),
  ];

  /// The selected variants.
  List<ProductVariantRecord> get variants => [
    for (final row
        in _reader.read(ProductModel.fields.variants) ?? const <BeakRecord>[])
      ProductVariantRecord.of(row),
  ];
}

/// Typed access to live Product form values.
extension ProductDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  ProductDraft get asProduct => ProductDraft(this);
}

/// A typed, zero-cost view over a products record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const ProductRecord._(BeakRecord record) {
  /// Views [record] as a products row.
  const ProductRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => ProductColumns.id.readFrom(record);

  /// Product name used in picker suggestions.
  String get name => ProductColumns.name.require(record);

  /// Current catalog unit price in euros.
  double get price => ProductColumns.price.require(record);

  /// Optional stock-keeping identifier for the base product.
  String? get sku => ProductColumns.sku.readFrom(record);

  /// Catalog description.
  String? get description => ProductColumns.description.readFrom(record);

  /// Whether this product can be sold.
  bool get active => ProductColumns.active.require(record);

  /// Foreign key backing [category].
  String? get categoryId => ProductColumns.categoryId.readFrom(record);

  /// Foreign key backing [taxRate].
  String? get taxRateId => ProductColumns.taxRateId.readFrom(record);

  /// The eager-loaded category, or null when unloaded or unset.
  CategoryRecord? get category => switch (record.relations['category']) {
    [final BeakRecord first, ...] => CategoryRecord.of(first),
    _ => null,
  };

  /// The eager-loaded tax rate, or null when unloaded or unset.
  TaxRateRecord? get taxRate => switch (record.relations['taxRate']) {
    [final BeakRecord first, ...] => TaxRateRecord.of(first),
    _ => null,
  };

  /// The eager-loaded attributes.
  List<ProductAttributeRecord> get attributes => [
    for (final row in record.relations['attributes'] ?? const <BeakRecord>[])
      ProductAttributeRecord.of(row),
  ];

  /// The eager-loaded images.
  List<ProductImageRecord> get images => [
    for (final row in record.relations['images'] ?? const <BeakRecord>[])
      ProductImageRecord.of(row),
  ];

  /// The eager-loaded variants.
  List<ProductVariantRecord> get variants => [
    for (final row in record.relations['variants'] ?? const <BeakRecord>[])
      ProductVariantRecord.of(row),
  ];
}

/// Views any record as a products row.
extension ProductRecordAccess on BeakRecord {
  /// This record, typed as a products row.
  ProductRecord get asProduct => ProductRecord.of(this);
}
