// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'variant_attribute.dart';

/// Typed column constants of the variant_attributes resource.
abstract final class VariantAttributeColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Characteristic name, such as grind or package size.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// Choice value.
  static const BeakStringColumn value = BeakStringColumn(
    key: 'value',
    label: 'Value',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// Foreign key backing [variant].
  static const BeakStringColumn variantId = BeakStringColumn(
    key: 'variant_id',
    label: 'Variant',
    rules: [BeakRequired()],
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [id, name, value, variantId];
}

/// Typed relationship constants of the variant_attributes resource.
abstract final class VariantAttributeRelations {
  /// Owning variant.
  static const BeakBelongsTo variant = BeakBelongsTo(
    key: 'variant',
    label: 'Variant',
    relatedTable: 'product_variants',
    displayColumnKey: 'name',
    foreignKey: 'variant_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for VariantAttribute.
final class VariantAttributeFields {
  /// Creates fields rooted at [model], optionally through [path].
  const VariantAttributeFields({
    BeakModel model = const VariantAttributeModel(),
    List<BeakRelationship> path = const [],
  }) : _model = model,
       _path = path;
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: VariantAttributeColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: VariantAttributeColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Value.
  BeakScalarField<String> get value => BeakScalarField<String>(
    model: _model,
    column: VariantAttributeColumns.value,
    path: _path,
    isRequired: true,
  );

  /// Variant.
  BeakScalarField<String> get variantId => BeakScalarField<String>(
    model: _model,
    column: VariantAttributeColumns.variantId,
    path: _path,
    isRequired: true,
  );

  /// Variant.
  ProductVariantToOneField get variant => ProductVariantToOneField(
    model: _model,
    relation: VariantAttributeRelations.variant,
    path: _path,
    isRequired: true,
  );
}

/// A to-one path to VariantAttribute, retaining its root owner.
final class VariantAttributeToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const VariantAttributeToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const VariantAttributeModel());

  /// Every target field, including names reserved by the path API.
  VariantAttributeFields get fields =>
      VariantAttributeFields(model: model, path: [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Value.
  BeakScalarField<String> get value => fields.value;

  /// Variant.
  BeakScalarField<String> get variantId => fields.variantId;

  /// Variant.
  ProductVariantToOneField get variant => fields.variant;
}

/// One characteristic of a product variant.
final class VariantAttributeModel extends BeakModel {
  /// Creates the variant_attributes model.
  const VariantAttributeModel();

  /// Typed field and relation references, including reserved names.
  static const VariantAttributeFields fields = VariantAttributeFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [value] in this model.
  static final value = fields.value;

  /// Typed reference to [variantId] in this model.
  static final variantId = fields.variantId;

  /// Typed reference to [variant] in this model.
  static final variant = fields.variant;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const VariantAttributeModel(),
    query: const VariantAttributeModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const VariantAttributeModel(),
        query: const VariantAttributeModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name', 'value']),
        ),
      );

  @override
  String get table => 'variant_attributes';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => VariantAttributeColumns.values;
  @override
  List<BeakModel> get relatedModels => const [ProductVariantModel()];

  @override
  List<BeakRelationship> get relationships => const [
    VariantAttributeRelations.variant,
  ];

  @override
  List<Enum> get formSlots => _VariantAttributeModelFormSlot.values;
}

/// Form-field slots of VariantAttributeModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field VariantAttribute can put on a form.
enum _VariantAttributeModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
}

/// A live, nullable view of an incomplete VariantAttribute draft.
final class VariantAttributeDraft {
  /// Reads values through the session so dependencies stay observable.
  const VariantAttributeDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(VariantAttributeModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(VariantAttributeModel.fields.name);

  /// Value, or null while incomplete.
  String? get value => _reader.read(VariantAttributeModel.fields.value);

  /// Variant, or null while incomplete.
  String? get variantId => _reader.read(VariantAttributeModel.fields.variantId);

  /// The selected variant.
  ProductVariantRecord? get variant =>
      switch (_reader.read(VariantAttributeModel.fields.variant)) {
        final BeakRecord record => ProductVariantRecord.of(record),
        null => null,
      };
}

/// Typed access to live VariantAttribute form values.
extension VariantAttributeDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  VariantAttributeDraft get asVariantAttribute => VariantAttributeDraft(this);
}

/// A typed, zero-cost view over a variant_attributes record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const VariantAttributeRecord._(BeakRecord record) {
  /// Views [record] as a variant_attributes row.
  const VariantAttributeRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => VariantAttributeColumns.id.readFrom(record);

  /// Characteristic name, such as grind or package size.
  String get name => VariantAttributeColumns.name.require(record);

  /// Choice value.
  String get value => VariantAttributeColumns.value.require(record);

  /// Foreign key backing [variant].
  String get variantId => VariantAttributeColumns.variantId.require(record);

  /// The eager-loaded variant, or null when unloaded or unset.
  ProductVariantRecord? get variant => switch (record.relations['variant']) {
    [final BeakRecord first, ...] => ProductVariantRecord.of(first),
    _ => null,
  };
}

/// Views any record as a variant_attributes row.
extension VariantAttributeRecordAccess on BeakRecord {
  /// This record, typed as a variant_attributes row.
  VariantAttributeRecord get asVariantAttribute =>
      VariantAttributeRecord.of(this);
}
