// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'category_attribute.dart';

/// Typed column constants of the category_attributes resource.
abstract final class CategoryAttributeColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Attribute label.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// Optional guidance for entering the value.
  static const BeakStringColumn description = BeakStringColumn(
    key: 'description',
    label: 'Description',
  );

  /// Expected value shape.
  static const BeakEnumColumn<AttributeValueType> valueType =
      BeakEnumColumn<AttributeValueType>(
        key: 'value_type',
        label: 'Value Type',
        rules: [BeakRequired()],
        defaultValue: AttributeValueType.text,
        values: AttributeValueType.values,
      );

  /// Comma-separated choices when the type is choice.
  static const BeakStringColumn choices = BeakStringColumn(
    key: 'choices',
    label: 'Choices',
  );

  /// Whether products should supply this attribute.
  static const BeakBoolColumn required = BeakBoolColumn(
    key: 'required',
    label: 'Required',
    rules: [BeakRequired()],
  );

  /// Foreign key backing [category].
  static const BeakStringColumn categoryId = BeakStringColumn(
    key: 'category_id',
    label: 'Category',
    rules: [BeakRequired()],
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    name,
    description,
    valueType,
    choices,
    required,
    categoryId,
  ];
}

/// Typed relationship constants of the category_attributes resource.
abstract final class CategoryAttributeRelations {
  /// Category that owns this definition.
  static const BeakBelongsTo category = BeakBelongsTo(
    key: 'category',
    label: 'Category',
    relatedTable: 'categories',
    displayColumnKey: 'name',
    foreignKey: 'category_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for CategoryAttribute.
final class CategoryAttributeFields {
  /// Creates the fields of CategoryAttribute, rooted at its own model.
  const CategoryAttributeFields()
    : _model = const CategoryAttributeModel(),
      _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const CategoryAttributeFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: CategoryAttributeColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: CategoryAttributeColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Description.
  BeakScalarField<String> get description => BeakScalarField<String>(
    model: _model,
    column: CategoryAttributeColumns.description,
    path: _path,
    isRequired: false,
  );

  /// Value Type.
  BeakScalarField<AttributeValueType> get valueType =>
      BeakScalarField<AttributeValueType>(
        model: _model,
        column: CategoryAttributeColumns.valueType,
        path: _path,
        isRequired: true,
      );

  /// Choices.
  BeakScalarField<String> get choices => BeakScalarField<String>(
    model: _model,
    column: CategoryAttributeColumns.choices,
    path: _path,
    isRequired: false,
  );

  /// Required.
  BeakScalarField<bool> get required => BeakScalarField<bool>(
    model: _model,
    column: CategoryAttributeColumns.required,
    path: _path,
    isRequired: true,
  );

  /// Category.
  BeakScalarField<String> get categoryId => BeakScalarField<String>(
    model: _model,
    column: CategoryAttributeColumns.categoryId,
    path: _path,
    isRequired: true,
  );

  /// Category.
  CategoryToOneField get category => CategoryToOneField(
    model: _model,
    relation: CategoryAttributeRelations.category,
    path: _path,
    isRequired: true,
  );
}

/// A to-one path to CategoryAttribute, retaining its root owner.
final class CategoryAttributeToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const CategoryAttributeToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const CategoryAttributeModel());

  /// Every target field, including names reserved by the path API.
  CategoryAttributeFields get fields =>
      CategoryAttributeFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Description.
  BeakScalarField<String> get description => fields.description;

  /// Value Type.
  BeakScalarField<AttributeValueType> get valueType => fields.valueType;

  /// Choices.
  BeakScalarField<String> get choices => fields.choices;

  /// Required.
  BeakScalarField<bool> get required => fields.required;

  /// Category.
  BeakScalarField<String> get categoryId => fields.categoryId;

  /// Category.
  CategoryToOneField get category => fields.category;
}

/// A reusable category attribute, such as roast or material.
final class CategoryAttributeModel extends BeakModel {
  /// Creates the category_attributes model.
  const CategoryAttributeModel();

  /// Typed field and relation references, including reserved names.
  static const CategoryAttributeFields fields = CategoryAttributeFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [description] in this model.
  static final description = fields.description;

  /// Typed reference to [valueType] in this model.
  static final valueType = fields.valueType;

  /// Typed reference to [choices] in this model.
  static final choices = fields.choices;

  /// Typed reference to [required] in this model.
  static final required = fields.required;

  /// Typed reference to [categoryId] in this model.
  static final categoryId = fields.categoryId;

  /// Typed reference to [category] in this model.
  static final category = fields.category;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const CategoryAttributeModel(),
    query: const CategoryAttributeModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const CategoryAttributeModel(),
        query: const CategoryAttributeModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'category_attributes';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => CategoryAttributeColumns.values;
  @override
  List<BeakModel> get relatedModels => const [CategoryModel()];

  @override
  List<BeakRelationship> get relationships => const [
    CategoryAttributeRelations.category,
  ];

  @override
  List<Enum> get formSlots => _CategoryAttributeModelFormSlot.values;
}

/// Form-field slots of CategoryAttributeModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field CategoryAttribute can put on a form.
enum _CategoryAttributeModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
}

/// A live, nullable view of an incomplete CategoryAttribute draft.
final class CategoryAttributeDraft {
  /// Reads values through the session so dependencies stay observable.
  const CategoryAttributeDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(CategoryAttributeModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(CategoryAttributeModel.fields.name);

  /// Description, or null while incomplete.
  String? get description =>
      _reader.read(CategoryAttributeModel.fields.description);

  /// Value Type, or null while incomplete.
  AttributeValueType? get valueType =>
      _reader.read(CategoryAttributeModel.fields.valueType);

  /// Choices, or null while incomplete.
  String? get choices => _reader.read(CategoryAttributeModel.fields.choices);

  /// Required, or null while incomplete.
  bool? get required => _reader.read(CategoryAttributeModel.fields.required);

  /// Category, or null while incomplete.
  String? get categoryId =>
      _reader.read(CategoryAttributeModel.fields.categoryId);

  /// The selected category.
  CategoryRecord? get category =>
      switch (_reader.read(CategoryAttributeModel.fields.category)) {
        final BeakRecord record => CategoryRecord.of(record),
        null => null,
      };
}

/// Typed access to live CategoryAttribute form values.
extension CategoryAttributeDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  CategoryAttributeDraft get asCategoryAttribute =>
      CategoryAttributeDraft(this);
}

/// A typed, zero-cost view over a category_attributes record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const CategoryAttributeRecord._(BeakRecord record) {
  /// Views [record] as a category_attributes row.
  const CategoryAttributeRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => CategoryAttributeColumns.id.readFrom(record);

  /// Attribute label.
  String get name => CategoryAttributeColumns.name.require(record);

  /// Optional guidance for entering the value.
  String? get description =>
      CategoryAttributeColumns.description.readFrom(record);

  /// Expected value shape.
  AttributeValueType get valueType =>
      CategoryAttributeColumns.valueType.require(record);

  /// Comma-separated choices when the type is choice.
  String? get choices => CategoryAttributeColumns.choices.readFrom(record);

  /// Whether products should supply this attribute.
  bool get required => CategoryAttributeColumns.required.require(record);

  /// Foreign key backing [category].
  String get categoryId => CategoryAttributeColumns.categoryId.require(record);

  /// The eager-loaded category, or null when unloaded or unset.
  CategoryRecord? get category => switch (record.relations['category']) {
    [final BeakRecord first, ...] => CategoryRecord.of(first),
    _ => null,
  };
}

/// Views any record as a category_attributes row.
extension CategoryAttributeRecordAccess on BeakRecord {
  /// This record, typed as a category_attributes row.
  CategoryAttributeRecord get asCategoryAttribute =>
      CategoryAttributeRecord.of(this);
}
