// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'category.dart';

/// Typed column constants of the categories resource.
abstract final class CategoryColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Category title.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
    sortable: true,
  );

  /// Description shown to administrators.
  static const BeakStringColumn description = BeakStringColumn(
    key: 'description',
    label: 'Description',
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [id, name, description];
}

/// Typed relationship constants of the categories resource.
abstract final class CategoryRelations {
  /// Attributes expected for products in this category.
  static const BeakHasMany attributes = BeakHasMany(
    key: 'attributes',
    label: 'Attributes',
    relatedTable: 'category_attributes',
    displayColumnKey: 'name',
    foreignKey: 'category_id',
    searchColumnKeys: ['name'],
    owned: true,
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for Category.
final class CategoryFields {
  /// Creates the fields of Category, rooted at its own model.
  const CategoryFields() : _model = const CategoryModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const CategoryFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: CategoryColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: CategoryColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Description.
  BeakScalarField<String> get description => BeakScalarField<String>(
    model: _model,
    column: CategoryColumns.description,
    path: _path,
    isRequired: false,
  );

  /// Attributes.
  BeakToManyField get attributes => BeakToManyField(
    model: _model,
    relation: CategoryRelations.attributes,
    target: const CategoryAttributeModel(),
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to Category, retaining its root owner.
final class CategoryToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const CategoryToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const CategoryModel());

  /// Every target field, including names reserved by the path API.
  CategoryFields get fields => CategoryFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Description.
  BeakScalarField<String> get description => fields.description;

  /// Attributes.
  BeakToManyField get attributes => fields.attributes;
}

/// Catalog grouping with reusable attribute definitions.
final class CategoryModel extends BeakModel {
  /// Creates the categories model.
  const CategoryModel();

  /// Typed field and relation references, including reserved names.
  static const CategoryFields fields = CategoryFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [description] in this model.
  static final description = fields.description;

  /// Typed reference to [attributes] in this model.
  static final attributes = fields.attributes;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const CategoryModel(),
    query: const CategoryModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const CategoryModel(),
        query: const CategoryModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'categories';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => CategoryColumns.values;
  @override
  List<BeakModel> get relatedModels => const [CategoryAttributeModel()];

  @override
  List<BeakRelationship> get relationships => const [
    CategoryRelations.attributes,
  ];

  @override
  List<Enum> get formSlots => _CategoryModelFormSlot.values;
}

/// Form-field slots of CategoryModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Category can put on a form.
enum _CategoryModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
}

/// A live, nullable view of an incomplete Category draft.
final class CategoryDraft {
  /// Reads values through the session so dependencies stay observable.
  const CategoryDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(CategoryModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(CategoryModel.fields.name);

  /// Description, or null while incomplete.
  String? get description => _reader.read(CategoryModel.fields.description);

  /// The selected attributes.
  List<CategoryAttributeRecord> get attributes => [
    for (final row
        in _reader.read(CategoryModel.fields.attributes) ??
            const <BeakRecord>[])
      CategoryAttributeRecord.of(row),
  ];
}

/// Typed access to live Category form values.
extension CategoryDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  CategoryDraft get asCategory => CategoryDraft(this);
}

/// A typed, zero-cost view over a categories record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const CategoryRecord._(BeakRecord record) {
  /// Views [record] as a categories row.
  const CategoryRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => CategoryColumns.id.readFrom(record);

  /// Category title.
  String get name => CategoryColumns.name.require(record);

  /// Description shown to administrators.
  String? get description => CategoryColumns.description.readFrom(record);

  /// The eager-loaded attributes.
  List<CategoryAttributeRecord> get attributes => [
    for (final row in record.relations['attributes'] ?? const <BeakRecord>[])
      CategoryAttributeRecord.of(row),
  ];
}

/// Views any record as a categories row.
extension CategoryRecordAccess on BeakRecord {
  /// This record, typed as a categories row.
  CategoryRecord get asCategory => CategoryRecord.of(this);
}
