// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'tax_rate.dart';

/// Typed column constants of the tax_rates resource.
abstract final class TaxRateColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Administrator-facing rate label.
  static const BeakStringColumn name = BeakStringColumn(
    key: 'name',
    label: 'Name',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// Percentage with exactly two decimal places, so 20.00 means 20 percent.
  static const BeakIntColumn ratePercent = BeakIntColumn(
    key: 'rate_percent',
    label: 'Rate Percent',
    rules: [BeakRequired(), BeakMin(0), BeakMax(100)],
    semantic: BeakSemantic.exactDecimal(scale: 2),
    suffix: '%',
  );

  /// Whether this rate is offered for new sales.
  static const BeakBoolColumn active = BeakBoolColumn(
    key: 'active',
    label: 'Active',
    rules: [BeakRequired()],
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [id, name, ratePercent, active];
}

/// Typed configuration references for TaxRate.
final class TaxRateFields {
  /// Creates the fields of TaxRate, rooted at its own model.
  const TaxRateFields() : _model = const TaxRateModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const TaxRateFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: TaxRateColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Name.
  BeakScalarField<String> get name => BeakScalarField<String>(
    model: _model,
    column: TaxRateColumns.name,
    path: _path,
    isRequired: true,
  );

  /// Rate Percent.
  BeakScalarField<BeakDecimal> get ratePercent => BeakScalarField<BeakDecimal>(
    model: _model,
    column: TaxRateColumns.ratePercent,
    path: _path,
    isRequired: true,
  );

  /// Active.
  BeakScalarField<bool> get active => BeakScalarField<bool>(
    model: _model,
    column: TaxRateColumns.active,
    path: _path,
    isRequired: true,
  );
}

/// A to-one path to TaxRate, retaining its root owner.
final class TaxRateToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const TaxRateToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const TaxRateModel());

  /// Every target field, including names reserved by the path API.
  TaxRateFields get fields => TaxRateFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Name.
  BeakScalarField<String> get name => fields.name;

  /// Rate Percent.
  BeakScalarField<BeakDecimal> get ratePercent => fields.ratePercent;

  /// Active.
  BeakScalarField<bool> get active => fields.active;
}

/// A configurable exclusive tax rate; this example is not a tax filing system.
final class TaxRateModel extends BeakModel {
  /// Creates the tax_rates model.
  const TaxRateModel();

  /// Typed field and relation references, including reserved names.
  static const TaxRateFields fields = TaxRateFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [name] in this model.
  static final name = fields.name;

  /// Typed reference to [ratePercent] in this model.
  static final ratePercent = fields.ratePercent;

  /// Typed reference to [active] in this model.
  static final active = fields.active;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const TaxRateModel(),
    query: const TaxRateModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const TaxRateModel(),
        query: const TaxRateModel().query(
          filter: filter,
          search: BeakSearch(term, const ['name']),
        ),
      );

  @override
  String get table => 'tax_rates';

  @override
  String get displayColumnKey => 'name';

  @override
  List<BeakColumn> get columns => TaxRateColumns.values;

  @override
  List<Enum> get formSlots => _TaxRateModelFormSlot.values;
}

/// Form-field slots of TaxRateModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field TaxRate can put on a form.
enum _TaxRateModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
}

/// A live, nullable view of an incomplete TaxRate draft.
final class TaxRateDraft {
  /// Reads values through the session so dependencies stay observable.
  const TaxRateDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(TaxRateModel.fields.id);

  /// Name, or null while incomplete.
  String? get name => _reader.read(TaxRateModel.fields.name);

  /// Rate Percent, or null while incomplete.
  BeakDecimal? get ratePercent => _reader.read(TaxRateModel.fields.ratePercent);

  /// Active, or null while incomplete.
  bool? get active => _reader.read(TaxRateModel.fields.active);
}

/// Typed access to live TaxRate form values.
extension TaxRateDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  TaxRateDraft get asTaxRate => TaxRateDraft(this);
}

/// A typed, zero-cost view over a tax_rates record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const TaxRateRecord._(BeakRecord record) {
  /// Views [record] as a tax_rates row.
  const TaxRateRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => TaxRateColumns.id.readFrom(record);

  /// Administrator-facing rate label.
  String get name => TaxRateColumns.name.require(record);

  /// Percentage with exactly two decimal places, so 20.00 means 20 percent.
  BeakDecimal get ratePercent =>
      TaxRateModel.fields.ratePercent.require(record);

  /// Whether this rate is offered for new sales.
  bool get active => TaxRateColumns.active.require(record);
}

/// Views any record as a tax_rates row.
extension TaxRateRecordAccess on BeakRecord {
  /// This record, typed as a tax_rates row.
  TaxRateRecord get asTaxRate => TaxRateRecord.of(this);
}
