// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'plan_feature.dart';

/// Typed column constants of the plan_features resource.
abstract final class PlanFeatureColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// Feature text.
  static const BeakStringColumn label = BeakStringColumn(
    key: 'label',
    label: 'Feature',
    rules: [BeakRequired(), BeakMaxLength(120)],
    searchable: true,
  );

  /// Whether the plan includes this feature (vs. crossed out).
  static const BeakBoolColumn included = BeakBoolColumn(
    key: 'included',
    label: 'Included',
    filterable: true,
  );

  /// Ordering within the plan.
  static const BeakIntColumn sortIndex = BeakIntColumn(
    key: 'sort_index',
    label: 'Order',
    min: 0,
    sortable: true,
  );

  /// Foreign key backing [plan].
  static const BeakStringColumn planId = BeakStringColumn(
    key: 'plan_id',
    label: 'Plan',
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    label,
    included,
    sortIndex,
    planId,
  ];
}

/// Typed relationship constants of the plan_features resource.
abstract final class PlanFeatureRelations {
  /// The owning plan.
  static const BeakBelongsTo plan = BeakBelongsTo(
    key: 'plan',
    label: 'Plan',
    relatedTable: 'pricing_plans',
    displayColumnKey: 'name',
    foreignKey: 'plan_id',
    searchColumnKeys: ['name'],
  );
}

/// The plan-features resource — one bullet on a pricing plan.
final class PlanFeatureModel extends BeakModel {
  /// Creates the plan_features model.
  const PlanFeatureModel();

  @override
  String get table => 'plan_features';

  @override
  String get displayColumnKey => 'label';

  @override
  List<BeakColumn> get columns => PlanFeatureColumns.values;

  @override
  List<BeakRelationship> get relationships => const [PlanFeatureRelations.plan];

  @override
  List<Enum> get formSlots => _PlanFeatureModelFormSlot.values;
}

/// Form-field slots of PlanFeatureModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field PlanFeature can put on a form.
enum _PlanFeatureModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
}

/// A typed, zero-cost view over a plan_features record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const PlanFeatureRecord._(BeakRecord record) {
  /// Views [record] as a plan_features row.
  const PlanFeatureRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => PlanFeatureColumns.id.readFrom(record);

  /// Feature text.
  String get label => PlanFeatureColumns.label.require(record);

  /// Whether the plan includes this feature (vs. crossed out).
  bool? get included => PlanFeatureColumns.included.readFrom(record);

  /// Ordering within the plan.
  int? get sortIndex => PlanFeatureColumns.sortIndex.readFrom(record);

  /// Foreign key backing [plan].
  String? get planId => PlanFeatureColumns.planId.readFrom(record);

  /// The eager-loaded plan, or null when unloaded or unset.
  PricingPlanRecord? get plan => switch (record.relations['plan']) {
    [final BeakRecord first, ...] => PricingPlanRecord.of(first),
    _ => null,
  };
}

/// Views any record as a plan_features row.
extension PlanFeatureRecordAccess on BeakRecord {
  /// This record, typed as a plan_features row.
  PlanFeatureRecord get asPlanFeature => PlanFeatureRecord.of(this);
}
