// GENERATED BY `beak prepare` — DO NOT EDIT.
// Run `beak prepare` after changing a schema class, a resource class, a screen or beak.yaml.
library;

import 'package:beak/panel.dart';
import 'package:beak/ui.dart';
import '../models/app_setting.dart';
import '../models/budget_account.dart';
import '../models/complaint.dart';
import '../models/customer.dart';
import '../models/delivery_location.dart';
import '../models/delivery_profile.dart';
import '../models/delivery_slot.dart';
import '../models/dish.dart';
import '../models/dish_option.dart';
import '../models/dish_variant.dart';
import '../models/invoice.dart';
import '../models/menu_plan.dart';
import '../models/message_delivery.dart';
import '../models/notification.dart';
import '../models/order.dart';
import '../models/organization.dart';
import '../models/payment_attempt.dart';
import '../models/payment_method.dart';
import '../models/saved_view.dart';
import '../models/staff_member.dart';
import '../models/voucher.dart';
import '../resources/orders/order_resource.dart';

/// The panel configuration for this project.
///
/// Assembled from `beak.yaml`, every model and resource class under
/// `lib/`, and the screens under `lib/screens/`.
BeakPanelConfig buildBeakPanel() {
  // The resource classes under lib/, keyed by the table of the model
  // each one configures. Each replaces that model's default resource.
  final authored = <String, BeakResource>{
    for (final resource in <BeakResource>[OrderResource()])
      resource.model.table: resource,
  };
  final config = BeakPanelConfig(
    title: 'Gabel',
    apiBaseUrl: const String.fromEnvironment(
      'BEAK_API_BASE_URL',
      defaultValue: 'http://localhost:8081',
    ),
    sidebarCollapsible: true,
    sidebarDefaultCollapsed: false,
    resources: [
      for (final resource in <BeakResource>[
        BeakResource(
          model: const AppSettingModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const BudgetAccountModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const ComplaintModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const CustomerModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const DeliveryLocationModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const DeliveryProfileModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const DeliverySlotModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const DishModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const DishOptionModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const DishVariantModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const InvoiceModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const MenuPlanModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const MessageDeliveryModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const NotificationModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const OrderModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const OrganizationModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const PaymentAttemptModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const PaymentMethodModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const SavedViewModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const StaffMemberModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const VoucherModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
      ])
        authored.remove(resource.model.table) ?? resource,
      ...authored.values,
    ],
  );
  return config;
}
