// GENERATED BY `beak prepare` — DO NOT EDIT.
// Run `beak prepare` after changing a schema class, a resource class, a screen or beak.yaml.
library;

import 'package:beak/beak.dart';
import '../models/app_setting.dart';
import '../models/budget_account.dart';
import '../models/complaint.dart';
import '../models/customer.dart';
import '../models/delivery_location.dart';
import '../models/delivery_profile.dart';
import '../models/delivery_slot.dart';
import '../models/dish.dart';
import '../models/dish_option.dart';
import '../models/dish_variant.dart';
import '../models/invoice.dart';
import '../models/menu_plan.dart';
import '../models/menu_plan_item.dart';
import '../models/message_delivery.dart';
import '../models/notification.dart';
import '../models/order.dart';
import '../models/order_activity.dart';
import '../models/order_item.dart';
import '../models/order_item_option.dart';
import '../models/order_note.dart';
import '../models/organization.dart';
import '../models/payment_attempt.dart';
import '../models/payment_method.dart';
import '../models/saved_view.dart';
import '../models/staff_member.dart';
import '../models/voucher.dart';

/// Every model discovered under `lib/`, in path order.
const List<BeakModel> beakModels = <BeakModel>[
  AppSettingModel(),
  BudgetAccountModel(),
  ComplaintModel(),
  CustomerModel(),
  DeliveryLocationModel(),
  DeliveryProfileModel(),
  DeliverySlotModel(),
  DishModel(),
  DishOptionModel(),
  DishVariantModel(),
  InvoiceModel(),
  MenuPlanModel(),
  MenuPlanItemModel(),
  MessageDeliveryModel(),
  NotificationModel(),
  OrderModel(),
  OrderActivityModel(),
  OrderItemModel(),
  OrderItemOptionModel(),
  OrderNoteModel(),
  OrganizationModel(),
  PaymentAttemptModel(),
  PaymentMethodModel(),
  SavedViewModel(),
  StaffMemberModel(),
  VoucherModel(),
];

/// A registry populated with every model in [beakModels].
BeakModelRegistry buildBeakRegistry() {
  final registry = BeakModelRegistry();
  for (final model in beakModels) {
    registry.register(model);
  }
  return registry;
}
