// GENERATED BY `beak prepare` — DO NOT EDIT.
// Run `beak prepare` after changing a schema class, a resource class, a screen or beak.yaml.
library;

import 'package:beak/panel.dart';
import 'package:beak/ui.dart';
import '../resources/categories/category_resource.dart';
import '../resources/categories/models/category.dart';
import '../resources/categories/models/category_attribute.dart';
import '../resources/companies/company_resource.dart';
import '../resources/companies/models/company.dart';
import '../resources/fulfillment/fulfillment_policy_resource.dart';
import '../resources/fulfillment/models/fulfillment_policy.dart';
import '../resources/invoices/invoice_resource.dart';
import '../resources/invoices/models/invoice.dart';
import '../resources/invoices/models/invoice_item.dart';
import '../resources/invoices/models/invoice_voucher.dart';
import '../resources/orders/models/order.dart';
import '../resources/orders/order_resource.dart';
import '../resources/products/models/product.dart';
import '../resources/products/models/product_attribute.dart';
import '../resources/products/models/product_image.dart';
import '../resources/products/models/product_variant.dart';
import '../resources/products/models/variant_attribute.dart';
import '../resources/products/product_resource.dart';
import '../resources/products/variant_resource.dart';
import '../resources/profiles/models/profile.dart';
import '../resources/profiles/profile_resource.dart';
import '../resources/taxes/models/tax_rate.dart';
import '../resources/taxes/tax_rate_resource.dart';
import '../resources/users/models/user.dart';
import '../resources/users/user_resource.dart';
import '../resources/vouchers/models/voucher.dart';
import '../resources/vouchers/voucher_resource.dart';

/// The panel configuration for this project.
///
/// Assembled from `beak.yaml`, every model and resource class under
/// `lib/`, and the screens under `lib/screens/`.
BeakPanelConfig buildBeakPanel() {
  // The resource classes under lib/, keyed by the table of the model
  // each one configures. Each replaces that model's default resource.
  final authored = <String, BeakResource>{
    for (final resource in <BeakResource>[
      CategoryResource(),
      CompanyResource(),
      FulfillmentPolicyResource(),
      InvoiceResource(),
      OrderResource(),
      ProductResource(),
      VariantResource(),
      ProfileResource(),
      TaxRateResource(),
      UserResource(),
      VoucherResource(),
    ])
      resource.model.table: resource,
  };
  final config = BeakPanelConfig(
    title: 'Clean Beak Shop',
    apiBaseUrl: const String.fromEnvironment(
      'BEAK_API_BASE_URL',
      defaultValue: 'http://localhost:8080',
    ),
    sidebarCollapsible: true,
    sidebarDefaultCollapsed: false,
    resources: [
      for (final resource in <BeakResource>[
        BeakResource(
          model: const CategoryModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const CategoryAttributeModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const CompanyModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const FulfillmentPolicyModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const InvoiceModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const InvoiceItemModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const InvoiceVoucherModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const OrderModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const ProductModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const ProductAttributeModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const ProductImageModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const ProductVariantModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const VariantAttributeModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const ProfileModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const TaxRateModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const UserModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
        BeakResource(
          model: const VoucherModel(),
          icon: BeakIconToken(OiIcons.table),
        ),
      ])
        authored.remove(resource.model.table) ?? resource,
      ...authored.values,
    ],
  );
  return config;
}
