// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'keeper_profile.dart';

/// Typed column constants of the keeper_profiles resource.
abstract final class KeeperProfileColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The licence the keeper holds.
  static const BeakStringColumn certification = BeakStringColumn(
    key: 'certification',
    label: 'Certification',
    rules: [BeakRequired()],
    searchable: true,
  );

  /// The number the keeper answers on when a bird escapes.
  static const BeakStringColumn emergencyPhone = BeakStringColumn(
    key: 'emergency_phone',
    label: 'Emergency Phone',
    semantic: BeakSemantic.phone(),
  );

  /// When the keeper was first certified.
  static const BeakDateTimeColumn certifiedSince = BeakDateTimeColumn(
    key: 'certified_since',
    label: 'Certified Since',
  );

  /// Foreign key backing [keeper].
  static const BeakStringColumn keeperId = BeakStringColumn(
    key: 'keeper_id',
    label: 'Keeper',
    rules: [BeakRequired()],
    visibleOn: {BeakContext.form},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    certification,
    emergencyPhone,
    certifiedSince,
    keeperId,
  ];
}

/// Typed relationship constants of the keeper_profiles resource.
abstract final class KeeperProfileRelations {
  /// The keeper the profile describes.
  static const BeakBelongsTo keeper = BeakBelongsTo(
    key: 'keeper',
    label: 'Keeper',
    relatedTable: 'keepers',
    displayColumnKey: 'name',
    foreignKey: 'keeper_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.cascade,
  );
}

/// Typed configuration references for KeeperProfile.
final class KeeperProfileFields {
  /// Creates the fields of KeeperProfile, rooted at its own model.
  const KeeperProfileFields()
    : _model = const KeeperProfileModel(),
      _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const KeeperProfileFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: KeeperProfileColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Certification.
  BeakScalarField<String> get certification => BeakScalarField<String>(
    model: _model,
    column: KeeperProfileColumns.certification,
    path: _path,
    isRequired: true,
  );

  /// Emergency Phone.
  BeakScalarField<String> get emergencyPhone => BeakScalarField<String>(
    model: _model,
    column: KeeperProfileColumns.emergencyPhone,
    path: _path,
    isRequired: false,
  );

  /// Certified Since.
  BeakScalarField<DateTime> get certifiedSince => BeakScalarField<DateTime>(
    model: _model,
    column: KeeperProfileColumns.certifiedSince,
    path: _path,
    isRequired: false,
  );

  /// Keeper.
  BeakScalarField<String> get keeperId => BeakScalarField<String>(
    model: _model,
    column: KeeperProfileColumns.keeperId,
    path: _path,
    isRequired: true,
  );

  /// Keeper.
  KeeperToOneField get keeper => KeeperToOneField(
    model: _model,
    relation: KeeperProfileRelations.keeper,
    path: _path,
    isRequired: true,
  );
}

/// A to-one path to KeeperProfile, retaining its root owner.
final class KeeperProfileToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const KeeperProfileToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const KeeperProfileModel());

  /// Every target field, including names reserved by the path API.
  KeeperProfileFields get fields =>
      KeeperProfileFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Certification.
  BeakScalarField<String> get certification => fields.certification;

  /// Emergency Phone.
  BeakScalarField<String> get emergencyPhone => fields.emergencyPhone;

  /// Certified Since.
  BeakScalarField<DateTime> get certifiedSince => fields.certifiedSince;

  /// Keeper.
  BeakScalarField<String> get keeperId => fields.keeperId;

  /// Keeper.
  KeeperToOneField get keeper => fields.keeper;
}

/// Certification details that belong to exactly one keeper.
final class KeeperProfileModel extends BeakModel {
  /// Creates the keeper_profiles model.
  const KeeperProfileModel();

  /// Typed field and relation references, including reserved names.
  static const KeeperProfileFields fields = KeeperProfileFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [certification] in this model.
  static final certification = fields.certification;

  /// Typed reference to [emergencyPhone] in this model.
  static final emergencyPhone = fields.emergencyPhone;

  /// Typed reference to [certifiedSince] in this model.
  static final certifiedSince = fields.certifiedSince;

  /// Typed reference to [keeperId] in this model.
  static final keeperId = fields.keeperId;

  /// Typed reference to [keeper] in this model.
  static final keeper = fields.keeper;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const KeeperProfileModel(),
    query: const KeeperProfileModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const KeeperProfileModel(),
        query: const KeeperProfileModel().query(
          filter: filter,
          search: BeakSearch(term, const ['certification']),
        ),
      );

  @override
  String get table => 'keeper_profiles';

  @override
  String get displayColumnKey => 'certification';

  @override
  List<BeakColumn> get columns => KeeperProfileColumns.values;
  @override
  List<BeakModel> get relatedModels => const [KeeperModel()];

  @override
  List<BeakRelationship> get relationships => const [
    KeeperProfileRelations.keeper,
  ];

  @override
  List<Enum> get formSlots => _KeeperProfileModelFormSlot.values;
}

/// Form-field slots of KeeperProfileModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field KeeperProfile can put on a form.
enum _KeeperProfileModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
}

/// A live, nullable view of an incomplete KeeperProfile draft.
final class KeeperProfileDraft {
  /// Reads values through the session so dependencies stay observable.
  const KeeperProfileDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(KeeperProfileModel.fields.id);

  /// Certification, or null while incomplete.
  String? get certification =>
      _reader.read(KeeperProfileModel.fields.certification);

  /// Emergency Phone, or null while incomplete.
  String? get emergencyPhone =>
      _reader.read(KeeperProfileModel.fields.emergencyPhone);

  /// Certified Since, or null while incomplete.
  DateTime? get certifiedSince =>
      _reader.read(KeeperProfileModel.fields.certifiedSince);

  /// Keeper, or null while incomplete.
  String? get keeperId => _reader.read(KeeperProfileModel.fields.keeperId);

  /// The selected keeper.
  KeeperRecord? get keeper =>
      switch (_reader.read(KeeperProfileModel.fields.keeper)) {
        final BeakRecord record => KeeperRecord.of(record),
        null => null,
      };
}

/// Typed access to live KeeperProfile form values.
extension KeeperProfileDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  KeeperProfileDraft get asKeeperProfile => KeeperProfileDraft(this);
}

/// A typed, zero-cost view over a keeper_profiles record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const KeeperProfileRecord._(BeakRecord record) {
  /// Views [record] as a keeper_profiles row.
  const KeeperProfileRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => KeeperProfileColumns.id.readFrom(record);

  /// The licence the keeper holds.
  String get certification =>
      KeeperProfileColumns.certification.require(record);

  /// The number the keeper answers on when a bird escapes.
  String? get emergencyPhone =>
      KeeperProfileColumns.emergencyPhone.readFrom(record);

  /// When the keeper was first certified.
  DateTime? get certifiedSince =>
      KeeperProfileColumns.certifiedSince.readFrom(record);

  /// Foreign key backing [keeper].
  String get keeperId => KeeperProfileColumns.keeperId.require(record);

  /// The eager-loaded keeper, or null when unloaded or unset.
  KeeperRecord? get keeper => switch (record.relations['keeper']) {
    [final BeakRecord first, ...] => KeeperRecord.of(first),
    _ => null,
  };
}

/// Views any record as a keeper_profiles row.
extension KeeperProfileRecordAccess on BeakRecord {
  /// This record, typed as a keeper_profiles row.
  KeeperProfileRecord get asKeeperProfile => KeeperProfileRecord.of(this);
}
