/// `worm schema:dump` command, plus the embedded
/// [SchemaIntrospector] helper that produces a Dart source snapshot
/// of the live schema and (on `--prune`) deletes superseded migration
/// files.
library;

import 'dart:io';

import '../../adapter/database_adapter.dart';
import '../worm_command_runner.dart';

/// Dump the live database schema by introspection.
///
/// * Default invocation writes `schema/schema_dump.dart` containing
///   a Dart source snapshot returned by [SchemaIntrospector.dump].
/// * `--prune` deletes every migration file under `migrations/`
///   after the dump is written. This is destructive and therefore
///   gated on `--force` in **every** environment (not just
///   production).
final class SchemaDumpCommand extends WormCommand {
  /// Creates a [SchemaDumpCommand].
  SchemaDumpCommand(super.context) {
    argParser
      ..addFlag(
        'prune',
        help: 'Delete migration files after dumping. Requires --force.',
        negatable: false,
      )
      ..addFlag(
        'force',
        help: 'Acknowledge --prune is irreversible.',
        negatable: false,
      );
  }

  @override
  String get name => 'schema:dump';

  @override
  String get description =>
      'Write schema/schema_dump.dart from the live database. '
      'Use --prune (with --force) to also delete migration files.';

  @override
  Future<int> run() async {
    final prune = argResults?.flag('prune') ?? false;
    final force = argResults?.flag('force') ?? false;
    if (prune && !force) {
      context.err.writeln(
        'error: --prune deletes every migration file under '
        'migrations/ and is irreversible. Re-run with --force to '
        'acknowledge.',
      );
      return 1;
    }
    final adapter = await context.adapterFactory();
    final introspector = SchemaIntrospector(
      adapter: adapter,
      projectRoot: context.projectRoot,
    );
    await _writeDump(introspector);
    if (prune) await _runPrune(introspector);
    return 0;
  }

  Future<void> _writeDump(SchemaIntrospector introspector) async {
    final source = await introspector.dump();
    final outFile = File('${context.projectRoot.path}/schema/schema_dump.dart');
    await outFile.parent.create(recursive: true);
    await outFile.writeAsString(source);
    context.out.writeln('wrote   schema/schema_dump.dart');
  }

  Future<void> _runPrune(SchemaIntrospector introspector) async {
    final removed = introspector.prune();
    context.out.writeln('pruned  $removed migration file(s).');
  }
}

/// Reflects the live database schema into a Dart source snapshot and
/// prunes superseded migration files. Stateless apart from the
/// injected [DatabaseAdapter] and [projectRoot]; safe to construct
/// per invocation and easily swappable in tests.
final class SchemaIntrospector {
  /// Creates a [SchemaIntrospector].
  const SchemaIntrospector({required this.adapter, required this.projectRoot});

  /// Adapter the introspector queries.
  final DatabaseAdapter adapter;

  /// Project root containing the `migrations/` directory the
  /// [prune] step deletes from and the `schema/` directory the
  /// dump is written to.
  final Directory projectRoot;

  /// Generate a Dart source snapshot of the live schema. The output
  /// is a single top-level `Map<String, List<String>>` constant
  /// suitable for being written to `schema/schema_dump.dart`.
  Future<String> dump() async {
    final schema = await adapter.introspectSchema();
    final buf = StringBuffer()
      ..writeln('// GENERATED by `worm schema:dump`. Do not edit.')
      ..writeln('library;')
      ..writeln()
      ..writeln('/// Snapshot of the live database schema captured by')
      ..writeln('/// the most recent `worm schema:dump` run.')
      ..writeln('const Map<String, List<String>> schemaDump =');
    if (schema.isEmpty) {
      buf.writeln('    <String, List<String>>{};');
      return buf.toString();
    }
    buf.writeln('    <String, List<String>>{');
    final tables = schema.keys.toList()..sort();
    for (final table in tables) {
      _writeTableEntry(buf, table, schema[table] ?? const <String>[]);
    }
    buf.writeln('    };');
    return buf.toString();
  }

  /// Delete every Dart file under `<projectRoot>/migrations/`.
  /// Returns the number of files removed. A no-op (returns `0`) when
  /// the directory does not exist.
  int prune() {
    final dir = Directory('${projectRoot.path}/migrations');
    if (!dir.existsSync()) return 0;
    final files = dir
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'))
        .toList();
    for (final f in files) {
      f.deleteSync();
    }
    return files.length;
  }

  void _writeTableEntry(StringBuffer buf, String table, List<String> cols) {
    buf.writeln("      '$table': <String>[");
    for (final col in cols) {
      buf.writeln("        '$col',");
    }
    buf.writeln('      ],');
  }
}
