import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

import 'beak_discovery.dart';
import 'beak_project_config.dart';

/// One file `beak prepare` writes, and whether the project commits it.
final class BeakGeneratedFile {
  /// Creates a generated file.
  const BeakGeneratedFile({
    required this.path,
    required this.contents,
    required this.isCommitted,
  });

  /// Project-relative path.
  final String path;

  /// The full file text, including its generated-by header.
  final String contents;

  /// Whether the file belongs in version control.
  ///
  /// The `lib/beak/*.g.dart` wiring is committed so a fresh clone analyzes
  /// before any `beak` command runs. The entrypoints are not: they sit at the
  /// canonical paths Flutter and Dart expect, so they must exist, but nothing
  /// about them is a decision worth reviewing.
  final bool isCommitted;
}

/// Turns a scanned project into the Dart files that wire it together.
///
/// The output is deliberately boring: declarations and one-line delegations
/// into `beak_core`/`beak_frontend`/`beak_backend`, never logic. That is what
/// lets generated code pass `--fatal-infos` on its own merits and what keeps
/// the emitters testable as plain string comparisons.
abstract final class BeakEmitters {
  /// The language version emitted code is formatted for.
  ///
  /// Pinned rather than inferred: a formatter disagreeing with the SDK's
  /// would produce a diff nobody wrote, which is the classic way generated
  /// code breaks a `format --set-exit-if-changed` gate.
  // --8<-- [start:beakEmitterFormat]
  static final Version languageVersion = Version(3, 11, 0);

  /// Formats [source] the way `dart format` would.
  static String format(String source) =>
      DartFormatter(languageVersion: languageVersion).format(source);
  // --8<-- [end:beakEmitterFormat]

  /// Header stamped on every generated file.
  static const String header =
      '// GENERATED BY `beak prepare` — DO NOT EDIT.\n'
      '// Run `beak prepare` after changing a schema class, a resource class, '
      'a screen or beak.yaml.\n';

  /// Header stamped on the files of a package that only holds schema classes.
  static const String modelsOnlyHeader =
      '// GENERATED BY `beak prepare` — DO NOT EDIT.\n'
      '// Run `beak prepare` after changing a schema class.\n';

  /// The one file a package of schema classes needs, given its [discovery].
  ///
  /// Such a package depends on `beak_core` alone, so the registry imports
  /// that and nothing of the app: the same list `beak prepare` writes and
  /// `beak doctor` compares.
  static List<BeakGeneratedFile> modelsOnly(BeakDiscovery discovery) => [
    BeakGeneratedFile(
      path: 'lib/beak/registry.g.dart',
      contents: format(registry(discovery, modelsOnly: true)),
      isCommitted: true,
    ),
  ];

  /// Every file the project needs, given its [config] and [discovery].
  static List<BeakGeneratedFile> all({
    required String packageName,
    required BeakProjectConfig config,
    required BeakDiscovery discovery,
  }) => [
    BeakGeneratedFile(
      path: 'lib/beak/registry.g.dart',
      contents: format(registry(discovery)),
      isCommitted: true,
    ),
    BeakGeneratedFile(
      path: 'lib/beak/panel.g.dart',
      contents: format(panel(config: config, discovery: discovery)),
      isCommitted: true,
    ),
    BeakGeneratedFile(
      path: 'lib/beak/app.g.dart',
      contents: format(app(config)),
      isCommitted: true,
    ),
    BeakGeneratedFile(
      path: 'lib/beak/server.g.dart',
      contents: format(
        server(packageName: packageName, discovery: discovery, config: config),
      ),
      isCommitted: true,
    ),
    BeakGeneratedFile(
      path: 'lib/main.dart',
      contents: format(mainEntrypoint(packageName)),
      isCommitted: false,
    ),
    BeakGeneratedFile(
      path: 'bin/serve.dart',
      contents: format(serveEntrypoint(packageName)),
      isCommitted: false,
    ),
    BeakGeneratedFile(
      path: 'bin/migrate.dart',
      contents: format(migrateEntrypoint(packageName)),
      isCommitted: false,
    ),
  ];

  /// The model registry, built from every discovered model.
  ///
  /// With [modelsOnly] it is the registry of a package that depends on
  /// `beak_core` alone: it imports that instead of the umbrella.
  static String registry(BeakDiscovery discovery, {bool modelsOnly = false}) {
    final buffer = StringBuffer(modelsOnly ? modelsOnlyHeader : header)
      ..writeln('library;')
      ..writeln()
      ..writeln(
        modelsOnly
            ? "import 'package:beak_core/beak_core.dart';"
            : "import 'package:beak/beak.dart';",
      );
    for (final path in _importPathsOf(discovery.models)) {
      buffer.writeln("import '../$path';");
    }
    buffer
      ..writeln()
      ..writeln('/// Every model discovered under `lib/`, in path order.')
      ..writeln('const List<BeakModel> beakModels = <BeakModel>[');
    for (final model in discovery.models) {
      buffer.writeln('  ${model.constFreeExpression},');
    }
    buffer
      ..writeln('];')
      ..writeln()
      ..writeln('/// A registry populated with every model in [beakModels].')
      ..writeln('BeakModelRegistry buildBeakRegistry() {')
      ..writeln('  final registry = BeakModelRegistry();')
      ..writeln('  for (final model in beakModels) {')
      ..writeln('    registry.register(model);')
      ..writeln('  }')
      ..writeln('  return registry;')
      ..writeln('}');
    return buffer.toString();
  }

  /// The panel configuration assembled from `beak.yaml` and discovery.
  ///
  /// Every model gets a default resource, presented as `beak.yaml` says.
  /// A `BeakResource` class the project wrote replaces the default of the
  /// model it configures. That match is made when the panel starts, by the
  /// table the class's own model reports, so the scan never has to evaluate
  /// a constructor to know which default a class stands in for.
  static String panel({
    required BeakProjectConfig config,
    required BeakDiscovery discovery,
  }) {
    final List<BeakDiscoveredSymbol> defaults = _shownModels(config, discovery);
    final buffer = StringBuffer(header)
      ..writeln('library;')
      ..writeln()
      ..writeln("import 'package:beak/panel.dart';");
    // The icons are all it uses obers_ui for, and only a default resource
    // names one: a project with no model yet would import it for nothing.
    if (defaults.isNotEmpty) {
      buffer.writeln("import 'package:beak/ui.dart';");
    }
    if (config.api.isAuto) {
      buffer.writeln("import 'package:flutter/foundation.dart';");
    }
    // Only the models this file names: a hidden resource keeps its model and
    // its API, but the panel never mentions it, and an unused import is an
    // analyzer warning in a file the project cannot edit.
    for (final path in _uniqueSorted([
      for (final model in defaults) model.importPath,
      for (final resource in discovery.resources) resource.importPath,
      for (final screen in discovery.screens) screen.importPath,
    ])) {
      buffer.writeln("import '../$path';");
    }
    final BeakDiscoveredSymbol? panelOverride =
        discovery.overrides[BeakOverrideKind.panel];
    if (panelOverride != null) {
      buffer.writeln("import '../${panelOverride.importPath}' as panel;");
    }
    final BeakDiscoveredSymbol? themeOverride =
        discovery.overrides[BeakOverrideKind.theme];
    if (themeOverride != null) {
      buffer.writeln("import '../${themeOverride.importPath}' as theme;");
    }
    final BeakDiscoveredSymbol? authOverride =
        discovery.overrides[BeakOverrideKind.auth];
    if (authOverride != null) {
      buffer.writeln("import '../${authOverride.importPath}' as auth;");
    }

    final bool hasAuthored = discovery.resources.isNotEmpty;
    buffer
      ..writeln()
      ..writeln('/// The panel configuration for this project.')
      ..writeln('///')
      ..writeln(
        '/// Assembled from `beak.yaml`, every model and resource class under',
      )
      ..writeln('/// `lib/`, and the screens under `lib/screens/`.')
      ..writeln('BeakPanelConfig buildBeakPanel() {');
    if (hasAuthored) {
      buffer
        ..writeln(
          '  // The resource classes under lib/, keyed by the table of the '
          'model',
        )
        ..writeln(
          '  // each one configures. Each replaces that model\'s default '
          'resource.',
        )
        ..writeln('  final authored = <String, BeakResource>{')
        ..writeln('    for (final resource in <BeakResource>[');
      for (final resource in discovery.resources) {
        buffer.writeln('      ${resource.expression},');
      }
      buffer
        ..writeln('    ])')
        ..writeln('      resource.model.table: resource,')
        ..writeln('  };');
    }
    buffer
      ..writeln('  final config = BeakPanelConfig(')
      ..writeln("    title: '${escape(config.name)}',")
      ..writeln('    apiBaseUrl: ${config.api.expression},')
      ..writeln('    sidebarCollapsible: ${config.sidebarCollapsible},')
      ..writeln(
        '    sidebarDefaultCollapsed: ${config.sidebarStartCollapsed},',
      );
    if (themeOverride != null) {
      buffer
        ..writeln('    theme: theme.beakLightTheme(),')
        ..writeln('    darkTheme: theme.beakDarkTheme(),');
    }
    if (authOverride != null) {
      buffer.writeln('    auth: auth.beakAuth(),');
    }
    buffer.writeln('    resources: [');
    if (hasAuthored) {
      buffer.writeln('      for (final resource in <BeakResource>[');
      for (final model in defaults) {
        buffer.writeln('        ${defaultResourceFor(model, config)},');
      }
      buffer
        ..writeln('      ])')
        ..writeln('        authored.remove(resource.model.table) ?? resource,')
        // A class whose model is hidden, or not a discovered model at all,
        // is still one the project wrote to be shown.
        ..writeln('      ...authored.values,');
    } else {
      for (final model in defaults) {
        buffer.writeln('      ${defaultResourceFor(model, config)},');
      }
    }
    buffer.writeln('    ],');
    if (discovery.screens.isNotEmpty) {
      buffer.writeln('    pages: [');
      for (final screen in discovery.screens) {
        buffer.writeln('      ${screen.expression},');
      }
      buffer.writeln('    ],');
    }
    buffer.writeln('  );');
    if (panelOverride != null) {
      buffer.writeln('  return panel.beakPanel(config);');
    } else {
      buffer.writeln('  return config;');
    }
    buffer.writeln('}');
    return buffer.toString();
  }

  /// An authored `lib/main.dart`: the panel as one `BeakPanel(resources:)`.
  ///
  /// What `beak create --authored` starts from and `beak eject main` hands
  /// over. It lists every resource the generated panel would show: the
  /// project's own resource class for a model that has one, and otherwise
  /// the default the generated panel would use, spelled out, so switching
  /// changes who owns the file and nothing about what the panel shows.
  ///
  /// `BeakPanel(resources:)` has no sidebar settings and no hook for
  /// `lib/panel.dart`, so a project that uses either gets the same list as a
  /// `BeakPanel(config: BeakPanelConfig(...))`, passed through
  /// `panel.beakPanel` when the override exists, as the generated panel does.
  static String authoredMain({
    required BeakProjectConfig config,
    required BeakDiscovery discovery,
  }) {
    final entries = <String>[];
    final defaultModels = <BeakDiscoveredSymbol>[];
    final usedResources = <BeakDiscoveredResource>{};
    for (final model in _shownModels(config, discovery)) {
      final BeakDiscoveredResource? own = discovery.resources
          .where((resource) => resource.configures(model.name))
          .firstOrNull;
      if (own != null) {
        entries.add(own.expression);
        usedResources.add(own);
      } else {
        entries.add(defaultResourceFor(model, config, asConstant: true));
        defaultModels.add(model);
      }
    }
    // A class whose model is hidden, or not a discovered model at all, is
    // still one the project wrote to be shown. The generated panel appends
    // these after the defaults, so the sidebar keeps its order.
    for (final resource in discovery.resources) {
      if (usedResources.add(resource)) {
        entries.add(resource.expression);
      }
    }

    final BeakDiscoveredSymbol? panelOverride =
        discovery.overrides[BeakOverrideKind.panel];
    final BeakDiscoveredSymbol? themeOverride =
        discovery.overrides[BeakOverrideKind.theme];
    final BeakDiscoveredSymbol? authOverride =
        discovery.overrides[BeakOverrideKind.auth];
    final bool defaultSidebar =
        config.sidebarCollapsible && !config.sidebarStartCollapsed;
    final bool asConfig = panelOverride != null || !defaultSidebar;
    // A config holding only constants must be `const` under strict lints,
    // and then nothing inside it may repeat the keyword.
    final bool constConfig =
        asConfig &&
        !config.api.isAuto &&
        themeOverride == null &&
        authOverride == null &&
        usedResources.every((resource) => resource.isConst) &&
        discovery.screens.every((screen) => screen.isConstVariable);
    final buffer = StringBuffer()..writeln("import 'package:beak/panel.dart';");
    if (defaultModels.isNotEmpty) {
      buffer.writeln("import 'package:beak/ui.dart';");
    }
    if (config.api.isAuto) {
      buffer.writeln("import 'package:flutter/foundation.dart';");
    }
    buffer
      ..writeln("import 'package:flutter/widgets.dart';")
      ..writeln();
    // One sorted block, prefixed imports included: the file is the
    // project's now, and `directives_ordering` may well be on.
    for (final directive in _uniqueSorted([
      for (final model in defaultModels) "import '${model.importPath}';",
      for (final resource in usedResources) "import '${resource.importPath}';",
      for (final screen in discovery.screens) "import '${screen.importPath}';",
      if (panelOverride != null)
        "import '${panelOverride.importPath}' as panel;",
      if (themeOverride != null)
        "import '${themeOverride.importPath}' as theme;",
      if (authOverride != null) "import '${authOverride.importPath}' as auth;",
    ])) {
      buffer.writeln(directive);
    }

    String inConfig(String expression) =>
        constConfig ? _withoutLeadingConst(expression) : expression;
    final arguments = <String>[
      "title: '${escape(config.name)}'",
      // The config's own default ignores BEAK_API_BASE_URL, which the
      // widget's honours, so only the widget may leave the origin unsaid.
      if (asConfig || !config.api.isDefault)
        'apiBaseUrl: ${inConfig(config.api.expression)}',
      if (!config.sidebarCollapsible) 'sidebarCollapsible: false',
      if (config.sidebarStartCollapsed) 'sidebarDefaultCollapsed: true',
      if (themeOverride != null) ...[
        'theme: theme.beakLightTheme()',
        'darkTheme: theme.beakDarkTheme()',
      ],
      if (authOverride != null) 'auth: auth.beakAuth()',
      'resources: [${_argumentList(entries.map(inConfig))}]',
      if (discovery.screens.isNotEmpty)
        'pages: [${_argumentList(discovery.screens.map((screen) => screen.expression))}]',
    ];
    final String configExpression =
        '${constConfig ? 'const ' : ''}'
        'BeakPanelConfig(${_argumentList(arguments)})';
    final String panelArguments = _argumentList([
      if (!asConfig)
        ...arguments
      else if (panelOverride != null)
        'config: panel.beakPanel($configExpression,)'
      else
        'config: $configExpression',
      'dataSource: dataSource',
    ]);
    buffer
      ..writeln()
      ..writeln('/// Boots the panel.')
      ..writeln('void main() => runApp(buildPanel());')
      ..writeln()
      ..writeln('/// The panel, and every resource it shows.')
      ..writeln('///')
      ..writeln(
        '/// This file is yours: `beak prepare` never rewrites it, so add each',
      )
      ..writeln('/// resource class you write to `resources`.')
      ..writeln('///')
      ..writeln(
        '/// [dataSource] replaces the HTTP-backed source, so a widget test',
      )
      ..writeln('/// can pump this exact panel against an in-memory one.')
      ..writeln(
        'BeakPanel buildPanel({BeakDataSource? dataSource}) => '
        'BeakPanel($panelArguments);',
      );
    return buffer.toString();
  }

  /// The root widget, keeping the `dataSource` seam widget tests rely on.
  static String app(BeakProjectConfig config) =>
      '''
$header
library;

import 'package:beak/panel.dart';
import 'package:flutter/widgets.dart';

import 'panel.g.dart';

/// The ${escape(config.name)} panel's configuration.
///
/// Built once, at startup: the config holds closures and block trees, so a
/// fresh one every frame would rebuild the router with it.
final BeakPanelConfig beakPanelConfig = buildBeakPanel();

/// The ${escape(config.name)} panel.
final class BeakApp extends StatelessWidget {
  /// Creates the app; [dataSource] injects a fake in widget tests.
  const BeakApp({this.dataSource, super.key});

  /// Test seam replacing the HTTP-backed data source.
  final BeakDataSource? dataSource;

  @override
  Widget build(BuildContext context) =>
      BeakPanel(config: beakPanelConfig, dataSource: dataSource);
}
''';

  /// The backend host, wiring the registry, migrations and seeders together.
  static String server({
    required String packageName,
    required BeakDiscovery discovery,
    required BeakProjectConfig config,
  }) {
    final buffer = StringBuffer(header)
      ..writeln('library;')
      ..writeln()
      ..writeln("import 'package:beak/server.dart';");
    for (final path in _importPathsOf([
      ...discovery.migrations,
      ...discovery.seeders,
    ])) {
      buffer.writeln("import '../$path';");
    }
    buffer.writeln("import 'registry.g.dart';");
    final BeakDiscoveredSymbol? serverOverride =
        discovery.overrides[BeakOverrideKind.server];
    final BeakDiscoveredSymbol? storageRegistry = discovery.storageRegistry;
    // Either one is a reason to import lib/server.dart; neither needs the
    // other, so a project registering a storage driver keeps the default
    // server.
    final String? serverPath =
        serverOverride?.importPath ?? storageRegistry?.importPath;
    if (serverPath != null) {
      buffer.writeln("import '../$serverPath' as server;");
    }
    buffer
      ..writeln()
      ..writeln('/// The configured backend for this project.')
      ..writeln('///')
      ..writeln('/// Reads `.env`, connects the database, resolves storage and')
      ..writeln('/// serves the generated API for every registered model.')
      ..writeln('///')
      ..writeln('/// [environment] overrides what the process supplies, so a')
      ..writeln('/// test can point the real host at `sqlite::memory:` and a')
      ..writeln('/// temporary upload directory without touching the machine.')
      ..writeln('BeakServeHost beakHost({Map<String, String>? environment}) =>')
      ..writeln('    BeakServeHost(')
      ..writeln('      environment: ${_environmentExpression(config)},')
      ..writeln('      registry: buildBeakRegistry(),')
      ..writeln('      migrations: const [')
      ..writeln('        BeakCommitReceiptsMigration(),')
      ..writeln('        BeakOutboxMigration(),');
    for (final migration in discovery.migrations) {
      buffer.writeln('        ${migration.constFreeExpression},');
    }
    buffer
      ..writeln('      ],')
      ..writeln('      seeders: const [');
    for (final seeder in discovery.seeders) {
      buffer.writeln('        ${seeder.constFreeExpression},');
    }
    buffer.writeln('      ],');
    if (serverOverride != null) {
      buffer.writeln('      configure: server.${serverOverride.name},');
    }
    if (storageRegistry != null) {
      buffer.writeln('      storageRegistry: server.${storageRegistry.name},');
    }
    buffer.writeln('    );');
    return buffer.toString();
  }

  /// The generated `lib/main.dart`: four lines, regenerated, git-ignored.
  ///
  /// `beak eject main` replaces it with [authoredMain], after which
  /// `beak prepare` leaves it alone.
  static String mainEntrypoint(String packageName) =>
      '''
$header
import 'package:flutter/widgets.dart';

import 'beak/app.g.dart';

/// Boots the panel.
void main() => runApp(const BeakApp());
''';

  /// `bin/serve.dart`: serves until told to stop.
  ///
  /// SIGINT (Ctrl+C) and SIGTERM (what a deploy or a container sends) close
  /// the server the host returned, which also stops the outbox loop it runs
  /// while it serves, and then exit cleanly. Requests in flight finish first.
  /// SIGTERM cannot be watched on Windows, where only Ctrl+C reaches a
  /// process.
  ///
  /// A configuration the host refuses (a bad `PORT`, `DATABASE_URL` or storage
  /// variable, or a port that is taken) ends with one line and exit 78, where
  /// it used to end with "Unhandled exception" and a trace.
  static String serveEntrypoint(String packageName) =>
      '''
$header
import 'dart:async';
import 'dart:io';

import 'package:beak/server.dart' show BeakConfigurationException;
import 'package:$packageName/beak/server.g.dart';

/// Serves the API until SIGINT or SIGTERM, then shuts down and exits.
Future<void> main() async {
  // Watching first: a signal that arrives while the server boots, or right
  // after it says it is listening, must stop it cleanly rather than kill it.
  final Future<ProcessSignal> stopped = Future.any([
    ProcessSignal.sigint.watch().first,
    if (!Platform.isWindows) ProcessSignal.sigterm.watch().first,
  ]);
  final HttpServer server;
  try {
    server = await beakHost().serve();
  } on BeakConfigurationException catch (error) {
    stderr.writeln('error: \${error.message}');
    exit(78);
  }
  stderr.writeln('listening on http://\${server.address.host}:\${server.port}');
  await stopped;
  stderr.writeln('shutting down');
  await server.close();
  exit(0);
}
''';

  /// What the generated host seeds its environment with.
  ///
  /// A `server:` block in `beak.yaml` is a *default*: the resolved
  /// environment is spread after it, so a real `PORT` in a deployment still
  /// decides where the process binds.
  static String _environmentExpression(BeakProjectConfig config) {
    if (config.server.isDefault) {
      return 'environment';
    }
    final String defaults = config.server.environmentDefaults.entries
        .map((entry) => "'${entry.key}': '${entry.value}'")
        .join(', ');
    return '{$defaults, ...environment ?? BeakEnv.resolve()}';
  }

  /// `bin/migrate.dart`: runs the worm CLI over the host.
  ///
  /// A configuration the host refuses ends with one line and exit 78, where it
  /// used to end with "Unhandled exception" and a trace.
  static String migrateEntrypoint(String packageName) =>
      '''
$header
import 'dart:io';

import 'package:beak/server.dart' show BeakConfigurationException;
import 'package:$packageName/beak/server.g.dart';

/// Runs migrations and seeders (`migrate`, `db:seed`, `migrate:fresh`, ...).
Future<void> main(List<String> args) async {
  try {
    exit(await beakHost().runCli(args));
  } on BeakConfigurationException catch (error) {
    stderr.writeln('error: \${error.message}');
    exit(78);
  }
}
''';

  /// The default `BeakResource` for [model], presented as `beak.yaml` says.
  ///
  /// beak.yaml is keyed by table name, and discovery read the real one off
  /// the declaration. Re-deriving it from the class name gave a second
  /// answer, so `@Resource(table: 'people')` on a `Person` silently lost its
  /// icon. [asConstant] writes the literal `const` as a whole, for a file a
  /// person owns and lints, rather than with a `const` model inside it.
  static String defaultResourceFor(
    BeakDiscoveredSymbol model,
    BeakProjectConfig config, {
    bool asConstant = false,
  }) {
    final BeakResourceOverride? presentation = config.resources[model.table];
    final String icon =
        'BeakIconToken(OiIcons.${presentation?.icon ?? 'table'})';
    final parts = <String>[
      'model: ${asConstant ? model.constFreeExpression : model.expression}',
      'icon: $icon',
      if (presentation?.label case final String label)
        "title: '${escape(label)}'",
      if (presentation?.section case final String section)
        "navigationGroup: '${escape(section)}'",
    ];
    return '${asConstant ? 'const ' : ''}BeakResource(${parts.join(', ')})';
  }

  /// The models that get a default resource: every one `beak.yaml` does not
  /// hide.
  ///
  /// A hidden resource keeps its API and stays reachable through a
  /// relationship; it just does not earn a sidebar entry.
  static List<BeakDiscoveredSymbol> _shownModels(
    BeakProjectConfig config,
    BeakDiscovery discovery,
  ) => [
    for (final model in discovery.models)
      if (!(config.resources[model.table]?.hidden ?? false)) model,
  ];

  /// [items] as the inside of an argument list or list literal, each one
  /// followed by a comma; [format] then decides the line breaks.
  static String _argumentList(Iterable<String> items) =>
      [for (final item in items) '$item,'].join();

  /// [expression] without the `const` it starts with, for a place that is
  /// already constant, where repeating the keyword is flagged as redundant.
  static String _withoutLeadingConst(String expression) =>
      expression.startsWith('const ')
      ? expression.substring('const '.length)
      : expression;

  /// [values] without duplicates, sorted.
  static List<String> _uniqueSorted(Iterable<String> values) =>
      values.toSet().toList()..sort();

  /// Unique import paths of [symbols], in path order.
  static List<String> _importPathsOf(List<BeakDiscoveredSymbol> symbols) {
    final paths = <String>{for (final symbol in symbols) symbol.importPath};
    return paths.toList()..sort();
  }

  /// [value] as the body of a single-quoted Dart string literal, so a title
  /// such as `Owner's $ report` from `beak.yaml` cannot end the literal early
  /// or interpolate.
  static String escape(String value) => value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
}
