import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';

/// What a static read of an authored `lib/main.dart` says about its panel.
///
/// An authored entrypoint is the project's own code, so nothing generated
/// keeps its `resources: [...]` list in step with the resource classes under
/// `lib/`. This reads the list from the syntax tree, without resolving
/// anything, so `beak doctor` can name a class the list is missing and
/// `beak make:resource` can print a registration line that compiles cleanly
/// where it is pasted.
///
/// ```dart
/// final BeakAuthoredMain? main = BeakAuthoredMain.read(projectRoot);
/// final Set<String>? listed = main?.listedResources; // {'NoteResource', ...}
/// ```
final class BeakAuthoredMain {
  /// Creates a reading of an entrypoint.
  const BeakAuthoredMain({
    required this.listedResources,
    required this.resourcesAreConstant,
  });

  /// Reads the syntax of [source], the text of an authored entrypoint.
  factory BeakAuthoredMain.parse(String source) {
    final visitor = _PanelVisitor();
    parseString(
      content: source,
      throwIfDiagnostics: false,
    ).unit.accept(visitor);
    return BeakAuthoredMain(
      listedResources: visitor.isReadable ? visitor.listed : null,
      resourcesAreConstant: visitor.lists.isNotEmpty && visitor.areAllConstant,
    );
  }

  /// The comment every file `beak prepare` owns starts with.
  static const String generatedMarker = '// GENERATED BY';

  /// The class and function names the entrypoint's panels list under
  /// `resources:`, or `null` when they cannot be told statically.
  ///
  /// `null` covers an entrypoint that builds no `BeakPanel` or
  /// `BeakPanelConfig` itself and a `resources:` argument that is anything
  /// but a list literal, such as a variable or a spread of one: claiming a
  /// class is missing from a list that was never read would be a false alarm.
  final Set<String>? listedResources;

  /// Whether every `resources:` list sits in a constant context.
  ///
  /// True for the list of a `const BeakPanelConfig(...)`, or one written
  /// `const [...]`. A `const` written on an entry there is flagged as
  /// redundant by `unnecessary_const`. False when there is no list to read.
  final bool resourcesAreConstant;

  /// Whether [root] has a `lib/main.dart` that Beak did not generate.
  ///
  /// The test `beak prepare` makes before it rewrites an entrypoint.
  static bool isAuthored(Directory root) {
    final main = File('${root.path}/lib/main.dart');
    return main.existsSync() &&
        !main.readAsStringSync().startsWith(generatedMarker);
  }

  /// The reading of [root]'s authored `lib/main.dart`, or `null` when there is
  /// none: the file is missing or Beak generated it.
  static BeakAuthoredMain? read(Directory root) => isAuthored(root)
      ? BeakAuthoredMain.parse(
          File('${root.path}/lib/main.dart').readAsStringSync(),
        )
      : null;
}

/// Finds every `BeakPanel` and `BeakPanelConfig` construction and gathers the
/// `resources:` lists passed to them.
final class _PanelVisitor extends RecursiveAstVisitor<void> {
  static const Set<String> _panelTypes = {'BeakPanel', 'BeakPanelConfig'};

  /// Every `resources:` value found.
  final List<Expression> lists = [];

  /// Whether every value found is a list literal that can be read through.
  bool get isReadable =>
      lists.isNotEmpty &&
      lists.every(
        (value) => value is ListLiteral && _isReadable(value.elements),
      );

  /// The names those lists mention.
  Set<String> get listed {
    final collector = _NameCollector();
    for (final value in lists) {
      value.accept(collector);
    }
    return collector.names;
  }

  /// Whether every list sits in a constant context.
  bool get areAllConstant => lists.every(_isConstant);

  @override
  void visitInstanceCreationExpression(InstanceCreationExpression node) {
    if (node.constructorName.name == null &&
        _panelTypes.contains(node.constructorName.type.name.lexeme)) {
      _collect(node.argumentList);
    }
    super.visitInstanceCreationExpression(node);
  }

  @override
  void visitMethodInvocation(MethodInvocation node) {
    // Without `new` or `const`, an unresolved parse reads `BeakPanel(...)` as
    // a call.
    if (node.target == null && _panelTypes.contains(node.methodName.name)) {
      _collect(node.argumentList);
    }
    super.visitMethodInvocation(node);
  }

  void _collect(ArgumentList arguments) {
    for (final argument in arguments.arguments) {
      if (argument is NamedExpression &&
          argument.name.label.name == 'resources') {
        lists.add(argument.expression);
      }
    }
  }

  /// Whether [elements] hold only what can be read without running code: no
  /// spread of anything but a list literal.
  static bool _isReadable(List<CollectionElement> elements) =>
      elements.every(_isElementReadable);

  static bool _isElementReadable(CollectionElement element) =>
      switch (element) {
        SpreadElement(:final expression) =>
          expression is ListLiteral && _isReadable(expression.elements),
        IfElement(:final thenElement, :final elseElement) =>
          _isElementReadable(thenElement) &&
              (elseElement == null || _isElementReadable(elseElement)),
        ForElement(:final body) => _isElementReadable(body),
        _ => true,
      };

  /// Whether [node] is in a constant context: `const` on it, on a literal or
  /// constructor call around it, or on the variable it initialises. A
  /// function body ends the search, since code inside one runs at run time.
  static bool _isConstant(AstNode node) {
    if (node is TypedLiteral && node.constKeyword != null) {
      return true;
    }
    for (
      AstNode? ancestor = node.parent;
      ancestor != null;
      ancestor = ancestor.parent
    ) {
      switch (ancestor) {
        case InstanceCreationExpression(:final keyword)
            when keyword?.lexeme == 'const':
        case TypedLiteral(:final constKeyword) when constKeyword != null:
        case VariableDeclarationList(:final keyword)
            when keyword?.lexeme == 'const':
          return true;
        case FunctionBody():
          return false;
      }
    }
    return false;
  }
}

/// Collects every capitalised name in a syntax tree: the classes it builds.
final class _NameCollector extends RecursiveAstVisitor<void> {
  /// The names seen.
  final Set<String> names = {};

  @override
  void visitNamedType(NamedType node) {
    _add(node.name.lexeme);
    super.visitNamedType(node);
  }

  @override
  void visitSimpleIdentifier(SimpleIdentifier node) {
    _add(node.name);
    super.visitSimpleIdentifier(node);
  }

  void _add(String name) {
    if (name.isNotEmpty && name[0] == name[0].toUpperCase() && name[0] != '_') {
      names.add(name);
    }
  }
}
