import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

import 'beak_discovery.dart';
import 'beak_project_config.dart';

/// One file `beak prepare` writes, and whether the project commits it.
final class BeakGeneratedFile {
  /// Creates a generated file.
  const BeakGeneratedFile({
    required this.path,
    required this.contents,
    required this.isCommitted,
  });

  /// Project-relative path.
  final String path;

  /// The full file text, including its generated-by header.
  final String contents;

  /// Whether the file belongs in version control.
  ///
  /// The `lib/beak/*.g.dart` wiring is committed so a fresh clone analyzes
  /// before any `beak` command runs. The entrypoints are not: they sit at the
  /// canonical paths Flutter and Dart expect, so they must exist, but nothing
  /// about them is a decision worth reviewing.
  final bool isCommitted;
}

/// Turns a scanned project into the Dart files that wire it together.
///
/// The output is deliberately boring: declarations and one-line delegations
/// into `beak_core`/`beak_frontend`/`beak_backend`, never logic. That is what
/// lets generated code pass `--fatal-infos` on its own merits and what keeps
/// the emitters testable as plain string comparisons.
abstract final class BeakEmitters {
  /// The language version emitted code is formatted for.
  ///
  /// Pinned rather than inferred: a formatter disagreeing with the SDK's
  /// would produce a diff nobody wrote, which is the classic way generated
  /// code breaks a `format --set-exit-if-changed` gate.
  static final Version languageVersion = Version(3, 11, 0);

  /// Formats [source] the way `dart format` would.
  static String format(String source) =>
      DartFormatter(languageVersion: languageVersion).format(source);

  /// Header stamped on every generated file.
  static const String header =
      '// GENERATED BY `beak prepare` — DO NOT EDIT.\n'
      '// Run `beak prepare` after changing lib/models, lib/screens or '
      'beak.yaml.\n';

  /// Every file the project needs, given its [config] and [discovery].
  static List<BeakGeneratedFile> all({
    required String packageName,
    required BeakProjectConfig config,
    required BeakDiscovery discovery,
  }) => [
    BeakGeneratedFile(
      path: 'lib/beak/registry.g.dart',
      contents: format(registry(discovery)),
      isCommitted: true,
    ),
    BeakGeneratedFile(
      path: 'lib/beak/panel.g.dart',
      contents: format(panel(config: config, discovery: discovery)),
      isCommitted: true,
    ),
    BeakGeneratedFile(
      path: 'lib/beak/app.g.dart',
      contents: format(app(config)),
      isCommitted: true,
    ),
    BeakGeneratedFile(
      path: 'lib/beak/server.g.dart',
      contents: format(
        server(packageName: packageName, discovery: discovery, config: config),
      ),
      isCommitted: true,
    ),
    BeakGeneratedFile(
      path: 'lib/main.dart',
      contents: format(mainEntrypoint(packageName)),
      isCommitted: false,
    ),
    BeakGeneratedFile(
      path: 'bin/serve.dart',
      contents: format(serveEntrypoint(packageName)),
      isCommitted: false,
    ),
    BeakGeneratedFile(
      path: 'bin/migrate.dart',
      contents: format(migrateEntrypoint(packageName)),
      isCommitted: false,
    ),
  ];

  /// The model registry, built from every discovered model.
  static String registry(BeakDiscovery discovery) {
    final buffer = StringBuffer(header)
      ..writeln('library;')
      ..writeln()
      ..writeln("import 'package:beak/beak.dart';");
    for (final path in _importPathsOf(discovery.models)) {
      buffer.writeln("import '../$path';");
    }
    buffer
      ..writeln()
      ..writeln(
        '/// Every model discovered under `lib/models/`, in path order.',
      )
      ..writeln('const List<BeakModel> beakModels = <BeakModel>[');
    for (final model in discovery.models) {
      buffer.writeln('  ${model.constFreeExpression},');
    }
    buffer
      ..writeln('];')
      ..writeln()
      ..writeln('/// A registry populated with every model in [beakModels].')
      ..writeln('BeakModelRegistry buildBeakRegistry() {')
      ..writeln('  final registry = BeakModelRegistry();')
      ..writeln('  for (final model in beakModels) {')
      ..writeln('    registry.register(model);')
      ..writeln('  }')
      ..writeln('  return registry;')
      ..writeln('}');
    return buffer.toString();
  }

  /// The panel configuration assembled from `beak.yaml` and discovery.
  static String panel({
    required BeakProjectConfig config,
    required BeakDiscovery discovery,
  }) {
    final buffer = StringBuffer(header)
      ..writeln('library;')
      ..writeln()
      ..writeln("import 'package:beak/panel.dart';")
      ..writeln("import 'package:beak/ui.dart';");
    if (config.api.isAuto) {
      buffer.writeln("import 'package:flutter/foundation.dart';");
    }
    // Only the models this file names: a hidden resource keeps its model and
    // its API, but the panel never mentions it, and an unused import is an
    // analyzer warning in a file the project cannot edit.
    for (final path in _importPathsOf([
      for (final model in discovery.models)
        if (!(config.resources[model.table]?.hidden ?? false)) model,
      ...discovery.screens,
    ])) {
      buffer.writeln("import '../$path';");
    }
    for (final table in discovery.resourceOverrides.keys.toList()..sort()) {
      buffer.writeln(
        "import '../${discovery.resourceOverrides[table]!.importPath}' "
        'as ${_resourceAlias(table)};',
      );
    }
    final BeakDiscoveredSymbol? panelOverride =
        discovery.overrides[BeakOverrideKind.panel];
    if (panelOverride != null) {
      buffer.writeln("import '../${panelOverride.importPath}' as panel;");
    }
    final BeakDiscoveredSymbol? themeOverride =
        discovery.overrides[BeakOverrideKind.theme];
    if (themeOverride != null) {
      buffer.writeln("import '../${themeOverride.importPath}' as theme;");
    }
    final BeakDiscoveredSymbol? authOverride =
        discovery.overrides[BeakOverrideKind.auth];
    if (authOverride != null) {
      buffer.writeln("import '../${authOverride.importPath}' as auth;");
    }
    final BeakDiscoveredSymbol? dashboardOverride =
        discovery.overrides[BeakOverrideKind.dashboard];
    if (dashboardOverride != null) {
      buffer.writeln(
        "import '../${dashboardOverride.importPath}' as dashboard;",
      );
    }

    buffer
      ..writeln()
      ..writeln('/// The panel configuration for this project.')
      ..writeln('///')
      ..writeln(
        '/// Assembled from `beak.yaml`, the models under `lib/models/`, and',
      )
      ..writeln('/// the screens under `lib/screens/`.')
      ..writeln('BeakPanelConfig buildBeakPanel() {')
      ..writeln('  final config = BeakPanelConfig(')
      ..writeln("    title: '${_escape(config.name)}',")
      ..writeln('    apiBaseUrl: ${config.api.expression},')
      ..writeln('    sidebarCollapsible: ${config.sidebarCollapsible},')
      ..writeln(
        '    sidebarDefaultCollapsed: ${config.sidebarStartCollapsed},',
      );
    if (themeOverride != null) {
      buffer
        ..writeln('    theme: theme.beakLightTheme(),')
        ..writeln('    darkTheme: theme.beakDarkTheme(),');
    }
    if (authOverride != null) {
      buffer.writeln('    auth: auth.beakAuth(),');
    }
    buffer.writeln('    resources: [');
    for (final model in discovery.models) {
      // A hidden resource keeps its API and stays reachable through a
      // relationship; it just does not earn a sidebar entry.
      if (config.resources[model.table]?.hidden ?? false) {
        continue;
      }
      buffer.writeln('      ${_resourceFor(model, config, discovery)},');
    }
    buffer.writeln('    ],');
    // A `lib/dashboard.dart` replaces the generated `/` screen, so it goes
    // first: the panel routes to whichever page declares `/`.
    if (discovery.screens.isNotEmpty || dashboardOverride != null) {
      buffer.writeln('    pages: [');
      if (dashboardOverride != null) {
        buffer.writeln('      dashboard.beakDashboard(),');
      }
      for (final screen in discovery.screens) {
        buffer.writeln('      ${screen.expression},');
      }
      buffer.writeln('    ],');
    }
    buffer.writeln('  );');
    if (panelOverride != null) {
      buffer.writeln('  return panel.beakPanel(config);');
    } else {
      buffer.writeln('  return config;');
    }
    buffer.writeln('}');
    return buffer.toString();
  }

  /// The root widget, keeping the `dataSource` seam widget tests rely on.
  static String app(BeakProjectConfig config) =>
      '''
$header
library;

import 'package:beak/panel.dart';
import 'package:flutter/widgets.dart';

import 'panel.g.dart';

/// The ${_escape(config.name)} panel's configuration.
///
/// Built once, at startup: the config holds closures and block trees, so a
/// fresh one every frame would rebuild the router with it.
final BeakPanelConfig beakPanelConfig = buildBeakPanel();

/// The ${_escape(config.name)} panel.
final class BeakApp extends StatelessWidget {
  /// Creates the app; [dataSource] injects a fake in widget tests.
  const BeakApp({this.dataSource, super.key});

  /// Test seam replacing the HTTP-backed data source.
  final BeakDataSource? dataSource;

  @override
  Widget build(BuildContext context) =>
      BeakPanel(config: beakPanelConfig, dataSource: dataSource);
}
''';

  /// The backend host, wiring the registry, migrations and seeders together.
  static String server({
    required String packageName,
    required BeakDiscovery discovery,
    required BeakProjectConfig config,
  }) {
    final buffer = StringBuffer(header)
      ..writeln('library;')
      ..writeln()
      ..writeln("import 'package:beak/server.dart';");
    for (final path in _importPathsOf([
      ...discovery.migrations,
      ...discovery.seeders,
    ])) {
      buffer.writeln("import '../$path';");
    }
    buffer.writeln("import 'registry.g.dart';");
    final BeakDiscoveredSymbol? serverOverride =
        discovery.overrides[BeakOverrideKind.server];
    if (serverOverride != null) {
      buffer.writeln("import '../${serverOverride.importPath}' as server;");
    }
    buffer
      ..writeln()
      ..writeln('/// The configured backend for this project.')
      ..writeln('///')
      ..writeln('/// Reads `.env`, connects the database, resolves storage and')
      ..writeln('/// serves the generated API for every registered model.')
      ..writeln('///')
      ..writeln('/// [environment] overrides what the process supplies, so a')
      ..writeln('/// test can point the real host at `sqlite::memory:` and a')
      ..writeln('/// temporary upload directory without touching the machine.')
      ..writeln('BeakServeHost beakHost({Map<String, String>? environment}) =>')
      ..writeln('    BeakServeHost(')
      ..writeln('      environment: ${_environmentExpression(config)},')
      ..writeln('      registry: buildBeakRegistry(),')
      ..writeln('      migrations: const [')
      ..writeln('        BeakCommitReceiptsMigration(),')
      ..writeln('        BeakOutboxMigration(),');
    for (final migration in discovery.migrations) {
      buffer.writeln('        ${migration.constFreeExpression},');
    }
    buffer
      ..writeln('      ],')
      ..writeln('      seeders: const [');
    for (final seeder in discovery.seeders) {
      buffer.writeln('        ${seeder.constFreeExpression},');
    }
    buffer.writeln('      ],');
    if (serverOverride != null) {
      buffer.writeln('      configure: server.beakServer,');
      if (serverOverride.alsoDeclares.contains('beakStorageRegistry')) {
        buffer.writeln('      storageRegistry: server.beakStorageRegistry,');
      }
    }
    buffer.writeln('    );');
    return buffer.toString();
  }

  /// `lib/main.dart` — four lines, regenerated, git-ignored.
  static String mainEntrypoint(String packageName) =>
      '''
$header
import 'package:flutter/widgets.dart';

import 'beak/app.g.dart';

/// Boots the panel.
void main() => runApp(const BeakApp());
''';

  /// `bin/serve.dart` — one statement.
  static String serveEntrypoint(String packageName) =>
      '''
$header
import 'dart:io';

import 'package:$packageName/beak/server.g.dart';

/// Serves the API.
Future<void> main() async {
  final HttpServer server = await beakHost().serve();
  stderr.writeln('listening on http://\${server.address.host}:\${server.port}');
}
''';

  /// What the generated host seeds its environment with.
  ///
  /// A `server:` block in `beak.yaml` is a *default*: the resolved
  /// environment is spread after it, so a real `PORT` in a deployment still
  /// decides where the process binds.
  static String _environmentExpression(BeakProjectConfig config) {
    if (config.server.isDefault) {
      return 'environment';
    }
    final String defaults = config.server.environmentDefaults.entries
        .map((entry) => "'${entry.key}': '${entry.value}'")
        .join(', ');
    return '{$defaults, ...environment ?? BeakEnv.resolve()}';
  }

  /// `bin/migrate.dart` — one statement.
  static String migrateEntrypoint(String packageName) =>
      '''
$header
import 'dart:io';

import 'package:$packageName/beak/server.g.dart';

/// Runs migrations and seeders (`migrate`, `db:seed`, `migrate:fresh`, …).
Future<void> main(List<String> args) async =>
    exit(await beakHost().runCli(args));
''';

  /// The `BeakResource` literal for [model], honouring any `beak.yaml`
  /// override and falling back to conventional defaults.
  static String _resourceFor(
    BeakDiscoveredSymbol model,
    BeakProjectConfig config,
    BeakDiscovery discovery,
  ) {
    // beak.yaml is keyed by table name, and discovery read the real one off
    // the declaration. Re-deriving it from the class name gave a second
    // answer, so `@Resource(table: 'people')` on a `Person` silently lost
    // its icon.
    final BeakResourceOverride? override = config.resources[model.table];
    final parts = <String>[
      'model: ${model.expression}',
      'icon: BeakIconToken(OiIcons.${override?.icon ?? 'table'})',
      if (override?.label != null) "label: '${_escape(override!.label!)}'",
      if (override?.section != null)
        "section: '${_escape(override!.section!)}'",
    ];
    final String generated = 'BeakResource(${parts.join(', ')})';
    // A `lib/resources/<table>.dart` gets the last word on its own resource:
    // it receives what Beak derived and returns the copy it wants.
    return discovery.resourceOverrides.containsKey(model.table)
        ? '${_resourceAlias(model.table!)}'
              '.${BeakProjectScanner.resourceOverrideSymbol}($generated)'
        : generated;
  }

  /// `order_items` -> `resource_order_items`, the import alias a per-resource
  /// override is called through.
  static String _resourceAlias(String table) => 'resource_$table';

  /// Unique import paths of [symbols], in path order.
  static List<String> _importPathsOf(List<BeakDiscoveredSymbol> symbols) {
    final paths = <String>{for (final symbol in symbols) symbol.importPath};
    return paths.toList()..sort();
  }

  static String _escape(String value) =>
      value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}
