// GENERATED BY `beak prepare` — DO NOT EDIT.
// Regenerated from the @Resource class in this library.

part of 'specimen.dart';

/// Typed column constants of the specimens resource.
abstract final class SpecimenColumns {
  /// Primary key.
  static const BeakStringColumn id = BeakStringColumn(
    key: 'id',
    label: 'Id',
    visibleOn: {BeakContext.detail},
  );

  /// The name keepers call the bird by (string column).
  static const BeakStringColumn commonName = BeakStringColumn(
    key: 'common_name',
    label: 'Common Name',
    rules: [BeakRequired(), BeakMaxLength(120)],
    searchable: true,
    sortable: true,
    maxLength: 120,
  );

  /// The Latin binomial (string column, searchable).
  static const BeakStringColumn scientificName = BeakStringColumn(
    key: 'scientific_name',
    label: 'Scientific Name',
    searchable: true,
  );

  /// A reference page with the species account (url semantic).
  static const BeakStringColumn referenceUrl = BeakStringColumn(
    key: 'reference_url',
    label: 'Reference Url',
    semantic: BeakSemantic.url(),
  );

  /// Who reported the bird, for follow-up (email semantic).
  static const BeakStringColumn reporterEmail = BeakStringColumn(
    key: 'reporter_email',
    label: 'Reporter Email',
    semantic: BeakSemantic.email(),
  );

  /// Free-form keeper notes (text column).
  static const BeakTextColumn notes = BeakTextColumn(
    key: 'notes',
    label: 'Notes',
  );

  /// The care guide, formatted (rich-text column).
  static const BeakRichTextColumn careGuide = BeakRichTextColumn(
    key: 'care_guide',
    label: 'Care Guide',
  );

  /// Eggs in the last clutch (int column).
  static const BeakIntColumn clutchSize = BeakIntColumn(
    key: 'clutch_size',
    label: 'Clutch Size',
    rules: [BeakRequired(), BeakMin(0), BeakMax(30)],
    min: 0,
    max: 30,
  );

  /// Wingspan tip to tip (int column with a unit in its name).
  static const BeakIntColumn wingspanInCentimeters = BeakIntColumn(
    key: 'wingspan_in_centimeters',
    label: 'Wingspan In Centimeters',
    rules: [BeakRequired(), BeakMin(1)],
    suffix: 'cm',
    min: 1,
  );

  /// Body weight (decimal column).
  static const BeakDecimalColumn weightInGrams = BeakDecimalColumn(
    key: 'weight_in_grams',
    label: 'Weight In Grams',
    rules: [BeakRequired(), BeakMin(0)],
    suffix: 'g',
    precision: 1,
  );

  /// What the bird cost to acquire (exact money, in the currency below).
  static const BeakIntColumn acquisitionCost = BeakIntColumn(
    key: 'acquisition_cost',
    label: 'Acquisition Cost',
    rules: [BeakRequired()],
    semantic: BeakSemantic.money(
      scale: 2,
      currencyColumn: SpecimenColumns.currency,
    ),
    defaultValue: BeakDecimal(0, scale: 2),
  );

  /// ISO currency of [acquisitionCost].
  static const BeakStringColumn currency = BeakStringColumn(
    key: 'currency',
    label: 'Currency',
    rules: [
      BeakRequired(),
      BeakInList(['EUR', 'USD']),
    ],
    defaultValue: 'EUR',
  );

  /// Whether the species is on a conservation list (bool column).
  static const BeakBoolColumn endangered = BeakBoolColumn(
    key: 'endangered',
    label: 'Endangered',
    rules: [BeakRequired()],
    filterable: true,
    trueLabel: 'Endangered',
    falseLabel: 'Stable',
  );

  /// When the bird hatched (date-time column).
  static const BeakDateTimeColumn hatchedAt = BeakDateTimeColumn(
    key: 'hatched_at',
    label: 'Hatched At',
    sortable: true,
  );

  /// The bird's diet (enum column with badges).
  static const BeakEnumColumn<Diet> diet = BeakEnumColumn<Diet>(
    key: 'diet',
    label: 'Diet',
    rules: [BeakRequired()],
    defaultValue: Diet.granivore,
    filterable: true,
    badgeColors: {
      Diet.granivore: BeakColor.warning,
      Diet.frugivore: BeakColor.error,
      Diet.insectivore: BeakColor.success,
      Diet.piscivore: BeakColor.info,
      Diet.nectarivore: BeakColor.secondary,
    },
    labels: {
      Diet.granivore: 'Granivore',
      Diet.frugivore: 'Frugivore',
      Diet.insectivore: 'Insectivore',
      Diet.piscivore: 'Piscivore',
      Diet.nectarivore: 'Nectarivore',
    },
    values: Diet.values,
  );

  /// Tracker readings as structured data (json column).
  static const BeakJsonColumn telemetry = BeakJsonColumn(
    key: 'telemetry',
    label: 'Telemetry',
  );

  /// The dominant feather colour (color column).
  static const BeakColorColumn plumageColor = BeakColorColumn(
    key: 'plumage_color',
    label: 'Plumage Color',
  );

  /// A portrait, resized on upload (image column).
  static const BeakImageColumn photo = BeakImageColumn(
    key: 'photo',
    label: 'Photo',
    storagePath: 'specimens',
    maxSizeInBytes: 5242880,
    allowedTypes: [BeakFileType.png, BeakFileType.jpeg, BeakFileType.webp],
    transforms: [
      BeakThumbnailTransform(
        size: BeakDimensions.square(320),
        name: 'thumbnail',
      ),
    ],
  );

  /// The vet's health certificate (file column).
  static const BeakFileColumn healthCertificate = BeakFileColumn(
    key: 'health_certificate',
    label: 'Health Certificate',
    storagePath: 'certificates',
    maxSizeInBytes: 10485760,
    allowedTypes: [BeakFileType.pdf],
  );

  /// The leg band, drawn by a renderer the app registers (custom column).
  static const BeakCustomColumn bandCode = BeakCustomColumn(
    key: 'band_code',
    label: 'Band Code',
    tag: BeakColumnTag('band-code'),
  );

  /// Foreign key backing [habitat].
  static const BeakStringColumn habitatId = BeakStringColumn(
    key: 'habitat_id',
    label: 'Habitat',
    visibleOn: {BeakContext.form},
  );

  /// When the record was created.
  static const BeakDateTimeColumn createdAt = BeakDateTimeColumn(
    key: 'created_at',
    label: 'Created',
    sortable: true,
    visibleOn: {BeakContext.detail},
  );

  /// When the record was last updated.
  static const BeakDateTimeColumn updatedAt = BeakDateTimeColumn(
    key: 'updated_at',
    label: 'Updated',
    sortable: true,
    format: BeakDateFormat.relative,
    visibleOn: {BeakContext.table, BeakContext.detail},
  );

  /// When the record was soft-deleted, if it was.
  static const BeakDateTimeColumn deletedAt = BeakDateTimeColumn(
    key: 'deleted_at',
    label: 'Deleted',
    visibleOn: {BeakContext.detail},
  );

  /// Every column, in declaration order.
  static const List<BeakColumn> values = [
    id,
    commonName,
    scientificName,
    referenceUrl,
    reporterEmail,
    notes,
    careGuide,
    clutchSize,
    wingspanInCentimeters,
    weightInGrams,
    acquisitionCost,
    currency,
    endangered,
    hatchedAt,
    diet,
    telemetry,
    plumageColor,
    photo,
    healthCertificate,
    bandCode,
    habitatId,
    createdAt,
    updatedAt,
    deletedAt,
  ];
}

/// Typed relationship constants of the specimens resource.
abstract final class SpecimenRelations {
  /// Where the bird lives (belongs-to relationship).
  static const BeakBelongsTo habitat = BeakBelongsTo(
    key: 'habitat',
    label: 'Habitat',
    relatedTable: 'habitats',
    displayColumnKey: 'name',
    foreignKey: 'habitat_id',
    searchColumnKeys: ['name'],
    onDelete: BeakOnDelete.setNull,
  );
}

/// Typed configuration references for Specimen.
final class SpecimenFields {
  /// Creates the fields of Specimen, rooted at its own model.
  const SpecimenFields() : _model = const SpecimenModel(), _path = const [];

  /// Creates fields rooted at [model] and reached through [path].
  const SpecimenFields.via(this._model, this._path);
  final BeakModel _model;
  final List<BeakRelationship> _path;

  /// Id.
  BeakScalarField<String> get id => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.id,
    path: _path,
    isRequired: false,
  );

  /// Common Name.
  BeakScalarField<String> get commonName => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.commonName,
    path: _path,
    isRequired: true,
  );

  /// Scientific Name.
  BeakScalarField<String> get scientificName => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.scientificName,
    path: _path,
    isRequired: false,
  );

  /// Reference Url.
  BeakScalarField<String> get referenceUrl => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.referenceUrl,
    path: _path,
    isRequired: false,
  );

  /// Reporter Email.
  BeakScalarField<String> get reporterEmail => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.reporterEmail,
    path: _path,
    isRequired: false,
  );

  /// Notes.
  BeakScalarField<String> get notes => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.notes,
    path: _path,
    isRequired: false,
  );

  /// Care Guide.
  BeakScalarField<String> get careGuide => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.careGuide,
    path: _path,
    isRequired: false,
  );

  /// Clutch Size.
  BeakScalarField<int> get clutchSize => BeakScalarField<int>(
    model: _model,
    column: SpecimenColumns.clutchSize,
    path: _path,
    isRequired: true,
  );

  /// Wingspan In Centimeters.
  BeakScalarField<int> get wingspanInCentimeters => BeakScalarField<int>(
    model: _model,
    column: SpecimenColumns.wingspanInCentimeters,
    path: _path,
    isRequired: true,
  );

  /// Weight In Grams.
  BeakScalarField<double> get weightInGrams => BeakScalarField<double>(
    model: _model,
    column: SpecimenColumns.weightInGrams,
    path: _path,
    isRequired: true,
  );

  /// Acquisition Cost.
  BeakScalarField<BeakDecimal> get acquisitionCost =>
      BeakScalarField<BeakDecimal>(
        model: _model,
        column: SpecimenColumns.acquisitionCost,
        path: _path,
        isRequired: true,
      );

  /// Currency.
  BeakScalarField<String> get currency => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.currency,
    path: _path,
    isRequired: true,
  );

  /// Endangered.
  BeakScalarField<bool> get endangered => BeakScalarField<bool>(
    model: _model,
    column: SpecimenColumns.endangered,
    path: _path,
    isRequired: true,
  );

  /// Hatched At.
  BeakScalarField<DateTime> get hatchedAt => BeakScalarField<DateTime>(
    model: _model,
    column: SpecimenColumns.hatchedAt,
    path: _path,
    isRequired: false,
  );

  /// Diet.
  BeakScalarField<Diet> get diet => BeakScalarField<Diet>(
    model: _model,
    column: SpecimenColumns.diet,
    path: _path,
    isRequired: true,
  );

  /// Telemetry.
  BeakScalarField<BeakJson> get telemetry => BeakScalarField<BeakJson>(
    model: _model,
    column: SpecimenColumns.telemetry,
    path: _path,
    isRequired: false,
  );

  /// Plumage Color.
  BeakScalarField<String> get plumageColor => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.plumageColor,
    path: _path,
    isRequired: false,
  );

  /// Photo.
  BeakScalarField<String> get photo => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.photo,
    path: _path,
    isRequired: false,
  );

  /// Health Certificate.
  BeakScalarField<String> get healthCertificate => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.healthCertificate,
    path: _path,
    isRequired: false,
  );

  /// Band Code.
  BeakScalarField<Object> get bandCode => BeakScalarField<Object>(
    model: _model,
    column: SpecimenColumns.bandCode,
    path: _path,
    isRequired: false,
  );

  /// Habitat.
  BeakScalarField<String> get habitatId => BeakScalarField<String>(
    model: _model,
    column: SpecimenColumns.habitatId,
    path: _path,
    isRequired: false,
  );

  /// Created.
  BeakScalarField<DateTime> get createdAt => BeakScalarField<DateTime>(
    model: _model,
    column: SpecimenColumns.createdAt,
    path: _path,
    isRequired: false,
  );

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => BeakScalarField<DateTime>(
    model: _model,
    column: SpecimenColumns.updatedAt,
    path: _path,
    isRequired: false,
  );

  /// Deleted.
  BeakScalarField<DateTime> get deletedAt => BeakScalarField<DateTime>(
    model: _model,
    column: SpecimenColumns.deletedAt,
    path: _path,
    isRequired: false,
  );

  /// Habitat.
  HabitatToOneField get habitat => HabitatToOneField(
    model: _model,
    relation: SpecimenRelations.habitat,
    path: _path,
    isRequired: false,
  );
}

/// A to-one path to Specimen, retaining its root owner.
final class SpecimenToOneField extends BeakToOneField {
  /// Creates a typed relationship path.
  const SpecimenToOneField({
    required super.model,
    required super.relation,
    super.path,
    super.isRequired,
  }) : super(target: const SpecimenModel());

  /// Every target field, including names reserved by the path API.
  SpecimenFields get fields => SpecimenFields.via(model, [...path, relation]);

  /// Id.
  BeakScalarField<String> get id => fields.id;

  /// Common Name.
  BeakScalarField<String> get commonName => fields.commonName;

  /// Scientific Name.
  BeakScalarField<String> get scientificName => fields.scientificName;

  /// Reference Url.
  BeakScalarField<String> get referenceUrl => fields.referenceUrl;

  /// Reporter Email.
  BeakScalarField<String> get reporterEmail => fields.reporterEmail;

  /// Notes.
  BeakScalarField<String> get notes => fields.notes;

  /// Care Guide.
  BeakScalarField<String> get careGuide => fields.careGuide;

  /// Clutch Size.
  BeakScalarField<int> get clutchSize => fields.clutchSize;

  /// Wingspan In Centimeters.
  BeakScalarField<int> get wingspanInCentimeters =>
      fields.wingspanInCentimeters;

  /// Weight In Grams.
  BeakScalarField<double> get weightInGrams => fields.weightInGrams;

  /// Acquisition Cost.
  BeakScalarField<BeakDecimal> get acquisitionCost => fields.acquisitionCost;

  /// Currency.
  BeakScalarField<String> get currency => fields.currency;

  /// Endangered.
  BeakScalarField<bool> get endangered => fields.endangered;

  /// Hatched At.
  BeakScalarField<DateTime> get hatchedAt => fields.hatchedAt;

  /// Diet.
  BeakScalarField<Diet> get diet => fields.diet;

  /// Telemetry.
  BeakScalarField<BeakJson> get telemetry => fields.telemetry;

  /// Plumage Color.
  BeakScalarField<String> get plumageColor => fields.plumageColor;

  /// Photo.
  BeakScalarField<String> get photo => fields.photo;

  /// Health Certificate.
  BeakScalarField<String> get healthCertificate => fields.healthCertificate;

  /// Band Code.
  BeakScalarField<Object> get bandCode => fields.bandCode;

  /// Habitat.
  BeakScalarField<String> get habitatId => fields.habitatId;

  /// Created.
  BeakScalarField<DateTime> get createdAt => fields.createdAt;

  /// Updated.
  BeakScalarField<DateTime> get updatedAt => fields.updatedAt;

  /// Deleted.
  BeakScalarField<DateTime> get deletedAt => fields.deletedAt;

  /// Habitat.
  HabitatToOneField get habitat => fields.habitat;
}

/// The kitchen sink: one field of every column kind Beak has.
///
/// Every file that names a column kind in the docs points here, and
/// `test/column_kind_matrix_test.dart` fails to compile when Beak gains a kind
/// this class does not use.
final class SpecimenModel extends BeakModel {
  /// Creates the specimens model.
  const SpecimenModel();

  /// Typed field and relation references, including reserved names.
  static const SpecimenFields fields = SpecimenFields();

  /// Typed reference to [id] in this model.
  static final id = fields.id;

  /// Typed reference to [commonName] in this model.
  static final commonName = fields.commonName;

  /// Typed reference to [scientificName] in this model.
  static final scientificName = fields.scientificName;

  /// Typed reference to [referenceUrl] in this model.
  static final referenceUrl = fields.referenceUrl;

  /// Typed reference to [reporterEmail] in this model.
  static final reporterEmail = fields.reporterEmail;

  /// Typed reference to [notes] in this model.
  static final notes = fields.notes;

  /// Typed reference to [careGuide] in this model.
  static final careGuide = fields.careGuide;

  /// Typed reference to [clutchSize] in this model.
  static final clutchSize = fields.clutchSize;

  /// Typed reference to [wingspanInCentimeters] in this model.
  static final wingspanInCentimeters = fields.wingspanInCentimeters;

  /// Typed reference to [weightInGrams] in this model.
  static final weightInGrams = fields.weightInGrams;

  /// Typed reference to [acquisitionCost] in this model.
  static final acquisitionCost = fields.acquisitionCost;

  /// Typed reference to [currency] in this model.
  static final currency = fields.currency;

  /// Typed reference to [endangered] in this model.
  static final endangered = fields.endangered;

  /// Typed reference to [hatchedAt] in this model.
  static final hatchedAt = fields.hatchedAt;

  /// Typed reference to [diet] in this model.
  static final diet = fields.diet;

  /// Typed reference to [telemetry] in this model.
  static final telemetry = fields.telemetry;

  /// Typed reference to [plumageColor] in this model.
  static final plumageColor = fields.plumageColor;

  /// Typed reference to [photo] in this model.
  static final photo = fields.photo;

  /// Typed reference to [healthCertificate] in this model.
  static final healthCertificate = fields.healthCertificate;

  /// Typed reference to [bandCode] in this model.
  static final bandCode = fields.bandCode;

  /// Typed reference to [habitatId] in this model.
  static final habitatId = fields.habitatId;

  /// Typed reference to [createdAt] in this model.
  static final createdAt = fields.createdAt;

  /// Typed reference to [updatedAt] in this model.
  static final updatedAt = fields.updatedAt;

  /// Typed reference to [deletedAt] in this model.
  static final deletedAt = fields.deletedAt;

  /// Typed reference to [habitat] in this model.
  static final habitat = fields.habitat;

  /// Declarative source for record choices.
  static BeakOptionQuery options({BeakFilter? filter}) => BeakOptionQuery(
    model: const SpecimenModel(),
    query: const SpecimenModel().query(filter: filter),
  );

  /// Searches the model display and searchable columns.
  static BeakOptionQuery search(String term, {BeakFilter? filter}) =>
      BeakOptionQuery(
        model: const SpecimenModel(),
        query: const SpecimenModel().query(
          filter: filter,
          search: BeakSearch(term, const ['common_name', 'scientific_name']),
        ),
      );

  @override
  String get table => 'specimens';

  @override
  String get displayColumnKey => 'common_name';

  @override
  List<BeakColumn> get columns => SpecimenColumns.values;
  @override
  List<BeakModel> get relatedModels => const [HabitatModel()];

  @override
  List<BeakRelationship> get relationships => const [SpecimenRelations.habitat];

  @override
  bool get softDeletes => true;

  @override
  List<Enum> get formSlots => _SpecimenModelFormSlot.values;
}

/// Form-field slots of SpecimenModel.
///
/// An implementation bridge, never shown and never stored:
/// auto forms key their fields by an enum, and this supplies
/// one value per field Specimen can put on a form.
enum _SpecimenModelFormSlot {
  /// Bridge slots.
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
  s15,
  s16,
  s17,
  s18,
  s19,
  s20,
  s21,
  s22,
  s23,
  s24,
}

/// A live, nullable view of an incomplete Specimen draft.
final class SpecimenDraft {
  /// Reads values through the session so dependencies stay observable.
  const SpecimenDraft(this._reader);
  final BeakDraftReader _reader;

  /// Id, or null while incomplete.
  String? get id => _reader.read(SpecimenModel.fields.id);

  /// Common Name, or null while incomplete.
  String? get commonName => _reader.read(SpecimenModel.fields.commonName);

  /// Scientific Name, or null while incomplete.
  String? get scientificName =>
      _reader.read(SpecimenModel.fields.scientificName);

  /// Reference Url, or null while incomplete.
  String? get referenceUrl => _reader.read(SpecimenModel.fields.referenceUrl);

  /// Reporter Email, or null while incomplete.
  String? get reporterEmail => _reader.read(SpecimenModel.fields.reporterEmail);

  /// Notes, or null while incomplete.
  String? get notes => _reader.read(SpecimenModel.fields.notes);

  /// Care Guide, or null while incomplete.
  String? get careGuide => _reader.read(SpecimenModel.fields.careGuide);

  /// Clutch Size, or null while incomplete.
  int? get clutchSize => _reader.read(SpecimenModel.fields.clutchSize);

  /// Wingspan In Centimeters, or null while incomplete.
  int? get wingspanInCentimeters =>
      _reader.read(SpecimenModel.fields.wingspanInCentimeters);

  /// Weight In Grams, or null while incomplete.
  double? get weightInGrams => _reader.read(SpecimenModel.fields.weightInGrams);

  /// Acquisition Cost, or null while incomplete.
  BeakDecimal? get acquisitionCost =>
      _reader.read(SpecimenModel.fields.acquisitionCost);

  /// Currency, or null while incomplete.
  String? get currency => _reader.read(SpecimenModel.fields.currency);

  /// Endangered, or null while incomplete.
  bool? get endangered => _reader.read(SpecimenModel.fields.endangered);

  /// Hatched At, or null while incomplete.
  DateTime? get hatchedAt => _reader.read(SpecimenModel.fields.hatchedAt);

  /// Diet, or null while incomplete.
  Diet? get diet => _reader.read(SpecimenModel.fields.diet);

  /// Telemetry, or null while incomplete.
  BeakJson? get telemetry => _reader.read(SpecimenModel.fields.telemetry);

  /// Plumage Color, or null while incomplete.
  String? get plumageColor => _reader.read(SpecimenModel.fields.plumageColor);

  /// Photo, or null while incomplete.
  String? get photo => _reader.read(SpecimenModel.fields.photo);

  /// Health Certificate, or null while incomplete.
  String? get healthCertificate =>
      _reader.read(SpecimenModel.fields.healthCertificate);

  /// Band Code, or null while incomplete.
  Object? get bandCode => _reader.read(SpecimenModel.fields.bandCode);

  /// Habitat, or null while incomplete.
  String? get habitatId => _reader.read(SpecimenModel.fields.habitatId);

  /// Created, or null while incomplete.
  DateTime? get createdAt => _reader.read(SpecimenModel.fields.createdAt);

  /// Updated, or null while incomplete.
  DateTime? get updatedAt => _reader.read(SpecimenModel.fields.updatedAt);

  /// Deleted, or null while incomplete.
  DateTime? get deletedAt => _reader.read(SpecimenModel.fields.deletedAt);

  /// The selected habitat.
  HabitatRecord? get habitat =>
      switch (_reader.read(SpecimenModel.fields.habitat)) {
        final BeakRecord record => HabitatRecord.of(record),
        null => null,
      };
}

/// Typed access to live Specimen form values.
extension SpecimenDraftAccess on BeakDraftReader {
  /// Nullable values backed by this tracked reader.
  SpecimenDraft get asSpecimen => SpecimenDraft(this);
}

/// A typed, zero-cost view over a specimens record.
///
/// Reads fields through their own columns, so a value comes
/// back as its declared Dart type rather than an `Object?`
/// the caller has to pattern-match.
extension type const SpecimenRecord._(BeakRecord record) {
  /// Views [record] as a specimens row.
  const SpecimenRecord.of(BeakRecord record) : this._(record);

  /// Primary key.
  String? get id => SpecimenColumns.id.readFrom(record);

  /// The name keepers call the bird by (string column).
  String get commonName => SpecimenColumns.commonName.require(record);

  /// The Latin binomial (string column, searchable).
  String? get scientificName => SpecimenColumns.scientificName.readFrom(record);

  /// A reference page with the species account (url semantic).
  String? get referenceUrl => SpecimenColumns.referenceUrl.readFrom(record);

  /// Who reported the bird, for follow-up (email semantic).
  String? get reporterEmail => SpecimenColumns.reporterEmail.readFrom(record);

  /// Free-form keeper notes (text column).
  String? get notes => SpecimenColumns.notes.readFrom(record);

  /// The care guide, formatted (rich-text column).
  String? get careGuide => SpecimenColumns.careGuide.readFrom(record);

  /// Eggs in the last clutch (int column).
  int get clutchSize => SpecimenColumns.clutchSize.require(record);

  /// Wingspan tip to tip (int column with a unit in its name).
  int get wingspanInCentimeters =>
      SpecimenColumns.wingspanInCentimeters.require(record);

  /// Body weight (decimal column).
  double get weightInGrams => SpecimenColumns.weightInGrams.require(record);

  /// What the bird cost to acquire (exact money, in the currency below).
  BeakDecimal get acquisitionCost =>
      SpecimenModel.fields.acquisitionCost.require(record);

  /// ISO currency of [acquisitionCost].
  String get currency => SpecimenColumns.currency.require(record);

  /// Whether the species is on a conservation list (bool column).
  bool get endangered => SpecimenColumns.endangered.require(record);

  /// When the bird hatched (date-time column).
  DateTime? get hatchedAt => SpecimenColumns.hatchedAt.readFrom(record);

  /// The bird's diet (enum column with badges).
  Diet get diet => SpecimenColumns.diet.require(record);

  /// Tracker readings as structured data (json column).
  BeakJson? get telemetry => SpecimenModel.fields.telemetry.readFrom(record);

  /// The dominant feather colour (color column).
  String? get plumageColor => SpecimenColumns.plumageColor.readFrom(record);

  /// A portrait, resized on upload (image column).
  String? get photo => SpecimenColumns.photo.readFrom(record);

  /// The vet's health certificate (file column).
  String? get healthCertificate =>
      SpecimenColumns.healthCertificate.readFrom(record);

  /// The leg band, drawn by a renderer the app registers (custom column).
  Object? get bandCode => SpecimenColumns.bandCode.readFrom(record);

  /// Foreign key backing [habitat].
  String? get habitatId => SpecimenColumns.habitatId.readFrom(record);

  /// When the record was created.
  DateTime? get createdAt => SpecimenColumns.createdAt.readFrom(record);

  /// When the record was last updated.
  DateTime? get updatedAt => SpecimenColumns.updatedAt.readFrom(record);

  /// When the record was soft-deleted, if it was.
  DateTime? get deletedAt => SpecimenColumns.deletedAt.readFrom(record);

  /// The eager-loaded habitat, or null when unloaded or unset.
  HabitatRecord? get habitat => switch (record.relations['habitat']) {
    [final BeakRecord first, ...] => HabitatRecord.of(first),
    _ => null,
  };
}

/// Views any record as a specimens row.
extension SpecimenRecordAccess on BeakRecord {
  /// This record, typed as a specimens row.
  SpecimenRecord get asSpecimen => SpecimenRecord.of(this);
}
